### ISSUE TITLE
feature request: automatically close error buffer when buffer of tex file is closed

### ISSUE THREAD

**Issue by heiderich** [lervag/vimtex#873] opened 2017-06-13 13:12 UTC
### Explain the issue

In my opinion it would be convenient if the error buffer would be closed automatically when the (last open) tex file is closed in vim.

1. Steps to reproduce

Open a .tex file that contains errors. Compile with vimtex. An error buffer will open (if vimtex is configured in this way, which I am assuming here). Close the .tex file (say, using :q).

2. Expected behaviour

The error buffer would also close.

3. Observed behaviour

The error buffer remains open.

**Comment by lervag** [comment] 2017-06-13 20:04
For me, this is already the observed behaviour, both with Vim and neovim.

Which version of Vim are you on?

As always, it really helps if you provide a minimal test case, and in particular a minimal vimrc file.

**Comment by lervag** [comment] 2017-06-23 14:37
I'm closing due to not being able to reproduce. Feel free to reopen if you add more details and a reproducible example.

**Closed by lervag** 2017-06-23 14:37 UTC

**Comment by heiderich** [comment] 2017-07-20 19:22
This happens at least when there is an error in a file that is included via \input into the main .tex file and the current buffer is the one of the file being included as in the following example:

```
% main.tex
\documentclass[12pt]{article}
\begin{document}
\input{foo.tex}
\end{document}
```


``` 
% foo.tex
\begin{theorem}
	Here we have a syntax error $
\end{theorem}
```

**Comment by lervag** [comment] 2017-07-20 21:58
Thanks, I've reproduced now. Will look into it.

**Comment by lervag** [comment] 2017-07-25 13:59
I think this should work now.
