### ISSUE TITLE
No compiler feedback in nvim

### ISSUE THREAD

**Issue by rthrmt** [lervag/vimtex#767] opened 2017-04-08 12:21 UTC
I don't get any compilation feedback in neovim anymore. It did work before. It does compile correctly (creates a pdf, etc.).

Here is a minimal vimrc file:
```vim
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex', { 'for': ['tex', 'latex'] }
call plug#end()

filetype plugin indent on
syntax enable

let g:vimtex_compiler_progname = "/usr/bin/nvr"
```

Edit: @lervag updated formatting and removed some unimportant comments from vimrc sample.

**Comment by lervag** [comment] 2017-04-08 17:47
Hi. Sorry, I am currently implementing support for neovim's `jobstart` and `job-control` interface. It worked for me, so I thought it would work for others, and so I updated the default backend to `nvim` if possible, see `:h g:vimtex_compiler_latexmk` and read about the `backend` key.

Could you report the output of `VimtexInfo` / `\li` after you have started compilation. Also, could you inspect the `latexmk` output through `VimtexOutput` / `\lo`, there might be some helpful info.

**Comment by lervag** [comment] 2017-04-09 18:57
I'm closing this since I can't reproduce it. However, feel free to reopen if you can provide more details that will make it possible for me to reproduce.

**Closed by lervag** 2017-04-09 18:57 UTC

**Comment by rthrmt** [comment] 2017-04-12 16:34
Here is the output of VimtexInfo, I changed the filenames due to privacy.

```
vimtex project: dummy_project
  base: dummy.tex
  root: /home/user/Project/
  tex: /home/user/Project/dummy.tex
  out: /home/user/Project/dummy.pdf
  log: /home/user/Project/dummy.log
  aux: /home/user/Project/dummy.aux
  packages: 
    tikz: 1
  compiler: latexmk
    backend: nvim
    output: /tmp/nvim3bUIL5/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options: 
        -verbose
        -pdf
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
    pid: 4004
    cmd: max_print_line=2000 latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e '$pdf_previewer = "okular --unique"' -e '$success_cmd = "'""/usr/bin/nvr""' --servername /tmp/nvim3bUIL5/0 --remote-expr \"vimtex\#compiler\#callback(1)\""' -e '$failure_cmd = "'""/usr/bin/nvr""' --servername /tmp/nvim3bUIL5/0 --remote-expr \"vimtex\#compiler\#callback(0)\""' 'dummy.tex'
  viewer: General
  qf: LaTeX logfile
    config: 
      fix_paths: 1
      packages: 
        default: 1
      default: 1

```

When I try to issue :VimtexOutput nvim complains that there is no such command.

**Comment by lervag** [comment] 2017-04-12 19:07
Sorry, I meant `VimtexCompileOutput`. Does it work if you use `nvr` instead of `/usr/bin/nvr`?

**Comment by rthrmt** [comment] 2017-04-12 22:03
`nvr` doesn't change it. 

Here is the output of VimtexCompilerOutput

```
Latexmk: This is Latexmk, John Collins, 5 Sep. 2016, version: 4.48.
Viewing pdf
Latexmk: I have not found a previewer that is already running. 
   So I will start it for 'dummy.pdf'
------------
------------
Running 'start xdg-open  "dummy.pdf"'
------------
Latexmk: All targets (dummy.pdf) are up-to-date
For rule 'view', running '&if_source(  )' ...
------------
Running ''nvr' --servername /tmp/nvim5mOgrO/0 --remote-expr "vimtex#compiler#callback(1)"'
------------
Evaluation failed: vimtex#compiler#callback(1)

```

**Comment by lervag** [comment] 2017-04-13 08:28
Huh. That's very strange! Ok, can you open the test document, start the compilation, and then from the terminal try to run the callback command, i.e.:

```
'nvr' --servername /tmp/nvim5mOgrO/0 --remote-expr "vimtex#compiler#callback(1)"
```

Which OS are you on, which version of neovim and nvr?

**Comment by rthrmt** [comment] 2017-04-13 09:09
I then get the same as in VimtexCompilerOutput
```

[user@laptop] ~ > 'nvr' --servername /tmp/nvim4y2v79/0 --remote-expr "vimtex#compiler#callback(1)"
Evaluation failed: vimtex#compiler#callback(1)
```

I'm running Arch, my neovim version is 0.1.7 and nvr is 1.5.2 (it was on 1.5.0, I've just updated it to see if that was the problem, but it didn't change anything).

**Comment by lervag** [comment] 2017-04-13 09:17
Ok, which shell are you running?

I'm also on Arch with the same versions. For me, everything works.

**Comment by rthrmt** [comment] 2017-04-13 09:26
I'm running bash. [Here](https://github.com/rthrmt/dotfiles/blob/master/bashrc) is my bashrc.

**Comment by lervag** [comment] 2017-04-13 09:28
Ok, can you open the sample file, then echo the servername. Now, in a terminal, verify thats `nvr` works as expected. E.g.:

```sh
nvr --servername SERVERNAME --remote-expr "echo 'test'"
```

**Comment by rthrmt** [comment] 2017-04-13 09:34
```
[user@laptop] ~ > nvr --servername /tmp/nvimIJNgXv/0 --remote-expr "echo 'test'"
Evaluation failed: echo 'test'   
```

Okay, it somehow fails to do anything.

**Comment by lervag** [comment] 2017-04-13 09:36
Right. So, this tempts me to claim that you should open an issue with the `nvr` team. But let's simplify first:

1. Open an empty neovim buffer with `nvim -u NONE`.
2. Take note of the servername: `:echo v:servername`.
3. Try `nvr --servername SERVERNAME --remote-expr "echo 'test'"` again.

If this fails, then it seems there is a problem with your `nvr` or neovim. I don't know too much about this, and I am afraid I can't help much further.

**Comment by rthrmt** [comment] 2017-04-13 09:45
Okay, thanks. Will do that. 
It still does the same. I tried the example commands from the [github page](https://github.com/mhinz/neovim-remote) and somehow they do work. `--remote-expr` is able to do the `5+5` but not the `echo`

**Comment by lervag** [comment] 2017-04-13 09:47
Sorry, my bad. I did not use an expression. Ok, so I think the problem is that the callback function somehow fails. I don't see why or what could be the problem, though.

**Comment by lervag** [comment] 2017-04-13 09:50
Ok, try:

1. Open a test LaTeX file.
2. Run `:call vimtex#compiler#callback(0)` inside `nvim`.

Next, try to run `nvr --servername SERVERNAME --remote-expr "vimtex#compiler#callback(0)"` on the terminal again. Try both with 0 and 1 for the argument.

Next, if you don't mind: Edit `VIMTEX/autoload/vimtex/compiler.vim`, go to the callback function, and insert at the top:

```vim
echom a:status
return
```

Now try again on the terminal.

**Comment by rthrmt** [comment] 2017-04-13 10:15
> Sorry, my bad. I did not use an expression. Ok, so I think the problem is that the callback function somehow fails. I don't see why or what could be the problem, though. 

Isn't `echo` an expression?

The `:call vimtex#compiler#callback(0)` (also with a 1) gives an error:
```
Error detected while processing function <SNR>43_fix_paths:
line   26:
E731: using Dictionary as a String
```
Then I have:

```
nvr --servername /tmp/nvimZR11ZE/0 --remote-expr "vimtex#compiler#callback(0)"
Evaluation failed: vimtex#compiler#callback(0)
```

And here the changed function (in case I changed it wrong):
```
function! vimtex#compiler#callback(status) abort " {{{1
  echom a:status
  return
  if get(b:vimtex.compiler, 'silence_next_callback')
    let b:vimtex.compiler.silence_next_callback = 0
    return
  endif
[...]
```
and the output:
```
nvr --servername /tmp/nvim9hWBFh/0 --remote-expr "vimtex#compiler#callback(0)"
0
```
(sockets are different because I had to reload nvim after changing the plugin)

**Comment by lervag** [comment] 2017-04-13 10:24
Ah, and there it is. There is a bug with neovim, see [here](https://github.com/lervag/vimtex/issues/750#issuecomment-290987411). You can temporarily fix it with

```vim
let g:vimtex_quickfix_latexlog = {'fix_paths':0}
```

But things should work when neovim 0.2.0 is ready.

**Comment by rthrmt** [comment] 2017-04-13 10:33
phew, thank you very much. It does display errors again.

**Comment by lervag** [comment] 2017-04-13 10:34
Great! :-)
