### ISSUE TITLE
Mainfile detection fails when \input is in enumerate environment

### ISSUE THREAD

**Issue by t-ye** [lervag/vimtex#2895] opened 2024-03-10 10:44 UTC
### Description

`main.tex`:

```vim
\documentclass{article}
\begin{document}
\begin{enumerate}
  \item \input{file.tex}
\end{enumerate}
\end{document}
```

`file.tex`:

```tex
Hello world!
```

### Steps to reproduce

1. Compile (`\ll`) from `main.tex`
2. Compile from `file.tex`

### Expected behavior

Successful compilation with PDF `Hello world!`

### Actual behavior

Compiling in `file.tex` results in an error:

```
VimTeX: Compilation error due to failed mainfile detection!
        Please ensure that VimTeX can locate the proper main .tex file.
        Read ":help vimtex-multi-file" for more info.
```

(I have tried setting `b:vimtex_main` and specifying the TeX root directive in `file.tex`, to no avail.)

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 22.04.2 LTS
  Vim version: VIM 8.2 (1-579, 1969, 580-1848, 4975, 5016, 5023, 5072, 2068, 1849-1854, 1857
  Has clientserver: true
  Servername: VIM

VimTeX project: file
  base: file.tex
  root: (...)
  tex: (...)
  main parser: fallback current file
  document class:
  compiler: latexmk
    engine: -pdf
    options:  -verbose  -file-line-error  -synctex=1  -interaction=nonstopmode
    out_dir: build
    aux_dir: aux
    callback: 1
    continuous: 1
    executable: latexmk
    job:
    jobid: process 271896 dead
    output: /tmp/vdt7z20/1
    cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=non
    pid: 271896
  viewer: General
  qf method: LaTeX logfile
```

**Comment by lervag** [comment] 2024-03-10 10:59
That's interesting! I've reproduced this and will look into it!

**Comment by lervag** [comment] 2024-03-10 11:05
This is the problem:

https://github.com/lervag/vimtex/blob/a77d14b2e4391c0d3e860708bb1fd56161ab68eb/autoload/vimtex/re.vim#L25

You are the first person who've tried to use `\input` (or similar) as something that's _not_ the first thing on a line! So, as a fallback, you could just put `\input{file.tex}` on the next line, and things should work.

The reason I fix the regex at the start of line is because I worry it will be much more expensive if I remove this restriction. And unfortunately, I have to admit that this thing is more messy than I would have liked, so I'm not 100% sure if it is a good idea to simply remove the restriction.

So, as a first go: Would you mind if I don't make any changes here and instead that you write it like this?

```tex
\begin{enumerate}
  \item
    \input{file.tex}
\end{enumerate}
```

I know it's probably a little bit annoying, but still...

**Comment by t-ye** [comment] 2024-03-10 12:38
Thanks for the explanation! This workaround is OK. I do typically only have `\input`'s at the top level; these enumerates grew out of a haphazard project...

**Comment by lervag** [comment] 2024-03-10 15:38
Great, glad to hear it. I'll close the issue as "won't fix" then.

**Closed by lervag** 2024-03-10 15:38 UTC
Labels: bug, won't fix
