### ISSUE TITLE
Show which float shows a warning message 

### ISSUE THREAD

**Issue by gssfaw** [lervag/vimtex#2864] opened 2024-01-03 10:10 UTC
First of all, thank you for making such a good plugin, it's already the third (or maybe fourth) year that I enjoy writing in Latex with the great help of vimtex.
**Is your feature request related to a problem? Please describe it.**
Currently, when the float specifier changes (e.g. from `h` to `ht`), the error message does not specify which float changed it. The warning message just says 
```main.tex|| LaTeX Warning: `h' float specifier changed to `ht'.```

**Describe the solution you'd like**
As far as I understand, this is a tricky task because the log messages can be different for different types of floats, and also sometimes the warning is not exactly near the float's info message. 
But still, the log files need to be parsed somehow to get that information. 
**Describe alternatives you've considered**
I've tried pplatex, but it can't display the warning in the way I wish either. 

**Additional context**
Minimal file to reproduce: 
<details>

<summary>Test.tex</summary>

````tex
\documentclass{memoir}
\usepackage{graphicx}
\usepackage{blindtext}
\begin{document}
\blindtext[4]
\begin{figure}[h]
    \begin{center}
        \includegraphics[width=0.95\textwidth]{1.jpg}
    \end{center}
    \caption{dasdasdas}\label{fig:qwe}
\end{figure}

Some text Some text Some text Some text Some text Some text Some text Some text Some text 
Some text Some text Some text Some text Some text Some text Some text Some text Some text 
Some text Some text Some text Some text Some text Some text Some text Some text Some text 
Some text Some text Some text Some text Some text Some text Some text Some text Some text 
Some text Some text Some text Some text Some text Some text Some text Some text Some text 
Some text Some text Some text Some text Some text Some text Some text Some text Some text 
\begin{figure}[h]
    \begin{center}
        \def\svgwidth{0.95\textwidth} \input{drawing.pdf_tex}
    \end{center}
    \caption{dslkadjaslkdj}
    \label{fig:SpinDistributionModel}
\end{figure}

\end{document}
````
</details>

svg figure:
Github won't allow me to upload the `pdf_tex` file, but I got it by `save a copy` in Inkscape as a pdf and selecting the option `Omit text in PDF and create LaTeX file`.

![drawing](https://github.com/lervag/vimtex/assets/95208998/1b67c1c3-2c86-47f5-8039-691bf07ca8de)

**Comment by lervag** [comment] 2024-01-04 16:37
> First of all, thank you for making such a good plugin, it's already the third (or maybe fourth) year that I enjoy writing in Latex with the great help of vimtex.

<3

> **Is your feature request related to a problem? Please describe it.**

>Currently, when the float specifier changes (e.g. from `h` to `ht`), the error message does not specify which float changed it. The warning message just says `` main.tex|| LaTeX Warning: `h' float specifier changed to `ht'. ``

This is very hard to improve on. The problem is that there is no line number information in the log file. Consider this:

```tex
\documentclass{memoir}
\usepackage{graphicx}
\usepackage{blindtext}
\begin{document}
\blindtext[4]
\begin{figure}[h]
    \begin{center}
        \includegraphics[width=0.95\textwidth]{example-image-a}
    \end{center}
    \caption{dasdasdas}\label{fig:qwe}
\end{figure}

Some text Some text Some text Some text Some text Some text Some text Some text Some text 
Some text Some text Some text Some text Some text Some text Some text Some text Some text 
Some text Some text Some text Some text Some text Some text Some text Some text Some text 
Some text Some text Some text Some text Some text Some text Some text Some text Some text 
Some text Some text Some text Some text Some text Some text Some text Some text Some text 
Some text Some text Some text Some text Some text Some text Some text Some text Some text 
\begin{figure}[h]
    \begin{center}
        \includegraphics[width=0.95\textwidth]{example-image-a}
    \end{center}
    \caption{dslkadjaslkdj}
    \label{fig:SpinDistributionModel}
\end{figure}

\end{document}
```

(Notice the use of `example-image-[ab]`, which is a nice little builtin feature.)

Now, if we compile, we get the following output (more or less):

```
This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023/Arch Linux) (preloaded format=pdflatex 2023.12.18)  4 JAN 2024 17:30
entering extended mode
 \write18 enabled.
 file:line:error style messages enabled.
 %&-line parsing enabled.
**test.tex
(./test.tex
LaTeX2e <2022-11-01> patch level 1
L3 programming layer <2023-02-22> (/usr/share/texmf-dist/tex/latex/memoir/memoir.cls
Document Class: memoir 2022/11/17 v3.7.19 configurable book, report, article document class

… (CUT OUT)

<example-image-a.pdf, id=1, 321.2pt x 240.9pt>
File: example-image-a.pdf Graphic file (type pdf)
<use example-image-a.pdf>
Package pdftex.def Info: example-image-a.pdf  used on input line 8.
(pdftex.def)             Requested size: 323.94896pt x 242.96889pt.


LaTeX Warning: `h' float specifier changed to `ht'.

<example-image-b.pdf, id=2, 321.2pt x 240.9pt>
File: example-image-b.pdf Graphic file (type pdf)
<use example-image-b.pdf>
Package pdftex.def Info: example-image-b.pdf  used on input line 21.
(pdftex.def)             Requested size: 323.94896pt x 242.96889pt.
[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}

]

LaTeX Warning: `h' float specifier changed to `ht'.

[2 </usr/share/texmf-dist/tex/latex/mwe/example-image-a.pdf>] [3 </usr/share/texmf-dist/tex/latex/mwe/example-image-b.pdf>] (./test.aux) ) 
```

The warnings are not really directly related to the info about the "example-image-… used on input line X", and as you see, there is not other info.

**Comment by lervag** [comment] 2024-01-04 16:38
If I knew a way to get the necessary information, then I might consider trying to make it work better. But I don't, and I've never heard of something like that before.

I'm closing, but feel free to continue the discussion. In particular, if you have any ideas, feel free to share.

**Closed by lervag** 2024-01-04 16:38 UTC
Labels: enhancement

**Comment by gssfaw** [comment] 2024-01-04 18:16
>If I knew a way to get the necessary information, then I might consider trying to make it work better. But I don't, and I've never heard of something like that before.

Yes, these log messages are indeed difficult to parse. And I've had the messages related to one float separated by the other log messages. I suppose there is no clear way to implement a stable method to deduce the exact float. 

I am not sure what the log parser can do, but maybe there is a way to implement a jump to the position of the message in the log file, instead of just jumping to the beginning of the main file?

**Comment by lervag** [comment] 2024-01-04 21:37
> I am not sure what the log parser can do, but maybe there is a way to implement a jump to the position of the message in the log file, instead of just jumping to the beginning of the main file?

I _can_ see how using e.g. the line number of the previous entry could be convenient, but I'm skeptical. I believe it would be confusing to people that don't know of this behaviour.

I think the way to implement this is to enrich the relevant quickfix entries after the log file is fully parsed, similar to what we do here:

https://github.com/lervag/vimtex/blob/f9b19d09ee6f0ba70dad0b5c2e710dd700681000/autoload/vimtex/qf/latexlog.vim#L123-L141
