### ISSUE TITLE
Unable to have two seperate neovim instances open zathura

### ISSUE THREAD

**Issue by ss7m** [lervag/vimtex#2265] opened 2021-12-02 15:26 UTC
### Description

If I open a tex file in neovim and start compiling with `\lv`, zathura opens as expected (and forwards/backwards search both work as expected). However, if in a second terminal I open a different tex file and try and start compiling with `\lv`, no zathura window is opened. (I still get the "VimTeX: Compilation completed" message.)

### Steps to reproduce

foo.tex and bar.tex both contain:
```tex
\documentclass{article}

\begin{document}
Hello, World!
\end{document}
```

minimal.vim contains:
```vim
call plug#begin()
Plug 'lervag/vimtex'
call plug#end()

let g:vimtex_view_method='zathura'
```

Then, run `nvim -u minimal.vim foo.tex`, and start compiling with `\lv`.
Next, in a second terminal, run `nvim -u minimal.vim bar.tex` and start compiling with `\lv`.

### Expected behavior

Both neovim instances have their pdf document opened in zathura by vimtex. 

### Actual behavior

Only the neovim instance with foo.tex had its pdf document opened in zathura.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Linux 5.15.5-arch1-1
  Vim version: NVIM v0.6.0
  Has clientserver: true
  Servername: /tmp/nvimYuOoKM/0

VimTeX project: x
  base: x.tex
  root: /home/sam/Documents/bar
  tex: /home/sam/Documents/bar/x.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 81788931
  qf method: LaTeX logfile
```

**Comment by ss7m** [comment] 2021-12-02 18:03
In case its relevant, I just checked and in the `:VimtexInfo` of both neovim instances, `Has clientserver` is `true` for both, and `Servername:` is different.

**Comment by lervag** [comment] 2021-12-02 21:06
First, I assume that you mean `\ll` in the original post? `\lv` does not compile, it will open the viewer or do forward search.

So, if you instead do this:

1. First open each of the two files one at a time and do `\ll` to compile it - this will probably open Zathura, but just close it immediately.
2. Now open each file in a separate terminal in parallel. Do `\lv` in each file. I now expect there to be two viewers.

Can you confirm my expectation in 2?

**Comment by ss7m** [comment] 2021-12-02 21:12
Yes, I did mean `\ll` in the original post. (An odd mistake to have made, considering I was repeatedly typing `\ll` as I was testing out this behavior before filing this issue.)

You are correct—if I do `\lv` in each file (and I do mean `\lv` this time ☺), there are now two viewers (displaying the correct PDF document).

**Comment by lervag** [comment] 2021-12-02 21:19
Thanks for the quick feedback. I'll look into the original issue with `\ll`, then.

In the mean time, I would like to propose that you use `let g:vimtex_view_automatic = 0` and use `\lv` to open the viewers manually. I personally prefer this as I find it is intrusive that the viewer opens automatically. Obviously this is opinionated, but at least it would "solve" your issue. :)

**Comment by lervag** [comment] 2021-12-09 20:38
I also tested the same steps but exchanging steps 2 and 3.

**Comment by lervag** [comment] 2021-12-10 08:33
Great, perhaps I somehow resolved the problem in one of the recent commits. In any case, it seems the issue is resolved, so I'll close it.

**Closed by lervag** 2021-12-10 08:33 UTC
Labels: bug
