### ISSUE TITLE
Compatibility of compiler plugins with vim-dispatch

### ISSUE THREAD

**Issue by dianlujitao** [lervag/vimtex#1854] opened 2020-11-14 12:23 UTC
**Issue**
To perform grammar check with YaLafi, the documented way is:

```vim
:compiler vlty
:make
:copen
```

This works quite well and properly fills the quickfix window like this:

![image](https://user-images.githubusercontent.com/5774651/99146478-80647200-26b3-11eb-9585-eb475d7faf6f.png)

But with Tim Pope's vim-dispatch plugin, after either:

```vim
:compiler vlty
:Make
```

or `:Dispatch -compiler=vlty`, I got additional boilerplate outputs as follows:

![image](https://user-images.githubusercontent.com/5774651/99146528-f8cb3300-26b3-11eb-8269-267e7bf17da1.png)

I failed to find the explanation from neither vimtex's nor vim-dispatch's doc, how to make vim-dispatch produce the same output as vim's built-in `:make` command?

Cc: @matze-dd

**Comment by lervag** [comment] 2020-11-14 15:33
Interesting and good question; I hope @matze-dd can look into it and help. I don't really know so much about this stuff myself.

**Comment by matze-dd** [comment] 2020-11-14 17:03
Thanks for reporting ...

> This works quite well and properly fills the quickfix window like this:

... and for the positive feedback!

The problem you describe is very probably due to a non-correct `errorformat` setting in compiler vlty. I will need some more time to propose a PR, but this quick fix did work for me in `.../vimtex/compiler/vlty.vim` (the commented lines starting with `"` are the ones to be replaced by the following ones).
```
if s:vlty.show_suggestions == 0
" let &l:errorformat .= '%ZMessage: %m,%-G%.%#'
  let &l:errorformat .= '%ZMessage: %m,%-G%.%#,%-G%.%#'
else
" let &l:errorformat .= '%CMessage: %m,%Z%m,%-G%.%#'
  let &l:errorformat .= '%CMessage: %m,%Z%m,%-G%.%#,%-G%.%#'
endif
```
It seems that the current `errorformat` does not consume enough of the message returned by YaLafi, so that vim-dispatch tries to assign it somehow.

BTW: It appears that you do not want to wait while the proofreader is running. Did you already try this option?
```
let g:vimtex_grammar_vlty.server = 'my'
```
The started LanguageTool server is faster thanks to the omitted start-up work at each check, and thanks to its internal sentence caching mechanism.

**Comment by dianlujitao** [comment] 2020-11-15 07:06
> ```
> if s:vlty.show_suggestions == 0
> " let &l:errorformat .= '%ZMessage: %m,%-G%.%#'
>   let &l:errorformat .= '%ZMessage: %m,%-G%.%#,%-G%.%#'
> else
> " let &l:errorformat .= '%CMessage: %m,%Z%m,%-G%.%#'
>   let &l:errorformat .= '%CMessage: %m,%Z%m,%-G%.%#,%-G%.%#'
> endif
> ```
> 
> It seems that the current `errorformat` does not consume enough of the message returned by YaLafi, so that vim-dispatch tries to assign it somehow.

It works as expected after changing errorformat, thanks.

> BTW: It appears that you do not want to wait while the proofreader is running. Did you already try this option?
> 
> ```
> let g:vimtex_grammar_vlty.server = 'my'
> ```
> 
> The started LanguageTool server is faster thanks to the omitted start-up work at each check, and thanks to its internal sentence caching mechanism.

Yes I took most of the options from https://github.com/matze-dd/YaLafi#plugin-vimtex

**Comment by matze-dd** [comment] 2020-11-17 13:57
See PR #1856. Does this work for you, @dianlujitao?

**Comment by dianlujitao** [comment] 2020-11-17 14:13
> See PR #1856. Does this work for you, @dianlujitao?

Warnings such as
```
|| *** yalafi.shell: warning:
|| *** could not load module 'yalafi.packages.hyperref'
```
are not consumed while the others are gone.

**Comment by matze-dd** [comment] 2020-11-17 14:37
Thanks for testing!

Unfortunately, I cannot reproduce that. With `:make`, these warnings appear in the terminal (written to stderr), but they are not in the quickfix list, neither with `:make`, nor with `:Make`.

Could you please provide a minimum example? Which Vim do you use?

**Comment by dianlujitao** [comment] 2020-11-17 14:56
> Thanks for testing!
> 
> Unfortunately, I cannot reproduce that. With `:make`, these warnings appear in the terminal (written to stderr), but they are not in the quickfix list, neither with `:make`, nor with `:Make`.
> 
> Could you please provide a minimum example? Which Vim do you use?

They are not in the quickfix list with `:make` here but they are with `:Make` and `:Dispatch -compiler=vlty`.

I'm able to reproduce the issue with https://github.com/MCG-NKU/CVPR_Template/blob/master/cvpr.tex

My vim version is as follows:

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov 15 2020 16:37:08)
Included patches: 1-1989
Compiled by Arch Linux
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             +mouse_sgr         +tag_binary
+arabic            +file_in_path      -mouse_sysmouse    -tag_old_static
+autocmd           +find_in_path      +mouse_urxvt       -tag_any_white
+autochdir         +float             +mouse_xterm       +tcl/dyn
-autoservername    +folding           +multi_byte        +termguicolors
+balloon_eval      -footer            +multi_lang        +terminal
+balloon_eval_term +fork()            -mzscheme          +terminfo
+browse            +gettext           +netbeans_intg     +termresponse
++builtin_terms    -hangul_input      +num64             +textobjects
+byte_offset       +iconv             +packages          +textprop
+channel           +insert_expand     +path_extra        +timers
+cindent           +ipv6              +perl/dyn          +title
+clientserver      +job               +persistent_undo   +toolbar
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           +python/dyn        +visual
+conceal           +linebreak         +python3/dyn       +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua/dyn           +ruby/dyn          +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       +X11
+dnd               +mouse             +sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              +mouse_gpm         +statusline        +xsmp_interact
+ex_extra          -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cloudproviders -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/at-spi-2.0 -pthread    -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -D_REENTRANT  -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc   -L. -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lz -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lSM -lICE -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lelf    -lcanberra  -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.32/core_perl/CORE -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/perl5/5.32/core_perl/CORE -lperl -lpthread -ldl -lm -lcrypt -lutil -lc   -L/usr/lib -ltclstub8.6 -ldl -lz -lpthread -lm
```

**Comment by matze-dd** [comment] 2020-11-17 19:38
Thanks!

We might have a problem with different Linux distributions. On my Lubuntu, neither Vim in a terminal window nor Gvim with GTK3 GUI do show the `*** ...` messages with your cvpr.tex example. Unfortunately, I only have access to an Arch Linux next week.

Perhaps, anybody else can comment on the problem? I have the impression that YaLafi's output to stderr is somehow mixed with its messages to stdout (only under Arch Linux?).

Does the problem also occur with Vim in a terminal window?

**Comment by dianlujitao** [comment] 2020-11-18 02:09
> Thanks!
> 
> We might have a problem with different Linux distributions. On my Lubuntu, neither Vim in a terminal window nor Gvim with GTK3 GUI do show the `*** ...` messages with your cvpr.tex example. Unfortunately, I only have access to an Arch Linux next week.
> 
> Perhaps, anybody else can comment on the problem? I have the impression that YaLafi's output to stderr is somehow mixed with its messages to stdout (only under Arch Linux?).
> 
> Does the problem also occur with Vim in a terminal window?

Oops the problem only occurs in tmux, with a normal Konsole window it works fine.

**Comment by matze-dd** [comment] 2020-11-18 08:09
> Oops the problem only occurs in tmux, with a normal Konsole window it works fine.

Sounds good, I'm relieved. Now that we know what's going on, I'd propose to include these `*** ...` messages into the `errorformat`.

Can do and test that next week. Could you please keep the PR open, @lervag?

**Comment by lervag** [comment] 2020-11-18 08:37
Yes, of course. :)

**Comment by matze-dd** [comment] 2020-11-18 15:42
Sorry for the noise, the problem did not let me rest.

[Here is the reason](https://github.com/tpope/vim-dispatch/issues/199#issuecomment-299336621), why the initial "dirty hack" from above does work. It indeed seems to be the recommended solution!

**Comment by lervag** [comment] 2020-11-18 21:57
Ah, it's always nice to get to the bottom of things! I'll be glad if we can also understand why @dianlujitao still experiences issues inside tmux.

**Comment by dianlujitao** [comment] 2020-11-19 02:46
> Ah, it's always nice to get to the bottom of things! I'll be glad if we can also understand why @dianlujitao still experiences issues inside tmux.

The initial "hack" which appends `,%-G%.%#` to the current format indeed worked for me, with both vanilla terminal and tmux.

**Comment by matze-dd** [comment] 2020-11-19 07:43
> I'll be glad if we can also understand why @dianlujitao still experiences issues inside tmux.

The reason for my continued search was a bad gut feeling. For instance, the isolated `=== <file name>` that is consumed in the PR's `errorfromat`, is also written to stdout by YaLafi. So, I realised that messages to stdout are indeed picked up by Vim.

Additionally, I finally could confirm @dianlujitao's observation with the `|| *** ` messages`, when not using an LT server at all, or when the server was not yet running. So it was my bad that I did all my tests with the server option, and having it always run already.

Why this suppresses the problem, remains a mystery. BTW, [here is](https://github.com/tpope/vim-dispatch/blob/master/autoload/dispatch.vim#L862) the relevant code line in vim-dispatch.

Might it be that the problem with the PR version in tmux only appears on the first proofreader invocation in the same Vim session, @dianlujitao? Afterwards, the server also should be running?

**Comment by dianlujitao** [comment] 2020-11-19 09:00
> Might it be that the problem with the PR version in tmux only appears on the first proofreader invocation in the same Vim session, @dianlujitao? Afterwards, the server also should be running?

It appears every time. I tested all the combinations with:
1. LT server enabled/disabled in vimrc
2. exist/new (kill the previous java process) LT server session
3. multiple runs in same/different vim instances

the PR version worked with none of the corner cases.

**Comment by matze-dd** [comment] 2020-11-19 10:54
Thanks for the efforts and your time, @dianlujitao and @lervag!

After exchanging that many words, I will modify the PR to the little "dirty hack" version next week.

**Comment by matze-dd** [comment] 2020-11-20 10:05
PR has been updated.

**Comment by lervag** [comment] 2020-11-20 17:23
Do I understand correctly that the PR now, at least in theory, should solve the present issue? If so, it would be nice if @dianlujitao could test it and confirm.

**Comment by dianlujitao** [comment] 2020-11-20 17:25
> Do I understand correctly that the PR now, at least in theory, should solve the present issue? If so, it would be nice if @dianlujitao could test it and confirm.

Yes it works for me

**Comment by lervag** [comment] 2020-11-20 17:31
Ok, then I'll just mark this issue as resolved by #1856 and then look into and merge that PR when I've made a quick review (probably later today).

**Closed by lervag** 2020-11-20 17:31 UTC

**Comment by matze-dd** [comment] 2020-11-20 18:21
> Do I understand correctly that the PR now, at least in theory, should solve the present issue?

I've invested quite some work and made (and documented) mistakes in that process. Hopefully, the contribution will be useful in practice, too.

**Comment by lervag** [comment] 2020-11-20 18:24
Great. Thank you very much for looking into and fixing this, @matze-dd!

**Comment by matze-dd** [comment] 2020-11-23 18:05
> Great. Thank you very much for looking into and fixing this, @matze-dd!

Thank you for the kind words. In the end, the circular path also led to a bug fix for YaLafi and more experience with `errorformat`'s magic ;)
