### ISSUE TITLE
Keeping the log open

### ISSUE THREAD

**Issue by 927589452** [lervag/vimtex#1449] opened 2019-08-12 14:38 UTC
Sometimes I want to view the full log file, so I would use `:VimtexLog` or `\lq`, but it closes when I try to move around

Keep it open until manually closed.

Its not my `.vimrc`, behaviour is repeatable with the `test/issue/1440` example

**Comment by lervag** [comment] 2019-08-12 18:28
You should be more explicit. What do you mean with "when I try to move around"? The log window will be wiped when it is hidden/closed. And the `q` key is mapped so as to close it. Else things should work as expected.

**Comment by lervag** [comment] 2019-08-12 18:29
The issue template is quite clear in that you should state which steps you are doing (please be explicit!), and to note the observed and expected behaviour.

**Comment by 927589452** [comment] 2019-08-12 20:33
I used the FR template, as I imagined it being a design choice.

to reproduce:
change into the `issues/1440`
`vim --servername VIM -u minivimrc-plug main1.tex`
press `\lq` to open the log
press an arrow key
log is closed and one of the letters `A`,`B`,`C`,`D` is inserted

(arrow keys work inside the normal buffer)

it seems the buffer of the log file is behaving differently

**Comment by lervag** [comment] 2019-08-12 21:05
Ok, the reason is that I've mapped `<esc>` to close the window. The arrow keys are based on escape sequences which begin with the escape character. If you use `hjkl` instead, things work as expected.

**Comment by 927589452** [comment] 2019-08-12 21:14
Ah thanks for explaining, should I add one or two lines on it to the documentation?

**Comment by lervag** [comment] 2019-08-12 21:18
No problem. I've made a minor update to the docs now. I did not comment on the arrow keys, but I did mention that both `q` and `<esc>` are mapped to quit. I think that should suffice.

**Closed by lervag** 2019-08-12 21:18 UTC
Labels: enhancement
