### ISSUE TITLE
Startup Error "List or Blob required"

### ISSUE THREAD

**Issue by ryleelyman** [lervag/vimtex#2188] opened 2021-10-01 15:58 UTC
### Description

When opening a LaTeX file in a project I get the following error:
<img width="1437" alt="Screen Shot 2021-10-01 at 11 45 41 AM" src="https://user-images.githubusercontent.com/46907231/135649540-a0503074-1bf7-4ab3-9bc7-3b1425ae65e8.png">

After this it appears that VimTeX fails to load; expected commands like `gf`, `\ll` and others do not work, and `:VimtexInfo` returns "Not an editor command".

### Steps to reproduce

Minimal test file:
``` lua
vim.g.maplocallleader = '\\'
vim.cmd 'packadd packer.nvim'

return require('packer').startup(function(use)
	use 'lervag/vimtex'
end)
```

Minimal test tex file: (opening `test.tex` as a new file works fine. After writing this and invoking `:e preamble.tex` I get the error above.)
``` latex
\documentclass{article}
\input{preamble}

\begin{document}
\input{content}
\end{document}
```

### Expected behavior

Vimtex to load

### Actual behavior

The error mentioned above:
<img width="1437" alt="Screen Shot 2021-10-01 at 11 45 41 AM" src="https://user-images.githubusercontent.com/46907231/135651007-1d4002da-c080-4753-ab47-cab4f307ef13.png">
 

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
This is what I get when running `:VimtexInfo` on the above file after saving it.
I also get a similar error to the one described above.

System info
  OS: macOS 11.5.2 (20G95)
  Vim version: NVIM v0.6.0-dev+368-g9337fff8a
  Has clientserver: true
  Servername: /var/folders/2y/hwll5x9j6271lr30klvck8f80000gn/T/nvimmPPTRh/0
```

If I instead run `:VimtexInfo` on a completely blank TeX document I get
```
System info
  OS: macOS 11.5.2 (20G95)
  Vim version: NVIM v0.6.0-dev+368-g9337fff8a
  Has clientserver: true
  Servername: /var/folders/2y/hwll5x9j6271lr30klvck8f80000gn/T/nvimmPPTRh/0

VimTeX project: test2
  base: test2.tex
  root: /Users/rylee/.config/nvim
  tex: /Users/rylee/.config/nvim/test2.tex
  main parser: current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
```

**Comment by clason** [comment] 2021-10-01 16:03
I cannot reproduce this (same Neovim version on macOS). Make sure you don't have stale packages lying around (`set packpath=` in your `init.vim` and add `vimtex` to `rtp` directly as in the issue template).

Also, how did you install Neovim?

**Comment by ryleelyman** [comment] 2021-10-01 16:04
`brew install --HEAD`. I'll try that suggestion now

**Comment by clason** [comment] 2021-10-01 16:08
Can you try building directly from the repo?

**Comment by ryleelyman** [comment] 2021-10-01 16:10
sure, I can try that. It started breaking on an earlier version of neovim after I did `:PackerSync`.

**Comment by clason** [comment] 2021-10-01 16:11
yeah, there were some vim patches related to blobs that got ported recently, but I wouldn't expect such breakage.

**Comment by ryleelyman** [comment] 2021-10-01 16:21
I built neovim from source, and now I get the same error with the following `init.vim`:
```vim
set nocompatible
set packpath=
let &runtimepath  = '~/.local/share/nvim/site/pack/packer/start/vimtex,' . &runtimepath
let &runtimepath .= ',~/.local/share/nvim/site/pack/packer/start/vimtex/after'
filetype plugin indent on
syntax enable
```

**Comment by clason** [comment] 2021-10-01 16:24
Hmm, that's the same I do. Maybe I'm not following the steps exactly. Could you make them more explicit ("step 1, step 2, step 3... crash?")

**Comment by ryleelyman** [comment] 2021-10-01 16:34
Step 1: `nvim --clean -u ~/.config/nvim/minit.vim` (that's what I've called it)
Step 2: `:e test.tex`
Step 3: Type in
```
\documentclass{article}
\input{preamble.tex}
\begin{document}
arst
\end{document}
```
Step 4: `:w`, `:e preamble.tex` gives the crash.

**Comment by clason** [comment] 2021-10-01 16:36
Nope, sorry, can't reproduce. Do I actually need to _type_ it (because I just copy&paste, because I'm lazy...)

**Comment by ryleelyman** [comment] 2021-10-01 16:37
Surely you shouldn't need to type it.

**Comment by ryleelyman** [comment] 2021-10-01 19:51
Doing `commit = "fbe94cd3eaed89d6c1236af486466b1fcc3b82c9"` fixes the issue for me, but any newer and I still get the error.

**Comment by lervag** [comment] 2021-10-01 20:24
AFK, but: try  :VimtexClearCache kpsewhich

**Comment by lervag** [comment] 2021-10-01 21:16
So, first: Sorry for this. I recently made some changes to the kpsewhich caching which makes old cache files invalid. I documented it in the commit log and was planning to announce this in the next release. However, I now see that it is better to give a proper and helpful error message.

Please update, and if required, run `:VimtexClearCache kpsewhich`.

**Comment by ryleelyman** [comment] 2021-10-01 22:12
The plugin now does load and functions fine, but I get asked to run `:VimtexClearCache kpsewhich` essentially in all situations where previously there was an error. Running the command does fix the issue each time. Should I expect this business of needing to run the command a lot to sort itself out over time?

**Comment by lervag** [comment] 2021-10-02 08:57
> The plugin now does load and functions fine, but I get asked to run `:VimtexClearCache kpsewhich` essentially in all situations where previously there was an error. Running the command does fix the issue each time. Should I expect this business of needing to run the command a lot to sort itself out over time?

No, this is very unexpected. I'm sorry for the invonvenience!

So, how to debug this... It could be helpful to see the content of your cache file. It should live at `~/.cache/vimtex/kpsewhich.json`; I believe this is the same for MacOS as on Linux. Could you copy the file (or some of it, if it is very long) here?

Perhaps there's a minor bug I'm unaware of. So another alternative is that you make a fully minimal example. If you can make a reproducible sample, then I should be able to fix it.

**Comment by ryleelyman** [comment] 2021-10-02 14:32
I actually don't have a file at `~/.cache/vimtex/kpsewhich.json`!

**Comment by ryleelyman** [comment] 2021-10-02 14:36
oh you know what, this is because I use [TinyTeX](https://yihui.org/tinytex/) rather than TeXLive. I did `tlmgr search --global kpsewhich` which gave me the `ltxfileinfo` package as a result. Installing that with `tlmgr install ltxfileinfo` and then running `fmtutil-sys -all` seems to have solved the issue for me.

**Comment by ryleelyman** [comment] 2021-10-02 14:48
Sorry, I spoke too soon; the errors are still cropping up. It is odd that my file at `~/.cache/vimtex/kpsewhich.json` is blank.

**Comment by lervag** [comment] 2021-10-02 19:49
Yes, very odd indeed!

Can you try your original minimal example again, but this time add `let g:vimtex_cache_root = '.'` to the `test.vim` file? Does it work now, when you follow the outlined steps? Does this create the `kpsewhich.json` file?

Could you run `nvim --headless -u test.vim` with this `test.vim` and show me the output?

```vim
set nocompatible
" NB: Use the proper path here - I may have been mistaken!
set runtimepath^=~/.local/share/nvim/site/pack/packer/start/vimtex
filetype plugin on

setfiletype tex

let s:cache = vimtex#cache#open('kpsewhich')
unsilent echo s:cache
quitall
```

**Comment by ryleelyman** [comment] 2021-10-02 23:43
```
{'has': function('39'), 'read': function('42'), 'data': {}, 'clear': function('43'), 'name': 'kpsewhich', 'persistent': 1, 'set': function('40'), 'modified': 0, 'local': 0, 'write': function('41'), 'get': function('38'), 'ftime': -1, 'path': '/Users/rylee/.cache/vimtex/kpsewhich.json'}% 
```

**Comment by ryleelyman** [comment] 2021-10-02 23:54
When I add `let g:vimtex_cache_root = '.'` to the minimal `.vim` file, not only does it run without errors, there *is* a `kspewhich.json` file created (in my root directory), whose contents are:

``` json
{"preamble.tex": [["", "/Users/rylee"]]}
```

This is after the following steps:
- `nvim --clean -u ~/.config/nvim/minit.vim`
- `:e test.tex`
- type 
``` latex
\documentclass{article}
\input{preamble.tex}
\begin{document}
[...]
\end{document}
```
- `:w`, I tried `gf` on `preamble.tex` and neovim stopped responding until I did `<C-c>` (Presumably there are lots of files in my root directory to check whether there exists `preamble.tex`
- `:e preamble.tex`, write some stuff and save.

**Comment by ryleelyman** [comment] 2021-10-02 23:59
In case it's useful, `~/.cache/vimtex/` has plenty of `.json` files in it of the form `bibcomplete%path%to%paper%main.json` or `bibfiles%...`, `refcomplete%...` and one called `pkgcomplete.json`, just no `kpsewhich.json`.

**Comment by ryleelyman** [comment] 2021-10-03 00:08
I got a little ambitious and just put `g:vimtex_cache_root = '/Users/rylee/.cache/vimtex'` in my `~/.config/nvim/plugin/vimtex.vim` file and so far I haven't been asked to do `:VimtexClearCache kpsewhich` in situations where I otherwise have been today.

**Comment by lervag** [comment] 2021-10-03 09:33
> I got a little ambitious and just put `g:vimtex_cache_root = '/Users/rylee/.cache/vimtex'` in my `~/.config/nvim/plugin/vimtex.vim` file and so far I haven't been asked to do `:VimtexClearCache kpsewhich` in situations where I otherwise have been today.

Interesting. Does the file exist now?

**Comment by lervag** [comment] 2021-10-03 09:34
I have to admit this issue annoys me, because as far as I can see, everything _should_ work; you should _not_ need to set the `g:vimtex_cache_root` yourself, especially if you use the default value. And I get annoyed when I don't understand things... :p

**Comment by ryleelyman** [comment] 2021-10-03 18:01
Yeah, now it has content like the following
``` json
{"./figures/#1.pdf_tex": [["", "/Users/rylee"], ["", "/Users/rylee/Research/Papers/TrainTracksonGraphsofGroups"], ["", "/Users/rylee/Dropbox/Research/Papers/TrainTracksonGraphsofGroups"], ["", "/Users/rylee/Research/Papers/SimplyConnectedatInfinity"]]}
```

**Comment by lervag** [comment] 2021-10-03 20:49
Great, that looks quite right. What happens if you comment out `let g:vimtex_cache_root ... ` now? Does it stop working?

**Comment by ryleelyman** [comment] 2021-10-04 12:44
It seems to still work!

**Comment by lervag** [comment] 2021-10-04 13:30
Great. I'll close the issue, then, even thought I still don't understand everything... :p

**Closed by lervag** 2021-10-04 13:30 UTC
Labels: bug
