### ISSUE TITLE
vimtex_complete_bib not populated at neovim startup

### ISSUE THREAD

**Issue by pbethke** [lervag/vimtex#1397] opened 2019-05-29 08:35 UTC
**Description**
```g:vimtex_complete_bib``` is not populated at neovim startup.
I wanted to only change the "simple" field and leave the rest at default values.

**Steps to reproduce**
  ```vim
let g:vimtex_complete_bib.simple = 1
  ```
gives the vim error ```E121: Undefined variable: g:vimtex_complete_bib```.
Opening a tex file, then sourcing the vimrc again works fine.

This might also be intended behavior.

**Comment by kiryph** [comment] 2019-05-29 12:39
You need to declare that `g:vimtex_complete_bib` is a dictionary:

```
let g:vimtex_complete_bib = {}
let g:vimtex_complete_bib.simple = 1
```

or alternatively
```
let g:vimtex_complete_bib = { 'simple': 1 }
```

(it is not a bug)

**Comment by kiryph** [comment] 2019-05-29 12:47
If you are interested in learning a little bit about dictionaries in vimscript checkout following resources

- [`:h dict`](https://vimhelp.org/eval.txt.html#Dictionary)
- [`:h expr-entry`](https://vimhelp.org/eval.txt.html#expr-entry)
- [*Learn Vimscript the Hard Way* Chapter 37 *Dictionaries*](http://learnvimscriptthehardway.stevelosh.com/chapters/37.html)

**Comment by pbethke** [comment] 2019-05-29 12:51
thank you. I wasn't sure whether the default values would be filled in if i declare the full dictionary (in either of your proposed ways). I guess this can be closed then.

**Comment by lervag** [comment] 2019-05-29 13:34
Thanks for helping, @kiryph! I'll close this as it is resolved now.

@pbethke Undefined keys in a dictionary will generally get the default value that is specified in the docs.

**Closed by lervag** 2019-05-29 13:34 UTC
Labels: bug

**Comment by kiryph** [comment] 2019-05-29 13:39
@pbethke 
> I wasn't sure whether the default values would be filled in if i declare the full dictionary (in either of your proposed ways)

I understand your concern.

Afaik following piece of code extends user specified options by defaults and does not overwrite them:

https://github.com/lervag/vimtex/blob/1080706daf15b088192f13a497f8e3c1792fdeb9/autoload/vimtex.vim#L291-L300

Maybe the help section for the option `g:vimtex_complete_bib` could get an explicit example as well.

**Comment by lervag** [comment] 2019-05-29 13:44
> Maybe the help section for the option g:vimtex_complete_bib could get an explicit example as well.

Do you have a concrete suggestion?

**Comment by kiryph** [comment] 2019-05-29 13:58
see PR #1398

**Comment by lervag** [comment] 2019-05-29 16:18
Thanks, @kiryph!
