### ISSUE TITLE
`Error detected while processing function vimtex#init` with a specific file name and directory setup

### ISSUE THREAD

**Issue by guiniol** [lervag/vimtex#921] opened 2017-07-26 08:11 UTC
### Explain the issue

When I open any of the files in `anydir/` or its subdirectory, I get the following error, and vimtex doesn't know where is the main file so it can't start compilation or show the current page or do completion.
```
Error detected while processing function vimtex#init[5]..<SNR>25_init_state[1]..vimtex#state#init[1]..<SNR>27_get_main[61]..<SNR>27_g
et_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recur
se[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>
27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_r
ecurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<
SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_ma
in_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28
]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_ge
t_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurs
e[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>2
7_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_re
curse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<S
NR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_mai
n_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]
..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get
_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse
[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27
_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_rec
urse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SN
R>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main
_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28].
.<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_main_recurse[28]..<SNR>27_get_
main_recurse[28]..<SNR>27_get_main_recurse:
line   10:
E132: Function call depth is higher than 'maxfuncdepth'
```

The problem seems to be the fact that one of the file is named `method.tex`. This file can be the first `\input`ed file or not. Also, the `\input` can be commented (but not deleted).
Here is a zip file with the basic vimrc and the files to trigger the error: [bug.zip](https://github.com/lervag/vimtex/files/1175860/bug.zip)
The `\inputs` in `main.tex` and in `anything.tex` can be commented and the bug still triggers. If `method.tex` is renamed, the bug doesn't trigger.

**Comment by lervag** [comment] 2017-08-02 09:42
Thanks, this should be fixed now.

**Closed** 2017-08-02 09:42 UTC

**Comment by guiniol** [comment] 2017-08-03 08:05
It works! Thank you so much.

**Comment by lervag** [comment] 2017-08-03 08:17
No problem; thank you for submitting a good issue description. I reproduced immediately and was quickly able to find the bug (although fixing it was harder than expected). :)

**Comment by guiniol** [comment] 2017-08-03 09:09
With the time vimtex saves me, it was the least I could do. I must say, it took a while to identify the exact triggering condition. And reading the fix, I don't even see why that precise filename was problematic.

**Comment by lervag** [comment] 2017-08-03 09:18
The problem was that I did not properly handle the list of already checked files while searching for the main file recursively. Thus your example put us into an infinite loop. I've added a dictionary that keeps track of the list of tried files for each file.

I also had to allow a function to continue to the next candidate if the current candidate was wrong. The old code did not allow this.

**Comment by lervag** [comment] 2017-08-03 09:19
Thus, there were actually two errors. Your example found both. :)

**Comment by guiniol** [comment] 2017-08-03 12:41
I got lucky with my example then! Guess I'm lucky at finding bugs ^^

**Comment by lervag** [comment] 2017-08-03 12:43
Feel free to find more :+1:

**Comment by guiniol** [comment] 2017-08-03 18:11
Don't worry, you'll be the first to know ^^

**Comment by aragonl** [comment] 2017-09-16 00:41
I have the same problem when using other filenames. I use Vundle to use the vimtex plugin. How do I know if I'm using vimtex with this bug fixed? (I've no idea how git-Vundle-vimtex work). thanks for any comment.

**Comment by guiniol** [comment] 2017-09-17 08:54
@aragonl the best way would be to update the plugin to the latest version. You'll want to do that before opening a bug report to make sure that it is present on the latest version. Otherwise, check that you have commits from after Aug. 3 in the git log.

**Comment by aragonl** [comment] 2017-09-17 12:55
@guiniol thanks! I now have the latest version and indeed this issue is solved! 
But also, with the update a new issue appeared. Should I report it separately? 

When the folder's name has the symbol `~` it gives the following error:

> 
> Error detected while processing function vimtex#init[5]..<SNR>25_init_state[1]..vimtex#state#init[9]..3[29]..9[5]..vimtex#paths#relative:
> E33: No previous substitute regular expression

This is quite inconvenient for the projects I have in my iCloud folder since the system names the directory `com~apple~CloudDocs` and even if I change the name with a link the problem persists.

**Comment by guiniol** [comment] 2017-09-17 22:31
@aragonl Great!
It's usually better to report issues separately, so please open a new issue and report the error.
