### ISSUE TITLE
User autocommands broken after commit 00ed2f1

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#2166] opened 2021-09-11 11:16 UTC
### Description

The latest commit https://github.com/lervag/vimtex/commit/00ed2f1612599c07de8d77cc85b4c1becfd1ae0f broke user autocommands; specifically the line https://github.com/lervag/vimtex/blob/00ed2f1612599c07de8d77cc85b4c1becfd1ae0f/syntax/tex.vim#L43
(removing the `<buffer>` avoids the error).

### Steps to reproduce

Use the following `mini.vim` (to avoid interference from installed packages):
```vim
let rtp = $VIMRUNTIME
let packpath = $VIMRUNTIME .. '/site'
set nocompatible
let &runtimepath  = '~/.local/share/nvim/site/pack/packer/start/vimtex,' . &runtimepath
let &runtimepath .= ',~/.local/share/nvim/site/pack/packer/start/vimtex/after'
filetype plugin indent on
syntax enable
```

1. `nvim --clean -u min.vim test.tex`
2. `:doautocmd User Foo`

(These steps are pointless but minimal; they reproduce similar errors from the builtin LSP client and Telescope when opening `tex` buffers, for example.)

### Actual behavior

```
Error detected while processing User Autocommands for "<buffer=1>":
E492: Not an editor command: VimtexEventInitPost call vimtex#syntax#core#init_post()
```

### VimtexInfo

```yaml
Vim version: NVIM v0.6.0-dev+249-g086631cd9
```

**Comment by Konfekt** [comment] 2021-09-11 14:19
Since this commit, opening a pandoc file with [vim-pandoc])https://github.com/vim-pandoc/vim-pandoc/issues/415) installed shows the error messages

```vim
Errore/i eseguendo User Auto comandi per "<buffer=2>":
E492: Non è un comando dell'editor: VimtexEventInitPost call vimtex#syntax#core#in
it_post()
Errore/i eseguendo function startify#open_buffers[13]..<SNR>321_open_buffer:
riga   12:
E171: Manca :endif
Errore/i eseguendo function startify#open_buffers:
```

Reverting back the latest commit (v 2.7) fixes this issue.

**Comment by storopoli** [comment] 2021-09-11 15:02
I can confirm that it broke both my mac nvim and linux nvim.

**Comment by jiajia2u** [comment] 2021-09-11 15:49
My UltiSinps is broken after this update.
After rolling back to vimtex-2.6, everything becomes fine.

**Comment by clason** [comment] 2021-09-11 16:10
Fixed indeed, thank you!

**Comment by lervag** [comment] 2021-09-11 16:11
Fixed now. I'm sorry for introducing the bug just before releasing v2.7.  But I believe most people more or less follow the latest version from github.

**Comment by clason** [comment] 2021-09-11 16:11
Probably want to cut a quick v2.7.1 nevertheless?

**Comment by lervag** [comment] 2021-09-11 16:12
> Fixed indeed, thank you!

Thanks for providing the useful and to the point issue description; and for noticing and reporting immediately!

**Comment by lervag** [comment] 2021-09-11 16:13
> Probably want to cut a quick v2.7.1 nevertheless?

Done.

**Closed** 2021-09-11 16:13 UTC
Labels: bug
