### ISSUE TITLE
vimtex_syntax_filetype on FreeBSD

### ISSUE THREAD

**Issue by 927589452** [lervag/vimtex#1428] opened 2019-07-22 22:35 UTC
**Describe the issue**
The error message
```
vimtex: "syntax on" seems to be applied before "filetype plugin on".
        This is suboptimal, because some syntax features require an initialized st
ate.
        Please see ":help vimtex_syntax_filetype".
```
appears, even when using @junegunn s vim-plug

**Steps to reproduce**

```vim
" ~/minivimrc
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
```

Running `´vim -u ~/minivimrc file.tex `works, but running ´`vim file.tex´` yields the error. Further, with minimal vimrc as vimrc it runs without error.

With this a my vimrc, the error returns:
```vim
set nocompatible

call plug#begin('$HOME/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()
```

There is no problem if the vimrc is sourced with `-u`.

By some fiddeling around, I found the problem. It seems the below vimrc shows the same behaviour for `-u` and vimrc:

```vim
set nocompatible
source $VIMRUNTIME/defaults.vim
call plug#begin('$HOME/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()
```

So my vim is sourcing the defaults.vim from somewhere or does something similiar.

I found #1354. Because of #1394, I looked at the `:scriptnames` and got a difference:
```
 with `-u`                                   | with ~/.vimrc
--- Scripts sourced ---                |  --- Scripts sourced ---
    1: ~/.vimrc                          |    1: /usr/local/etc/vim/vimrc
    2: ~/.vim/autoload/plug.vim          |    2: /usr/local/share/vim/vim81/syntax
    3: /usr/local/share/vim/vim81/filetyp|    3: /usr/local/share/vim/vim81/syntax
    4: /usr/local/share/vim/vim81/ftplugi|    4: /usr/local/share/vim/vim81/syntax
    5: /usr/local/share/vim/vim81/indent.|    5: /usr/local/share/vim/vim81/filety
    6: /usr/local/share/vim/vim81/syntax/|    6: ~/.vimrc
    7: /usr/local/share/vim/vim81/syntax/|    7: ~/.vim/autoload/plug.vim
```

and a short look into `/usr/local/etc/vim/vimrc` shows:
```
...
try
    syntax on         " Enable syntax highlighting
catch | endtry        " vim-tiny is installed without the syntax files
...
```

and adding this file to our minimalrc reproduces the problem for both variants again,

```vim
set nocompatible
source /usr/local/etc/vim/vimrc
call plug#begin('$HOME/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()
```

but the syntax highighting has been there for a [time](https://svnweb.freebsd.org/ports/head/editors/vim/files/vimrc?r1=382520&r2=503239) and either I didn't realize it until now or the modifications of loading order trigger this now.

I could probably override the systemincluded file, so this might be a won't fix @lervag, but I hope if it is, it is at least a read saving other people this time.

----

Edited by @lervag: Removed some unnecessary content and improved formatting.

**Comment by ruifm** [comment] 2019-07-22 23:14
I have the same issue. If more information is required I can provide it on demand so as to avoid duplication.

Seems to be a duplicate of #1354 , #1387 and #1394 . Maybe it reappeared because of a vim-plug update.

**Comment by 927589452** [comment] 2019-07-23 06:01
So I had a look with fresh eyes this morning

```
   **1: /usr/local/etc/vim/vimrc**
  **2: /usr/local/share/vim/vim81/syntax/syntax.vim**
  **3: /usr/local/share/vim/vim81/syntax/synload.vim**
  **4: /usr/local/share/vim/vim81/syntax/syncolor.vim**
   **5: /usr/local/share/vim/vim81/filetype.vim**
  **6: ~/.vimrc**
  **7: ~/.vim/autoload/plug.vim**
  8: /usr/local/share/vim/vim81/ftoff.vim
  9: /usr/local/share/vim/vim81/ftplugin.vim
 10: /usr/local/share/vim/vim81/indent.vim
 11: /usr/local/share/vim/vim81/plugin/getscriptPlugin.vim
 12: /usr/local/share/vim/vim81/plugin/gzip.vim
 13: /usr/local/share/vim/vim81/plugin/logiPat.vim
 14: /usr/local/share/vim/vim81/plugin/manpager.vim
 15: /usr/local/share/vim/vim81/plugin/matchparen.vim
 16: /usr/local/share/vim/vim81/plugin/netrwPlugin.vim
 17: /usr/local/share/vim/vim81/plugin/rrhelper.vim
 18: /usr/local/share/vim/vim81/plugin/spellfile.vim
 19: /usr/local/share/vim/vim81/plugin/tarPlugin.vim
 20: /usr/local/share/vim/vim81/plugin/tohtml.vim
 21: /usr/local/share/vim/vim81/plugin/vimballPlugin.vim
 22: /usr/local/share/vim/vim81/plugin/zipPlugin.vim
 **23: /usr/local/share/vim/vim81/autoload/dist/ft.vim**
 **24: /usr/local/share/vim/vim81/syntax/tex.vim**
 **25: ~/.vim/plugged/vimtex/after/syntax/tex.vim**
 26: /usr/local/share/vim/vim81/syntax/dot.vim
 27: /usr/local/share/vim/vim81/syntax/lua.vim
 28: /usr/local/share/vim/vim81/syntax/gnuplot.vim
 **29: ~/.vim/plugged/vimtex/ftplugin/tex.vim**
 **30: ~/.vim/plugged/vimtex/autoload/vimtex.vim**
 31: ~/.vim/plugged/vimtex/autoload/vimtex/util.vim
 32: ~/.vim/plugged/vimtex/autoload/vimtex/log.vim
 33: ~/.vim/plugged/vimtex/autoload/vimtex/debug.vim
 34: ~/.vim/plugged/vimtex/autoload/vimtex/echo.vim
 35: ~/.vim/plugged/vimtex/autoload/vimtex/state.vim
 36: ~/.vim/plugged/vimtex/autoload/vimtex/re.vim
 37: ~/.vim/plugged/vimtex/autoload/vimtex/paths.vim
 38: ~/.vim/plugged/vimtex/autoload/vimtex/parser.vim
 39: ~/.vim/plugged/vimtex/autoload/vimtex/parser/general.vim
 40: ~/.vim/plugged/vimtex/autoload/vimtex/view.vim
 41: ~/.vim/plugged/vimtex/autoload/vimtex/view/general.vim
 42: ~/.vim/plugged/vimtex/autoload/vimtex/view/common.vim
 43: ~/.vim/plugged/vimtex/autoload/vimtex/compiler.vim
 44: ~/.vim/plugged/vimtex/autoload/vimtex/compiler/latexmk.vim
 45: ~/.vim/plugged/vimtex/autoload/vimtex/qf.vim
 46: ~/.vim/plugged/vimtex/autoload/vimtex/qf/latexlog.vim
 47: ~/.vim/plugged/vimtex/autoload/vimtex/toc.vim
 48: ~/.vim/plugged/vimtex/autoload/vimtex/fold.vim
 49: ~/.vim/plugged/vimtex/autoload/vimtex/fold/envs.vim
 50: ~/.vim/plugged/vimtex/autoload/vimtex/fold/cmd_single_opt.vim
 51: ~/.vim/plugged/vimtex/autoload/vimtex/fold/markers.vim
 52: ~/.vim/plugged/vimtex/autoload/vimtex/fold/preamble.vim
 53: ~/.vim/plugged/vimtex/autoload/vimtex/fold/sections.vim
 54: ~/.vim/plugged/vimtex/autoload/vimtex/fold/cmd_addplot.vim
 55: ~/.vim/plugged/vimtex/autoload/vimtex/fold/env_options.vim
 56: ~/.vim/plugged/vimtex/autoload/vimtex/fold/cmd_multi.vim
 57: ~/.vim/plugged/vimtex/autoload/vimtex/fold/cmd_single.vim
 58: ~/.vim/plugged/vimtex/autoload/vimtex/cmd.vim
 59: ~/.vim/plugged/vimtex/autoload/vimtex/complete.vim
 60: ~/.vim/plugged/vimtex/autoload/vimtex/delim.vim
 61: ~/.vim/plugged/vimtex/autoload/vimtex/doc.vim
 62: ~/.vim/plugged/vimtex/autoload/vimtex/env.vim
 63: ~/.vim/plugged/vimtex/autoload/vimtex/format.vim
 64: ~/.vim/plugged/vimtex/autoload/vimtex/fzf.vim
 65: ~/.vim/plugged/vimtex/autoload/vimtex/imaps.vim
 66: ~/.vim/plugged/vimtex/autoload/vimtex/include.vim
 67: ~/.vim/plugged/vimtex/autoload/vimtex/info.vim
 68: ~/.vim/plugged/vimtex/autoload/vimtex/kpsewhich.vim
 69: ~/.vim/plugged/vimtex/autoload/vimtex/matchparen.vim
 70: ~/.vim/plugged/vimtex/autoload/vimtex/misc.vim
 71: ~/.vim/plugged/vimtex/autoload/vimtex/motion.vim
 72: ~/.vim/plugged/vimtex/autoload/vimtex/pos.vim
 73: ~/.vim/plugged/vimtex/autoload/vimtex/process.vim
 74: ~/.vim/plugged/vimtex/autoload/vimtex/profile.vim
 75: ~/.vim/plugged/vimtex/autoload/vimtex/scratch.vim
 76: ~/.vim/plugged/vimtex/autoload/vimtex/text_obj.vim
 77: /usr/local/share/vim/vim81/ftplugin/tex.vim
 **78: ~/.vim/plugged/vimtex/after/ftplugin/tex.vim**
 79: ~/.vim/plugged/vimtex/indent/tex.vim
 80: /usr/local/share/vim/vim81/indent/tex.vim
 81: /usr/local/share/vim/vim81/bugreport.vim
-
```

if we could a) register being run by vimplug and b) add a reload of the sytax after the filetype plugin, we could mitigate this problem at least for everybody running a plugin manager

**Comment by 927589452** [comment] 2019-07-23 06:16
> Seems to be a duplicate of #1354 , #1387 and #1394 . Maybe it reappeared because of a vim-plug update.

its not exactly #1387, as there was a filetype plugin setting syntax
#1354 is probably at fault here, as the warning was introduced because of it
though @voldikss (comment)[https://github.com/lervag/vimtex/issues/1354#issuecomment-482038050]and @Geremias (comment)[https://github.com/lervag/vimtex/issues/1354#issuecomment-482331106] sound similiar
#1394 was a problem based on ondemand loading of vimtex

**Comment by lervag** [comment] 2019-07-23 23:02
This is getting annoying (this issue, not you!). The warning message was added because the syntax plugin uses the filetype plugin, and so the load order is important. I think I'll try to find a different way to do this which should solve the issue once and for all.

My initial idea is something like:

1. Check if vimtex ftplugin is loaded.
2. If it is, then load syntax as usual. Done.
3. It not: Stop loading (vimtex) syntax additions and request that vimtex ftplugin resources the syntax after initialization.

This should be relatively simple to do through autocommands and hooks. I'll work on it when I get the time.

PS! Sorry about lagging behind on issues. Vacation and all.

**Comment by ruifm** [comment] 2019-07-24 00:31
@lervag come on, give yourself a break, you are doing this for free and I use vimtex almost everyday.
I can probably live for a while with a harmless warning.

**Comment by 927589452** [comment] 2019-07-24 06:13
On 19-07-23 16:02:37, Karl Yngve Lervåg wrote:
> This is getting annoying (this issue, not you!). The warning message was added because the syntax plugin uses the filetype plugin, and so the load order is important. I think I'll try to find a different way to do this which should solve the issue once and for all.
I'm glad I am not getting annoying; wrote a few reports and PRs in the
last weeks^^
>
> My initial idea is something like:
>
> 1. Check if vimtex ftplugin is loaded.
> 2. If it is, then load syntax as usual. Done.
> 3. It not: Stop loading (vimtex) syntax additions and request that vimtex ftplugin resources the syntax after initialization.
But this would break vimwiki again wouldn't it?
Oh I see, the idea is to split the vimtex specific tweaks( which needs
the ftplugin) and the rest; this sounds good if possible.
>
> This should be relatively simple to do through autocommands and hooks. I'll work on it when I get the time.
>
> PS! Sorry about lagging behind on issues. Vacation and all.
Take your vacation; I plan to use vimtex for quite a while to come, so
no use in you burning out ;)
Enjoy it

**Comment by kiryph** [comment] 2019-07-24 07:19
I agree that this message has led to too many issues and raised comments.

@lervag  Sorry for having you pushed into this direction with #1354.

I would propose to remove the message and add a note to `:h vimtex-syntax` and an entry to the `:h vimtex-faq` about the order of `syntax on` and `filetype plugin on`.

In particular, `defaults.vim` of vim8 has the "wrong" order and therefore people who want syntax highlighting for `biblatex, listings, cleveref, minted, dot2tex, lualatex, gnuplottex, asymptote, pythontex` etc have to add to their vimrc:

```viml
filetype plugin on
syntax on
```

We simply have to live in times of vim8 with the order in defaults.vim.

BTW not all package related additions in `vimtex/after/syntax/tex.vim` are guarded by lines like

```viml
if exists('b:vimtex.packages.tabularx') || exists('b:vimtex.packages.array')
...
if exists('b:vimtex.packages.array')
...
if exists('b:vimtex.packages.pythontex')
...
```

It is not a bad idea to restrict the number of syntax groups to have faster syntax highlighting. This could be a reason to add more lines like these for biblatex, csquotes, cleveref, asymptote, gnuplottex.

BTW, if all the nested syntax highlighting (minted, listings, gnuplottex, pythontex, asymptote, lua, dot) bog down a large LaTeX file, I would consider the variable `g:tex_fast=n` to disable nested syntax highlight on user request.

**Comment by lervag** [comment] 2019-07-24 16:16
Ok, long reply coming. First, to address the original issues from @927589452: As you yourself recognized, the problem is due to your distributions `vimrc` file, which includes `syntax on`. In my opinion, a distribution should not hijack the vimrc files!

----

@ruifm Thank you, I appreciate your comment! I'm very happy to see that there is an active community these days that helps me to respond to new issues and suggest actions for solving them (and even submitting PRs to directly solve them in some cases). I don't have as much time for vimtex as I used to, but I still want to keep it well maintained.

@927589452
> I'm glad I am not getting annoying; wrote a few reports and PRs in the last weeks^^

No problem! In my opinion, opening issues and submitting PRs is clearly a positive contribution, and I'm just happy for it.

It is very helpful if you can review your report before submitting. Please keep in mind:
- Use proper Markdown formatting.
- Use `` ` `` for inline code, not `´`.
- Also, there is no need for hardwrapping lines in github comments/reports.
- Try to be consistent. Try to only include what is relevant (I understand that
it is sometimes difficult to know _what_ is relevant).
- For simple comment replies, email is fine. But keep in mind that emails don't allow Markdown formatting,.

> But this would break vimwiki again wouldn't it?

I don't think so. But it is not clear in my mind how vimtex is loaded for Vimwiki. If I end up breaking Vimwiki, then feel free to open a new issue on this. :)

@kiryph
> @lervag Sorry for having you pushed into this direction with #1354.

Hah, no problem. It is not your fault, instead I agree it is an annoyance with the defaults. And in any case, I think vimtex should "just work", and so by adding the warnings I have become more aware of some edge cases that should be fixed.

> I would propose to remove the message and add a note to :h vimtex-syntax and an entry to the :h vimtex-faq about the order of syntax on and filetype plugin on.

I much rather want to fix this issue once and for all. If I can manage that, then I can also remove the warning message, and the issue will be fully resolved. Note that adding things to ones `vimrc` file is not sufficient, since the distribution vimrc is sourced first.

> BTW not all package related additions in vimtex/after/syntax/tex.vim are guarded by lines like ... It is not a bad idea to restrict the number of syntax groups to have faster syntax highlighting. This could be a reason to add more lines like these for biblatex, csquotes, cleveref, asymptote, gnuplottex.

I agree. I would appreciate if you (or someone else) opens this as a separate issue.

> BTW, if all the nested syntax highlighting (minted, listings, gnuplottex, pythontex, asymptote, lua, dot) bog down a large LaTeX file, I would consider the variable g:tex_fast=n to disable nested syntax highlight on user request.

Yes, that could be possible. But I would only consider it if proposed as a separate issue which also gives a clear example that the nested syntax highlighting gives a noticable lag.

**Comment by lervag** [comment] 2019-07-27 21:48
Ok, I think I've fixed this issue once and forall. Can anyone who has had this problem please test?

**Closed** 2019-07-27 21:48 UTC
Labels: bug

**Comment by 927589452** [comment] 2019-07-27 22:36
On 19-07-24 09:16:15, Karl Yngve Lervåg wrote:
> Ok, long reply coming. First, to address the original issues from @927589452: As you yourself recognized, the problem is due to your distributions `vimrc` file, which includes `syntax on`. In my opinion, a distribution should not hijack the vimrc files!
I feel you very much here, but as the systemwide file is always sourced,
I would love for vimtex to work on a system with an overproviding admin.
> ----
>
> > I'm glad I am not getting annoying; wrote a few reports and PRs in the last weeks^^
>
> No problem! In my opinion, opening issues and submitting PRs is clearly a positive contribution, and I'm just happy for it.
>
> It is very helpful if you can review your report before submitting. Please keep in mind:
> - Use proper Markdown formatting.
> - Use `` ` `` for inline code, not `´`.
> - Also, there is no need for hardwrapping lines in github comments/reports.
> - Try to be consistent. Try to only include what is relevant (I understand that
> it is sometimes difficult to know _what_ is relevant).
> - For simple comment replies, email is fine. But keep in mind that emails don't allow Markdown formatting,.

Will try to keep this in mindm but for example this bug report was
entered while debugging, so sorry for the bad style and I will try
improving
(linewrap may also come from me not properly cleaning my terminal
output.)
