### ISSUE TITLE
Brackets - Very Slow

### ISSUE THREAD

**Issue by rafaeluriarte** [lervag/vimtex#867] opened 2017-06-09 09:03 UTC
Good morning,

first of all, thank you for the great plugin. I am currently having  a small but annoying problem with it, when I open brackets in a tex file it takes quite a long time, 5 to 10 seconds ( "(", "{" ....). I tried adding the fastfold plugin but did not work. That's my minimum vimrc:

```vim
set rtp+=~/.vim/bundle/Vundle.vim/
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'lervag/vimtex'
call vundle#end()
filetype plugin indent on
syntax on
```

Vim version:

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 10 2017 00:49:42)
Included patches: 1-488, 576
Extra patches: 8.0.0378, 8.0.0377, 8.0.0322, 8.0.0056)
```

With small tex files it is much faster but while writing academic paper things get annoying (10 double column pages divided into 5 or 6 tex files). If you want I can send through email one example. I am pretty sure it is related to Issue #598 ("vimtex-indent causing slowdowns") since when I define "filetype plugin indent off " it works properly, but I cannot leave it off all the time. Ideas or suggestions?

Thank you,

**Comment by lervag** [comment] 2017-06-09 10:17
It would be good if you could also provide a small TeX sample where you notice the lag. You can either upload it as a file in a comment, or send it to my email.

Note, if this is due to indentation, then Fastfold obv. won't help. Also, it does not make sense to set `filetype plugin indent off`, because that will also disable vimtex entirely. Instead, you should try `let g:vimtex_indent_enabled = 0`.

**Comment by rafaeluriarte** [comment] 2017-06-09 13:29
thank you for the great work.  Setting:
"g:vimtex_indent_enabled = 0"
in the vimrc solves the problem. In any case I am sending to you through email an example in which you can reproduce the problem (if you don't add that option in the vimrc).

Thank you

**Comment by rafaeluriarte** [comment] 2017-06-09 13:30
thank you for the great work.  Setting:
"g:vimtex_indent_enabled = 0"
in the vimrc solves the problem. In any case I am sending to you through email an example in which you can reproduce the problem (if you don't add that option in the vimrc).

Thank you

**Comment by lervag** [comment] 2017-06-09 19:00
Thanks for the example! I've tried to reproduce the problem, but unfortunately, for me, the lag is barely noticable with my normal Vim configuration, and not noticable at all with a minimal vimrc file (see below). So, some questions:

1. Are you sure you are on the most recent version of vimtex?
2. Which version of Vim are you using? (or neovim)
3. Which OS are you on?

----

Please try the following minimal vimrc file (double check if we use the same bundle paths):

```vim
set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
```

**Comment by rafaeluriarte** [comment] 2017-06-10 08:21
Good Morning,


I tried with your vimrc and I still have the smae problem (with the same file I sent you). Please, find below the answers:


    Are you sure you are on the most recent version of vimtex?
I updated with Vundle a couple of days ago, so should be the most recent (how do I check the version?).

    Which version of Vim are you using? (or neovim)
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 10 2017 00:49:42)
Included patches: 1-488, 576
Extra patches: 8.0.0378, 8.0.0377, 8.0.0322, 8.0.0056)

    Which OS are you on?
Debian  8.8


I hope it helps,

thank you

**Comment by lervag** [comment] 2017-06-12 21:40
Ok, I've now tested this with the same version of Vim with a minimal vimrc file. I do not experience any lag at all.

This makes it very difficult to debug.

An obvious question: What kind of machine are you using? Personally, I'm testing with a Lenovo Yoga Pro 2, which has the intel i5-4210U CPU clocked at 1.7 GHz; 2 cores. I think this is pretty low-end, and so when I don't see any lag, I am suspecting that there might be other things that contribute to the lag for you.

Could you try to do some profiling on your end? Something like this:
1. Use my suggested minimal vimrc file (which does _not_ use vundle), load your example file with `vim -u minivimrc example.tex`.
2. Start profiling with `:profile start ~/timing.log`
3. Do one or more actions that you claim take a long time
4. Stop profiling with `:profile stop`

Feel free to send me the timing.log file if you can't analyse it yourself.

**Comment by rafaeluriarte** [comment] 2017-06-13 19:05
Thank you for the reply, I tried profiling with the vimrc you sent (and open {} in insert mode and takes many seconds when in the text, e.g., in the abstract, whilst  in the latex comments (e.g, "% {}{}{}") it is instantaneous) but had no output at all (file is empty). No worries, the "let g:vimtex_indent_enabled = 0" is working for me...

thank you again,

Best

**Comment by lervag** [comment] 2017-06-13 19:26
Ok. If you should ever feel that this needs to be resolved, then feel free to reopen or open a new issue. In the meantime, I'll take your "... is working for me..." as a sign that you think it is OK to close this issue for now.

Thanks!

**Closed by lervag** 2017-06-13 19:26 UTC

**Comment by zsteinberg** [comment] 2022-10-09 04:15
I ran into this issue in 2022, where scrolling with neovim and vimtex became unbearably slow in a file I was using with lots of inline math surrounded by \$ dollar signs \$. Adding `let g:vimtex_indent_enabled = 0` to my ~/.config/init.vim instantly eliminated the lag, but the fact that this workaround was needed means the issue in vimtex indenting is probably still lurking in the code. If it's been a few years and the issue hasn't gone away, it could be worth taking another look and trying to reproduce it.

**Comment by lervag** [comment] 2022-10-09 19:41
Sorry, but it's not that simple. Or, to be more specific: I don't really have any major issue with indentation. And unless someone opens an issue and provides an example of a specific performance issue, it is hard for me to improve things. So, feel free to open a new issue where you explain how to reproduce a particular slowdown. If you do, please include a minimal example. That is, a LaTeX file that is as small as possible for an issue to be reproduced. In this case, it may need to be quite large, for all I know.
