### ISSUE TITLE
Skim forward search not working on macOS 12.1

### ISSUE THREAD

**Issue by Zeta611** [lervag/vimtex#2279] opened 2021-12-14 08:30 UTC
### Description

I recently got an M1 Mac (if relevant) and setup Neovim + vimtex almost identically to my previous intel Mac.
However, forward search does not work anymore.

I installed both Neovim and Skim via Homebrew.

### Steps to reproduce

I invoked `neovim` with `NVIM_LISTEN_ADDRESS=/tmp/nvimsocket nvim -u minimal.vim minimal.tex`.

```vim
set nocompatible

let &runtimepath  = '~/.local/share/nvim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.local/share/nvim/plugged/vimtex/after'

filetype plugin indent on
syntax on

let g:vimtex_view_method = 'skim'
```

```tex
\documentclass{article}

\begin{document}
Hello, \TeX!
\end{document}
```

### Expected behavior

Forward search should work with `\ll` or `:VimtexView`.

### Actual behavior

Skim does not get focused nor 'forward-search'ed.

Initial `\ll` does wake Skim and open the document (without current line being focused).

Backward search does work properly.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 12.1 (21C52)
  Vim version: NVIM v0.6.0
  Has clientserver: true
  Servername: /tmp/nvimsocket

VimTeX project: test
  base: test.tex
  root: /Users/jay/Developer/TeXProjects/test
  tex: /Users/jay/Developer/TeXProjects/test/test.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Skim
  qf method: LaTeX logfile
```

**Comment by clason** [comment] 2021-12-14 08:39
That was quick :) Yes, macOS 12.1 broke Skim's forward search functionality, see https://sourceforge.net/p/skim-app/bugs/1438/

There's unfortunately nothing that can be done about it right now; we'll have to wait for the Skim dev to release a new version to work around these changes (if that is possible).

**Comment by Zeta611** [comment] 2021-12-14 09:06
So is it broken regardless of the CPU architecture in macOS 12.1?

**Comment by lervag** [comment] 2021-12-14 09:32
Yes. CPU architecture does not have any thing to do with this, I think - it is a software regression. And as @clason implies, there is nothing I can do currently from the VimTeX side except wait for updates on Skim. I believe @clason plans to submit a PR when Skim is updated, so stay tuned. :)

**Comment by clason** [comment] 2021-12-14 09:40
@lervag maybe leave it open or pin it? I expect this will get asked _a lot_ in the coming days...

**Comment by pbrosnan** [comment] 2021-12-16 03:48
I can't even get Skim to open now on macOS 12.1.   Thinking of switching to zathura while this is getting fixed.  BTW, Thanks for writing vimtex levrag!

**Comment by lervag** [comment] 2021-12-16 07:26
Thanks, @pbrosnan (and sorry about the state of Skim...  of course, you could just move over to the light side and use Linux 😃 )

**Comment by clason** [comment] 2021-12-17 11:40
Short update: On the linked Skim issue, there is now a prerelease that restores functionality on macOS 12.1 (go to the end of page 3), so the next release will Just Work again.

**Comment by lervag** [comment] 2021-12-17 18:25
That's great news! :)

**Comment by clason** [comment] 2021-12-17 18:30
Unfortunately, the 1.6.7 that was just released is apparently not the same as the last test version -- forward search is again not working 😞

**Comment by lervag** [comment] 2021-12-18 12:42
That's not so great news. :(

**Comment by clason** [comment] 2021-12-18 12:48
Unclear. There _was_ a (test) version that was working, so a fix is possible; the fact that the actual release based on this test didn't work anymore means that actual problem is still unclear. So it might take a bit longer, but I expect that a later release will indeed fix that (unless macOS 12.2, which is currently in beta, adds new breakages...)

**Comment by lervag** [comment] 2021-12-19 11:51
Ok; I'll keep my fingers crossed, then.

**Comment by uthpalaherath** [comment] 2021-12-20 16:53
Probably irrelevant, but I downgraded to skim version 1.6.4 to see if that did anything but it didn't. So I guess it's solely due to updating to MacOS 12.1. 

Thanks again @lervag for vimtex! Hopefully, we get the vimtex-skim integration working again. 

Cheers!

**Comment by clason** [comment] 2021-12-28 23:34
Apparently, you can also use JavaScript to control macOS apps -- which a) is a marginally less unpleasant language than AppleScript and b) doesn't seem to suffer from the same bug in macOS 12.1.

**Comment by sbryngelson** [comment] 2021-12-29 05:36
Can confirm this same issue on my macOS 12.1 machine as well. Using the latest, Skim 1.6.7

**Comment by lervag** [comment] 2021-12-29 23:07
I'll close this issue as it is now addressed in #2289. I will review the PR as soon as I have time!

**Closed by lervag** 2021-12-29 23:07 UTC
Labels: bug

**Comment by clason** [comment] 2022-01-22 15:31
@lervag I think that issue can be un-pinned now?

**Comment by lervag** [comment] 2022-01-22 15:32
Thanks, I forgot about that!
