### ISSUE TITLE
Inverse search not working when called from another Neovim instance or command line on macOS

### ISSUE THREAD

**Issue by 594212** [lervag/vimtex#2700] opened 2023-05-07 16:58 UTC
**Issue description**:
The `vimtex#view#inverse_search` function works as expected when called within the Neovim instance that has the TeX ``%file`` open(i.e. he jumps to specific ``%line``). However, it doesn't work when called from another Neovim instance or the command line using `--remote-send`, `--headless -c`, or a Python script. I have tried various methods to call the function remotely, but none of them work.

**Steps to reproduce**:
1. Open a TeX file in Neovim with the `--listen` option: `nvim --listen /tmp/nvimsocket /path/to/texfile.tex`
2. Try calling the `vimtex#view#inverse_search` function from another Neovim instance or the command line using the `--remote-send` command, `nvim --headless -c`, or a Python script.

**Expected behavior**:
The `vimtex#view#inverse_search` function should be called in the Neovim instance with the TeX file open, and the cursor should jump to the specified line number.

**Actual behavior**:
The function call doesn't seem to work, and the cursor doesn't move to the specified line number. Empty output.

**System information**:
- Neovim version: v0.9.0
- LuaJIT version: 2.1.0-beta3
- macOS version: 13.3.1 (22E772610a)
- vimtex version: 2.12

**Configuration**:

`ftplugin/tex.vim`:
```vim
if exists("b:did_my_ftplugin")
  finish
endif

let maplocalleader = "\\"
let b:did_did_my_ftplugin_ftplugin = 1
let g:vimtex_quickfix_open_on_warning = 0
" let g:vimtex_view_skim_activate = 1
let g:vimtex_quickfix_ignore_filters = [
      \ 'Underfull \\hbox',
      \ 'Overfull \\hbox',
      \ 'LaTeX Warning: .\+ float specifier changed to',
      \ 'LaTeX hooks Warning',
      \ 'Package siunitx Warning: Detected the "physics" package:',
      \ 'Package hyperref Warning: Token not allowed in a PDF string',
      \]

function! s:TexFocusVim() abort
  silent execute "!open -a Warp"
  redraw!
endfunction

augroup vimtex_event_focus
  au!
  au User VimtexEventViewReverse call s:TexFocusVim()
augroup END
let g:vimtex_view_method = 'skim'
```

**Troubleshooting**:

1. Tried calling the `vimtex#view#inverse_search` function using `nvim --headless -c "call vimtex#view#inverse_search_cmd(%line, '%file')"` from the command line.
2. Tried calling the `vimtex#view#inverse_search` function using `nvim --headless -c "VimtexInverseSearch %line '%file'"` from the command line.
3. Also trying the same thing in `nvim` instance.

**Comment by lervag** [comment] 2023-05-07 18:34
> The `vimtex#view#inverse_search` function works as expected when called within the Neovim instance that has the TeX `%file` open(i.e. he jumps to specific `%line`). However, it doesn't work when called from another Neovim instance or the command line using `--remote-send`, `--headless -c`, or a Python script.

First, I believe you won't need to call `vimtex#view#inverse_search` as you can instead use the `VimtexInverseSearch` command. The setup is explained in the docs, see `:help vimtex-view-skim` (just below the Configuration line) and `:help vimtex-synctex-inverse-search`.

If this doesn't work for you, then you are most likely using a plugin manager and loading VimTeX lazily. VimTeX is already lazy by design, so don't force it to be lazy, as that will break the `:VimtexInverseSearch` command.

> 2. Try calling the `vimtex#view#inverse_search` function from another Neovim instance or the command line using the `--remote-send` command, `nvim --headless -c`, or a Python script.

First, you should not call `vimtex#view#inverse_search` from _another_ Neovim instance. This function should be called from the instance where you want the inverse search to happen.

Now, when you provide steps for reproducing, you should be explicit. Given your input, I have no idea what you actually tried. There are several things I can imagine:

```sh
# This is just wrong - you cant call a function with --remote-send
nvim --headless --remote-send "vimtex#view#inverse_search(5,10)"

# This probably won't work because you need to specify the correct server
nvim --headless --remote-expr "vimtex#view#inverse_search(5,10)"

# This should work
nvim --headless --server /tmp/nvimsocket --remote-expr "vimtex#view#inverse_search(5,10)"
```

> **Expected behavior**: The `vimtex#view#inverse_search` function should be called in the Neovim instance with the TeX file open, and the cursor should jump to the specified line number.

This is only expected if you do things the right way.

> **System information**:
> 
> * vimtex version: 2.12

Are you on pinned on v2.12, or are you following the `master` branch?

> **Configuration**:
> 
> `ftplugin/tex.vim`:

When you put your VimTeX configuration in `ftplugin/tex.vim`, you should be aware that there is a possible race condition between when scripts are loaded. You should check `:scriptnames` and verify that `ftplugin/tex.vim` is loaded _before_ `VIMTEX/ftplugin/tex.vim`. If it is, then I think you're fine.

A couple of comments to your config:

```viml
" THIS IS NOT A VIMTEX OPTION! See :help maplocalleader
" -> move it to your init.lua or init.vim, e.g. to where you define your
" general mappings
let maplocalleader = "\\"

" This seems wrong? did_my_ftplugin vs did_did_my_ftplugin_ftplugin...
let b:did_did_my_ftplugin_ftplugin = 1
```

> **Troubleshooting**:

Ah, you should write these under "steps to reproduce". So:

> 1. Tried calling the `vimtex#view#inverse_search` function using `nvim --headless -c "call vimtex#view#inverse_search_cmd(%line, '%file')"` from the command line.

This will fail for several reasons:

1. You should also provide the `--server` argument to specify the correct Neovim instance.
2. `%line` and `%file` needs to be numbers.

> 2. Tried calling the `vimtex#view#inverse_search` function using `nvim --headless -c "VimtexInverseSearch %line '%file'"` from the command line.

1. `%line` and `%file` needs to be numbers.

> 3. Also trying the same thing in `nvim` instance.

That won't work.

**Comment by 594212** [comment] 2023-05-08 21:51
Thank you for your response.

>If this doesn't work for you, then you are most likely using a plugin manager and loading VimTeX lazily. VimTeX is already lazy by design, so don't force it to be lazy, as that will break the :VimtexInverseSearch command.

- I use packer to manage my plugins, and I do not use lazy loading. Here is a chunk of how I include the `vimtex` plugin in my `plugin.lua` file:

```lua 
use { 'lervag/vimtex' }
```
> When you put your VimTeX configuration in ftplugin/tex.vim, you should be aware that there is a possible race condition between when scripts are loaded. You should check :scriptnames and verify that ftplugin/tex.vim is loaded before VIMTEX/ftplugin/tex.vim. If it is, then I think you're fine.

- I'm checked, like you said the `ftplugin/tex.vim` file is loaded before the `VIMTEX/ftplugin/tex.vim` file.

> Are you on pinned on v2.12, or are you following the master branch?
- I am using the master branch of the `vimtex` plugin.

>Now, when you provide steps for reproducing, you should be explicit. Given your input, I have no idea what you actually tried. There are several things I can imagine:
- ``` nvim --headless -c "VimtexInverseSearch 10 /path/to/tex"```
I'm assumed that `%file` is a path so, it's not worked. How you convert /path/to/tex into number so I can test.

**Comment by lervag** [comment] 2023-05-10 19:43
> `nvim --headless -c "VimtexInverseSearch 10 /path/to/tex"`
>
> I'm assumed that `%file` is a path so, it's not worked. How you convert /path/to/tex into number so I can test.

I don't understand what you mean. `%file` is a path and `%line` is a number. The syntax is explained in the docs (`:help vimtex-synctex-inverse-search`).

So, open two terminals. In the first terminal, `cd` to the path where you have the `.tex` file. Open neovim with `nvim texfile.tex` [^1]. Compile if necessary. In the other terminal, run `nvim --headless -c "VimtexInverseSearch 10 /path/to/texfile.tex"`. This should navigate to line 10 in the first terminal.

Now, you would want to configure Skim to run this command on inverse search: `nvim --headless -c "VimtexInverseSearch %line '%file'"`. As explained in `:help vimtex-view-skim`. `%line` and `%file` will be filled in by Skim with the line number and file path.

[^1]: You don't need the `--listen` option, but in some cases you may need to create a directory - see #2701.

**Comment by lervag** [comment] 2023-05-10 19:43
I believe this issue is (or will be) resolved through the discussion, so I'm closing it.

**Closed by lervag** 2023-05-10 19:43 UTC
