### ISSUE TITLE
latexmk reports fail even though the compliation succeeded on the second run

### ISSUE THREAD

**Issue by nilsbecker** [lervag/vimtex#344] opened 2016-02-05 16:44 UTC
the status line often remains at `latexmk compile: fail` for me, even after a successful run has eventually produced a pdf file. to check if there really was an error i then have to open the .log file manually.

steps to reproduce: make a short latex file with a label and a reference, switch on latexmk compilation, switch off again, do full clear of aux files, switch on again. e.g.

```

\documentclass{minimal}
\begin{document}

\begin{equation}
    \label{eq:eq}
    x = y
\end{equation}

Hello World, behold eq.~\ref{eq:eq}

\end{document}
```

**Comment by lervag** [comment] 2016-02-06 19:33
Hmm, sorry, I can't reproduce this. It seems to work as expected for me... can you add a minimal vimrc file as well, and perhaps make the steps to reproduce even more verbose?

**Comment by nilsbecker** [comment] 2016-02-07 18:40
not seeing this behavior myself on another mac. will try reinstalling macvim on the troubled computer.

**Comment by lervag** [comment] 2016-02-07 20:02
Ok. I'll take the liberty and close the issue. Feel free to reopen if there is anything you can pinpoint on the vimtex side.

**Closed by lervag** 2016-02-07 20:02 UTC

**Comment by nilsbecker** [comment] 2016-02-08 10:52
after a lot of digging it seems the latexmk configuration was the culprit. i have now completely removed the `.latexmkrc` and everything seems to work much better.

**Comment by lervag** [comment] 2016-02-08 12:01
Glad to hear things are working!
