### ISSUE TITLE
warning message about filetype and syntax

### ISSUE THREAD

**Issue by zhuosongz** [lervag/vimtex#1387] opened 2019-05-21 01:23 UTC
Hello, I got a warning message from vimtex when I open tex files. It says: 

 "syntax on" seems to be applied before "filetype plugin on".
        This is suboptimal because some syntax features require an initialized state.
        Please see ":help vimtex_syntax_filetype".
I checked my vimrc file, and I think the order is correct. However, every time when I use  `:e %` to reload the current file, this warning message always appears. Can I disable this warning message? Or how can I find the reason for it? Could you please help me with this? Thank you very much! 

Best, 
Mat

**Comment by musoke** [comment] 2019-05-21 23:35
I have the same problem appearing.
It appears from `git bisect` that this was introduced in 556930ecc21810d5cdeef0d29938bdfbc36cae81.

**Comment by musoke** [comment] 2019-05-21 23:41
The fix for this is in the [changes to `doc/vimtex.txt` in that same commit](https://github.com/lervag/vimtex/commit/556930ecc21810d5cdeef0d29938bdfbc36cae81#diff-4bb7bb82dfb788844c6c9e003beccb2dR211).

> see |vimtex-syntax|. Some of the improvements require that the filetype
>  plugin has been loaded first. This means one must have the following lines
>  in the following order in ones `vimrc` file: >
>
>        filetype plugin indent on
>        syntax on
><
>  Note: Many plugin managers, like |vim-plug|, will automatically add these
>        lines in the correct order.

**Comment by zhuosongz** [comment] 2019-05-22 00:28
Thank you for your reply. However, this setting didn't fix my problem.

**Comment by lervag** [comment] 2019-05-26 14:13
> Could you please help me with this? Thank you very much!

Yes, I'll definately try! :)

> I checked my vimrc file, and I think the order is correct. However, every time when I use `:e %` to reload the current file, this warning message always appears.

Why are you reloading your file? I don't see why that would be necessary.

> Can I disable this warning message? Or how can I find the reason for it?

I would prefer to find the reason for the message and fix it. It should either be a problem with your configuration, or a bug in vimtex.

----

So, the first step for solving this is for you to provide the well-known minimal example that was described in the [issue template](https://github.com/lervag/vimtex/blob/master/ISSUE_TEMPLATE.md).

Let me know if you need help in creating the minimal example.

**Comment by zhuosongz** [comment] 2019-05-26 14:59
Thank you a lot for your reply. I have created a local minimal example with my own vimdc files, could you kindly let me know how can I upload the issue? Thanks! 

Best, 
Mathieu

**Comment by lervag** [comment] 2019-05-26 19:47
I need a minimal example, which is:

- A LaTeX file for which the issue may be reproduced. As small as possible.
- A vimrc file, again, as small as possible. Please remove whatever you have in your vimrc file that does not affect the issue. It should not take you very long to remove lines and test if the problem is still there.
- A list of steps for how to reproduce, e.g. something like this:

    1. Open the example with `vim -u myvimrc test.tex`
    2. Do **something**
      - Observed: Warning message appears.
      - Expected: The warning message should not appear.

**Comment by lervag** [comment] 2019-05-26 19:50
Please also take the time to read the issue template and the links for formatting comments/posts on github. If I should invest time to help you, I think it is only fair that you invest some time in learning how to properly format and describe your issues. It may also be helpful to read old and closed issues for examples on how other people describe their issues.

**Comment by zhuosongz** [comment] 2019-05-27 03:27
Thank you for your reply. 

Here is my subfolder of my `.vim` folder:

```
'~/.vim/after,~/.vim/autoload,~/.vim/bundle,~/.vim/colors,~/.vim/ftplugin,~/.vim/indent,~/.vim/plugin,~/.vim/spell,~/.vim/syntax,~/.vim/UltiSnips,~/.vim/tmp'
```

My minivimrc file: 

```{vim}
set nocompatible
let &runtimepath = '~/.vim,' . &runtimepath
"let &runtimepath  = '~/.vim/after,~/.vim/autoload,~/.vim/bundle,~/.vim/colors,~/.vim/ftplugin,~/.vim/indent,~/.vim/plugin,~/.vim/spell,~/.vim/syntax,~/.vim/UltiSnips,~/.vim/tmp,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after,~/.vim/colors,~/.vim/ftplugin,~/.vim/indent,~/.vim/plugin,~/.vim/autoload'
filetype plugin indent on
syntax enable


if has("user_commands")
    command! -bang -nargs=? -complete=file E e<bang> <args>
    command! -bang -nargs=? -complete=file W w<bang> <args>
    command! -bang -nargs=? -complete=file Wq wq<bang> <args>
    command! -bang -nargs=? -complete=file WQ wq<bang> <args>
    command! -bang Wa wa<bang>
    command! -bang WA wa<bang>
    command! -bang Q q<bang>
    command! -bang QA qa<bang>
    command! -bang Qa qa<bang>
endif

set nocompatible
filetype plugin indent on
syntax on

" augroup nonvim
"    au!
"    au BufRead *.png,*.jpg,*.pdf,*.gif,*.xls*,*.ppt*,*.doc*,*.rtf sil exe "!open " . shellescape(expand("%:p")) | bd | let &ft=&ft
" augroup end

source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

if has("gui_running")
    set encoding=utf-8
    set fileencodings=ucs-bom,utf-8,chinese,prc,taiwan,latin-1

    if has("win32")
        set fileencoding=chinese
    else
        set fileencoding=utf-8
    endif

    let &termencoding=&encoding

source $VIMRUNTIME/delmenu.vim
source $VIMRUNTIME/menu.vim
language messages zh_CN.utf-8
endif

set backupdir=.backup/,~/.backup/,/tmp//
set directory=.swp/,~/.swp/,/tmp//
set undodir=.undo/,~/.undo/,/tmp//



" set the runtime path to include Vundle and initialize
" set rtp+=~/Dropbox/config/vim/.vim/bundle/Vundle.vim
call plug#begin('~/Dropbox/config/vim/.vim/bundle')
"
" Plugins 
"Plug 'Vimball'
Plug 'scrooloose/nerdtree'

" open a NERDTree automatically when vim starts up if no files were specified
"autocmd StdinReadPre * let s:std_in=1
"autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
" 
" Stick this in your vimrc to open NERDTree with Ctrl+n (you can set whatever
" key you want):
"map <C-g> :NERDTreeToggle<CR>
" close vim if the only window left open is a NERDTree 
" Stick this in your vimrc:
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Use these variables in your vimrc. Note that below are default arrow
" symbols
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'

Plug 'kana/vim-textobj-user'
Plug 'rbonvall/vim-textobj-latex'
Plug 'tpope/vim-surround'

" Plug 'kien/ctrlp.vim'
Plug 'kien/ctrlp.vim'

"Change the default mapping and the default command to invoke CtrlP:
  let g:ctrlp_map = '<C-p>'
  let g:ctrlp_cmd = 'CtrlP'
  let g:ctrlp_user_command = 'find %s -type f'        " MacOSX/Linux

" Plug 'altercation/vim-colors-solarized'
Plug 'altercation/vim-colors-solarized'
syntax enable
set background=dark
colorscheme solarized

" Airlines
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
"Plug 'ybian/smartim'
Plug 'machakann/vim-sandwich'

" add the following to your vimrc to enable the extension:
let g:airline#extensions#tabline#enabled = 1

" Separators can be configured independently for the tabline, so here is how
" you can define "straight" tabs:
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'

" YouCompleteMe
" 
" Plug 'valloric/youcompleteme'

" Plug 'justinmk/vim-sneak'
"let g:sneak#label = 1


" Unisnips
" 
" Track the engine.
Plug 'SirVer/ultisnips'

" Snippets are separated from the engine. Add this if you want them:
Plug 'honza/vim-snippets'

" Trigger configuration. Do not use <tab> if you use https://github.com/Valloric/YouCompleteMe.
let g:UltiSnipsExpandTrigger=",a"
let g:UltiSnipsJumpForwardTrigger=",a"
let g:UltiSnipsJumpBackwardTrigger=",z"




" If you want :UltiSnipsEdit to split your window.
let g:UltiSnipsEditSplit="vertical"



" easy align 
"
Plug 'junegunn/vim-easy-align'
" Start interactive EasyAlign in visual mode (e.g. vipga)

xnoremap ga <Plug>(EasyAlign)

" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nnoremap ga <Plug>(EasyAlign)

Plug 'tpope/vim-repeat'

Plug 'tpope/vim-commentary'
Plug 'scrooloose/nerdcommenter'
" Add spaces after comment delimiters by default
let g:NERDSpaceDelims = 1

" Use compact syntax for prettified multi-line comments
let g:NERDCompactSexyComs = 1

" Align line-wise comment delimiters flush left instead of following code indentation
let g:NERDDefaultAlign = 'left'

" Set a language to use its alternate delimiters by default
let g:NERDAltDelims_java = 1

" Add your own custom formats or override the defaults
let g:NERDCustomDelimiters = { 'c': { 'left': '/**','right': '*/' } }

" Allow commenting and inverting empty lines (useful when commenting a region)
let g:NERDCommentEmptyLines = 1

" Enable trimming of trailing whitespace when uncommenting
let g:NERDTrimTrailingWhitespace = 1

" Enable NERDCommenterToggle to check all selected lines is commented or not 
let g:NERDToggleCheckAllLines = 1

Plug 'jiangmiao/auto-pairs'



Plug 'shougo/neocomplete.vim'
" ==================================================
"   Settings for neocomplete
" ==================================================
"Note: This option must be set in .vimrc(_vimrc).  NOT IN .gvimrc(_gvimrc)!
" Disable AutoComplPop.
let g:acp_enableAtStartup = 0
" Use neocomplete.
let g:neocomplete#enable_at_startup = 1
" Use smartcase.
let g:neocomplete#enable_smart_case = 1
" Set minimum syntax keyword length.
let g:neocomplete#sources#syntax#min_keyword_length = 3

" Define dictionary.
let g:neocomplete#sources#dictionary#dictionaries = {
    \ 'default' : '',
    \ 'vimshell' : $HOME.'/.vimshell_hist',
    \ 'scheme' : $HOME.'/.gosh_completions'
        \ }

" Define keyword.
if !exists('g:neocomplete#keyword_patterns')
    let g:neocomplete#keyword_patterns = {}
endif
let g:neocomplete#keyword_patterns['default'] = '\h\w*'

" Plugin key-mappings.
inoremap <expr><C-g>     neocomplete#undo_completion()
inoremap <expr><C-l>     neocomplete#complete_common_string()

" Recommended key-mappings.
" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
  return (pumvisible() ? "\<C-y>" : "" ) . "\<CR>"
  " For no inserting <CR> key.
  "return pumvisible() ? "\<C-y>" : "\<CR>"
endfunction
" <TAB>: completion.
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
" <C-h>, <BS>: close popup and delete backword char.
inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"

" ==================================================
"   End of setting of neocomplete
" ==================================================



" " Enable omni completion.
" autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
" autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
" autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
" autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
" autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

" Enable heavy omni completion.
if !exists('g:neocomplete#sources#omni#input_patterns')
  let g:neocomplete#sources#omni#input_patterns = {}
endif
"let g:neocomplete#sources#omni#input_patterns.php = '[^. \t]->\h\w*\|\h\w*::'
"let g:neocomplete#sources#omni#input_patterns.c = '[^.[:digit:] *\t]\%(\.\|->\)'
"let g:neocomplete#sources#omni#input_patterns.cpp = '[^.[:digit:] *\t]\%(\.\|->\)\|\h\w*::'

" For perlomni.vim setting.
" https://github.com/c9s/perlomni.vim
let g:neocomplete#sources#omni#input_patterns.perl = '\h\w*->\h\w*\|\h\w*::'
Plug 'lervag/vimtex'
" Plug 'gerw/vim-latex-suite'
let g:vimtex_syntax_enable=0
autocmd! BufNewFile,BufRead *.tex set filetype=tex
""设置latex suite
set shellslash
filetype indent on
filetype plugin on
filetype on
set grepprg=grep\ -nH\ $*

" end
" set winaltkeys=no
" Plug 'AndrewRadev/switch.vim'
" nnoremap - :Switch<cr>

"filetype plugin indent on
call plug#end()            " required



set nu 
set rnu 
set shiftwidth=4
set autoindent             "自动对齐
"全局性地关闭令人讨厌的模式高亮（特别是换行符）：
set hls!
"文档的一行不超过110个字符
match DiffAdd '\%>110v.*'

set so=1
set sidescrolloff=1
set sidescroll=1
set makeprg=make
set tabstop=4
set softtabstop=4
set shiftwidth=4
set fdc=2 
set nobackup! "不生成备份文件（~文件）。

" 关闭警告提示音
set noerrorbells
set vb t_vb=



nnoremap q :qall!<cr>

let g:vimtex_view_automatic = 0

"silent edit main.tex
```

Here is my test tex file: 

```
% test.tex
\documentclass{article}

\begin{document}
	Hello, World! 
\end{document}
```

When I run: 
```
mvim --servername VIM -u minivimrc test.tex
```
it appears the following warning message: 
```
vimtex: "syntax on" seems to be applied before "filetype plugin on".
        This is suboptimal, because some syntax features require an initialized state.
        Please see ":help vimtex_syntax_filetype".
```

However, if I change the second line of my minivimrc file to: 
```
let &runtimepath  = '~/.vim/after,~/.vim/autoload,~/.vim/bundle,~/.vim/colors,~/.vim/ftplugin,~/.vim/indent,~/.vim/plugin,~/.vim/spell,~/.vim/syntax,~/.vim/UltiSnips,~/.vim/tmp,' . &runtimepath
```
This warning message is gone. 

I guess that there might be some hidden problem with my configuration.

**Comment by lervag** [comment] 2019-05-27 10:46
@zhuosongz It seems as #1394 is the same issue as this one, do you agree? Can you confirm that @Edenharder's minimal example reproduces your issue as well? That would help, because it would provide a much more concise minimal example.

**Comment by zhuosongz** [comment] 2019-05-27 10:59
Hi, @lervag thanks for your reply. I tried with the minivimrc in #1394, and it works without the warning message. 

Thanks!

**Comment by lervag** [comment] 2019-05-27 21:01
@zhuosongz Please clean up your minimal vimrc file. I am sure there is a lot of stuff that may be removed while still being able to reproduce it. It's too much work for me to make your vimrc file work, and I would not be surprised if it ends up not reproducing your problem.

With "clean up your minimal vimrc file", I mean the following procedure: Given `minivimrc` and `test.tex` such that `mvim --servername VIM -u minivimrc test.tex` provides the warning message, do iteration:

1. Edit `minivimrc` file, remove lines (and plugins) that seem unrelated.
2. Test if warning message still appears. If it does, repeat from 1. If not, undo previous step and try to remove other lines.
3. Repeat step 2 until you can not simplify further.

**Comment by zhuosongz** [comment] 2019-05-30 12:25
Thank you. I have carefully checked my local setting and found the reason for the problem. Thank you very much for your help! Now I will close this issue.

**Closed** 2019-05-30 12:25 UTC

**Comment by lervag** [comment] 2019-05-30 12:58
No problem! I would be interested to know the reason, if you would be willing to share.

**Comment by zhuosongz** [comment] 2019-05-30 13:04
Sure. There are some syntax setting in my `~/.vim/ftplugin/tex.vim` file, and then it calls the warning message every time when I open tex file. Now I have put these settings into `~/.vim/after/syntax/tex.vim` file, and it works normally.

**Comment by lervag** [comment] 2019-06-05 20:13
Thanks! I expect your `~/.vim/ftplugin/tex.vim` file included the `let b:current_syntax = "tex"` line, then, which would explain the issue.
