### ISSUE TITLE
vimtex-indent causing slowdowns

### ISSUE THREAD

**Issue by thomasteoh** [lervag/vimtex#598] opened 2016-10-23 23:48 UTC
### Explain the issue

Firstly thank you for vimtex! I've been noticing for a document of mine that vimtex-indent has been causing slowdowns, locking up vim for noticeable periods
# 1. Steps to reproduce

Progressive slowdown as more curly brackets are introduced. Noticeable after a few hundred. 
# 2. Expected behaviour

Minimal slowdowns
# 3. Observed behaviour

My log profile has the following entries:

```

FUNCTION  VimtexIndent()
Called 2 times
Total time:  14.537858
 Self time:   0.001414

count  total (s)   self (s)
    2   0.007878   0.000043   let l:prev_lnum = s:get_prev_line(prevnonblank(a:lnum - 1))
    2              0.000015   if l:prev_lnum == 0 | return indent(a:lnum) | endif

                              " Get current and previous line and remove comments
    2              0.000062   let l:line = substitute(getline(a:lnum), '\\\@<!%.*', '', '')
    2              0.000263   let l:prev_line = substitute(getline(l:prev_lnum),   '\\\@<!%.*', '', '')

                              " Check for verbatim modes
    2   0.013373   0.000028   if s:is_verbatim(l:line, a:lnum)
                                return empty(l:line) ? indent(l:prev_lnum) : indent(a:lnum)
                              endif

                              " Align on ampersands
    2              0.000025   if l:line =~# '^\s*&' && l:prev_line =~# '\\\@<!&.*'
                                return indent(a:lnum) + match(l:prev_line, '\\\@<!&') - stridx(l:line, '&')
                              endif

                              " Use previous indentation for comments
    2              0.000010   if l:line =~# '^\s*%'
                                return indent(a:lnum)
                              endif

                              " Ensure previous line does not start with ampersand
    2   0.007993   0.000033   let l:prev_lnum = s:get_prev_line(l:prev_lnum, 'ignore-ampersands')
    2              0.000011   if l:prev_lnum == 0 | return 0 | endif
    2              0.000281   let l:prev_line = substitute(getline(l:prev_lnum), '\\\@<!%.*', '', '')

                              " Indent environments, delimiters, and tikz
    2              0.000011   let l:ind = indent(l:prev_lnum)
    2   0.000703   0.000507   let l:ind += s:indent_envs(l:line, l:prev_line)
    2  14.506685   0.000032   let l:ind += s:indent_delims(l:line, a:lnum, l:prev_line, l:prev_lnum)
    2   0.000483   0.000028   let l:ind += s:indent_tikz(l:prev_lnum, l:prev_line)
    2              0.000004   return l:ind


FUNCTION  vimtex#util#in_syntax()
Called 1821 times
Total time:  14.382734
 Self time:  14.382734

count  total (s)   self (s)

                              " Usage: vimtex#util#in_syntax(name, [line, col])

                              " Get position and correct it if necessary
 1821              0.016471   let l:pos = a:0 > 0 ? [a:1, a:2] : [line('.'), col('.')]
 1821              0.007665   if mode() ==# 'i'
 1821              0.011517     let l:pos[1] -= 1
 1821              0.003780   endif
 1821              0.018468   call map(l:pos, 'max([v:val, 1])')

                              " Check syntax at position
 1821             14.311981   return match(map(synstack(l:pos[0], l:pos[1]),          "synIDattr(v:val, 'name')"),      '^' . a:name) >= 0
```

I've noticed that disabling matching parenthesis and indentation in my .vimrc resolves much of the slowdown. 

```
let g:vimtex_motion_matchparen = 0
let g:vimtex_indent_enabled = 0
```
### Minimal vimrc file

``` vim
call plug#begin('~/.vim/plugged')

" A modern vim plugin for editing LaTeX files.
Plug 'lervag/vimtex'

" Add plugins to &runtimepath
call plug#end()

" Vimtex settings
let g:tex_flavor = 'latex'
let g:vimtex_view_method='mupdf'
```

**Comment by lervag** [comment] 2016-10-24 13:18
Thanks for reporting. Could you please provide some more info:

- Vim version
- File size where the problem occurs (is it 1821 lines, perhaps)?
- How do you do the indentation? The whole file (`gg=G`)?
- Could you specify how you make the profiling report (I can use that to try to reproduce your results with a personal LaTeX file that is large enough to reproduce the slowdown)?

I don't think the matching paranthesis has anything to do with this (or at least it is fully separated from slowdown due to indentation). But I have relatively recently improved the indentation and knowingly made it less efficient in the process. I was hoping it wouldn't be too slow, but your report unfortunately shows the opposite.

So: I am not that surprised that it is slow. I will look into it and try to improve it, else I will make the slow features optional.

**Comment by Rmano** [comment] 2016-10-24 16:03
I also feel slowdowns when typing an unmatched ([{ on certain files. There is a pause of a second or couple of seconds that is enough to disrupt the flow of typing.
It doesn't happen anytime, but it happens for example in files where there are a lot of very long lines (500+) chars. You start typing `\emph{` and you have a noticeable stop at the (unmatched) brace. No loss of chars, but the thing is distracting.  
I am in a rush now, but I will try to prepare a test case if I can.

**Comment by lervag** [comment] 2016-10-24 19:46
@Rmano Could you please veriy that this is due to indentation, e.g. by disabling vimtex indents with `let g:vimtex_indent_enabled = 0` or by disabling indentation (use `filetype indent off` in your vimrc file)? If it lags even without indentation, then the slowdown you see is for a different reason and should be raised as a separate issue.

**Comment by thomasteoh** [comment] 2016-10-24 21:30
Thanks for replying! 

Vim version:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct 23 2016 19:28:10)
Included patches: 1-46
```

File size: To multiple files, but the one from the report above is 200 lines long. Lines of up to 2000-3000 characters long similar to @Rmano 

Indentation: expandtab and tabstop not set
```
set shiftwidth=2
```

Profile log: I followed [this guide](http://stackoverflow.com/questions/12213597/how-to-see-which-plugins-are-making-vim-slow)
```
:profile start profile.log
:profile func *
:profile file *
" At this point do slow actions
:profile pause
:noautocmd qall!
```

**Comment by lervag** [comment] 2016-10-25 05:59
I think I was unclear: Could you also explain exactly what the slow actions are? I now have almost all pieces necessary to start the investigation, but I want to make it as close to your particular case as possible before I start.

**Comment by thomasteoh** [comment] 2016-10-25 06:05
Sorry, the slow occurs whenever a bracket is typed, so for example \textit{test} would make vim freeze once when the open bracket is typed, and freeze again for a bit longer when the close bracket is typed. Can be anything else as well, even just plain typing {}{}{} seems to cause the issue for me.

**Comment by lervag** [comment] 2016-10-25 06:24
Ok, I see. Then it would be very helpful if you could provide a "minimal" LaTeX sample that reproduces this. I've tried on some of my own files, and I don't experiences the lag.

Could it be due to long lines? I usually hardwrap my lines at 79 columns.

**Comment by thomasteoh** [comment] 2016-10-25 06:46
Here is an example document. the slowdown occurs when I add a new line and start typing something that requires brackets. With more brackets the time seems to increase
[test.tex.zip](https://github.com/lervag/vimtex/files/549806/test.tex.zip)

**Comment by lervag** [comment] 2016-10-25 06:52
Thanks! I'll look at this when I get the time, perhaps this evening.

**Comment by oliviertilmans** [comment] 2016-10-25 07:00
I have a similar issue on my end. When I edit a class file, both neovim and vim 8.0.46 hangs for an indefinite amount of time whenever I press enter.

I reduced the MWE to: (theme.cls)
```tex
% vim: ft=tex
\endinput%
```
If I add this to my vimrc:
`filetype indent off`
The problem is solved.

More correct MWE (theme.cls):
```tex
% vim: ft=tex
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{theme}[2016/08/24 Theme]

\let\CP@olditemize\itemize%
\def\itemize{\@ifnextchar[\itemize@i \itemize@ii}% Are there any arg ?
\def\itemize@i[#1]{\CP@olditemize[#1]\setlength{\itemsep}{\fill}}
\def\itemize@ii{\CP@olditemize\setlength{\itemsep}{\fill}}

\LoadClass{beamer}

\endinput%
```

minimal vimrc:
```vimL
filetype off                   

let mapleader = ","

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex', { 'for': 'tex' }                                                        " Better latex support
call plug#end()
```

**Comment by oliviertilmans** [comment] 2016-10-25 07:10
1d126b98b924 Is a clean commit here.
4249328a0 and onwards trigger error `Error detected while processing function vimtex#delim#get_delim_regexes:` (Fixed by c72fcbc0df9)
7fb8643d4f24 Introduces the bug

**Comment by Rmano** [comment] 2016-10-25 08:01
@lervag, @thomasteoh  --- for me too it happens by just inserting a (unbalanced) {  (or [ or other opening brackets), and in lesser measure on the closing one. 
I can confirm that setting `let g:vimtex_indent_enabled=0` in my `.vimrc` fixes (or at least greatly reduces) the lag.

**Comment by lervag** [comment] 2016-10-26 21:18
As you might have noticed, I have started my investigation; it was easy to find the reason for the slowdown. I'm using a rather crude way of splitting lines into normal tex and math mode, where I call `vimtex#util#in_mathzone` on every column of every line.

I'll work on finding a better way to do this, which should resolve the issue.

In the meantime: It will help considerably if you use short lines, because the lag scales linearly with the length of the lines.

**Comment by lervag** [comment] 2016-10-26 21:26
I've pushed an updated set of test files. The issue is now very easily reproduced with `vim -u vimrc`. This generates the `profile.log` file that shows the slow line in the `s:split()` function.

**Comment by lervag** [comment] 2016-10-27 21:24
I've pushed a first version of a fix. I'll work some more on it to improve the style of the implementation, but I think it should make things faster.

**Comment by process91** [comment] 2016-10-28 00:42
This improved things quite a bit, however there is a new intermittent problem - when typing an opening delimiter of any sort, I've experienced vim crashing completely. (Freezes, cannot interact with that terminal window in any way, process goes up to 100% CPU.) This happened around 3-4 times during an hour of using it, but so far I haven't been able to reproduce it reliably.

**Comment by lervag** [comment] 2016-10-30 20:58
This does not occur for me. Please open a new issue if you are able to create a reproducible example.

**Comment by lervag** [comment] 2016-10-31 19:04
@process91 I'm curious, could this be related to #616?

**Comment by process91** [comment] 2016-10-31 19:06
Yes, seems identical to my experience.

**Comment by lervag** [comment] 2016-10-31 19:06
Great. I'm working on that now, hope to push a fix soon.

**Closed** 2016-10-31 20:33 UTC

**Comment by clason** [comment] 2016-12-15 10:39
Sorry to piggy back on this, but I've also been wondering about the slowness of the indent (an order of magnitude slower than with LaTeX-Box -- the only remaining "regression" after my switch).

The profiler led me to the function `s:split` as well, and I am curious why you need to split the line for indentation at all -- isn't only the beginning of the line relevant for alignment? Could you maybe explain a bit what your indentation does differently from the vanilla indentation? I didn't see much difference apart from the alignment at `&`, but I assume there's more going on that justifies the additional work?

(Maybe it would be an option to have the expensive part, well, optional -- have a `vimtex_indent` allowing for `off`, `simple` and `full`?)

**Comment by lervag** [comment] 2016-12-15 12:14
Hi @clason, and thanks for your thoughts and questions. The split is necessary for improving the correctness of the delimiter matching. We need to match different delimiters depending on if we are in normal text mode or in math mode. 

However, perhaps I have overly complicated things. In particular, I have allowed delimiters to add indents for inline maths. Perhaps that is not really necessary or desired. I.e., the following is an example of how things are indented now:

```tex
this is some text $(
asdasd )$ asdasd $f(x) = a*(
  testeste + asd
)$ asdasd
```

As you see, if you have multiple lines of inline math, the math delimiters will increase and decrease indents. This might not be necessary or desired, and I think we could simplify (and improve speed) if we say that inline maths should not be indented.

Also, I allow tex delimiters to be indented in normal text mode. that is:

```tex
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, {\color{red} sed diam
  nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed
  diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet
clita kasd gubergren}, no sea takimata sanctus est Lorem ipsum dolor sit
amet.
```

One cold also argue that this is not necessary, but I do find it convenient...

In any case, I agree we could add an option to set the indent mode to either simple or full, for instance (with definitions in the documentation on what differs between the modes). But before I do this, I want to get help to make explicit how things should be indented (in either mode).

**Comment by clason** [comment] 2016-12-15 12:35
Thank you for the explanation, that makes sense -- I did not think of inline math! I try to stick to the convention to have line breaks so that every sentence is its own line (if I remember to break lines at all...), and to make any formula that takes more than half a line displayed, so the indentation in text mode is indeed not relevant to me personally. (Although I can see the use case for the second example when revising papers.)

I can see two options:

1. Apply (optionally) indentation for delimiters only for displayed math (although that would add additional logic for checking environments, so I'm not sure how much performance would be gained).

2. Make indentation of delimiters optional.

My vote would be for the lazy option (2); I've been playing with the commented out `indent_delims` for a while, and so far I've been pretty happy with both the results and the performance. (Although maybe I have just not hit a situation where this would fail badly yet. Do you know of any?)

Another thought: Maybe explaining this briefly in the `vimtex-indent` section of the documentation would be a good idea?

**Comment by clason** [comment] 2016-12-15 12:48
I just found a situation where it does make a difference: `algorithm2e` uses braces to group clauses (for, while, if, etc.). For those to be indented requires `indent-delims`. That might be an argument in favor of option 1 (indent delims only inside `equation` and friends -- including `algorithm*`)?

**Comment by lervag** [comment] 2016-12-15 18:22
I think your option 1 is the best approach. Checking the environment is cheap, or at least much cheaper (order of magnitude) than the current `s:split` method. In this case, we have two types of delimiter indentations:

1. In normal text, we indent on braces. Inline math is ignored.
2. In displayed math, we indent similar to how it is done now.

This change would simplify the indendation algorithm a great deal, and I think it would make things much faster. I would prefer not to add more options, so an important question is if this change would remove a feature that someone would find indispensible.

**Comment by clason** [comment] 2016-12-15 18:35
Agreed. I don't see anything that would be a problem at the moment, but I'll be happy to test any implementation.

What about just ignoring the difference between normal text and inline math? What would go wrong in this case? 

(Should this issue be reopened -- or should I open a new issue -- to make this more visible so other people can weigh in?)

**Comment by lervag** [comment] 2016-12-16 07:08
The difference is that normal text and math has very different definitions of delimiters.

I would be happy if you could open a new issue. As you say, it makes it more visible for other people. In addition, if you would be so kind as to make a summary of this discussion, it would be a very good starting point for me to work on this. I will most likely create a separate branch that will be merged only when you (and others) agree it is ready.
