### ISSUE TITLE
continuous compilation (partially) blocks neovim

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#923] opened 2017-07-27 22:05 UTC
Some commands do not work while continuous compilation is running using neovim (HEAD) and neovim-remote (1.7.4, but the problem occurred at least for 1.7.1 already).

Possibly related to https://github.com/neovim/neovim/issues/6166?
### Steps to reproduce

1. Start continuous compilation with `<leader>ll`.
2. Enter `gg=G`.

### Expected behaviour

The whole buffer is (re)indented.

### Observed behaviour

The cursor jumps to the beginning of the buffer, then the end (i.e., same behaviour as `ggG`).

### Minimal working example

Any (sufficiently large) TeX file.

### Minimal vimrc

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

let g:vimtex_compiler_progname = 'nvr'
```

**Comment by lervag** [comment] 2017-07-29 15:51
This is a strange issue! First, I'll confirm this does not happen with a minimal LaTeX file. I've tried to find an example where this is reproduced, but I was not able. I've pushed test files now, so you can see what I've tried. It would be helpful if you could provide a LaTeX sample.

**Comment by clason** [comment] 2017-07-29 17:16
I can confirm that the minimal file is "too minimal"; probably latexmk needs at least two runs, possibly including a bibtex (or biber) run. I'll try to make an example, but it might end not to be minimal at all... For me, it happens with any paper or set of lecture notes.

**Comment by clason** [comment] 2017-07-30 10:23
I can reproduce this with your `minivimrc` and a more complicated MWE (see below), but the behavior seems to depend on exactly at what point in the compilation `gg=G` is issued: you either

1. get the expected indentation;
2. the command is "queued" -- nothing happens for a bit, and then the file is indented as expected;
3. the `=` gets "eaten".

It's probably easiest to observe by starting compilation and then immediately and constantly "spamming" `gg=G`. I realize that this makes the issue exceedingly difficult to debug... Is there a way of logging what's happening?

```
\documentclass{article}
\usepackage{filecontents}
\begin{filecontents}{\jobname.bib}
@book{book,
author={Author, An},
title={A book},
publisher={A publisher},
year={2017}
}
\end{filecontents}
\usepackage{biblatex}
\addbibresource{\jobname.bib}
\usepackage{lmodern}
\usepackage{microtype}
\begin{document}

Hello World!

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

\begin{equation}\label{eq:1}
\int_0^1 f(x) \,dx = F(1)-F(0). 
\end{equation}
See (\ref{eq:1}) and also \cite{book}.

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

\begin{equation}\label{eq:1}
\int_0^1 f(x) \,dx = F(1)-F(0). 
\end{equation}
See (\ref{eq:1}) and also \cite{book}.
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

\begin{equation}\label{eq:1}
\int_0^1 f(x) \,dx = F(1)-F(0). 
\end{equation}
See (\ref{eq:1}) and also \cite{book}.
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

\begin{equation}\label{eq:1}
\int_0^1 f(x) \,dx = F(1)-F(0). 
\end{equation}
See (\ref{eq:1}) and also \cite{book}.
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

\begin{equation}\label{eq:1}
\int_0^1 f(x) \,dx = F(1)-F(0). 
\end{equation}
See (\ref{eq:1}) and also \cite{book}.
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

\begin{equation}\label{eq:1}
\int_0^1 f(x) \,dx = F(1)-F(0). 
\end{equation}
See (\ref{eq:1}) and also \cite{book}.
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd
gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

\begin{equation}\label{eq:1}
\int_0^1 f(x) \,dx = F(1)-F(0). 
\end{equation}
See (\ref{eq:1}) and also \cite{book}.

\printbibliography 
\end{document}
```

**Comment by clason** [comment] 2017-07-30 13:19
A note: if I set the `backend` to `process`, things work as expected.

**Comment by lervag** [comment] 2017-08-04 21:15
Interesting. This means that the problem is related to the shell somehow. Note, though, that I still can't reproduce this. Perhaps I'm unlucky with the "spamming" of keys, but for me, the indent always works as expected.

**Comment by clason** [comment] 2017-08-04 23:20
That's very strange; I get this both on macOS and Linux (with the same `init.vim`, though, both on fairly up-to-date neovim and neovim-remote). Maybe your machine is just faster than mine? Do you have any ideas how to triangulate this?

**Comment by lervag** [comment] 2017-08-06 20:09
One idea is to make a test programmatically. I've updated the minivimrc file to show you what I mean. Please try it: You open `nvim -u minivimrc`, and now you should be able to reproduce with a proper count in milliseconds and `<space>x`. E.g. `100<space>x`. I am not able to reproduce like this, no matter what I try for the sleep time.

**Comment by clason** [comment] 2017-08-06 20:50
That does what it's supposed to, so it seems in fact to be how actual keystrokes are processed. (Although try exchanging the order of `gg=G` and `execute...`: You'll (or at least I) see that it says `85 lines indented`, but the buffer is actually not updated until the `redraw` event.)

It's really weird; the only thing I can imagine is that we're using different neovim versions, and something changed between them. (Since this happens for me with the same `minivimrc` and `minimal.tex` as you, on macOS *and* Linux.) What version are you using (I'm following HEAD, compiled from source; on macOS:
```
:version
NVIM v0.2.1-653-g5bec94652
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -
D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wn
o-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-str
ong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170806-89630-1p0z8x4/b
uild/config -I/tmp/neovim-20170806-89630-1p0z8x4/src -I/usr/local/include -I/usr/local/include -I/us
r/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gett
ext/include -I/usr/include -I/tmp/neovim-20170806-89630-1p0z8x4/build/src/nvim/auto -I/tmp/neovim-20
170806-89630-1p0z8x4/build/include
Compiled by clason@shodan.fritz.box

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-5bec946_1/share/nvim"
```

and on Linux:

```
:version
NVIM v0.2.1-655-g5bec94652
Build type: Release
Compilation: /usr/bin/cc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wal
l -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvl
a -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -
I/scratch/build/neovim/build/config -I/scratch/build/neovim/src -I/scratch/build/neovim/.deps/usr/in
clude -I/scratch/build/neovim/.deps/usr/include -I/scratch/build/neovim/.deps/usr/include -I/scratch
/build/neovim/.deps/usr/include -I/scratch/build/neovim/.deps/usr/include -I/scratch/build/neovim/.d
eps/usr/include -I/usr/include -I/scratch/build/neovim/build/src/nvim/auto -I/scratch/build/neovim/b
uild/include
Compiled by clason@dhcp-ce063234

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"
```


)?

**Comment by lervag** [comment] 2017-08-06 21:02
No reason to change the order of lines. The reason it does not say anything is that Vim does not do any redrawing when it executes a function (I think this is controlled by `set lazyredraw`). The `execute` lines is there because I got the impression that the time between you started to compile and the keys `gg=G` were typed was important. It will sleep for the amount of milliseconds that you specify with the mapping count.

My neovim version is 0.2.0, it is from the Arch Linux repos:

```
NVIM v0.2.0                                                                     
Build type: Release                                                             
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protecto
r-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wal
l -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -
fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATION
S -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.
0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include
 -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/
neovim/src/build/include                                                        
Compiled by builduser                                                           
                                                                                
Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences                             
                                                                                
   system vimrc file: "$VIM/sysinit.vim"                                        
  fall-back for $VIM: "/usr/share/nvim"                                         
```

**Comment by lervag** [comment] 2017-08-06 21:04
But the updated minivimrc shows you how I would try to automate this bug. Perhaps you could play around with it and see if you were able to reproduce programatically. You could try to use `feedkeys()`, for instance, instead of `normal! gg=G`: `call feedkeys('gg=G')` (you could also try some the flags on the optional argument).

**Comment by clason** [comment] 2017-08-06 21:09
Hmm, with the old order, indentation happens immediately. I'll try around with the script (although I know next to no vimL). It might be due to the bundled libraries: could you try cloning the GitHub repo and building from source (`CMAKE_BUILD_TYPE=Release make` should do the trick)?

**Comment by lervag** [comment] 2017-08-06 21:17
Some comments to the code:

```vim
function! Test()
  VimtexCompile

  " Wait some time after we start compilation
  execute 'sleep' string(v:count > 0 ? v:count : 500) . 'm'
  normal! gg=G

  " This redraw makes sure that we see the result of the indentation immediately
  redraw!
  echo 'Sleeping to wait until compilation has completed'

  " The last part simply stops the compilation and cleans up after some time
  sleep 6
  VimtexStop
  sleep 100m
  VimtexClean!
  call delete('minimal.bib')
endfunction
```

My proposal was to try the `feedkeys()` function instead of the `normal! gg=G` in the above function. You can find info on this function with `:h feedkeys(`.

I could try to build neovim locally, yes. It will have to be later, perhaps tomorrow. Need some sleep now :)

**Comment by clason** [comment] 2017-08-06 21:22
Indeed, changing `normal!` to `call feedkeys()` doesn't indent until after `Test()` completes (even without the first `sleep` line).

**Comment by lervag** [comment] 2017-08-07 07:05
But if it does indent, then I don't think it reproduces your original problem. I've changed the order of cleaning and testing now, which is good, I think, because it means the function ends after the reindent. I also think this should make the `feedkeys()` approach slightly more controlled. There are some interesting flags for the feedkeys function. I've not used it much before, so I am not 100% sure how it works and which flags are most appropriate here.

**Comment by clason** [comment] 2017-08-07 07:18
It's not the original problem, but I believe it is related (especially since -- like the original problem -- I observe it and you don't). With the updated `minivimrc`, I can't reproduce the delay anymore, so it seems that it's crucial for the reindent being called *during* the script. (In the "full" problem, the issue is probably that `gg=G` is called between two `pdflatex` runs started by `latexmk`.)

**Comment by lervag** [comment] 2017-08-07 07:21
Does this code produce a delay?

```vim
function! Test()
  " Clean up first
  silent VimtexStop
  sleep 100m
  silent VimtexClean!

  " Test compile then keys
  VimtexCompile
  execute 'sleep' string(v:count > 0 ? v:count : 500) . 'm'
  call feedkeys('gg=G')
  sleep 4
endfunction
```

If it does, then I'll test if it produces a delay for me (I have not tried using the `feedkeys()` function myself yet).

**Comment by clason** [comment] 2017-08-07 07:27
Yes, that shows the delay. Actually, 

```
function! Test()
  call feedkeys('gg=G')
  sleep 4
endfunction
```

suffices for this (even with the `backend` set to `process`).

**Comment by lervag** [comment] 2017-08-07 07:29
I believe this is because of how `feedkeys()` work, and so it is not related to the current issue. That was why I updated the minimal vimrc file. With the sleep there, what happens if you use the `'i'` flag? Or the `'x'` flag? I think `'i'` might make things work "as expected".

**Comment by clason** [comment] 2017-08-07 07:34
No, neither flag works. The issue is that I see `85 lines indented` immediately, but the indentation actually happens only after the `sleep` is over. That can't be intended behaviour :)

**Comment by clason** [comment] 2017-08-07 08:38
I also get the same behaviour if I comment out everything related to vimtex (message before and indentation after sleep with flag `'x'`, message and indentation after sleep with flag `'t'`), so this seems a bit like a red herring.

Here's what I think is going on: the indentation function (or part of it) can be preempted by certain commands such as `sleep`. For some reason, calling `latexmk` using the`nvim` API behaves like such a command, while calling `latexmk` with the `process` API (and maybe vim8's `jobs` API) doesn't. (I don't know if that's a bug or by design, and in the latter case, there's some option to change this.)

**Comment by lervag** [comment] 2017-08-07 20:51
Ok, I've tried myself. I also have the delay with `feedkeys`, but as I said, this is as expected. `feedkeys()` adds actions on a stack. If you add the `x` flag, it will act immediately, but you need a `redraw!` inside the function after the `feedkeys()` to see the effect.

Thus we are back at trying to reproduce the original problem. I think the current version of the `minivimrc` file should be a good starting point for trying som different wait times (i.e., try the mapping with different counts, e.g. type `200<space>x`, `300<space>x`, etc., and see if you can reproduce the behaviour observed in the original post.

I agree it is strange that the problem only happens with the neovim jobs api, and so far, I have no idea why.

**Comment by clason** [comment] 2017-08-07 21:19
I now tested some more, and it does seem to be an issue with the neovim jobs api. On 0.2.0, I nearly always get indentation or complete blocking (i.e., nothing happens for a while, and then the stack gets executed in one go):

```
NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion
 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDIS
ABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=
gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATE
D_DECLARATIONS -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/config -I
/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/src -I/usr/local/include -I/usr/
local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/
usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-
20170707-80027-1bg0wcx/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170707-8
0027-1bg0wcx/neovim-0.2.0/build/include
Compiled by brew@Sierra-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0_1/share/nvim"
```

The oldest neovim I can reproduce the "skipping" of the indentation with is the one bundled with vimR (where `:version` just reports `vim-0.2.0-dev` but not in a buffer so I can't easily copy it here). I'll see what newer commits bring, and wait for a rainy Sunday to try a `git bisect`. That means you can ignore the issue for now. I really appreciate the time you took for this wild goose chase!

**Comment by lervag** [comment] 2017-08-07 21:22
Ok, thanks! It's fun to try to understand complex things. :)

I hope it's OK that I close this issue. Feel free to reopen when/if you want me to consider any updates. (Although I also reply to and consider updates to closed issues.)

**Closed by lervag** 2017-08-07 21:22 UTC

**Comment by clason** [comment] 2017-09-05 20:42
https://github.com/neovim/neovim/commit/541dde36e3302314e2646415dbfd2b79a6c2a1fc seems to have fixed this, but https://github.com/neovim/neovim/commit/ce852bab04c63262ce8545c01a4ff4fc827148a1 broke it again (to the point where neovim completely freezes during async compilation (at least for complicated files involving externalized TikZ figures), making it unusable. 

I'll have to test a bit more.

**Comment by diravan** [comment] 2017-09-12 13:47
I cannot reproduce the behaviour with gg=G but I can confirm that compilation blocks neovim for a while. I am using neovim HEAD on Ubuntu 17.04. @clason do you need my vimrc to before opening that neovim issue?

**Comment by clason** [comment] 2017-09-15 15:21
@diravan Thanks for the offer -- if your `vimrc` (or `minimal.tex`) is smaller than mine, that would be helpful, otherwise I'll use the one from the thread above.
