### ISSUE TITLE
Quickfix window does not appear for warnings

### ISSUE THREAD

**Issue by PatrBal** [lervag/vimtex#1312] opened 2019-01-20 22:44 UTC
Quickfix window show up normally to display errors. However, it does not show up in the case where there are only warnings. I tried the following investigation:

> let g:vimtex_quickfix_method

and obtained the answer:

> g:vimtex_quickfix_method  latexlog

and then:

> let g:vimtex_quickfix_latexlog

and obtained the answer:

> E121: Undefined variable: g:vimtex_quickfix_latexlog

I have this issue both in MacVim and terminal Vim, with every tex file. Any idea about the origin of this problem?

**Comment by PatrBal** [comment] 2019-01-21 21:35
Yes, g:vimtex_quickfix_open_on_warning is enabled (equal to 1), but, nonetheless, the quickfix window does not open on warnings. It seems to be due that g:vimtex_quickfix_latexlog is undefined, and, in particular, it has not the default value mentioned in the doc. I cannot find the reason why g:vimtex_quickfix_latexlog is undefined

**Comment by lervag** [comment] 2019-01-21 21:37
Can you provide a minimal example? (see [issue template](https://github.com/lervag/vimtex/blob/master/ISSUE_TEMPLATE.md))

**Comment by PatrBal** [comment] 2019-01-21 22:38
Ok, thanks. Here is my minimal .vimrc

```vim
execute pathogen#infect()
set nocompatible
syntax on
filetype plugin indent on
let g:polyglot_disabled = ['markdown','latex']
```

Here is a minimal .tex file, called toto.tex

```tex
\documentclass{article}
\begin{document}
\end{document}
```

I open toto.tex in MacVim:

> mvim toto.tex

Then, I inspect g:vimtex_quickfix_method

> :let g:vimtex_quickfix_method

I obtain:

>  g:vimtex_quickfix_method  latexlog

as expected. Then I inspect g:vimtex_quickfix_latexlog

> :let g:vimtex_quickfix_latexlog

and I obtain:

> E121: Undefined variable: g:vimtex_quickfix_latexlog

In particular, g:vimtex_quickfix_latexlog has not the default value mentioned in the Vimtex documentation. I suspect that it could be the reason why  the quickfix window does not show up in the case where there are only warnings.

Of course, I have inspected g:vimtex_quickfix_open_on_warning

> :let g:vimtex_quickfix_open_on_warning

which has its normal default value:

> g:vimtex_quickfix_open_on_warning  1

**Comment by lervag** [comment] 2019-01-22 07:51
To check the content of a variable, you should use `:echo VARNAME`, not `:let VARNAME`. The reason that `g:vimtex_quickfix_latexlog` is not set is that the default value is used "behind the scene", i.e., the variable may be unset, but if it is, then the documented default value is used.

In your example, please outline the steps required to observe your actual problem.

**Comment by PatrBal** [comment] 2019-01-22 12:14
Ok, sorry. My problem is that the quickfix window shows up only if there are errors during the compilation. It does not show up if there are only warnings.

Here is a minimal example.

Minimal .vimrc file:
```vim
execute pathogen#infect()
set nocompatible
syntax on
filetype plugin indent on
let g:polyglot_disabled = ['markdown','latex']
```

Minimal toto.tex file
```tex
\documentclass{article}
\begin{document}
$$
\mbox{This is a very looooooooooooooooooooooooooooooooooooooooooooooong line, likely to produce an overflow}
$$
\end{document}
```

First, I open the file toto.tex in MacVim:

> mvim toto.tex

Second, I compile toto.tex from MacVim:

> :VimtexCompile

The file toto.pdf is produced. The quickfix window does not show up in MacVim, although the file toto.log contains the line:

> Overfull \hbox (130.47371pt too wide) detected at line 5

So, in this minimal example, the quickfix window does not open on warnings such as "Overfull \hbox", although it should by default, if I understand the Vimtex doc correctly. Thanks in advance for your help.

**Comment by lervag** [comment] 2019-01-24 22:12
Can you please use a minimal vimrc file as well? Do _not_ include `execute pathogen#infect()`. Instead, use something like this:

```vim
set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
" Obviously, change the path above to the current path to vimtex
filetype plugin indent on
syntax enable
```

With your current example, I have **no idea** which plugins are loaded, and as such, the example is very far from minimal.

**Comment by lervag** [comment] 2019-01-24 22:17
However, I was still able to reproduce this and I think it is fixed now.

**Closed** 2019-01-24 22:16 UTC

**Comment by PatrBal** [comment] 2019-01-25 12:13
Thanks!

**Comment by lervag** [comment] 2019-01-25 12:19
No problem. :)
