### ISSUE TITLE
compile problem with \include{somefile}

### ISSUE THREAD

**Issue by pengyun04** [lervag/vimtex#332] opened 2016-01-22 13:42 UTC
When I use command \include{somefile}, somefile will not be compiled.

But after I change it to \input{somefile}, the compile does. Does it support \include command?

**Comment by lervag** [comment] 2016-01-22 13:45
Sorry, but I have NO idea what you mean. Can you please provide a full example? See [here](https://github.com/lervag/vimtex/tree/master/test/template) for a useful template.

**Comment by pengyun04** [comment] 2016-01-22 15:00
There are two .tex files: main.tex and chap1.tex

in main.tex:
	 \documentclass{minimal}
	 \begin{document}
	 
	 \include{chap1.tex}
	 
	 \end{document}

in chap2.tex:
        Hello World!

When I press "\ll", it prompts the messages "latexmk compile: fail"
But when I change "\include{chap1.tex}" to "\input{chap1.tex}", it will compile sucessfully.

Thanks for your reply.

**Comment by pengyun04** [comment] 2016-01-23 06:59
Sorry, I would give more details. 

There are two files: main.tex and chap1.tex

main.tex

           \documentclass{minimal}
           \begin{document}
                 \include{chap1.tex}        % This line may change.
           \end{document}

chap1.tex

           Hello world!

And I set the build directory to directory "build":

           let g:vimtex_latexmk_build_dir = 'build'

There are two problems.

Problem 1:

  Put main.tex and chap1.tex in the same directory:

           | main.tex
           | chap1.tex

  Then using    "\include{chap1.tex}" will result in "compile fail".
  While using  "include{chap1}",  "\input{chap1.tex}", and "\input{chap1}" will compile successful.
  This problem is minor, which can be passed by using "include{chap1}".

Problem 2:

  Put chap1.tex in the subdirectory "data":

           | main.tex
           + data
           | --chap1.tex


  Then when I use    "\include{data/chap1}" will result in a error

                 main.tex|5 error| I can't write on file `data/chap1.aux'.

while the "\input" command works correctly.

I think there may be a bug about the build dir:
          let g:vimtex_latexmk_build_dir = 'build'

**Comment by nasenatmer** [comment] 2016-01-23 14:09
Problem 1 is not a problem but default with the `\include` command:
> The issue is the .tex extension. It is always optional and will be added automatically. However, in the case of \include is is not be allowed. The reason is that it also creates a <name>.aux file and needs the name without extension for that. Otherwise it will create <name>.tex.aux and try to read `<name>.tex.tex, which causes the error. [source](http://tex.stackexchange.com/a/34793)

Problem 2: I can confirm this happening both with `let g:vimtex_latexmk_build_dir` being set to `build` and `./build`.

**Comment by lervag** [comment] 2016-01-23 16:12
Thanks, I'll look into this when I get the time.

**Comment by lervag** [comment] 2016-01-24 22:33
Thanks for the clarification about problem 1, @nasenatmer. I have now added test files that reproduce problem 2, see the commit with reference to this issue.

**Comment by pengyun04** [comment] 2016-01-25 11:09
Great, thanks for your response.

**Comment by lervag** [comment] 2016-01-25 19:03
Ok, so, this problem can be reproduced without vimtex. I run `latexmk -pvc -pdf -outdir=build main.tex` on a clean version of the test directory, and I get this output:

```
> latexmk -pvc -pdf -outdir=build main.tex

Latexmk: This is Latexmk, John Collins, 5 February 2015, version: 4.43a.
Latexmk: making output directory 'build'
Viewing pdf
Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex -synctex=1 -interaction=nonstopmode --shell-escape  -recorder -output-directory="build"  "main.tex"'
------------
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (TeX Live 2015/Arch Linux) (preloaded format=pdflatex)
 \write18 enabled.
entering extended mode
(./main.tex
LaTeX2e <2015/10/01> patch level 2
Babel <3.9m> and hyphenation patterns for 79 languages loaded.
(/usr/share/texmf-dist/tex/latex/base/minimal.cls
Document Class: minimal 2001/05/25 Standard LaTeX minimal class
) (build/main.aux)
! I can't write on file `data/chap1.aux'.
\@include ...\immediate \openout \@partaux #1.aux
                                                  \immediate \write \@partau...
l.4 \include{data/chap1}

(Press Enter to retry, or Control-D to exit; default file extension is `.tex')
Please type another output file name
! Emergency stop.
\@include ...\immediate \openout \@partaux #1.aux
                                                  \immediate \write \@partau...
l.4 \include{data/chap1}

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on build/main.log.
Latexmk: Directory 'build/data' created
Latexmk: Errors, so I did not complete making targets
Latexmk: Failure to make the files correctly
    ==> You will need to change a source file before I do another run <==
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 256

=== Watching for updated files. Use ctrl/C to stop ...
```

My initial thought is therefore that the problem is not really a vimtex problem, and that there is little that I can do to help. I'll investigate some more, though, perhaps this can be fixed with some other options for latexmk?

**Comment by pengyun04** [comment] 2016-01-26 11:57
Haha, I see, I think you can help!

If  I create "build/data" subdirectory first, then it will compile nicely. The Latexmk can do build the "build" directory, but it can not build the subdirectory "data". I have just tested it.

So, could you help build the directory "build" and its subdirectory "build/data" before Latexmk compiles?

**Comment by lervag** [comment] 2016-01-27 17:54
Ah, good catch! I think I've fixed it with the last commit.

**Closed** 2016-01-27 17:54 UTC
