### ISSUE TITLE
Undefined variable s:re

### ISSUE THREAD

**Issue by Rmano** [lervag/vimtex#606] opened 2016-10-27 12:19 UTC
Opening with a minimal vimrc the file at: https://github.com/jboalml/latex/blob/master/teaching/teaching.cls gives this error: 

```
"teaching.cls" 713L, 30044C
Error detected while processing function vimtex#delim#get_delim_regexes:
line    1:
E121: Undefined variable: s:re
E15: Invalid expression: [s:re.delim_math.open, s:re.delim_math.close,  s:re.del
im_tex.open,  s:re.delim_tex.close]
```

Moreover,  this file shows a very bad example of (I think) bug #598 - if you go to line 407, and try to add a line to the `literate` options, vimtex freezes. I waited one minute and then hit ctrl-c.

**Comment by lervag** [comment] 2016-10-27 12:21
I think this bug was fixed recently, see #595.

**Comment by lervag** [comment] 2016-10-27 12:22
I am working on the slowdown issue. I hope to have a fix ready in not too long. It is my main priority at the moment.

**Comment by Rmano** [comment] 2016-10-27 12:24
Ah ok. Pulled the change only on the other machine. Sorry for the noise!

**Comment by lervag** [comment] 2016-10-27 12:24
No problem :)

**Comment by Rmano** [comment] 2016-10-27 12:38
...anyway, check the solution with the linked file --- I am not sure it is the same issue. I left the thing running 10 minutes, and nothing happens.

**Comment by lervag** [comment] 2016-10-27 12:38
Hmm, that's strange. I'll test.

**Comment by lervag** [comment] 2016-10-27 13:50
It seems this is the same as #609. Since #609 has a reproducible MWE, I'll close this issue.

**Closed by lervag** 2016-10-27 13:50 UTC
