### ISSUE TITLE
Compilation status is always `fail`

### ISSUE THREAD

**Issue by maxfl** [lervag/vimtex#790] opened 2017-04-14 08:53 UTC
I'm using the commit 3b968d7 and mwe from #763. The compiler status is always `fail`, even when `latexmk` is called for the second time and does nothing.

**Comment by lervag** [comment] 2017-04-14 18:17
Hmm. If I go to the #763 test folder (`VIMTEX/test/issues/763`), then run `vim --servername VIM -u minivimrc`, I observer:

- The `sub.tex` file is opened
- Main file is toggled, so that the local `subfile` is enabled

Now I start compilation, which occurs in the background because of the minimal vimrc settings. When compilation is finished, I get `compiler: success`.

Thus, I can't reproduce your issue...

**Comment by maxfl** [comment] 2017-04-26 09:41
I have not specified it in the first message. The issue is not subfiles. I've tried the latest vimtex and it failed again. I will dig more into the problem in order to provide something useful for the analysis.

Just in casel, here is the `latexmk` output which is captured by `vimtex`
```
Latexmk: All targets (test.pdf) are up-to-date
2016, version: 4.48.
```

The actual output that goes to the console is:
```
Latexmk: This is Latexmk, John Collins, 5 Sep. 2016, version: 4.48.
Latexmk: All targets (test.pdf) are up-to-date
```
first line goes to stderr and the scond line to stdout.

May it happen that vimtex somehow interprets the 'version' line?

**Comment by lervag** [comment] 2017-04-26 09:46
No, vimtex does not parse the `version` line. With the minivimrc file from #763, which turns off callbacks and continuous compilation, the compile status is parsed by parsing the log file with the Vim errorformat. As said, this works as expected for me.

Is the problem still there with the last version of vimtex?

Could you add some more detail:
- What exact steps do you do to reproduce?
- Which OS are you on?
- Which version of Vim (or neovim)? With/Without gui?

**Comment by maxfl** [comment] 2017-04-26 09:57
ok, let me play with minimalrc, options and errorformat and I will share details in case I still get the `fail` status.

**Comment by lervag** [comment] 2017-04-26 10:01
Sounds good!

Suggestion: If you can reproduce again and can provide steps and details that I can use to reproduce as well, then open a new issue to explain. I'll close this one. That way it will be easier for me, since i won't have to read all the extra comments if it should take a while.

**Closed by lervag** 2017-04-26 10:01 UTC
