### ISSUE TITLE
Better error handling for latexmk

### ISSUE THREAD

**Issue by s4shmz** [lervag/vimtex#964] opened 2017-10-02 04:08 UTC
First of all, thanks for developing vimtex. The plugin helps my daily works very well.

This is my small ftplugin that I use with vimtex. The function `FilterLatexmkMessages` picks messages of each last-run command called by latexmk.

```vim
setlocal errorformat-=%-G%.%#

augroup FilterLatexmkMessages
  autocmd!
  autocmd QuickfixCmdPost <buffer> call s:FilterLatexmkMessages()
augroup END

function! s:FilterLatexmkMessages()
  let qflist = getqflist()

  "
  " Add log messages to a dictionary. Keys of the dictionary are command rules
  " called by latexmk. If same rule is processed more than once, only the
  " last-run message is stored in the dictionary
  "
  let match_rule="Run number . of rule "
  let log_dict={}
  let log_key=''

  for i in qflist
    if match(i.text, match_rule) != -1
      let log_key = i.text[match(i.text, match_rule)+len(match_rule):]
      let log_dict[log_key] = []
    endif
    if log_key != ''
      call add(log_dict[log_key], i)
    endif
  endfor

  "
  " Reconstruct qflist from the dictionary
  "
  " By this if statement, this function is compatible for single command(latex,
  " pdflatex , bibtex or something else).
  if log_key != ''
    let qflist=[]
    for key in keys(log_dict)
      for i in log_dict[key]
        if ! i.valid
          continue
        endif
        call add(qflist, i)
      endfor
    endfor
    call setqflist(qflist)
  endif
endfunction

" Errorformat for bibtex
setlocal errorformat+=%.%#---line\ %l\ of\ file\ %f
setlocal errorformat+=Sorry---you've\ exceeded\ BibTeX's\ %.%#
setlocal errorformat+=%.%#---this\ can't\ happen
setlocal errorformat+=I\ found\ %.%#---while\ reading\ file\ %f
setlocal errorformat+=refers\ to\ entry\ "%.%#
setlocal errorformat+=%tarning--I\ didn't\ find\ a\ database\ entry\ for\ %.%#
setlocal errorformat+=%tarning--%m
setlocal errorformat+=Aborted\ at\ line\ %l\ of\ file\ %f
setlocal errorformat+=%.%#\ WARN\ -\ %.%#
setlocal errorformat+=%.%#\ ERROR\ -\ %.%#
```

By using this function, `:make` can handle errors/warnings from latexmk appropriately. I use vimtex with `g:vimtex_compiler_enabled=0` because I prefer vim’s standard `:make` command.

In addition, using this function, I think vimtex can handle errors/warnings from bibtex or makeindex or dvipdf. I added some “errorformat” for bibtex to my small ftplugin. Note that my settings of the “errorformat” are not well-tested.

Is this helpful?

**Comment by lervag** [comment] 2017-10-03 20:56
I am happy to hear that you like the plugin!

I took the liberty of editing your post to improve formattting and some vimscript syntax.

So, I'm trying to understand exactly what you are doing/suggesting here. My understanding is that you have defined your own `makeprg` that uses `latexmk`, and that you are using the errorformat defined by vimtex, except that you apply some customizations. First, you remove the errorformat line that ignores the remaining parts, then you modify the quickfix list in order to only show the entries relevant to the last run command, or something like that.

I am not quite seeing how to use this for vimtex. But that might just be because I'm slightly confused.

Some questions:
- Is your errorformat still applied to the `.log` file?
- Can you provide an example log file that has e.g. bibtex errors that you are parsing with your customized errorformat?

**Comment by s4shmz** [comment] 2017-10-04 11:44
Thank you for your reply!

Last month, the warning of 'empty author' was in my paper,
and I cannot detect it since it was produced by bibtex.
That is why I wrote my customizations and I call latexmk in my makefile or `makeprg`.

For your questions,

> Is your errorformat still applied to the .log file?

Yes. With my customizations, I can also use `:VimtexCompileSS` or `:VimtexError` and it works.
But all lines are shown because my ftplugin removes `%-G%.%#`.
I think unnecessary lines can be removed by `autocmd QuickfixCmdPost`, like `if ! i.valid`  in my `FilterLatexmkMessages()`.

As you say, I use vimtex with `g:vimtex_quickfix_enabled=1`, and I use errorformat defined by vimtex to parse logs from 'latex' commands.
Removing `%-G%.%#` from errorformat is to give all lines to my function `FilterLatexmkMessages()`.
Added "errorformat" is for bibtex, and they are ignored in latex log files, I think.

In addtion, `FilterLatexmkMessages()` does not filter any lines of latex log files.
That is because of the if statement `if log_key != ''` in `FilterLatexmkMessages()`.
For the messages from latexmk,  the if statement `if match(i.text, match_rule) != -1` will be true at least once and log_key will not be empty.
For the latex log file,  the if statement `if match(i.text, match_rule) != -1` will not be true and `log_key` will be empty.
If `log_key` is empty, the function `FilterLatexmkMessages()` does not filter messages.
I use this logic because my ftplugin is just a personal customization.
I think vimtex can use `FilterLatexmkMessages()` only for messages from latexmk.
For the latex log files, vimtex uses cgetfile(Is that right?).
Therefore, for cgetfile, vimtex does not have to use `FilterLatexmkMessages()`.
For `:make` or cexpr or somewhat that calls latexmk, vimtex can filter messages with `FilterLatexmkMessages()`.

> Can you provide an example log file that has e.g. bibtex errors that you are parsing with your customized errorformat?

To add errorformat for bibtex, I referenced to the code of latexrun.
I'm sorry but I don't knonw how to reproduce all errors/warnings from bibtex.
The errorformat for bibtex may be inappropriate.

Here is a small document that generates the warning of 'empty author'.
With my customizations and `set makeprg=latexmk\ -file-line-error\ -interaction=nonstopmode\ $*`, `:make` can handle bibtex warnings with the example.
VimtexCompileSS also works with the example document.

```latex
\documentclass{article}

\begin{document}

\cite{noauthor} has no author.
\cite{undefined} is undefined.

\bibliographystyle{plain}
\bibliography{ref}
\end{document}
```

And this is a bib file example.

```
@article{noauthor,
    title={article title},
    journal={a journal},
    year={2015},
}
```

**Comment by s4shmz** [comment] 2017-10-04 11:59
I modified the function `FilterLatexmkMessages()`.
The line `setqflist(filter(copy(getqflist()), 'v:val["valid"]'), 'r')` works like `%-G%.%#`.
With this version of `FilterLatexmkMessages()`, `:VimtexCompileSS` does not show unnecessary lines.

```vim
func! s:FilterLatexmkMessages()
	let qflist = getqflist()

	""
	"" Add log messages to a dictionary.
	"" Keys of the dictionary are command rules called by latexmk.
	"" If same rule is processed more than once,
	"" only the last-run message is stored in the dictionary
	""
	let match_rule="Run number . of rule "
	let log_dict={}
	let log_key=''

	for i in qflist
		if match(i.text, match_rule) != -1
			let log_key = i.text[match(i.text, match_rule)+len(match_rule):]
			let log_dict[log_key] = []
		endif
		if log_key != ''
			call add(log_dict[log_key], i)
		endif
	endfor

	""
	"" Reconstruct qflist from the dictionary
	""
	if log_key != '' "By this if statement, this function is compatible for single command(latex, pdflatex or bibtex).
		let qflist=[]
		for key in keys(log_dict)
			for i in log_dict[key]
				call add(qflist, i)
			endfor
		endfor
		call setqflist(qflist)
	endif

	""
	"" Remove unnecessary lines
	""
	setqflist(filter(copy(getqflist()), 'v:val["valid"]'), 'r')
endfunc
```

**Comment by lervag** [comment] 2017-10-05 20:51
Would you consider this issue solved if I added parsing of the `.blg` file to the standard behaviour of vimtex? That is, in addition to showing errors/warnings from the `.log` file, `VimtexErrors` could also show errors/warnings from the `.blg` file?

**Comment by s4shmz** [comment] 2017-10-05 23:13
Yes.
I think your solution is better for vimtex.
I forgot `g:vimtex_compiler_latexmk['continuous'] = 1` or something else.

Thanks for your consideration!

**Comment by lervag** [comment] 2017-10-07 21:08
Ok, I've made a first implementation. For now it only parses the "empty X in Y" type of errors. I don't want to parse more errors until I can "reproduce" them. Thus we need to improve/add to the example files before I add more error types.

Note: This will append bibtex errors/warnings to the quickfix list below the LaTeX related errors.

To test, set

```vim
let g:vimtex_quickfix_bibtex = {'enabled': 1}
```

**Comment by s4shmz** [comment] 2017-10-08 09:23
Thanks for your work!

I wrote some warning examples here.

```latex
\documentclass{article}

\begin{document}

%Warning--I didn't find a database entry for "undefined"
\cite{undefined}

%Warning--to sort, need author or key in bib1
%Warning--empty author in bib1
%Warning--empty title in bib1
%Warning--empty journal in bib1
\cite{bib1}


%Repeated entry---line 11 of file ref.bib
% : @article{bib2
% :              ,
%I'm skipping whatever remains of this entry
\cite{bib2}


%Warning--entry type for "bib3" isn't style-file defined
%--line 18 of file ref.bib
\cite{bib3}


\bibliographystyle{plain}
\bibliography{ref}
\end{document}
```

and bib file

```
@article{bib1,
	year={2017},
}

@article{bib2,
	author={a},
	title={t},
	journal={j},
	year={2017},
}
@article{bib2,
	author={a},
	title={t},
	journal={j},
	year={2017},
}

@nostyle{bib3,
	author={a},
	title={t},
	journal={j},
	year={2017},
}
```

**Comment by lervag** [comment] 2017-10-08 20:36
Thanks, I'm adding these now. Feel free to update if/when you have more errors. I'm deliberately not parsing some of the errors, e.g. "%Warning--to sort, need author or key in bib1". It feel's appropriate (but I might be wrong).

**Comment by lervag** [comment] 2017-10-08 21:01
It would be nice to add similar functionality for biber, but it seems to be more difficult to parse the errors. Perhaps I'm looking in the wrong file, though. In any case, I'm now enabling this by default and adding some docs for it. With that, I'm also closing the issue as resolved. Hope you find that OK.

**Closed by lervag** 2017-10-08 21:01 UTC

**Comment by s4shmz** [comment] 2017-10-08 23:32
Thanks!

I think this should be closed.

I will report errors/warnings if I find new one.
For now, I feel `Repeated entry` should be treated as a warning.

FYR,
https://tex.stackexchange.com/questions/1380/how-to-avoid-bibtex-error-message-repeated-entry-for-an-entry-appearing-in-sev

Some users may want to disable `Repeated entry` optionally.

**Comment by lervag** [comment] 2017-10-09 08:53
Based on that SO post, it seems to me that it is still "wrong" to have repeated entries. Are you sure that it is safe to ignore the message?

**Comment by s4shmz** [comment] 2017-10-09 09:23
If some entries are duplicated, the document (e.g the example in this issue) will be generated and it looks fine.

But I found btxFAQ.pdf in CTAN that says,
> You should therefore ensure that the key you choose for each item contains a part that identifies the file, so that there is no chance of ambiguous or duplicated keys when using multiple database files simultaneously.

https://ctan.org/tex-archive/biblio/bibtex/contrib/doc/

I'm sorry but it should not be ignored according to btxFAQ.pdf.

**Comment by lervag** [comment] 2017-10-09 15:11
So, you agree to treat this as an error? Perhaps we can add an option to filter bibtex errors/warnings; then people who do not care about e.g. this particular error can ignore it? Something like:

```vim
let g:vimtex_quickfix_bibtex = {
    \ 'ignored' = ['pat1', ..., 'patn'],
    \}
```

where the `patx`s are regular expressions to match the error/warning messages?

**Comment by s4shmz** [comment] 2017-10-10 00:05
> So, you agree to treat this as an error?

Yes, it should be an error.

I wrote a example.

```latex
\documentclass{article}

\begin{document}

\cite{bib}

\bibliographystyle{plain}
\bibliography{ref}
\end{document}
```

```
@article{bib,
	author={a},
	title={t},
	journal={j},
	year={2017},
}
@article{bib,
	author={a},
	title={t},
	journal={j},
	year={2017},
}
```

The last line of blg file says,

> (There was 1 error message)

Therefore it should be an error.
I don't know what happened if people ignore this error.
I'm not sure if this can be ignored.

**Comment by lervag** [comment] 2017-10-10 06:35
Great, I agree. Thanks!

**Comment by lervag** [comment] 2017-10-10 21:11
I now added a parser for biblatex/biber as well. There might obv. be some bugs, so please let me know if you find any problems!

**Comment by s4shmz** [comment] 2017-10-12 13:18
> I now added a parser for biblatex/biber as well. There might obv. be some bugs, so please let me know if you find any problems!

It works and looks good, thank you!

**Comment by lervag** [comment] 2017-10-12 13:20
No problem! Thank you for suggesting this (or at least making me aware of the valuable content of the `.blg` files); I already use and appreciate the new feature myself.
