### ISSUE TITLE
Interface hanging after compilation (when parsing log?)

### ISSUE THREAD

**Issue by Djoop** [lervag/vimtex#1635] opened 2020-03-23 17:44 UTC
Hi and thanks for the great plugin.

Vimtex hangs for me just after compilation. I sadly cannot produce a MWE, as it happens only with large documents. I'm compiling with lualatex and misc. font options, so the compilation process is slow and produces a large log file. Compilation being asynchronous, this is not really a problem (and anyway not vimtex-related), but once compilation is performed the interface just hangs for a few seconds before the quickfix window shows up, and then again a 2-3 seconds after "compilation completed" is written.
I tried desactivating the quickfix window (with g:vimtex_quickfix_enabled) and it looks like the problem does disappear.

My guess is that at this point vimtex is parsing the log, but I don't get how this could be so slow, so what else is performed at this point and could be the problem?

**Comment by lervag** [comment] 2020-03-23 20:28
> Hi and thanks for the great plugin.

Your welcome :)

> Vimtex hangs for me just after compilation. I sadly cannot produce a MWE, as it happens only with large documents. I'm compiling with lualatex and misc. font options, so the compilation process is slow and produces a large log file. Compilation being asynchronous, this is not really a problem (and anyway not vimtex-related), but once compilation is performed the interface just hangs for a few seconds before the quickfix window shows up, and then again a 2-3 seconds after "compilation completed" is written.
> I tried desactivating the quickfix window (with g:vimtex_quickfix_enabled) and it looks like the problem does disappear.

Yes, there is a callback after compilation that might be responsible for this. However, I've not experienced it myself, and I didn't really think it should give such large delays.

The delay is not related to parsing the log file (99.9% sure). My guess is that it is related to parsing the LaTeX document itself for changes to e.g. syntax and stuff like that.

I know it is much to ask, but: could you provide me an example document in which you have these experiences and a set of operations that can reproduce it? I understand if you hesitate sharing such a document, at least on github. You could possibly email it to me?

One way to avoid the issue is to disable callbacks. This may be done by adding the following configuration to your vimrc file:

```vim
let g:vimtex_compiler_latexmk = {'callback': 0}
```

**Comment by Djoop** [comment] 2020-03-24 08:19
Thank you for this suggestion. Is there a difference between disabling the callback and the quickfix window ? If I understand correctly, parsing the file is necessary to produce the informations in the quickfix window, it's not possible to e.g. just parse the log but somehow disable the parsing step? Is there anything that could make this process particularly slow, or should it just be roughly proportional to the document size? And I guess there is no reason it should depend on the tex engine used either?

I sadly cannot share my document, and I tried producing a dumb long document by copy-pasting text but the problem doesn't appear. I also tried with the source of open-source latex books (with pdftex), no problem either. Looks like it's really the combo many chapters in many files + many equations + many figures + many packages that produces the problem. I understand if you cannot help more than that without a document to work with.

**Comment by lervag** [comment] 2020-03-24 09:06
> Thank you for this suggestion. Is there a difference between disabling the callback and the quickfix window?

Yes. If you disable the quickfix feature you can't do `:VimtexErrors` to parse the log file for errors. Disabling callback will only prevent the callback feature from working, which does more than this. But it is not strictly necessary.

> I sadly cannot share my document, and I tried producing a dumb long document by copy-pasting text but the problem doesn't appear. I also tried with the source of open-source latex books (with pdftex), no problem either. Looks like it's really the combo many chapters in many files + many equations + many figures + many packages that produces the problem. I understand if you cannot help more than that without a document to work with.

Yes, sorry. It is really not easy to help without working with a working example. Note, though, that I'm currently working on a similar issue #1634, and improvements here might also benefit this issue.

**Comment by lervag** [comment] 2020-03-24 21:39
I'm pushing an update that I think should improve things quite a bit. Please test newest version.

**Comment by Djoop** [comment] 2020-03-25 08:32
I just updated the package. I can confirm that it is better for me. The interface still hangs after compilation, but everything happens a bit faster than it used to, I think I can deal with that. When I have more time, I can try to see how to profile the plugin execution and give some clues of what could still be improved.

**Comment by lervag** [comment] 2020-03-25 08:36
Sounds good. I'll take the liberty of closing the issue, but feel free to reopen if/when you update with more information regarding your particulra issue. thanks!

**Closed by lervag** 2020-03-25 08:36 UTC
Labels: bug
