### ISSUE TITLE
Latest Skim update: \ll n longer jumps to the current location

### ISSUE THREAD

**Issue by msiniscalchi** [lervag/vimtex#1260] opened 2018-11-19 21:47 UTC
What it says in the title. 

Software version: macOS Mojave, Skim 1.4.37, vimtex updated as of 11/19/2018, MacVim 8.1.280. (I see the same behavior with nvim / VimR).

I have the following in my .vimrc:

```vim
let g:vimtex_view_method = 'skim'
let g:vimtex_view_automatic = 1 " Hopefully fixes things!
```
With any TeX file, `\ll` launches latexmk, which compiles correctly, etc. However, Skim then jumps to the very beginning of the file. I didn't have this behavior before the latest update (to Mojave or Skim; can't tell which one because I did both at the same time). I have no such problem on Windows with SumatraPDF.

I also tried other editors (Sublime Text with the LatexTools plugin), and --- after requesting permission to "control Skim" --- everything worked as before. 

I also checked in the System Settings, and MacVim *is* allowed to "control Skim."

**Comment by clason** [comment] 2018-11-19 21:56
Are you sure that you didn't also update `vimtex` at the same time? This behavior is by design (see, e.g. #982; changed in #997) -- to jump to the current location, use `<localleader>lv`.

**Comment by clason** [comment] 2018-11-19 22:02
Yes, you're right; I can reproduce this. Looking at the patch notes, this is something that changed on the Skim side in one of the last two version; it's not specific to `vimtex` (I just verified that the AppleScript code is still identical to that bundled with `vimtex`.) 

I'm afraid you have to open an issue with Skim (please do! this *is* annoying).

**Comment by msiniscalchi** [comment] 2018-11-19 22:07
Yes, that's what I see---it always jumps back to the beginning. SumatraPDF doesn't do that (I just checked, after updating everything).

I also need to check how LatexTools on Sublime does things, because there it works fine. I think it explicitly jumps to the current location. Maybe vimtex only tells Skim to reload, which now jumps back to the beginning of the file. I'll explore further...

**Comment by lervag** [comment] 2018-11-19 22:10
@clason @msiniscalchi I'll be following this up when necessary/relevant. I don't use OSX and Skim, so for now, I'll just "stay in the background".

**Comment by clason** [comment] 2018-11-19 22:13
Yes, that is correct -- vimtex only reloads on file change (because you might not be working on the same TeX source that you are looking at). You can either downgrade to version 1.4.36 (use the link in the linked issue) or edit `autoload/vimtex/view/skim.vim` to copy the two lines
```viml
       \ '-e ''set theSource to POSIX file "' . expand('%:p') . '"''',
```
and
```viml
       \ '-e ''tell front document to go to TeX line theLine from theSource',
```
from the `s:skim.view` function to `s:skim.compiler_callback`.

@lervag Maybe it would make sense to wrap this with a vimtex option? (Make ALL THE OPTIONS...)

**Comment by lervag** [comment] 2018-11-20 08:32
Does it make sense for Skim users to have this option? What should the name of the option be, if so?

**Comment by clason** [comment] 2018-11-20 08:53
I'd prefer it to be off (obviously), but somebody else might prefer the old behavior? As for the name, maybe `g:vimtex_view_skim_callback_sourcesync`? (Bit long, though.)

**Comment by msiniscalchi** [comment] 2018-11-20 16:03
Thanks guys. I'll see if I can experiment some more, but I am drowning in work right now :-(

**Comment by msiniscalchi** [comment] 2018-11-20 17:17
Quick notes, from the Skim forum:

1. Apparently a fix will be pushed out soon. 
2. As a work-around, hitting CMD-[ (i.e., back) will take you, well, back where you were. You still need to focus Skim to do it, but it's something!

**Comment by lervag** [comment] 2018-11-20 20:31
Thanks for new input! I'm tempted to _not_ add a new option, and instead let you live with the "bad" version of Skim until it is fixed. It feels a little bit like the option is only necessary right now, since no one has complained about how the Skim interface works before just now. However, I might be persuaded otherwise if you feel this option is important.

**Comment by clason** [comment] 2018-11-21 07:53
@znculee You can also just download it from the project homepage. Here's the direct link:
https://sourceforge.net/projects/skim-app/files/Skim/Skim-1.4.36/Skim-1.4.36.dmg/download

**Comment by clason** [comment] 2018-11-25 09:05
This is now fixed in Skim 1.4.38.

**Comment by lervag** [comment] 2018-11-25 09:47
In that case, I'm closing this issue. Hope that's alright with everyone.

**Closed by lervag** 2018-11-25 09:47 UTC

**Comment by unnikrishnanta** [comment] 2020-09-02 03:16
Just following up on this issue, to be clear, `\ll` should now move to the current latex line in Skim? Because it doesn't work for me. `\ll` opens Skim but doesn't update the position to the line. `\lv' works just fine and moves to the line number in latex. What should I change if I want `\ll` to move to the current line?

**Comment by lervag** [comment] 2020-09-02 06:54
Which version of Skim are you on, @unnikrishnanta?

**Comment by clason** [comment] 2020-09-02 07:08
@unnikrishnanta Yes, you are correct, this is by design. If you want to change that, see https://github.com/lervag/vimtex/issues/1260#issuecomment-440060765

(You could also add an autocommand that calls `\lv` after a successful compile; this is probably easiest. @lervag I had been thinking about making that script smarter to highlight the line if and only if skim is opened for the first time, but not when it reloads, but I think the new vimtex events are a better approach for making this configurable. What do you think?)

**Comment by unnikrishnanta** [comment] 2020-09-02 07:38
> Which version of Skim are you on, @unnikrishnanta?

I am using Version 1.5.11. 

I am trying to see how I can call `\lv` after compiling. 

 ```
augroup MyVimtex
 au!
 autocmd User VimtexEventCompileStopped call b:vimtex.viewer.view('')<CR>
 augroup END
```

Doesn't seem to work. 

A rather lazy mapping 
`nnoremap <silent> <leader>ll : call vimtex#compiler#compile()<CR> : call b:vimtex.viewer.view('')<CR> `
works but then Skim gets refreshed way too many times when I press `\lv`. 


These are my settings: 

```
let g:tex_conceal = ""
let g:vimtex_fold_enabled = 0
let g:vimtex_fold_types = {'sections' : {'parse_levels': 1}}
" Hide quick fix window on warnings
let g:vimtex_quickfix_open_on_warning = 0
let g:vimtex_compiler_latexmk = {
        \ 'continuous' : 0,
        \ 'executable' : 'latexmk',
        \ 'hooks' : [],
        \ 'options' : [
        \   '-verbose',
        \   '-file-line-error',
        \   '-synctex=1',
        \   '-interaction=nonstopmode',
        \ ],
        \}

let g:tex_flavor = "latex"
let g:vimtex_view_automatic = 1
let g:vimtex_compiler_progname = 'nvr'
let g:vimtex_view_method = 'skim'

```

**Comment by clason** [comment] 2020-09-02 07:42
I think you want `VimtexEventCompileSuccess` -- `VimtexEventCompileStopped` is probably triggered when you stop compilation manually.

**Comment by unnikrishnanta** [comment] 2020-09-02 07:47
> I think you want `VimtexEventCompileSuccess` -- `VimtexEventCompileStopped` is probably triggered when you stop compilation manually.
> 
> And you should probably call `<plug>(vimtex-view)` instead of the buffer function?

Ah! Excellent. Thank you so much. This works as expected. 

I could see from the discussion here that some people prefer to not move the PDF automatically after compiling. I prefer to move it instead. Having the option to customise the behaviour is a win-win. Thank you for that.

**Comment by lervag** [comment] 2020-09-02 19:01
> @lervag I had been thinking about making that script smarter to highlight the line if and only if skim is opened for the first time, but not when it reloads, but I think the new vimtex events are a better approach for making this configurable. What do you think?

Keep it simple (unless necessary); I think the events should work well, and if it works, don't fix it. :)

In the meantime, I see @unnikrishnanta figured out how to do it. The final solution is not posted, so I'll post something I think should work here.

Note: I've just pushed a minor update that defines `vimtex#view#view()`, which wraps the `b:vimtex.viewer.view()` so that we avoid errors when the buffer function is called (e.g. if you've moved to a non vimtex buffer when the event is executed).

```vim
augroup MyVimtex
 autocmd!
 autocmd User VimtexEventCompileSuccess call vimtex#view#view()<cr>
augroup END
```

> I could see from the discussion here that some people prefer to not move the PDF automatically after compiling. I prefer to move it instead. Having the option to customise the behaviour is a win-win. Thank you for that.

And I prefer to let people have a choice to customize things to their own preferences, and I'm happy to hear that it works!

**Comment by unnikrishnanta** [comment] 2020-09-03 01:17
> ```viml
> augroup MyVimtex
>  autocmd!
>  autocmd User VimtexEventCompileSuccess call vimtex#view#view()<cr>
> augroup END
> ```

Thank you. For me the final solution you posted without an explicit `<CR>` at the end works. Otherwise, I get an error saying there are trailing whitespaces in the command. 

```viml
augroup MyVimtex
 autocmd!
 autocmd User VimtexEventCompileSuccess call vimtex#view#view()
augroup END
```

**Comment by lervag** [comment] 2020-09-03 06:09
> Thank you. For me, the final solution you posted without an explicit `<CR>` at the end, works.

Sorry about that, my mistake!

> Thank you so much for creating and actively maintaining this plug-in. I am close to submitting my PhD thesis (about 80k words) and the bulk of it was written and revised using Neovim + Vimtex. The plug-in has been a lifesaver for me.

Thanks for the kind words, I'm happy to hear that its been useful to you! Good luck on finishing your thesis!
