### ISSUE TITLE
weird jump movement after vimtex compiled

### ISSUE THREAD

**Issue by lee-shun** [lervag/vimtex#2661] opened 2023-03-05 20:28 UTC
### Description

Hello!

Every time vimtex finishes compiling, if at that moment I am navigating using "h", there will be a weird movement that takes me to the next line.

**NOTE:** I tried without noice and notify, the bug disappears.

For example, in the following gif, I am pressing "h" only, but once the "message vimtex compile failed!" there will be a movement takes me to the next line...

![Peek 2023-03-04 22-27](https://user-images.githubusercontent.com/46647235/222985213-99df4d26-f92b-4664-9ec8-88f9930fd1ef.gif)

### Steps to reproduce

I use lazy.nvim.

```lua
{
	"lervag/vimtex",
	ft = "tex",
	config = function()
		vim.g.vimtex_view_method = "zathura"
		vim.g.vimtex_quickfix_mode = 0
		vim.g.vimtex_mappings_enabled = 0
		vim.g.vimtex_imaps_enabled = 0
		vim.g.vimtex_text_obj_enabled = 0
		vim.g.vimtex_fold_enabled = 0
		vim.g.tex_conceal = "abdmg"
		vim.g.vimtex_syntax_conceal_disable = 1
		vim.g.vimtex_format_enabled = 0
		vim.g.vimtex_syntax_enabled = 0
	end,
}
```

noice.nvim

```lua
{
	"folke/noice.nvim",
	event = "VeryLazy",
	dependencies = { "MunifTanjim/nui.nvim" },
	opts = {
		lsp = {
			override = {
				["vim.lsp.util.convert_input_to_markdown_lines"] = true,
				["vim.lsp.util.stylize_markdown"] = true,
				["cmp.entry.get_documentation"] = true,
			},
		},
		presets = {
			bottom_search = false,
			command_palette = false,
			long_message_to_split = false,
			inc_rename = true,
			lsp_doc_border = true,
		},
	},
  -- stylua: ignore
  keys = {
    { "<S-Enter>", function() require("noice").redirect(vim.fn.getcmdline()) end, mode = "c", desc = "Redirect Cmdline" },
    { "<leader>nl", function() require("noice").cmd("last") end, desc = "Noice Last Message" },
    { "<leader>nh", function() require("noice").cmd("history") end, desc = "Noice History" },
    { "<leader>na", function() require("noice").cmd("all") end, desc = "Noice All" },
    { "<c-f>", function() if not require("noice.lsp").scroll(4) then return "<c-f>" end end, silent = true, expr = true, desc = "Scroll forward", mode = {"i", "n", "s"} },
    { "<c-b>", function() if not require("noice.lsp").scroll(-4) then return "<c-b>" end end, silent = true, expr = true, desc = "Scroll backward", mode = {"i", "n", "s"}},
  },
	config = function(_, opts)
		require("noice").setup(opts)
		require("which-key").register({
			n = { name = "Noice" },
		}, {
			mode = "n",
			prefix = "<leader>",
			buffer = nil,
			silent = true,
			noremap = true,
			nowait = false,
		})
	end,
}
```

notify.nvim

```lua
{
	"rcarriga/nvim-notify",
	keys = {
		{
			"<leader>nu",
			function()
				require("notify").dismiss({ silent = true, pending = true })
			end,
			desc = "Delete all Notifications",
		},
	},
	opts = {
		timeout = 3000,
		max_height = function()
			return math.floor(vim.o.lines * 0.75)
		end,
		max_width = function()
			return math.floor(vim.o.columns * 0.75)
		end,
	},
	config = function(_, opts)
		require("notify").setup(opts)
		require("telescope").load_extension("notify")

		local wk = require("which-key")
		local telescope_map = {
			f = {
				name = "Find",
				n = { "<cmd>Telescope notify<cr>", "Find notify" },
			},
		}
		local telescope_map_opt = {
			mode = "n",
			prefix = "<leader>",
			buffer = nil,
			silent = true,
			noremap = true,
			nowait = false,
		}
		wk.register(telescope_map, telescope_map_opt)
	end,
}
```

### Actual behavior

weird movement

### Do you use a latexmkrc file?

NO

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 20.04.5 LTS
  Vim version: NVIM v0.9.0-dev
  Has clientserver: true
  Servername: /run/user/1000/nvim.2135.0

VimTeX project: main
  base: main.tex
  root: /home/ls/forest_fire_thesis/CU_thesis
  tex: /home/ls/forest_fire_thesis/CU_thesis/main.tex
  main parser: recursive search
  document class: report
  packages: ConcordiaU algorithm algorithmicx algpseudocode amsbsy amsfonts amsgen amsmath amsopn amstext appendix atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset cite color enumitem epstopdf-base etexcmds float geometry gettitlestring graphics graphicx hycolor hyperref iftex ifthen ifvtex indentfirst infwarerr intcalc keyval kvdefinekeys kvoptions kvsetkeys letltxmacro ltxcmds multirow nameref pdfescape pdftexcmds refcount rerunfilecheck setspace setup/ConcordiaU subfigure times trig uniquecounter url
  source files:
    main.tex
    configs/Constants.tex
    supplements/Abstract.tex
    supplements/Acknowledgements.tex
    chapters/Introduction.tex
    chapters/Related_Works.tex
    chapters/System_Platform.tex
    chapters/Alg_detection.tex
    chapters/Alg_geolocation.tex
    chapters/Alg_reconstruction.tex
    chapters/Experiment.tex
    chapters/Conclusion.tex
    supplements/Appendix_A.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```

**Comment by lervag** [comment] 2023-03-05 21:00
> Every time vimtex finishes compiling, if at that moment I am navigating using "h", there will be a weird movement that takes me to the next line.
> 
> For example, in the following gif, …

It looks like this is related to nvim-notify.

> **NOTE:** I tried without noice and notify, the bug disappears.

Then it seems this is a bug with either noice or notify. Can you make a minimal example? E.g. something like this:

```tex
% test.tex
\documentclass{minimal}
\begin{document}
Hello world
\end{document}
```

```vim
" test.vim
set runtimepath^=~/path/to/vimtex
set runtimepath^=~/path/to/noice.nvim
set runtimepath^=~/path/to/nui.nvim
set runtimepath^=~/path/to/nvim-notify
set runtimepath+=~/path/to/vimtex/after
filetype plugin indent on
syntax enable

lua <<EOF

vim.g.vimtex_view_method = "zathura"
vim.g.vimtex_quickfix_mode = 0
vim.g.vimtex_mappings_enabled = 0
vim.g.vimtex_imaps_enabled = 0
vim.g.vimtex_text_obj_enabled = 0
vim.g.vimtex_fold_enabled = 0
vim.g.vimtex_syntax_conceal_disable = 1
vim.g.vimtex_format_enabled = 0
vim.g.vimtex_syntax_enabled = 0

-- options for noice.nvim, etc, goes here

EOF
```

Now run `nvim --clean -u test.vim test.tex` in some test folder and try and reproduce the error.

By the way, regarding your configuration:

* Don't use `ft = "tex"` when loading VimTeX! VimTeX is already properly lazy by use of autoloaded functions and `ftplugin/tex.vim`.
* `g:tex_conceal` is irrelevant and you can safely remove it.

**Comment by lervag** [comment] 2023-03-05 21:01
It is probably related to _both_ nvim-notify and noice. If you can make a minimal example like I've tried to help you start with, then it will be much easier to debug it. So I suggest you start there.

**Comment by lee-shun** [comment] 2023-03-05 21:03
> 

Thank you for your reply! Yes, because when I disable the noice and notify, this bug disappers. I will make a minimal example soon.

**Comment by lee-shun** [comment] 2023-03-05 21:08
Hmmmm, interestingly I use the minimal "test.tex" with my current vim config, but this bug seems to have disappeared...

**Comment by lee-shun** [comment] 2023-03-05 21:10
like this:
![Peek 2023-03-05 16-09](https://user-images.githubusercontent.com/46647235/222986174-28472084-a4a8-4527-a174-54147feeefcf.gif)

**Comment by lee-shun** [comment] 2023-03-06 01:34
Hello! After hundreds of tries, I found that the "callback" option matters. After I put the following setting in my config, this bug disappeared.

```vim
let g:vimtex_compiler_latexmk = {
        \ 'build_dir' : '',
        \ 'callback' : 0,  " just disable this one
        \ 'continuous' : 1,
        \ 'executable' : 'latexmk',
        \ 'hooks' : [],
        \ 'options' : [
        \   '-verbose',
        \   '-file-line-error',
        \   '-synctex=1',
        \   '-interaction=nonstopmode',
        \ ],
        \}
```

But could you explain to me what exactly the callback does? And why it will generate this weird movement with noice.nvim?

**Comment by lervag** [comment] 2023-03-06 20:33
Yes: the callback option (which you should probably keep enabled!) allows the `latexmk` process that VimTeX starts that is responsible for compiling your project to communicate the status ("success", "failed", "new compilation triggered") to VimTeX. This in turn allows for the notifications you see, e.g. "VimTeX: compilation completed" or "VimTeX: compilation failed".

I don't believe there is an error or bug here, and I'm quite convinced that the problem is related to the combination of noice and notify. For debugging this, I would do this:

1. First create a minimal LaTeX file on which you can reproduce the problem. Start with the one in your original post and simplify it until you can't make it smaller without removing the problem.
2. Now, similarly, create a minimal `.vimrc`, `init.vim` or `init.lua` file with which you can reproduce the problem (similar to how I explained earlier).

If you are able to provide both a minimal LaTeX file, a minimal configuration, and a simple set of instructions with which I or anyone else can use to reproduce this problem, then the chance of it being fixed is MUCH higher!

**Comment by lee-shun** [comment] 2023-03-10 00:30
Hello! Thank you for your answer, I just got time to reproduce the issue with the following minimal config:

```vim
		vim.g.vimtex_view_method = "zathura"
		vim.g.vimtex_quickfix_mode = 0
		vim.g.vimtex_mappings_enabled = 0
		vim.g.vimtex_imaps_enabled = 0
		vim.g.vimtex_text_obj_enabled = 0
		vim.g.vimtex_fold_enabled = 0
		vim.g.tex_conceal = "abdmg"
		vim.g.vimtex_syntax_conceal_disable = 1
		vim.g.vimtex_format_enabled = 0
		vim.g.vimtex_syntax_enabled = 0
```

**Comment by lervag** [comment] 2023-03-11 12:09
I can reproduce this with a much more minimal setup. The steps:

1. Download the Concordia template files provided by @lee-shun
2. Unzip them to some directory, e.g. `test`
3. Prepare:

    ```sh
    cd test
    git clone --depth=1 https://github.com/lervag/vimtex
    git clone --depth=1 https://github.com/folke/noice.nvim
    git clone --depth=1 https://github.com/MunifTanjim/nui.nvim
    ```

4. Create minimal `init.vim` with following contents:

    ```vim
    " init.vim
    set runtimepath^=vimtex
    set runtimepath^=nui.nvim
    set runtimepath^=noice.nvim
    filetype plugin on

    let g:vimtex_quickfix_mode = 0

    lua require("noice").setup {}

    silent edit main.tex

    silent! VimtexClean
    normal! 38G
    sleep 250m
    VimtexCompile
    ```

5. Now do `nvim --clean -u init.vim`
6. When the file has loaded, press and hold `h`
7. Observe that the cursor moves to the next line when the VimTeX callback is finished.

I've looked into this, and as far as I can see, there is no bug on the VimTeX side. The line of code in VimTeX that is called when this thing happens is here:

https://github.com/lervag/vimtex/blob/4c942d475bbc4eecb319c0c45c81a09ab05ca22d/autoload/vimtex/qf/u.vim#L14

The stack trace:

```
FILE                                          LINE  FUNCTION CALL
vimtex/autoload/vimtex/qf/u.vim               15
vimtex/autoload/vimtex/qf/latexlog.vim              call vimtex#qf#u#caddfile(self, fnameescape(a:log))
vimtex/autoload/vimtex/qf.vim                 127   call b:vimtex.qf.addqflist(l:tex, l:log)
vimtex/autoload/vimtex/qf.vim                 46    call vimtex#qf#setqflist()
vimtex/autoload/vimtex/compiler.vim           95    call vimtex#qf#open(0)
vimtex/autoload/vimtex/compiler/_template.vim 500   call vimtex#compiler#callback(l:status)
vimtex/autoload/vimtex/compiler/_template.vim 439   call s:check_callback()
```

Brief description of this stack trace: The call stack starts from a callback from a `jobstart` that is started here:

https://github.com/lervag/vimtex/blob/4c942d475bbc4eecb319c0c45c81a09ab05ca22d/autoload/vimtex/compiler/_template.vim#L392

This callback is used to check for the status of `latexmk` and to act accordingly. An error is reported, so VimTeX starts to parse the log file to build the quickfix entries.

I have _no_ idea why this would cause any problems. I'm hoping that the minimal example can be helpful for others that may be able to help. I strongly believe that, if there is a bug, it is either 1) with noice.nvim or nui.nvim or 2) with neovim itself.

I tried to simplify this entire business further to avoid VimTeX as a dependency at all, but that was hard.

**Comment by lervag** [comment] 2023-03-11 12:11
Notice, though, that this only happens when there is an _error_ in the latex log.

**Comment by lervag** [comment] 2023-03-11 12:16
Perhaps @folke would be able to help here with his expertice on both lua and noice.nvim?

**Comment by folke** [comment] 2023-03-12 09:07
I also have no idea what could cause. This is the only issue that reports this kind of behavior. Since I'm not a vimtex user, and the issue is not really breaking, I'm not planning to spend time investigating this further.

If someone would figure it out and it turns out to be a noice issue, then feel free to create a PR

**Comment by lervag** [comment] 2023-03-12 14:19
> I also have no idea what could cause. This is the only issue that reports this kind of behavior. Since I'm not a vimtex user, and the issue is not really breaking, I'm not planning to spend time investigating this further.

That's fair. And it's the same for me; I've tried to figure it out, but I failed.

> If someone would figure it out and it turns out to be a noice issue, then feel free to create a PR

Same for me; if someone should understand something I don't that explains why this is a VimTeX issue, then I would be happy to hear it and/or see a PR.

**Comment by lervag** [comment] 2023-03-12 14:19
I'm closing this with "won't fix", as I don't plan to spend more time on it.

**Closed by lervag** 2023-03-12 14:19 UTC
Labels: bug

**Comment by lee-shun** [comment] 2023-03-12 14:21
Thank you!

**Comment by lervag** [comment] 2023-03-12 14:24
Sorry that I couldn't be of more help. :\

**Comment by lee-shun** [comment] 2023-03-12 14:26
> Sorry that I couldn't be of more help. :\

No worry! Thank you and @folke for creating these great plugins! 
Nothing is perfect, Cheers! :+1:

**Comment by lervag** [comment] 2023-03-12 14:29
Thanks! :) <3

**Comment by a-torgovitsky** [comment] 2024-08-28 14:06
@lee-shun Did you ever find a workaround for this problem?
