### ISSUE TITLE
Reverse search with SumatraPDF doesn't work with nvim-qt

### ISSUE THREAD

**Issue by pmazumder3927** [lervag/vimtex#1819] opened 2020-10-06 12:23 UTC
As the documentation state, I added the following lines to my `init.vim`:

```vim
let g:vimtex_view_general_options
      \ = '-reuse-instance -forward-search @tex @line @pdf'
      \ . ' -inverse-search "' . exepath(v:progpath)
      \ . ' --servername ' . v:servername
      \ . ' --remote-send \"^<C-\^>^<C-n^>'
      \ . ':execute ''drop '' . fnameescape(''\%f'')^<CR^>'
      \ . ':\%l^<CR^>:normal\! zzzv^<CR^>'
      \ . ':call remote_foreground('''.v:servername.''')^<CR^>^<CR^>\""'
```

However, both forward and backwards search seem to be broken. The only command that summons Sumatra is `\ll`. I have confirmed that a synctex file exists. I am running nvim-qt on Windows 10.

**Comment by lervag** [comment] 2020-10-06 12:28
Does it work if you use `\lv` to open and use the viewer?

**Comment by pmazumder3927** [comment] 2020-10-06 13:51
No; unfortunately `\lv` seems to do nothing at all

**Comment by lervag** [comment] 2020-10-06 20:15
Ok. Can you please provide the following, as suggested in the [issue template](https://raw.githubusercontent.com/lervag/vimtex/master/.github/ISSUE_TEMPLATE/issue_report.md)?

1. A full minimal vimrc.

2. A simple/minimal LaTeX file.

3. Steps to reproduce (including _how_ you start Vim).

4. The output of `:VimtexInfo`.

It might also be interesting to note the version of SumatraPDF you have installed.

**Comment by pmazumder3927** [comment] 2020-10-07 01:53
init.vim:
```vim
call plug#begin('C:\Users\Pramit\AppData\Roaming\Oni\plugins')
Plug 'lervag/vimtex'
    let g:tex_flavor='latex'
    let g:vimtex_quickfix_mode=0
    let g:vimtex_view_general_viewer = 'SumatraPDF'
            let g:vimtex_view_general_options
                \ = '-reuse-instance -forward-search @tex @line @pdf'
                \ . ' -inverse-search "' . exepath(v:progpath)
                \ . ' --servername ' . v:servername
                \ . ' --remote-send \"^<C-\^>^<C-n^>'
                \ . ':execute ''drop '' . fnameescape(''\%f'')^<CR^>'
                \ . ':\%l^<CR^>:normal\! zzzv^<CR^>'
                \ . ':call remote_foreground('''.v:servername.''')^<CR^>^<CR^>\""'
    let g:vimtex_view_general_options_latexmk = '-reuse-instance'
call plug#end()
```

LaTeX file:
```tex
\documentclass{article}
\begin{document}
Hello world.
\end{document}
```

I start nvim-qt via the .exe as administrator, per the documentation. I then :e a test file with the content above. Then I press \lv to no avail; only \ll does anything and both forward and reverse search are broken.

VimtexInfo:
```
System info
  OS: Microsoft Windows 10 Pro (10.0.18363 N/A Build 18363)
  Vim version: NVIM v0.4.4
  Has clientserver: true
  Servername: \\.\pipe\nvim-21304-0

vimtex project: test
  base: test.tex
  root: C:\Users\Pramit\Downloads\Neovim\bin
  tex: C:\Users\Pramit\Downloads\Neovim\bin\test.tex
  out: C:\Users\Pramit\Downloads\Neovim\bin/test.pdf
  log: C:\Users\Pramit\Downloads\Neovim\bin/test.log
  aux: C:\Users\Pramit\Downloads\Neovim\bin/test.aux
  fls: C:\Users\Pramit\Downloads\Neovim\bin/test.fls
  main parser: current file verified
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  qf: LaTeX logfile
    addqflist: 49
    fix_paths: 50
    set_errorformat: 48
  document class: article
```

**Comment by lervag** [comment] 2020-10-07 16:17
Thanks. Does the viewer work if you remove or comment out `g:vimtex_view_general_options`, i.e. with the following options?

```
let g:tex_flavor='latex'
let g:vimtex_quickfix_mode=0
let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options_latexmk = '-reuse-instance'
```

With "work", I mean this: Start nvim-qt and edit your LaTeX file. Do `\ll` - the document should compile and the viewer should open. If you do `\lv`, the viewer should get focus. Close the viewer. Do `\lv`, the viewer should open again. Note, though, that there will not be any forward or backward search since it is not configured.

If it works, then try this next:

```
let g:tex_flavor='latex'
let g:vimtex_quickfix_mode=0
let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options
    \ = '-reuse-instance -forward-search @tex @line @pdf'
let g:vimtex_view_general_options_latexmk = '-reuse-instance'
```

Now forward search should work. Can you confirm this?

**Comment by pmazumder3927** [comment] 2020-10-08 02:42
`\lv` still does nothing. When the viewer is open, it does not focus. When the viewer is closed, it does not open.

**Comment by lervag** [comment] 2020-10-08 06:15
Ok, this probably means that you can't start SumatraPDF from your `nvim-qt` instance. Can you try to simply do `:!SumatraPDF` from nvim? If you open a `CMD` shell, can you start SumatraPDF there?

**Comment by pmazumder3927** [comment] 2020-10-08 08:57
You are correct; I cannot open it from the command line. I attempted to add it to my path, but I still can't.

**Comment by lervag** [comment] 2020-10-08 09:02
Well, there's your problem. Let me know when you figure out how to make this work. I can help with vimtex related things, but my Windows-fu is not so strong. Sorry!

**Comment by andyliuhaowen** [comment] 2021-01-10 18:26
@pmazumder3927 You can try installing sumatra with scoop. Scoop will make sure it is in your PATH.

**Comment by lervag** [comment] 2021-01-10 19:57
Thanks for pitching in. I'll close this issue as I don't see any clear way forward. Feel free to still continue the discussion.

**Closed by lervag** 2021-01-10 19:57 UTC
Labels: bug
