### ISSUE TITLE
Unintended scroll on basic vim operations

### ISSUE THREAD

**Issue by OliverLew** [lervag/vimtex#2180] opened 2021-09-24 12:09 UTC
### Description

First of all, I couldn't reproduce this issue intentionally, I even don't know if it's a issue of vimtex. I have this issue for several months. Up til now, I have only run into it from time to time, but haven't figured out what triggered it. So I am reporting this with a screen recording when I ran into it again today, hoping someone also had this issue and know what's wrong:

https://user-images.githubusercontent.com/12032219/134668654-d1efbcab-cae2-495e-be89-dbfd5a6723f7.mp4

- The only possible related thing I noticed is that it usually (or always?) happens sometime after I start to edit more files/buffers, something like `:e refs.bib` and `:bn`. If I edit only one file, this may not happen at all.
- When the issue appears, various operations will cause the scroll, such as mode switching (as in the screen cast), `x`, `p`, etc.
- The scroll is always upwards.
- It's the first time I noticed when I was recording, that even in the same line, whether it scrolls depends on the cursor position, but I haven't seen any pattern of that.

I have been trying commenting part of my vimrc to see if it's my own settings that's causing the issue, but honestly I can't be sure of anything since I don't know how to trigger it. So I will leave the rest of this report blank. I'll add more if I found anything.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Linux 5.14.6-arch1-1
  Vim version: VIM 8.2 (1-3441)
  Has clientserver: true
  Servername: VIM1

VimTeX project: QuantumDeformation.epjc-zh
  base: QuantumDeformation.epjc-zh.tex
  root: /home/oliver/Work/8-QuantumDeformation
  tex: /home/oliver/Work/8-QuantumDeformation/QuantumDeformation.epjc-zh.tex
  out: /home/oliver/Work/8-QuantumDeformation/output/QuantumDeformation.epjc-zh.pdf
  log: /home/oliver/Work/8-QuantumDeformation/output/QuantumDeformation.epjc-zh.log
  aux: /home/oliver/Work/8-QuantumDeformation/output/QuantumDeformation.epjc-zh.aux
  fls: /home/oliver/Work/8-QuantumDeformation/output/QuantumDeformation.epjc-zh.fls
  main parser: current file verified
  tex program: xelatex
  source files:
    QuantumDeformation.epjc-zh.tex
    RefsNames.EPJC.tex
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      build_dir: output
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -xelatex
    job: process 665458 run
    pid: 665458
    cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -xelatex -outdir=output -pvc -e '$new_viewer_always = "0"' -e '$pdf_previewer = "zathura  -x \"/usr/bin/vim --servername VIM1 --remote +\%{line} \%{input}\" \%S"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'QuantumDeformation.epjc-zh.tex'
  viewer: Zathura
    xwin id: 41943043
  qf: LaTeX logfile
    root: /home/oliver/Work/8-QuantumDeformation
    addqflist: 91
    fix_paths: 92
    main: /home/oliver/Work/8-QuantumDeformation/QuantumDeformation.epjc-zh.tex
    set_errorformat: 90
  document class: article
  packages:
    amsbsy
    amsfonts
    amsgen
    amsmath
    amsopn
    amssymb
    amstext
    appendix
    color
    ctex
    ctexhook
    ctexpatch
    enumitem
    everysel
    everysel-2011-10-28
    expl3
    fix-cm
    fontenc
    fontspec
    fontspec-xetex
    geometry
    graphics
    graphicx
    hyperref
    iftex
    ifvtex
    indentfirst
    keyval
    l3keys2e
    trig
    xeCJK
    xparse
    xparse-2020-10-01
    xtemplate
    zhnumber
```

**Comment by lervag** [comment] 2021-09-24 13:01
> First of all, I couldn't reproduce this issue intentionally, I even don't know if it's a issue of vimtex.

I am quite certain it is not an issue with VimTeX. And without it being reproducible, it is very hard to give any more help.

My suggestion would be to simplify your vimrc file.

When you do experience the issue, try to reproduce it. I.e., try to redo whatever you just did. If you _can_ reproduce the issue, then you should also be able to solve it!

> I have been trying commenting part of my vimrc to see if it's my own settings that's causing the issue, but honestly I can't be sure of anything since I don't know how to trigger it.

Well, I'm pretty sure that this is either due to your config, or due to another plugin.

> So I will leave the rest of this report blank. I'll add more if I found anything.

If you're ever able to reproduce it, and in particular, if you notice that VimTeX is somehow resposible, then I'll be glad to help figure it out. In the meantime, I'll take the liberty of closing the issue, as I can't see anything more to do here.

(Btw: You should update your plugins. The `:VimtexInfo` output indicates that you are somewhat behind the most recent version of VimTeX.)

**Closed by lervag** 2021-09-24 13:01 UTC
Labels: bug

**Comment by OliverLew** [comment] 2021-09-24 13:18
@lervag Thank you for the commenting. Will dig further.
