### ISSUE TITLE
Support for nvim-cmp.

### ISSUE THREAD

**Issue by moshiur-raj** [lervag/vimtex#2215] opened 2021-10-21 19:53 UTC
Vimtex has documentations for how to make it work with nivm-compe. However nvim-compe is now deprecated and succeeded  by [nvim-cmp](https://github.com/hrsh7th/nvim-cmp). Can you guys add documentations for nvim-cmp?

**Comment by jhossbach** [comment] 2021-10-31 10:31
I am experimenting on this although I am a little short on time for a couple days. So far I have followed [this](https://github.com/hrsh7th/nvim-cmp/issues/258) issue, and I have come across some interesting behavior: starting the commands with a small letter does not trigger any completion whatsoever, but writing the same command but with a capital letter in the beginning shows completion for all the commands that match, including commands with small letters (e.g. writing `\D` triggers both suggestions for `\Delta` and `\dag`).
I am using NVIM v0.6.0-dev+518-g1dbbaf89b, this is my minimal vimrc:

```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

set packpath=/tmp/plugged/

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'lervag/vimtex'
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-omni'
call plug#end()
PlugInstall | quit

let g:testpattern = ''

lua << EOF
local cmp = require "cmp"
cmp.setup {
	sources = {
		{ name = "omni" ,
		    keyword_pattern = vim.g["vimtex#re#neocomplete"]},
		},
	}
EOF
```
I am open to suggestions concerning this minimal vim example.

**Comment by ranebrown** [comment] 2021-10-31 11:44
I think the keyword pattern needs rewritten to be compatible with lua. I tried copying the contents of `vimtex#re#neocomplete` and using it directly but kept getting errors. That is my guess at least.

**Comment by krishnakumarg1984** [comment] 2021-10-31 14:13
Same. I get lots of errors in using this with `nvim-cmp`.

**Comment by lervag** [comment] 2021-10-31 20:54
> I think the keyword pattern needs rewritten to be compatible with lua. I tried copying the contents of `vimtex#re#neocomplete` and using it directly but kept getting errors. That is my guess at least.

What does "compatible with lua" mean here? That is, my understanding is that nvim-cmp uses vim regexes, and `vimtex#re#neocomplete` is a vim regex.

**Comment by lervag** [comment] 2021-10-31 20:57
One suggestion would be to hard code everything in the first iteration. I.e., copy the regex from here:

https://github.com/lervag/vimtex/blob/8c1a8fd5484d894f7173db8dcdea4183a357f7a2/autoload/vimtex/re.vim#L35-L58

Possibly simplify and only use the part for the commands, so e.g.

```lua
  keyword_pattern = '\v\\\a*'
```

Then add the branches one by one, e.g.

```lua
  keyword_pattern = '\v\\%(%(\a*cite|Cite)\a*\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*|\a*)'
```

and test if things works as expected.

**Comment by jhossbach** [comment] 2021-11-01 10:52
> What does "compatible with lua" mean here? That is, my understanding is that nvim-cmp uses vim regexes, and `vimtex#re#neocomplete` is a vim regex.

Patterns are indeed evaluated using vim regex in the [lua/cmp/utils/pattern.lua](https://github.com/hrsh7th/nvim-cmp/blob/e8cb695b0bcf53ea51837421d24ff01cadb4f4e5/lua/cmp/utils/pattern.lua) file.

> ```lua
>   keyword_pattern = '\v\\\a*'
> ```
> ```lua
>   keyword_pattern = '\v\\%(%(\a*cite|Cite)\a*\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*|\a*)'
> ```

None of these patterns trigger nvim-cmp so far, normal omnicompletion via `<C-x><C-o>` works. My guess is that there is a problem with cmp-omni, but I will look into this as soon as I have more time.

**Comment by jhossbach** [comment] 2021-11-28 20:00
The problem is that the omnifunc is called with the wrong string:
https://github.com/hrsh7th/cmp-omni/blob/3fec8a57d6d230c81d24c03dd80e97c62d4eda63/lua/cmp_omni/init.lua#L20
``` lua
  local result = self:_invoke(vim.bo.omnifunc, { 0, string.sub(params.context.cursor_before_line, offset) })
```
The last part is the string that will be passed to the omnifunc. The problem is that the backslash is also passed to the omnifunc, so when typing `\b`, the string `\b` would be passed altough it should not (right?). As a workaround, one can by hand set `offset` to `offset + 1` in the above. To immediately get completion, one also has to set `keyword_pattern = 0` in the source config for `omni`, e.g.
```lua
cmp = require'cmp'
cmp.setup {
  ...
  sources = cmp.config.sources {
    { name = 'omni', keyword_length = 0 }
  }
}
```
I think this is a bug on cmp-omni's side, so I will give an update [over there](https://github.com/hrsh7th/cmp-omni/issues/1) as well. As soon as this is fixed I will give an update here.

**Comment by lervag** [comment] 2021-11-28 20:02
Great, glad to get help on this one!

**Comment by avonmoll** [comment] 2021-11-29 16:12
Thanks for the update on this. I have another question:

Pressing `<C-x><C-o>` after `\cite{` shows the citekey as well as a parsed version of the reference (i.e. Author1 & Author2 (2021), "Title of the reference"). Is it possible to have this information in the nvim-cmp window? For, e.g., UltiSnips entries the actual snippet code shows up on hover.

**Comment by jhossbach** [comment] 2021-11-29 16:37
I think the best thing is to write a new source for nvim-cmp and pass everything that the vimtex omnifunc provides. I'll work on that if I have some free time

**Comment by hrsh7th** [comment] 2021-11-29 16:40
Hmm ... I don't think the offset should be a `+ 1` value ...

I think it's a matter of keyword pattern regex. What's wrong?

**Comment by jhossbach** [comment] 2021-11-29 16:49
Let's move the discussion [here](https://github.com/hrsh7th/cmp-omni/issues/1) and get back when the issue is solved.

**Comment by jhossbach** [comment] 2021-11-29 17:54
@lervag I am a little confused about the `mode` entry in vimtex's omnifunc, I can't find it anywhere in the vim docs. Is that a deprecated entry? I can only think of those from here: https://vimhelp.org/insert.txt.html#complete-items

**Comment by clason** [comment] 2021-11-29 17:57
Isn't that a custom thing for VimTeX to indicate whether you're in math mode or not  (so you can get context-dependent completion)?

https://github.com/lervag/vimtex/blob/d9e05f5e8010ce43670d19655058a6dc8cad300e/autoload/vimtex/complete.vim#L319

**Comment by jhossbach** [comment] 2021-11-29 18:44
Ok, so completion should work now out-of-the-box when using cmp-omni and the above config.
However, the `menu` item is not yet implemented, to change this one has to tweak the code in line 32-35 in lua/cmp_omni/init.lua to something like
```lua
    elseif type(v) == 'table' then
      if v.menu then -- Add this
        table.insert(items, {
	  label = v.abbr or v.word .. '\t' .. v.menu,
	  insertText = v.word,
	})
      else  --
      table.insert(items, {
        label = v.abbr or v.word,
        insertText = v.word,
      })
      end  --
    end
```
However, this only does part of the trick, see this screenshot:

![image](https://user-images.githubusercontent.com/50084485/143923841-0e8774da-8eee-4b04-8b2f-300a1a81c5ea.png)

On the other hand, vimtex's omnifunc beautifully indents and increases the popup window:
![image](https://user-images.githubusercontent.com/50084485/143924540-6faf6fa1-f79b-4f8f-8566-8296eb35dad3.png)

As for the `menu` item, this should be implemented into `cmp-omni`. For the popup window we could maybe reuse some of vimtex's logic, but this is as far as I can go right now.

**Comment by lervag** [comment] 2021-11-29 21:32
> @lervag I am a little confused about the `mode` entry in vimtex's omnifunc ...

> Isn't that a custom thing for VimTeX ...

Precisely. VimTeX "abuses" the completion entry dicts in this case and adds some context to help filter candidates.

> Ok, so completion should work now out-of-the-box when using cmp-omni and the above config.

Great! For reference, could you be specific which configuration would be the corret to use? Did you refer to what you wrote [here](https://github.com/lervag/vimtex/issues/2215#issuecomment-981142735)?

I'd be happy to write out some descriptions in the docs to guide users to a functional configuration, but it helps to be sure what would be considered good.

> However, the `menu` item is not yet implemented, ...

Vim's internal completion automatically displays the completion in a nicely aligned table. VimTeX does not need to do anything except providing the candidates with the standard dictionaries with e.g. `word`, `abbr`, and `menu`.

I don't know any of the `nvim-cmp` or `cmp-omni` internals and I'm not sure how I could help with the formatting here. But perhaps one could use some logic/snippet from coc.nvim or similar that has a similar omnifunc interaction?

**Comment by moshiur-raj** [comment] 2021-11-30 04:57
@lervag It works fine with the config given by @jhossbach.
``` lua
cmp = require'cmp'
cmp.setup {
  ...
  sources = cmp.config.sources {
    { name = 'omni', keyword_length = 0 }
  }
}
```
Omitting `keyword_length = 0` part disables triggering suggestion if no key is pressed. Both configurations are working fine as far as I've seen. However I don't know how much beneficial omitting `keyword_length = 0` will be from a performance standpoint.

**Comment by jhossbach** [comment] 2021-11-30 08:46
The menu key is now also displayed in the completion menu similar to the omnifunc, great thanks to @hrsh7th for helping on that!
 > However I don't know how much beneficial omitting keyword_length = 0 will be from a performance standpoint.

I think you're right, the `keyword_length` should be omitted.
As for the documentation, you can write something like: (parts are copied from the old entry for nvim-compe)

> nvim-cmp is the successor of nvim-compe. It provides completion for different sources, including omni-completion, making it easy to use  for VimTex. The plugin is available here:
https://github.com/hrsh7th/nvim-cmp
>
> To include omni-completion, the cmp-omni package has to be installed and added to the list of sources in your config. For example, in Lua, it should look something like this:
> ```lua
>cmp = require'cmp'
>cmp.setup {
>  -- additional config
>  sources = cmp.config.sources {
>    { name = 'omni'},
>    -- additional sources
>  }
>}
>```

**Comment by lervag** [comment] 2021-11-30 20:49
> @lervag It works fine with the config given by @jhossbach.
> 
> ```lua
> cmp = require'cmp'
> cmp.setup {
>   ...
>   sources = cmp.config.sources {
>     { name = 'omni', keyword_length = 0 }
>   }
> }
> ```

Thanks! Silly question: do I understand correctly that `require'cmp'` is equivalent to `require("cmp")`? Is there a reason to prefer the latter form?

> Omitting `keyword_length = 0` part disables triggering suggestion if no key is pressed.

The default value is 1, right? Which means that omni completion would only be triggered after typing at least 1 character, e.g. `\a` and not `\`?

Also, do I understand correctly that there is no keyword pattern? Does this mean that nvim-cmp will attempt omni completion after every single key press?

> So enabling omni only for tex filetypes might be a good idea.

How would one do that? It could be useful to add that as an example in the docs.

> The menu key is now also displayed in the completion menu similar to the omnifunc, great thanks to @hrsh7th for helping on that!

Great! Good work!

> I think you're right, the `keyword_length` should be omitted. As for the documentation, you can write something like: (parts are copied from the old entry for nvim-compe)

Thanks! I'm pushing a first version now.

**Comment by clason** [comment] 2021-11-30 20:54
> Thanks! Silly question: do I understand correctly that require'cmp' is equivalent to require("cmp")? Is there a reason to prefer the latter form?

Yes, that's a Lua specialty: you can omit parentheses around single arguments that are either string or table literals, so `foo('bar') == foo("bar") == foo 'bar' == foo "bar"` (and similarly for `foo({bar=baz}`).

Which you prefer is a matter of taste (without parentheses, you can mimic "casts", like `u"foo"` to convert a string to utf8 or something. (Many projects use https://github.com/JohnnyMorganz/StyLua as a code formatter, so it doesn't really matter how people write it.)

**Comment by lervag** [comment] 2021-11-30 20:57
Thanks!

**Comment by jhossbach** [comment] 2021-11-30 21:26
> The default value is 1, right? Which means that omni completion would only be triggered after typing at least 1 character, e.g. \a and not \?
> Also, do I understand correctly that there is no keyword pattern? Does this mean that nvim-cmp will attempt omni completion after every single key press?

The default value is 1 and the backslash counts as the first character, so completion is triggered after typing `\`. As for the second part, I couldn't really figure out the regex used in nvim-cmp to trigger (the keyword pattern is `\k\+` which I have have trouble interpreting). I believe nvim-cmp has some sort of cache functionality, but I am unsure if this is used here. If I interpret the calls correctly when using `-V9` verbosity with nvim, the omnifunction is called after each key stroke. Can you tell us more @hrsh7th?

> How would one do that? It could be useful to add that as an example in the docs.

From https://github.com/hrsh7th/nvim-cmp/issues/433#issuecomment-974646423:
```lua
autocmd FileType tex lua require('cmp').setup.buffer { sources = { { name = 'omni' } } }
```
IMO I don't think it is necessary as nvim-cmp will not try to use cmp-omni as source if the omnifunc is not set, and if you set it you most likely want to use it. But it's probably a good idea to include in the docs anyway.

**Comment by lervag** [comment] 2021-11-30 21:34
> The default value is 1 and the backslash counts as the first character

Ah, I see!

> the keyword pattern is `\k\+` which I have have trouble interpreting

I think we can design a useful regular expression here to avoid calling the omnifunction except in relevant contexts. If this is a standard Vim regular expression, then `\k` means a keyword character as defined by the `'iskeyword'` option (see `:help 'iskeyword'` and `:help \k`).

But the point here is that I believe it should be possible to define a regular expression that would help pinpoint the context.

**Comment by jhossbach** [comment] 2021-11-30 22:27
I see, I way trying to get some info from http://www.vimregex.com, looks like this is well outdated... I should have looked into the vim docs first. Now that the bug in cmp-omni was fixed, the neocomplete pattern from one of the previous comments should do the trick. I will test this some time tomorrow.

**Comment by hrsh7th** [comment] 2021-12-01 03:56
If you want to autocompletion when press specific characters, you can use nvim-cmp's feature.

```
local cmp = require('cmp')

cmp.setup {
  sources = {
    { name = 'omni', trigger_characters = { '\\' }
  }
}
```

**Comment by lervag** [comment] 2021-12-01 22:01
Thanks, @hrsh7th!

@jhossbach I'll update the docs with the `trigger_characters` after you (or anyone else) have tested it with e.g. the neocomplete pattern. Let me know, and feel free to also show the proper configuration syntax if you find it works. :)

**Comment by moshiur-raj** [comment] 2021-12-01 22:20
@lervag if you want to include documentations for loading `cmp-omni` only for tex files in lua, here's the configuration I'm using:
```lua
vim.cmd(string.gsub([[
autocmd FileType tex lua require('cmp').setup.buffer{
sources = {
-- include other plugins  you're using
{ name = 'omni' },
}
}
]], '\n', ' '))
```
vim.cmd executes a vim cmd and string.gsub is there for substituting the newline characters with spaces. This way you can comfortably use line breaks without using escape characters.

**Comment by lervag** [comment] 2021-12-02 21:22
Thanks, @moshiur-raj - I've already added a comment on this that feels adequate to me.

**Comment by jhossbach** [comment] 2022-01-08 11:57
Sorry for the wait, it works well for me when using `vimtex#re#neocomplete`, this is a sample .vim config:
```vim
lua << EOF
cmp = require'cmp'
cmp.setup {
 -- additional config
 sources = cmp.config.sources {
     { name = 'omni', trigger_characters = vim.g["vimtex#re#neocomplete"] },
   -- additional sources
 }
}
EOF
```
Also tested using the docker image provided in vimtex. Seems we are good to go now.

**Comment by moshiur-raj** [comment] 2022-01-08 12:03
@jhossbach what is the use for `trigger_characters = vim.g["vimtex#re#neocomplete"]`? Are there any benefits to using this?

**Comment by jhossbach** [comment] 2022-01-08 12:13
@moshiur-raj  It will trigger the omnifunc only if specific patterns given in `trigger_characters` are typed in. This should increase performance as the omnifunc is only called when needed. You can add custom patterns to the `trigger_characters` table, e.g. `'\\'` will call omnifunc every time you type in `\`

**Comment by hrsh7th** [comment] 2022-01-08 12:17
The trigger_characters only accepts array of one char.

**Comment by jhossbach** [comment] 2022-01-08 13:05
@hrsh7th so `keyword_pattern` should be used instead? whats the purpose of `trigger_characters` then?

**Comment by hrsh7th** [comment] 2022-01-08 13:09
The trigger characters is for force invoking the completion with specific characters.
For example, if the user press `/`, the completion engine should display path source results. This situation is keyword length is zero. But the trigger character will achieve this.

**Comment by lervag** [comment] 2022-01-08 13:15
Thanks, @jhossbach! I've pushed a minor update now.

Is there a simple, built-in way to make this configuration only applicable to tex files? I.e., let's say one wants the `omni` source to be active for `.tex` files with the specified `keyword_pattern`?

One way, of course, is to use the autocmd approach. But it seems quite verbose from a user perspective. Say I want `nvim-cmp` with `cmp-omni` completion for three different file types with different configs and patterns - then I suddenly need several autocommand based config snippets.

Or - let's say I activate the omni source at the global level, perhaps with a preferred global `keyword_pattern`. In addition, I use a FileType autocommand like this:

```vim
augroup VimTeX
  autocmd!
  autocmd FileType tex
        \ lua require('cmp').setup.buffer { sources = { { name = 'omni', keyword_pattern = ... } } }
augroup END
```

Do I understand correctly that this will override the global settings?

**Comment by hrsh7th** [comment] 2022-01-08 13:55
The `sources` field is array of source config. The nvim-cmp doesn't merge `array` so the sources option will overwrite the global config.

The sources[n].keyrod_pattern is source-specific keyword pattern. It is preferred over a global one. (but global keyword length isn't overwrite)

**Comment by lervag** [comment] 2022-01-08 14:45
@hrsh7th Ok. Let's say I wanted one `keyword_pattern` for the omni source in LaTeX, and another `keyword_pattern` for the omni source in another filetype (e.g. `.foo`). If I understand correctly, this would not really work, since one would override the setting globally whenever the config is changed.

**Comment by Xystel** [comment] 2022-01-08 19:26
Hello, I tried the suggested settings from 0f8b4f08e266cb4107706989049431059468f8f3, but it ended up in following error:

```
Error detected while processing TextChangedI Autocommands for "*":                                                                                                                                                  
E5108: Error executing lua .../site/pack/packer/start/nvim-cmp/lua/cmp/utils/cache.lua:15: invalid value (table) at index 2 in table for 'concat'                                                                   
stack traceback:                                                                                                                                                                                                    
        [C]: in function 'key'                                                                                                                                                                                      
        .../site/pack/packer/start/nvim-cmp/lua/cmp/utils/cache.lua:15: in function 'get'                                                                                                                           
        .../site/pack/packer/start/nvim-cmp/lua/cmp/utils/cache.lua:34: in function 'get_offset'                                                                                                                    
        .../nvim/site/pack/packer/start/nvim-cmp/lua/cmp/source.lua:234: in function 'complete'                                                                                                                     
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:253: in function 'complete'                                                                                                                     
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:166: in function 'callback'                                                                                                                     
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:216: in function 'autoindent'                                                                                                                   
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:158: in function 'on_change'                                                                                                                    
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/init.lua:301: in function 'callback'                                                                                                                     
        ...ite/pack/packer/start/nvim-cmp/lua/cmp/utils/autocmd.lua:31: in function 'emit'                                                                                                                          
        [string ":lua"]:1: in main chunk
```

I then tried `trigger_characters` as suggested from @jhossbach, but I'm not sure if this does that expected behaviour of only trigger omni completion when `\` is typed.

But as I'm here, I may also have a proposal for improvement of the documentation. In nvim-cmp it is possible to format the completion menu. But then the additional information from vimtex are lost, for example from which package the command is from. We discussed that in [this Issue](https://github.com/hrsh7th/nvim-cmp/issues/668).

I currently load following snippet in `after/ftplugin/tex.lua` and invoke cmp.setup.buffer function, to only apply to tex files:

```lua
local cmp = require('cmp')
cmp.setup.buffer {
	formatting = {
		format = function(entry, vim_item)
			vim_item.menu = ({
				omni = (vim.inspect(vim_item.menu):gsub('%"', "")),
				luasnip = "[LuaSnip]",
				buffer = "[Buffer]",
			})[entry.source.name]
		return vim_item
		end,
	},
	sources = {
		{ name = 'omni' },
		{ name = 'luasnip' },
		{ name = 'buffer' },
	},
}
```
This results in a completion window like this:

![image](https://user-images.githubusercontent.com/76221461/148656945-73bca88e-b16f-4089-bcc9-4b3bc8b71d8e.png)

As you can see it uses the information provided by vimtex in the menu, and for the other sources it uses the custom defined descriptions. Maybe it would be interesting to mention that in the documentation too.

**Comment by lervag** [comment] 2022-01-08 22:50
Thanks! I'm updating the docs again. I'll remove the mention of `keyword_patterns` as it seems to be faulty for now. I hope the latest iteration is closer to decent!

I'll also take the liberty of closing this issue. Feel free to continue the discussion or opening related issues.

**Closed by lervag** 2022-01-08 22:50 UTC
Labels: enhancement, help-wanted

**Comment by jdhao** [comment] 2022-03-13 16:22
@lervag  It seems that now the config does not work anymore. I have the following conf under `~/.config/nvim/after/ftplugin/tex.lua`:

```
local cmp = require('cmp')
cmp.setup.buffer {
	formatting = {
		format = function(entry, vim_item)
			vim_item.menu = ({
				omni = (vim.inspect(vim_item.menu):gsub('%"', "")),
				buffer = "[Buffer]",
			})[entry.source.name]
		return vim_item
		end,
	},
	sources = {
		{ name = 'omni' },
		{ name = 'buffer' },
	},
}
```

But the autocompletion does not work. I run the `CmpStatus` command and it says that `omni` source is unkown? (I have installed cmp-omni already)
<img width="458" alt="image" src="https://user-images.githubusercontent.com/16662357/158069089-77a2f890-cf71-4d48-84c2-6c7ab870dcce.png">


Tested on latest master of nvim-cmp, cmp-omni and vimtex.

**Comment by Xystel** [comment] 2022-03-14 16:03
For me it works with that config. I don't know why it does not for you.

Have you double checked, that the `cmp-omni` plugin is installed properly? If you use packer.nvim as package manager you could run `:PackerStatus`. 

Another thing you could test is, if the omni source works if you specify it in the main cmp config.

Also note that the `:CmpStatus` command isn't always reliable. See [nvim-cmp/doc](https://github.com/hrsh7th/nvim-cmp/blob/1001683bee3a52a7b7e07ba9d391472961739c7b/doc/cmp.txt#L310-L313).

**Comment by jdhao** [comment] 2022-03-15 04:38
I have tried to specify cmp-omni source in main cmp config. It does not work either.

`PackerStatus` shows that both nvim-cmp and cmp-omni is loaded.

**Comment by jhossbach** [comment] 2022-03-15 07:54
@jdhao I can also confirm it works for me. Can you check if removing buffer as source and in the function changes anything?
Also check that `echo &omnifunc` still returns `vimtex#complete#omnifunc`

**Comment by jdhao** [comment] 2022-03-15 08:14
This is my full cmp config for now:

```
local cmp = require'cmp'
local lspkind = require'lspkind'

cmp.setup({
  snippet = {
    expand = function(args)
      -- For `ultisnips` user.
      vim.fn["UltiSnips#Anon"](args.body)
    end,
  },
  mapping = {
    ['<Tab>'] = function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      else
        fallback()
      end
    end,
    ['<S-Tab>'] = function(fallback)
      if cmp.visible() then
        cmp.select_prev_item()
      else
        fallback()
      end
    end,
    ['<Esc>'] = cmp.mapping.close(),
    ['<CR>'] = cmp.mapping.confirm({ select = true }),
    ['<C-d>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
  },
  sources = {
    { name = 'nvim_lsp' }, -- For nvim-lsp
    { name = 'ultisnips' }, -- For ultisnips user.
    { name = 'nvim_lua' }, -- for nvim lua function
    { name = 'path' }, -- for path completion
    { name = 'omni' },
    { name = 'emoji', insert = true, } -- emoji completion
  },
  completion = {
    keyword_length = 1,
    completeopt = "menu,noselect"
  },
  view = {
    entries = 'custom',
  },
  formatting = {
    format = lspkind.cmp_format({
      mode = "symbol_text",
      menu = {
        nvim_lsp = "[LSP]",
        ultisnips = "[US]",
        nvim_lua = "[Lua]",
        path = "[Path]",
        buffer = "[Buffer]",
        emoji = "[Emoji]",
      },
    }),
  },
})
```

`set omnifunc` shows the correct result:

<img width="485" alt="image" src="https://user-images.githubusercontent.com/16662357/158334210-333fff36-5339-4755-9115-2f1bdede4b30.png">

I can trigger omni completion with `Ctrl-X Ctrl-O`, but no luck with auto-completion.

**Comment by lervag** [comment] 2022-03-15 08:18
@jdhao Thanks for sharing your problems. I'm sorry to say I can't be of much help, but I'm glad to see @Xystel and @jhossbach is pitching in and trying to assist. I'll follow the discussion, and if I notice anything where I can be of help, I'll let you know!

Also, to all of you: If you notice something that should be fixed or update (e.g. in docs), please let me know!

**Comment by jdhao** [comment] 2022-03-15 08:37
@lervag  On a sidenote,  the following conf can not start vimtex properly:

```
set runtimepath+=/Users/jdhao/.local/share/nvim/site/pack/packer/opt/vimtex

filetype plugin indent on
syntax enable

set runtimepath+=/Users/jdhao/.local/share/nvim/site/pack/packer/opt/nvim-cmp/
set runtimepath+=/Users/jdhao/.local/share/nvim/site/pack/packer/opt/cmp-omni/

lua << EOF
  local cmp = require('cmp')
  cmp.setup {
    sources = { { name = 'omni' }, },
  }
EOF
```

I open a test.tex file like this: `nvim -u init.vim test.tex`. Upon openning it, the only available command for vimtex is `VimtexInverseSearch`:

<img width="415" alt="image" src="https://user-images.githubusercontent.com/16662357/158337492-7efd8cfb-c6df-498e-ae61-266d6be163bb.png">

It seems that vimtex is not properly initialized. I manually run this command: `call vimtex#init()` [here](https://github.com/lervag/vimtex/blob/master/ftplugin/tex.vim#L25). Then vimtex is initialized properly.

Still the autocompletion won't work if I type `\` e.g.,, I have to press `Ctrl-X Ctrl-O` to activate the completion menu. Then the autocompletion seems to work as long as `\` is retained.

**Comment by lervag** [comment] 2022-03-15 08:40
> @lervag On a sidenote, the following conf can not start vimtex properly:
> 
> ```
> set runtimepath+=/Users/jdhao/.local/share/nvim/site/pack/packer/opt/vimtex
> ```

Don't put VimTeX in `/opt`! It should be in `/start`. See `:help runtime-search-path` and `:help pack-add`. VimTeX is a proper filetype plugin that is already only loaded when necessary, and there is more or less no penalty of keeping it in `/start`.

**Comment by jdhao** [comment] 2022-03-15 08:44
okay, I will put vimtex in `start` directory. 

> Still the autocompletion won't work if I type \ e.g.,, I have to press Ctrl-X Ctrl-O to activate the completion menu. Then the autocompletion seems to work as long as \ is retained.

I have also recorded a screen shot to show the issue:

![vimtex-completion](https://user-images.githubusercontent.com/16662357/158339307-6a1ddf2d-5e1c-4b25-ad73-50f77b57ef8e.gif)

**Comment by lervag** [comment] 2022-03-15 08:56
The autocompletion issue is what I referred to when I stated that I can't be of much more help. As we see from the earlier posts, things seem to work well for others who use nvim-cmp.

**Comment by jdhao** [comment] 2022-03-15 08:59
@jhossbach  Can you try my minimal conf [here](https://github.com/lervag/vimtex/issues/2215#issuecomment-1067705761) (change the plugin path to your actual path) and confirm if it works for you?

**Comment by Xystel** [comment] 2022-03-15 09:00
I just tried to use your provided cmp config to make a minimal example in one file. This is my result:

```lua
require('packer').startup(function(use)
  use { 'wbthomason/packer.nvim' }
  use { 'lervag/vimtex' }
  use { 'hrsh7th/nvim-cmp' }
  use { 'hrsh7th/cmp-omni' }
  use { 'hrsh7th/cmp-buffer' }
  use { 'SirVer/ultisnips' }
  use { 'onsails/lspkind-nvim' }
  use { 'hrsh7th/cmp-nvim-lsp' }
  use { 'hrsh7th/cmp-nvim-lua' }
  use { 'hrsh7th/cmp-path' }
  use { 'hrsh7th/cmp-emoji' }
end)

-- Setup nvim-cmp.
local cmp = require'cmp'
local lspkind = require'lspkind'

cmp.setup({
  snippet = {
    expand = function(args)
      -- For `ultisnips` user.
      vim.fn["UltiSnips#Anon"](args.body)
    end,
  },
  mapping = {
    ['<Tab>'] = function(fallback)
      if cmp.visible() then
        cmp.select_next_item()
      else
        fallback()
      end
    end,
    ['<S-Tab>'] = function(fallback)
      if cmp.visible() then
        cmp.select_prev_item()
      else
        fallback()
      end
    end,
    ['<Esc>'] = cmp.mapping.close(),
    ['<CR>'] = cmp.mapping.confirm({ select = true }),
    ['<C-d>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
  },
  sources = {
    { name = 'nvim_lsp' }, -- For nvim-lsp
    { name = 'ultisnips' }, -- For ultisnips user.
    { name = 'nvim_lua' }, -- for nvim lua function
    { name = 'path' }, -- for path completion
    { name = 'omni' },
    { name = 'buffer' },
    { name = 'emoji', insert = true, } -- emoji completion
  },
  completion = {
    keyword_length = 1,
    completeopt = "menu,noselect"
  },
  view = {
    entries = 'custom',
  },
  formatting = {
    format = lspkind.cmp_format({
      mode = "symbol_text",
      menu = ({
        nvim_lsp = "[LSP]",
        ultisnips = "[US]",
        nvim_lua = "[Lua]",
        path = "[Path]",
        buffer = "[Buffer]",
        emoji = "[Emoji]",
	omni = "[Omni]",
      }),
    }),
  },
})
```

For me it worked. The only thing I added to you cmp config is that `<C-Space>` can invoke the completion menu from cmp.

Can you make a backup of your `~/.config/nvim` folder and place this code I provided in your `~/.config/nvim/init.lua`?

**Comment by jdhao** [comment] 2022-03-15 09:14
@Xystel  Thanks, your config works for me, autocompletion now starts immediately as I type `\`  followed by some characters. I think the issue may have something to do with lazyloading, since I am lazy loading all nvim-cmp related plugins.  It can be hell to make all those plugins work together with lazyloading. I will dig into this. Thanks a million, at least I have got a working config 😅

**Comment by Xystel** [comment] 2022-03-15 09:39
@jdhao Glad to help. :) If you want to lazy load things, maybe [NvChad](https://github.com/NvChad/NvChad) provides a good reference. But I'm unsure, if you don't get the same error with it. For me there isn't a reason to lazy load plugins. I have a total of 42 Plugins and it still loads in 120ms. But most of my plugins are in lua, which is AFAIK much faster parsed then vimscript. 

As I'm talking about lua and vimscript plugins: Is there a special reason, why you are using UltiSnips over LuaSnip?

**Comment by jdhao** [comment] 2022-03-15 09:58
I have been using Ultisnips for over three years, and I have written quite a few snippets for ultisnips. The transition cost for me would be huge, with no perceivable benefit. With its powerful Python interpolation feature, I am sure that no snippet plugin can compete with Ultisnips. So there is no reason for switching to LuaSnip or other similar plugins.

**Comment by lervag** [comment] 2022-03-15 11:26
Good to hear things are working now! Btw., I do agree with @jdhao reg. UltiSnips. Perhaps LuaSnip is good, even great, but I also use Ultisnips - it works very well, and I don't see any reason to change it. There is no significant performance cost either. So, if it ain't broke, don't fix it.

**Comment by Xystel** [comment] 2022-03-15 12:54
That sounds like a good reason. I agree that switching for no explicit benefit is pointless. I was curious, I never used UltiSnips, thanks for the answers. From my point of view, I wouldn't change to UltiSnips either. That Python interpolation feature sounds great. But in LuaSnip you could use Lua functions, which is also powerful. So I assume they are both good choices.

**Comment by lervag** [comment] 2022-03-16 07:51
Yes, exactly: I also have the impression that both are good choices. I can see how one can be tempted to change to LuaSnip if one is going into a pure neovim Lua configuration, but essentially I don't think there is much to gain. And in some cases, it can be a big job to convert existing snippets to a new format.

**Comment by clason** [comment] 2022-03-16 07:59
One benefit of LuaSnip (or similar) is that you remove the need for the external dependency (Python3), which some (but not all, clearly) will consider an advantage. And LuaSnip can (now) load snippets in SnipMate format (https://github.com/L3MON4D3/LuaSnip#add-snippets), so in many cases there will be no need to rewrite existing snippets.

(Not that that will convince anybody; just wanted to add these data points.)
