### ISSUE TITLE
Invoking Skim / displayline after compilation fails.

### ISSUE THREAD

**Issue by tnull** [lervag/vimtex#982] opened 2017-10-23 08:35 UTC
Hello, 

as mentioned in #204, I get an syntax error after `let g:vimtex_view_method = 'skim'` in the `.vimrc` or `ftplugin/tex.vim` and running `\ll`. This is strange, as invoking Skim manually by calling `\lv` works fine.

To make this reproducable, I created a minimal example:

```
\documentclass{article}
\usepackage[backend=bibtex]{biblatex}
\begin{document}
Hello World!
\end{document}

```

Running `\ll` produces:
```
Latexmk: This is Latexmk, John Collins, 19 Jan. 2017, version: 4.52c.
Viewing pdf
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'xelatex  -file-line-error -synctex=1 -interaction=nonstopmode -recorder  "test.tex"'
------------

. . .
. . . 

Transcript written on test.log.
Latexmk: Log file says output to 'test.pdf'
=== TeX engine is 'XeTeX'
Latexmk: Found bibliography file(s) [test-blx.bib]
Latexmk: I have not found a previewer that is already running. 
   So I will start it for 'test.pdf'
------------
------------
Running 'start /Applications/Skim.app/Contents/SharedSupport/displayline  "test.pdf"'
------------
Latexmk: All targets (test.pdf) are up-to-date
For rule 'view', running '&if_source(  )' ...
------------
Running '/Applications/VimR.app/Contents/Frameworks/SwiftNeoVim.framework/Versions/A/PlugIns/NeoVimServer --servername /var/folders/76/w433cm8d655cznw1qmd866gc0000gn/T/nvimhw7Q3i/0 --remote-expr "vimtex#compiler#callback(1)"'
------------
17:22: 
syntax error: A unknown token can’t go after this identifier. (-2740)
```

And indeed, running the shown command (`/Applications/Skim.app/Contents/SharedSupport/displayline  "test.pdf"`) manually, it returns the same error. This is, because displayline also needs a line parameter:

```
$ /Applications/Skim.app/Contents/SharedSupport/displayline "test.pdf"
17:22: syntax error: A unknown token can’t go after this identifier. (-2740)
$ /Applications/Skim.app/Contents/SharedSupport/displayline                                                                                                      
Usage: displayline [-r] [-b] [-g] LINE PDFFILE [TEXSOURCEFILE]
Options:
-r, -revert      Revert the file from disk if it was open
-b, -readingbar  Indicate the line using the reading bar
-g, -background  Do not bring Skim to the foreground
$ /Applications/Skim.app/Contents/SharedSupport/displayline 10 "test.pdf"
$ 
```

So, it appears that after a regular compilation Skim should be invoked via `open`, rather than trying to highlighting a specific line via `displayline`, which fails?

**Comment by lervag** [comment] 2017-10-24 18:27
Could you provide a minimal vimrc file?

**Comment by lervag** [comment] 2017-10-24 18:36
Also, if you are able to do some testing: Could you attempt to change line 82 of `autoload/vimtex/view/skim.vim`. For instance, you could try to change to something like this:

```vim
    return vimtex#compiler#latexmk#wrap_option('pdf_previewer', self.path . ' 1')
```

As you might know already, I don't work with OSX and can't do any relevant development here. Thus I strongly rely on the community for help on making and testing changes to e.g. the skim interface.

**Comment by tnull** [comment] 2017-10-25 07:59
Adding the ' 1' to the `displayline` command worked. Now, after the compilation finishes, Skim opens and highlights the first line of the document. Thanks, this works alright. 
However, it kinda seems like a workaround. I still think in the case where no explicit line has to be highlighted, `open -a Skim $document` is preferable to `displayline`.

**Comment by clason** [comment] 2017-10-25 17:30
For me it works with VimR (snapshot 232), latest commit of vimtex and Skim (1.4.29) out of the box; my `.vimrc` (or rather, `init.vim`) contains
```
" vimtex settings
let g:tex_flavor='latex'
let g:vimtex_quickfix_latexlog = {
            \ 'font' : 0,
            \ 'overfull' : 0,
            \ 'underfull' : 0,
            \ 'packages' : {
            \   'default' : 0,
            \ },
            \ }
let g:vimtex_compiler_progname = 'nvr'
let g:vimtex_view_method = 'skim'
```
(and of course I have `neovim-remote` installed).

That being said, I have to say that I do agree with @tnull that using `displayline` in the callback to highlight the current line after every successful compilation is often jarring; I would prefer the PDF display to remain stable, and only jump when explicitly requested by `\lv`.

**Comment by lervag** [comment] 2017-10-26 20:36
Ok, I'm creating a branch for testing. Please check out the `feature/skim` branch. Let me know how it feels. 

Please see `:h vimtex_viewer_skim` for some updated info.

**Comment by lervag** [comment] 2017-10-26 20:40
Basically, what I did was:

1. If `g:vimtex_view_automatic` is enabled, then I pass `-view=none` to latexmk and use `open -a Skim` in the callback function, if no other skim process was found by `pgrep`.

2. If `g:vimtex_view_automatic` is disabled, then the callback will not start Skim, but the latexmk process will start it with `open -a Skim`. (Other build tools, i.e. arara, latexrun, is not controlled in this manner.)

This seems like it might solve the issue at hand, while at the same time behave more appropriately.

As said, please test by checking out the `feature/skim` branch with `git checkout -b feature/skim`. Obv., you should first to `git pull`.

**Comment by clason** [comment] 2017-10-26 20:48
Thanks! On that branch, I get an error when opening any TeX file:
```
Error detected while processing function vimtex#init[5]..<SNR>54_init_state[1]..vimtex#state#init[9]
..1[31]..vimtex#view#init_state[5]..vimtex#view#skim#new:
line    2:
E716: Key not present in Dictionary: path)
E116: Invalid arguments for function executable
E15: Invalid expression: !executable(s:skim.path)
Error detected while processing function vimtex#init[5]..<SNR>54_init_state[1]..vimtex#state#init:
line    9:
E171: Missing :endif
Error detected while processing /Users/clason/.vim/plugged/vimtex/after/syntax/tex.vim:
line  292:
E484: Can't open file syntax/asy.vim
```
Is that obvious to you, or should I try to track down what causes this?

**Comment by lervag** [comment] 2017-10-26 20:53
Sorry, try now (`git pull`).

**Comment by clason** [comment] 2017-10-26 20:57
The error message is gone now, but now the PDF doesn't update anymore (it does start a new instance if Skim isn't running, but if it is, it's not updated).

**Comment by tnull** [comment] 2017-10-27 07:41
Same here, currently `\ll` compiles but states "Not using a previewer", so Skim is never opened.
`\lv` still works as expected.

**Comment by lervag** [comment] 2017-10-29 21:02
Ok, Just updated again. I am not sure we can make this work as you want it to, but I'm trying. In the latest version, the callback will run the `displayline` app. I think this should work as expected, but at the same time, I think this was essentially what we tried to do before as well...

**Comment by clason** [comment] 2017-10-29 21:24
And your trying is very much appreciated! Unfortunately, the update didn't change anything (for me) --  the callback doesn't update the PDF at all. 

Indeed, `displayline` was the original solution, but takes a mandatory line number as an argument which will be displayed. In other words, it's impossible to use `displayline` *just* to refresh without updating the viewport. If the original solution based on `open` doesn't work (anymore), it's probably easiest to stick with the current implementation on master (which at least consistently refreshes after successful compilation) and see if the Skim developers can add a non-highlighting refresh to `displayline`. If I can find out how (and @tnull doesn't beat me to it before I return), I'll open an issue.

Again, thanks for looking into this!

**Comment by lervag** [comment] 2017-10-29 21:31
Then I believe the problem might be that the `empty(system('pgrep'))` does not work. That is more difficult to check from my side, and some input is appreciated. Could either of you please do something like this:

0. Start Vim on some project, and open the Skim viewer, e.g. with `\lv`
1. Do `:echo "x" . system('pgrep Skim') . "y"`
2. Close all Skim viewers and repeat step 1.

**Comment by clason** [comment] 2017-10-29 21:33
Sure! With Skim running:
```
x7746
y
```
No Skim running:
```
xy
```

**Comment by lervag** [comment] 2017-10-29 21:38
Hmm, OK. Could you add some minor code (in `skim.vim`) and test:

```vim
  if empty(system('pgrep Skim'))
    echom 'x1'
    if g:vimtex_view_automatic
      echom 'x2'
      let l:cmd = join([self.exe_start, vimtex#util#shellescape(self.out())])
    endif
  else
    echom 'y'
    let l:cmd = join([
          \ self.path,
          \ '-r',
          \ '-g',
          \ line('.'),
          \ vimtex#util#shellescape(self.out()),
          \ vimtex#util#shellescape(expand('%:p'))
          \])
  endif
  echom l:cmd
```

I've added 4 `echom` commands. Could you alter the code, then open an example and do some testing, then report whether each of the blocks is reached as expected. I'm not sure if I am clear, but I hope this makes sense...

**Comment by clason** [comment] 2017-10-29 21:43
In both cases (Skim running or not), I only see the `y` output. (Weird, because the `y` branch shouldn't be running on first compilation?)

**Comment by lervag** [comment] 2017-10-29 21:51
Hmm. Could you repeat what I asked before about `:echo "x" . system(...) . "y"`, but now instead do `:echo empty(system('pgrep Skim'))`? I suspect it will result in 0 both times.

**Comment by lervag** [comment] 2017-10-29 21:52
To be clear: I think the problem was never really the `displayline` call itself, but the conditional `pgrep` line. If we can find an appropriate form for this line, then I think we will solve this issue.

**Comment by clason** [comment] 2017-10-29 21:53
No, sorry, that works as expected (`1` if not running, `0` if running).

**Comment by tnull** [comment] 2017-10-30 10:20
Thank you for your efforts! 
Sadly, I can confirm this behavior: Skim doesn't open after compilation finishes via `\ll`.
And `:echo empty(system('pgrep Skim'))` does return `0`/`1` if Skim is running/not running, respectively.

**Comment by lervag** [comment] 2017-10-30 20:32
Bummer. Well, I've pushed a minor update that adds a new `echom`. Could you test again with/without Skim opened and report the echoed messages?

**Comment by clason** [comment] 2017-10-30 21:18
Without Skim running: `xy - 1`

With Skim running: `x13553^@y - 0`

**Comment by lervag** [comment] 2017-10-31 19:20
Sorry, I made a silly type. Try now, perhaps that fixed things?

**Comment by clason** [comment] 2017-11-01 00:46
Indeed, now the callback works again (but updates the viewport, just like the old behavior on master).

**Comment by lervag** [comment] 2017-11-01 08:29
As far as I can understand:

- Skim does not auto-update when a PDF is updated.
- Therefore, we have attempted to use the vimtex callback to make Skim update (through `displayline`).
- However, based on the feedback I understand that `displayline` does not allow to update without marking the line.

I do not quite see what more I can do. Perhaps you could play with the command line options for `displayline`, @clason? We might have missed something..? If nothing works, then I suspect one could make it work with Osascript, but I don't know how to do that.

**Comment by tnull** [comment] 2017-11-01 08:33
> Skim does not auto-update when a PDF is updated.
Hum, from my experience, it does. In fact, before using vimtex, I would compile via latexmk and Skim would detect the updated file and update its rendering.

**Comment by lervag** [comment] 2017-11-01 08:45
Interesting. Which settings did you use for `latexmk` then?

I just pushed a new update where we do not update Skim from the callbacks. If Skim autoupdates, then this should work now.

**Comment by clason** [comment] 2017-11-01 08:46
Skim does have an option to auto-update when the file is changed on disk, but this is discouraged since it can lead to race conditions (e.g., if latexmk runs pdflatex and/or bibtex/biber/etc. multiple times). The developers suggest to use an osascript for that (see https://sourceforge.net/p/skim-app/wiki/TeX_and_PDF_Synchronization/; it might be as easy as `osascript -e 'tell application "Skim" to revert front document'`), and in fact `vimtex` used to use that in the beginning (see the discussion in #383) before @nhooyr suggested to use `displayline` instead since it is also useful for forward searching (`\lv`).

But `displayline` indeed does not allow to update without marking the line (at least with a red dot) and, more importantly, jumping to that line in the view. (I checked, there's no command line option to prevent that -- hence my suggestion to open an issue to request such.)

**Comment by tnull** [comment] 2017-11-01 08:49
Sorry, edited my comment, you guys were too fast. ;)

Maybe using the osascript for `\ll` and `displayline` for `\lv` would be an option..

**Comment by clason** [comment] 2017-11-01 08:52
@tnull That was the initial suggestion; if this turns out to be awkward, I would suggest asking the Skim developers to add an option to `displayline` (or `Skim`) that *only* reloads the document.

**Comment by lervag** [comment] 2017-11-01 08:53
Thanks for illuminating, @clason. Then I also think we should use Osascript in the callback.

Btw: I would propose that those of you who use Skim open issues with the Skim developers. I don't think it makes sense that I open any issues, since I can't test things and verify that any implementation works. So, feel free to open issues with the developers of `displayline` or `Skim`. In the meantime, I would prefer that we try to find a viable solution within the currently available versions.

**Comment by lervag** [comment] 2017-11-01 08:56
Ok, I've made a simple update that uses the osascript suggested by @clason. Does this work?

**Comment by lervag** [comment] 2017-11-01 08:57
(If not, would you be able to test locally and suggest something that should work, @clason?)

**Comment by clason** [comment] 2017-11-01 09:13
That does seem to work, thank you! (If I use a continuous view, the viewport still gets shifted slightly after the callback, but I don't think there's anything that can be done about it on this side.)

I'll test with a larger document later, and when I (or @tnull?) have time, I'll still open a Skim issue so the callback can be simplified again.

**Comment by lervag** [comment] 2017-11-01 09:41
Great! When you have tested on a larger document and when @tnull also reports that things now work OK, then I'll clean up and merge with master.

**Comment by lervag** [comment] 2017-11-01 09:44
That's strange. Which settings are you using, and did you do `git pull` first? Are you sure you are on the `feature/skim` branch?

**Comment by tnull** [comment] 2017-11-01 09:48
This happens with my regular vimrc (and settings in `ftplugin/tex.vim`), as well as with this minimal vimrc:
```
set nocompatible
let &rtp = '~/.vim/bundles/repos/github.com/lervag/vimtex/,' . &rtp
let &rtp .= ',~/.vim/bundles/repos/github.com/lervag/vimtex/after'

filetype plugin indent on
syntax enable

let maplocalleader = "\\"
let g:vimtex_view_method = 'skim'
```

And:
```
~/.vim/bundles/repos/github.com/lervag/vimtex> git pull
Already up-to-date.
~/.vim/bundles/repos/github.com/lervag/vimtex> git branch
* feature/skim
  master
```

**Comment by lervag** [comment] 2017-11-01 09:51
Thanks for the details! Which steps are you performing to get the
unexpected behaviour?

Den ons. 1. nov. 2017, 10:48 skrev Elias Rohrer <notifications@github.com>:

**Comment by tnull** [comment] 2017-11-01 09:55
1. Opening something.tex file
2. Hitting `\ll`
3. Seeing the "vimtex: Compiler started in continuous mode."
4. PDF updates, but skimwise nothing happens.
5. Hitting `\lo`, log:

```
Latexmk: This is Latexmk, John Collins, 19 Jan. 2017, version: 4.52c.
Not using a previewer
------------
Running '/Applications/VimR.app/Contents/Frameworks/SwiftNeoVim.framework/Versions/A/PlugIns/NeoVimServer --servername /var/folders/76/w433cm8d655cznw1qmd866gc0000gn/T/nvimHNm2ju/0 --remote-expr "vimtex#compiler#callback(1)"'
------------
Latexmk: All targets (master.pdf) are up-to-date
```

**Comment by lervag** [comment] 2017-11-01 09:57
How does this compare to you, @clason?

**Comment by clason** [comment] 2017-11-01 10:24
For me it works, but I didn't have the problem in the original issue description either. (The whole discussion about `displayline` vs. `osascript` was orthogonal to it; I kinda feel bad about highjacking the issue...)

@tnull, what's your (neo)vim version?

**Comment by tnull** [comment] 2017-11-01 10:45
I use the current VimR build ( 0.19.1 (229) / NVIM v0.2.1-dev). 
Same issue arises with neovim 0.2.0, however, this might be due to another independent bug/issue:
```
Latexmk: This is Latexmk, John Collins, 19 Jan. 2017, version: 4.52c.
Not using a previewer
------------
Running '/usr/local/Cellar/neovim/0.2.0_1/bin/nvim --servername /var/folders/76/w433cm8d655cznw1qmd866gc0000gn/T/nvimvQUAQ6/0 --remote-expr "vimtex#compiler#callback(1)"'
------------
Latexmk: All targets (master.pdf) are up-to-date
nvim: Unknown option argument: "--servername"
More info with "nvim -h"
```

**Comment by clason** [comment] 2017-11-01 10:46
Oh, if you use `neovim`, you *need* `neovim-remote` installed and set `let g:vimtex_compiler_progname = 'nvr'` in your `.vimrc` (see my setup in my first comment).

**Comment by tnull** [comment] 2017-11-01 10:57
Ah, this explains it. Success! Finally! ;)
So, I can confirm your state: Skim opens and gets updated via the `osascript`. As noted, the viewport is shifted a bit, but I'd say this is the best solution so far! 
👍  for merging. :)

@lervag Thanks for the good work and patience!
@clason do you want to open an Issue over at the Skim tracker, or should I?

**Comment by clason** [comment] 2017-11-01 10:58
@tnull Great! If you have time to do this, I'd appreciate it; otherwise I'll do it after my return next week.

**Comment by tnull** [comment] 2017-11-01 11:54
@clason Ok, I created a ticket: https://sourceforge.net/p/skim-app/bugs/1204/

**Comment by lervag** [comment] 2017-11-01 17:01
I've cleaned up and merged with master now. Let me know what you think and if you have more suggestions for improving this.

**Closed** 2017-11-01 17:00 UTC

**Comment by clason** [comment] 2017-11-01 18:11
Well, that Skim issue got closed quickly... Very disappointing. 

I'll see if I can adapt the `displayline` script myself. @lervag, would you be willing to include such a fork in vimtex? Or maybe just extract the apple script for the two specific cases of "update" and "forward search" and move it into `skim.vim`?

**Comment by lervag** [comment] 2017-11-01 22:07
I'm not sure; it feels sort of ... "wrong". However, I'd definately be willing to discuss it. If it feels right, then perhaps. It could perhaps also sort of solve issues related to versions of the displayline app...

**Comment by clason** [comment] 2017-11-02 00:15
I understand your concern; it does seem more like a Skim problem. On the other hand, apart from some bash glue, all `displayline` does is the following bit of Apple script:
```
/usr/bin/osascript << EOF
  set theLine to $line as integer
  set theFile to POSIX file "$file"
  set thePath to POSIX path of (theFile as alias)
  tell application "Skim"
    if $activate then activate
    if $revert then
      try
        set theDocs to get documents whose path is thePath
        if (count of theDocs) > 0 then revert theDocs
      end try
    end if
    open theFile
    if "$source" is "" then
      tell front document to go to TeX line theLine showing reading bar $bar
    else
      set theSource to POSIX file "$source"
      tell front document to go to TeX line theLine from theSource showing
      reading bar $bar
    end if
  end tell
EOF
```
Hard-coding the respective options for the callback and the forward search, the combined code for both code paths should amount to the same number of lines, so it doesn't seem too bad for me -- especially if the bash glue can be replaced by VimL (which I don't know how to do, unfortunately). I'd be happy to work on the Apple script side of things (and take responsibility for keeping it up-to-date with Skim).

**Comment by lervag** [comment] 2017-11-02 19:31
If it is _possible_ to write a simple osascript similar to the one you propose, attach it as a self contained script with the vimtex repo, and then use this instead of displayline, then I agree this sounds like a nice alternative to using displayline itself.

Feel free to make a modified version. I'll try and add it in a new separate branch that you can test before we make the changes.

**Comment by clason** [comment] 2017-11-02 23:05
It should not be more difficult than the current script, and would indeed completely replace the dependence on `displayscript` (or, ideally, any external bash script). The only thing I might need help with is getting the full PDF and source file paths and the line number as variables in VimL to pass to the `osascript` call. 

(If I understand correctly, I can just build a system call using `let self.process = vimtex#process#start(l.cmd)`, where `l.cmd` is a (multi-line) string built using `join`? And `vimtex#util#shellescape(expand('%:p'))` gives me the current source path? Then I can probably take a stab at modifying `skim.vim`.)

**Comment by lervag** [comment] 2017-11-03 07:29
No problem, I will be happy to help. You are right about your understandings. One minor comment:

- The `l:cmd` may of course also be built without `join`; it is essentially just a string that defines the command to run in the shell. The difficult part is to get the escaping right.
