### ISSUE TITLE
Vimtex Inverse Search with Skim not working

### ISSUE THREAD

**Issue by Xydru** [lervag/vimtex#2692] opened 2023-04-21 21:03 UTC
### Description

Hello, I tried setting up Inverse Search on Skim, but it didn't work. I'm using Neovim as my editor and I'm running on MacOS. I did it in the exact same as the documentation told me to do - to be more precise, I did the exact same thing as this article did in the section Inverse-Search (I can't spot any differences compared to the documentation): https://dr563105.github.io/blog/skim-vimtex-setup/

But when I opened the PDF in my `.tex` file via `:VimtexCompile`, the Skim-provided Shortcut `<cmd>-<shift>-<left-click>` doesn't do anything. Vimtex, Neovim as well as Skim have all been installed this week so everything should be up-to-date.

My Skim settings in the Sync tab:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/59253224/233681570-caaffd3c-aada-4fb7-b960-1066190fdc4f.png">

My init.vim:
```vim
call plug#begin()
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
let g:deoplete#enable_at_startup = 1

Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets' " Necessary for Ultisnips
Plug 'lervag/vimtex'
Plug 'ludovicchabant/vim-gutentags'
call plug#end()

imap <C-S> <ESC>:w<CR>a

let g:tex_flavor='latex'
let g:vimtex_view_method = "skim"
let g:vimtex_view_skim_sync = 1
let g:vimtex_view_skim_activate = 1

call deoplete#custom#var('omni', 'input_patterns', {
      \ 'tex': g:vimtex#re#deoplete
      \})

let g:UltiSnipsExpandTrigger='<tab>'
let g:UltiSnipsJumpForwardTrigger='<c-b>'
let g:UltiSnipsJumpBackwardTrigger='<c-z>'
```

### Steps to reproduce

1. `nvim test.tex`
2. compiling with `:VimtexCompile`
3. `<cmd>-<shift>-<left-click>` on an arbitrary word in the pdf document in Skim (openend by vimtex)

### Expected behavior

The pointer in nvim moves to the corresponding line

### Actual behavior

Nothing happens

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 13.2.1 (22D68)
  Vim version: NVIM v0.9.0
  Has clientserver: true
  Servername: /var/folders/pc/lxy6kdgs4j7c3hdgntkkf0jh0000gn/T/nvim.felix/xVKw7I/nvim.69087.0

VimTeX project: test
  base: test.tex
  root: /Users/felix/Documents/Test
  tex: /Users/felix/Test/test.tex
  main parser: current file verified
  document class: article
  packages: algorithm algorithmicx algpseudocode amsbsy amsgen amsmath amsopn amstext babel float ifthen inputenc
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job:
      jobid: 7
      output: /var/folders/pc/lxy6kdgs4j7c3hdgntkkf0jh0000gn/T/nvim.felix/xVKw7I/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex
_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "ech
o vimtex_compiler_callback_failure"' 'test.tex'
      pid: 69097
  viewer: Skim
  qf method: LaTeX logfile
```

**Comment by ejmastnak** [comment] 2023-04-22 10:29
@Xydru, at the risk of stating the obvious, you mention using the shortcut '--' for inverse search, but (unless it has changed recently), the Skim shortcut to trigger inverse search on macOS is Cmd+Shift+Click, i.e. a left mouse click while also holding down the Shift and Command keys.

**Comment by ejmastnak** [comment] 2023-04-22 10:33
Also, I think `let g:tex_flavor='latex'` is not needed (perhaps the blog post you linked has outdated instructions) and you can simpilfy your VimTeX configuration to 

```vim
let g:vimtex_view_method = "skim"
let g:vimtex_view_skim_sync = 1
let g:vimtex_view_skim_activate = 1
```

But I'll let @lervag confirm that.

**Comment by lervag** [comment] 2023-04-22 21:08
@ejmastnak I believe there was a Markdown formatting error in the original
post, and that @Xydru use the correct sequence perform inverse search.

@Xydru First, the comment by @ejmastnak is correct that you don't need `g:tex_flavor`. Now, your issue description is very good, but unfortunately I don't use MacOS and I have no idea why things don't work.

> But when I opened the PDF in my `.tex` file via `:VimtexCompile`, the Skim-provided Shortcut `<cmd>-<shift>-<left-click>` doesn't do anything.

To be clear: You press and hold `<cmd>` and `<shift>` and then click with your mouse at some point in the PDF in Skim?

If yes: With some simple, minimal test file, could you try and run the inverse search command from a terminal? E.g.:

1. Open `test.tex` with VimTeX and compile.
2. Open a terminal at the same folder.
3. Run `nvim --headless -c "VimtexInverseSearch 10 test.tex"` (or use full path to `test.tex`).
4. Report what you observe. Does this work?

**Comment by Xydru** [comment] 2023-04-22 22:26
> at the risk of stating the obvious, you mention using the shortcut '--' for inverse search, but (unless it has changed recently), the Skim shortcut to trigger inverse search on macOS is Cmd+Shift+Click, i.e. a left mouse click while also holding down the Shift and Command keys.

No, I'm not using the '--', exactly as you stated it I'm using Cmd+Shift+Click.

> To be clear: You press and hold `<cmd>` and `<shift>` and then click with your mouse at some point in the PDF in Skim?

Yes, I'm doing exactly that.

> 4\. Report what you observe. Does this work?

Yes, it worked and moved the pointer to line number 10.

**Comment by lervag** [comment] 2023-04-27 19:53
> > 4. Report what you observe. Does this work?
> 
> Yes, it worked and moved the pointer to line number 10.

Good.

Now, it seems there is something strange going on with Skim. Either 1) the backward search command is not properly performed or 2) the command is wrong.

Number 2 seems to be untrue, but it should be easy to test. If you change the command to "Befehl" = `echo` and "Argumente" = `"foo" > /tmp/foobar.txt` (or `/private/tmp/foobar.txt` or whatever would be a valid temporary file path), then you should see the file being created after you do `<cmd><shift><left-click>`. If the file is not created, then the problem is with how you invoke the inverse search/sync. Either you are pressing the wrong sequence or you are pressing the sequence in a wrong manner.

**Comment by Xydru** [comment] 2023-04-27 20:34
> Number 2 seems to be untrue, but it should be easy to test. If you change the command to "Befehl" = `echo` and "Argumente" = `"foo" > /tmp/foobar.txt` (or `/private/tmp/foobar.txt` or whatever would be a valid temporary file path), then you should see the file being created after you do `<cmd><shift><left-click>`. If the file is not created, then the problem is with how you invoke the inverse search/sync. Either you are pressing the wrong sequence or you are pressing the sequence in a wrong manner.

I tested it, following your instructions and it did work (a file named foobar.txt was created in /private/tmp that contained "foo").

**Comment by lervag** [comment] 2023-04-27 20:42
Ok, that gets us closer. Next step:

* Befehl: `echo`
* Argumente: `"nvim --headless -c VimtexInverseSearch %line '%file' > /path/to/foobar.txt"`

This should echo the command with `%line` and `%file` expanded. Can you post the content of the `foobar.txt` file after you've fired the sync?

**Comment by Xydru** [comment] 2023-04-27 21:44
Your provided Argumente-section didn't work, I believe it's because of the position of the `"`-character. So, instead, I typed the following into the Argumente-section:
`"nvim --headless -c VimtexInverseSearch %line '%file'" > /path/to/foobar.txt`

Doing that, I was able to get the text file.
The content of foobar.txt after firing the sync was this:
`nvim --headless -c VimtexInverseSearch 87 '/Users/felix/test space/test space.tex'`

After seeing this, I got curious and tried the original sync command again in Skim (nvim for Befehl, ....)!
And it (the Inverse-Search!) did work for the following file-path in nvim: `/Users/felix/test space/test space.tex`

So I suspected Skim to have problems with the file path, since besides that nothing else changed about my tests compared to when I initially posted this issue. The initial test-file was inside a path that contained letters that were not path of the ASCII-table such as 'ü'. Noticing that, I made another tex-file with another file path, this time, however, containing the letter 'ü'. And when I tried to Inverse-Search again, it suddenly didn't work anymore.

This result shows, that the process of Inverse-Search is not working for file paths containing the German letters ä, ö, ü (but it does without those). I didn't test if all characters outside of the ASCII-table are causing that problem, but this would definitely be my guess.

Ultimately, I found out what was causing the Inverse-Search-process to not work and I would be able to solve that problem by changing all my folder names that contain such letters. However, I would prefer, if there would be another way to deal with that as this solution is not a real "solution" in my opinion. I can imagine, though, that this is a problem on Skim's side rather than yours so you can probably not do anything about it.
Nevertheless, I want to thank you for helping me, as without your help and the debugging instructions you provided to me I would've never come so far. Greetings from Germany :)

**Comment by lervag** [comment] 2023-04-28 06:06
> This result shows, that the process of Inverse-Search is not working for file paths containing the German letters ä, ö, ü (but it does without those). I didn't test if all characters outside of the ASCII-table are causing that problem, but this would definitely be my guess.

That does not sound surprising. Perhaps @clason or @ejmastnak could confirm that this is also the case for them?

> I can imagine, though, that this is a problem on Skim's side rather than yours so you can probably not do anything about it.

Yes, I don't see how this could be a VimTeX issue. You could test the `nvim --headless` command in a terminal with a filename with special characters, I believe it should work as expected.

> Nevertheless, I want to thank you for helping me, as without your help and the debugging instructions you provided to me I would've never come so far. Greetings from Germany :)

I'm glad to help! Greetings from Norway :)

**Comment by lervag** [comment] 2023-04-28 06:06
I'll close the issue, but feel free to continue the discussion.

**Closed by lervag** 2023-04-28 06:06 UTC
Labels: bug

**Comment by clason** [comment] 2023-04-28 07:48
Yes, I can reproduce the issue with non-ASCII paths. Also not sure where the issue is exactly (but the general recommendation is to stick to ASCII and avoid spaces for filenames at all costs anyway).

**Comment by ejmastnak** [comment] 2023-04-28 11:23
I'd be happy to test, but I'm afraid to say I'm travelling and don't have access to macOS (and thus Skim) right now. But it sounds like you guys have pinpointed/resolved the issue.

**Comment by clason** [comment] 2023-04-28 11:32
Looks like it's a known issue, but "wontfix". I suspect that the hangup is actually in the `osascript` (Javascript) handling, in which case there's nothing to be done.
