### ISSUE TITLE
Any help to autocomplete commands?

### ISSUE THREAD

**Issue by xuebinsu** [lervag/vimtex#931] opened 2017-08-03 04:25 UTC
I would like to use YouCompleteMe to autocomplete LaTeX commands. However, when I type "\\" into vim, YouCompleteMe only gives a list of file names instead of LaTeX commands? What can I do?

I'm using Vim 8.0 on Windows 10 and set the semantic triggers as 

```vimscript
if !exists('g:ycm_semantic_triggers')
    let g:ycm_semantic_triggers = {}
endif
let g:ycm_semantic_triggers.tex = g:vimtex#re#youcompleteme
```

**Comment by lervag** [comment] 2017-08-03 06:21
Good question. I don't know why that doesn't work. I don't use youcompleteme, so the suggested settings are based on input from other people.

Perhaps you could try to set it manually, e.g. try

```vim
let g:ycm_semantic_triggers.tex = ['re!\\[A-Za-z]*']
```

This should enable automatic command completion (and nothing else). If this works, then the next step would be to examine `g:vimtex#re#youcompleteme`.

**Comment by xuebinsu** [comment] 2017-08-03 07:03
@lervag Thanks for your reply! Unfortunately, your suggestion still does not work. What completion engine are you using and what configuration are you using?

**Comment by lervag** [comment] 2017-08-03 07:33
I'm using `nvim-completion-manager`. The configuration is available [here](https://github.com/lervag/dotvim) (see the `vimrc` file). I also know that both deoplete and neocomplete works well with the suggested configuration.

Note that all these autocomplete plugins typically require some amount of configuration to work properly. The configuration suggested in the vimtex doc is _only_ for the LaTeX specific part.

**Comment by dnivra** [comment] 2017-08-08 05:10
@xuebinsu I use YouCompleteMe on Ubuntu and can confirm `g:vimtex#re#youcompleteme` works for me. However, I was using the below config earlier. Perhaps it might work.

```vim
let g:ycm_semantic_triggers.tex = [
    \ 're!\\[A-Za-z]*cite[A-Za-z]*(\[[^]]*\]){0,2}{[^}]*',
    \ 're!\\[A-Za-z]*ref({[^}]*|range{([^,{}]*(}{)?))',
    \ 're!\\hyperref\[[^]]*',
    \ 're!\\includegraphics\*?(\[[^]]*\]){0,2}{[^}]*',
    \ 're!\\(include(only)?|input){[^}]*',
    \ 're!\\\a*(gls|Gls|GLS)(pl)?\a*(\s*\[[^]]*\]){0,2}\s*\{[^}]*',
    \ 're!\\includepdf(\s*\[[^]]*\])?\s*\{[^}]*',
    \ 're!\\includestandalone(\s*\[[^]]*\])?\s*\{[^}]*',
    \ 're!\\usepackage(\s*\[[^]]*\])?\s*\{[^}]*',
    \ 're!\\documentclass(\s*\[[^]]*\])?\s*\{[^}]*',
    \ 're!\\[A-Za-z]*',
    \ ]
```

**Comment by xuebinsu** [comment] 2017-08-08 06:58
Thanks, I'll check that.

2017-08-08 13:10 GMT+08:00 dnivra <notifications@github.com>:

**Comment by lervag** [comment] 2017-08-08 06:59
I'll close this. Feel free to reopen, but if you do, please provide a full example and a description that I can use to reproduce what you do that does not work.

**Closed by lervag** 2017-08-08 06:59 UTC

**Comment by znculee** [comment] 2018-07-31 07:56
```
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()
if !exists('g:ycm_semantic_triggers')
    let g:ycm_semantic_triggers = {}
endif
au VimEnter * let g:ycm_semantic_triggers.tex=g:vimtex#re#youcompleteme
```
This will work.
@xuebinsu @lervag

**Comment by znculee** [comment] 2018-08-01 05:45
I think the reason may be that `g:ycm_semantic_triggers` is an undefined variable before YCM server has started properly. If `let g:ycm_semantic_triggers.tex=g:vimtex#re#youcompleteme` is directly set in .vimrc, there will be an error as following.
`Undefined variable: g:ycm_semantic_triggers`

However, `au VimEnter * let g:ycm_semantic_triggers.tex=g:vimtex#re#youcompleteme` will run after VimEnter event.

**Comment by lervag** [comment] 2018-08-01 06:33
Ok, thanks for explaining.

**Comment by znculee** [comment] 2018-08-02 02:35
This will work before start YCM. The advantage of this is able to allow vim-plug start vimtex only for tex file.
```
" ...
Plug 'lervag/vimtex', {'for': 'tex'}
" ...
" ... After config YCM
let g:ycm_semantic_triggers.tex=['re!\\[A-Za-z]+',
  \ 're!\\(usepackage|RequirePackage)(\s*\[[^]]*\])?\s*\{[^}]*',
  \ 're!\\documentclass(\s*\[[^]]*\])?\s*\{[^}]*',
  \ 're!\\begin(\s*\[[^]]*\])?\s*\{[^}]*',
  \ 're!\\end(\s*\[[^]]*\])?\s*\{[^}]*',
  \ 're!\\[A-Za-z]*cite[A-Za-z]*(\[[^]]*\]){0,2}{[^}]*',
  \ 're!\\(text|block)cquote\*?(\[[^]]*\]){0,2}{[^}]*',
  \ 're!\\(for|hy)[A-Za-z]*cquote\*?{[^}]*}(\[[^]]*\]){0,2}{[^}]*',
  \ 're!\\[A-Za-z]*ref({[^}]*|range{([^,{}]*(}{)?))',
  \ 're!\\hyperref\[[^]]*',
  \ 're!\\\a*(gls|Gls|GLS)(pl)?\a*(\s*\[[^]]*\]){0,2}\s*\{[^}]*',
  \ 're!\\includegraphics\*?(\[[^]]*\]){0,2}{[^}]*',
  \ 're!\\(include(only)?|input|subfile){[^}]*',
  \ 're!\\includepdf(\s*\[[^]]*\])?\s*\{[^}]*',
  \ 're!\\includestandalone(\s*\[[^]]*\])?\s*\{[^}]*']
```

**Comment by lervag** [comment] 2018-08-02 06:02
@znculee Nah, this does not really bring any advantages. Vimtex is a filetype plugin, so it won't be loaded until you open a TeX file anyway. If you compare startup times with and without the `{'for': 'tex'}` clause, you will see that the difference is O(10) milliseconds, or something like that.

Note also that this way of doing it will not keep the trigger up to date if the completion feature and the trigger regexp is updated, i.e., you must manually update the regexp.

**Comment by znculee** [comment] 2018-08-02 06:05
Thanks lervag, I agree with you. Thank you for the comments!
