### ISSUE TITLE
Vimtex always opens the logfile

### ISSUE THREAD

**Issue by maxfl** [lervag/vimtex#998] opened 2017-11-11 19:04 UTC
Regardless of errors during the compilation `vimtex` always opens the quickfix window.

The test file is attached. It contains MWE tex, .latexmkrc and compilation output.

[test.zip](https://github.com/lervag/vimtex/files/1464013/test.zip)

**Comment by lervag** [comment] 2017-11-12 11:46
This is not reproducible for me. The `test.out` file is empty. Just to be clear, I received the following minimal files, first the `test.tex` file:

```tex
\documentclass[]{beamer} 
\mode<presentation>

\begin{document}

\begin{frame}{Table of contents}
  Test
\end{frame}

\end{document}
```

And this `latexmkrc` file:

```perl
$pdf_mode = 1;
$dvi_mode = $postscript_mode = 0;
$pdflatex = "lualatex --file-line-error --synctex=1 --interaction=nonstopmode %O %S";
```

When I use these, I get no errors or problems during compilation, and the quickfix window is not opened.

**Comment by maxfl** [comment] 2017-11-12 11:56
I'm sorry, I should have sent `test.log` file. I expect that we are using different latex version and perhaps my `test.log` is a bit different from yours which triggers quickfix window to be opened. May I ask you to compare them?

[test.log.zip](https://github.com/lervag/vimtex/files/1464583/test.log.zip)

**Comment by lervag** [comment] 2017-11-12 22:24
There is no difference in our log files, except user names and version difference on lualatex. I'm on lualatex 2017.8.3, your on 2017.10.31, it seems.

Could you please test with a minimal vimrc file as well?

**Comment by manishrjain** [comment] 2017-11-16 10:24
I'm seeing this issue as well on neovim.

**Comment by maxfl** [comment] 2017-11-16 10:48
I can not repeat the issue with minimal configuration file. It will require some time before I can figure out which other plugin is interacting.

**Comment by lervag** [comment] 2017-11-21 21:39
I'm closing this due to lack of reproducability. I've pushed test files that I've used when trying to reproduce, so that you can see what I've tried. The `minivimrc` file can be used like this: `vim -u minivimrc` (or `nvim -u minivimrc`). It will open the LaTeX test file, start compilation and then try to open the quickfix list. However, for me, it is empty and simply outputs "No errors".

Further, the log file generated for me is basically identical to the one posted by @maxfl.

**Closed by lervag** 2017-11-21 21:39 UTC
