### ISSUE TITLE
Quickfix doesn't navigate to line outside of working directory

### ISSUE THREAD

**Issue by fuzzybear3965** [lervag/vimtex#256] opened 2015-10-24 02:28 UTC
This issue has a long title but I've found that the quickfix window won't navigate to the line of interest if the LaTeX file that includes the error is not in the working directory (not tested with multi-file projects). I'm running vimtex on Windows 8.1 with Vim 7.4.

Example: While the command line working directory is ``C:\`` I execute the following command ``vim C:\somedir\test.tex`` and warnings/errors in the file raise the quickfix window. Hitting ``enter`` on any of the quickfix lines closes ``C:\somedir\test.tex`` an opens an empty file. This file is a new file of the same name in the working directory of vim (in this example the file opened is ``C:\test.tex``). I have determined this by executing ``1 <ctrl>+g`` while in normal mode (prints absolute path of current file).

Clearly, vimtex is looking in the current directory for the LaTeX file when the quickfix window is used. It shouldn't do this.

**Comment by lervag** [comment] 2015-10-24 19:55
I am actually not sure if this really is something that can be fixed by vimtex, or if this is a problem with how the quickfix feature works. In any case, can you please verify that things work as expected if you open Vim from `C:\somedir`.

Could you then add `set autochdir` to your vimrc and test the original issue? I think this should solve the issue, although it might not be a valid solution.

If my understanding is correct, then I will investigate whether there is something to be done so that things just work as expected, regardless of vimrc settings.

**Comment by real-or-random** [comment] 2015-11-18 17:18
I can confirm that `set autochdir` "fixes" the problem. So the issue is indeed the working directory.

**Comment by lervag** [comment] 2015-11-18 22:01
Thanks, @real-or-random, this verifies my suspicion. Unfortunately, I am not really sure if this can be fixed. I'll look into it, anyway, and perhaps I can find some Vim command or function that can set the current directory for the quickfix list.

**Comment by real-or-random** [comment] 2015-11-18 22:42
This looks like a good start:
http://vim.wikia.com/wiki/Set_working_directory_to_the_current_file

**Comment by lervag** [comment] 2015-11-20 08:48
I think it should work now. You need to enable the option `g:vimtex_quickfix_fix_paths`, though.

**Closed** 2015-11-20 08:48 UTC
