### ISSUE TITLE
Vimtex does not respect quickfix_mode

### ISSUE THREAD

**Issue by Chiel92** [lervag/vimtex#918] opened 2017-07-25 08:35 UTC
### Explain the issue

The quickfix window gets focus, no matter the value of g:vimtex_quickfix_mode.

1. Open a tex file.
2. Make some changes, make sure there are warnings or errors
3. Run `\ll`
4. Make more changes, make sure there are still warnings or errors
5. Save the file explicitly
6. The cursor jumps to the quickfix window

I'm on windows 7, using vim 7.4.

### Minimal working example

```tex
\documentclass{minimal}
\begin{document}

Hello World! \foobar

\end{document}
```

### Minimal vimrc file

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
" Even though its the default, lets set it explicitly
let g:vimtex_quickfix_mode = 2
```

**Comment by lervag** [comment] 2017-07-25 13:16
I can't reproduce this on Linux with Vim or neovim.

Can I ask you to do some manual debugging? If so:

1. Could you edit `VIMTEX/autoload/vimtex/qf.vim`. Add a line below line 107 (beginning of `s:window_restore()`) with something like `unsilent echom "testing"`. Check if your test prints this line. You might have to do `:message` after doing the test to see the message.

2. If 1 proves true: continue with the same method to find which branch you enter. I assume you enter the `else` branch. This means that the `w:vimtex_remember_window` variable is used to go back to the original window. I'll give more pointers when/if you have some feedback.

**Comment by Chiel92** [comment] 2017-07-25 14:19
It doesn't seem to get there altogether. I put an echoerr statement on line 42, but nothing appears in messages. Very strange.

**Comment by lervag** [comment] 2017-07-25 19:49
That's strange. You say that the quickfix window does open. If it opens, then the `vimtex#qf#open` function has to run, so if you add an `echoerr` after line 42 it should be clearly visible. Although, perhaps not. If you do `echom 'test'`, then do `:messages` after the quickfix window has opened, then you should see the message.

**Comment by Chiel92** [comment] 2017-07-26 08:22
No it shows nothing. The file (and thus the function) is loaded though, it shows in `:scriptnames`. Moreover, putting an echoerr statement in the global script scope in that file, it does give an error message. But putting it in the function, nothing is shown when reproducing this issue as in the OP.

There must be something trivial going wrong. I'm probably overseeing something obvious.

Could it be that the qf window is opened by something else? Note that I use the bare vimrc as in the OP.

**Comment by lervag** [comment] 2017-08-02 08:34
Sorry, life's been quite busy lately.

I don't think something else is opening the qf window (at least not if you are running with the minimal vimrc file).

I think the best approach for understanding this is to know exactly which code is running. Thus the next step is to take a step back. Could you add `echoerr` or similar (perhaps with `unsilent` prepended) to `vimtex#compiler#callback()` (this is the autoload function syntax, let me know if you do not know what I mean by this). I would first put an echo in the beginning and verify that it is there also on the second invocation. If this works, then I would move the echo to just before the call to `vimtex#qf#open(0)`. If you still get the message, now you move the echo inside the `vimtex#qf#open` function, to the very top of the function.

Remember to use `unsilent`.

Also, it would be useful to see the output of `:scriptnames` (when you run with the minimal vimrc file). Perhaps there is a windows specific settings file loaded that is breaking things.

**Comment by lervag** [comment] 2017-08-08 20:00
I'm closing this because I can't reproduce it. It becomes close to impossible for me to debug/solve.

Feel free to reopen or continue the discussion if you have more input/find more clues.

**Closed by lervag** 2017-08-08 20:00 UTC

**Comment by logarytm** [comment] 2020-02-21 11:53
Sorry for digging an old thread, but I had a similar problem and it could help someone. `\ll` stopped live compiling and the quickfix window always stole focus. It turned out that I have recently installed `vim-polyglot`, which binds `<leader>ll` to `:Latexmk`. I've solved it by disabled the latex integration of vim-polyglot as described in https://github.com/sheerun/vim-polyglot/issues/204.

**Comment by lervag** [comment] 2020-02-21 11:58
> as described in sheerun/vim-polyglot#204.

Also, see `:help vimtex-troubleshooting`, the very first problem.

> By the way, thanks a lot for making such a good plugin. <333

Happy you like it :)
