### ISSUE TITLE
Error while running :VimtexCompile

### ISSUE THREAD

**Issue by hicsuntdragons** [lervag/vimtex#1195] opened 2018-08-16 17:22 UTC
The following happens with every '.tex' file i try to run. I open vim, run the compiler function, and it gives the folowing error:

```
Error detected while processing function vimtex#compiler#compile[5]..40[24]..42[39]..232[5]..237:
line 2:
E484: Can't open file $appdata$\Local\Temp\VIoFE12.tmp
```

The temporary file name aways changes.

When i run the compiler for the first time, it compiles, despite the error. if I try to stop the interpreter (`:VimtexStopAll`) and run again, it doesn't work anymore. If i try to open, compile, then make a change and `:w` it, vimtex also works.

I tested latexmk im cmd and it works fine:

```
cd $path_to_tex$
latexmk -pdf main.tex
```

Honest warning: i installed miktex couple months ago, and it stopped working completely. then, this error started. then, i clean re-installed miktex with latexmk.pl and tested on cmd, working fine, but the error didn't disappear. I tried re-installing vimtex to no resolution.

Some of my vimrc file:

```vim
if has('win32')
    	let $PATH .= ';' . 'C:\Program Files (x86)\SumatraPDF'
	let $PATH .= ';' . 'C:\Strawberry\perl\bin'
	let $PYTHONHOME =  'C:\Users\julia\AppData\Local\Programs\Python\Python35'
endif

call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-sensible'
Plug 'lervag/vimtex'
Plug 'xolox/vim-misc'
Plug 'xolox/vim-session'
Plug 'neomake/neomake'
Plug 'Valloric/YouCompleteMe'
"Plug 'SirVer/ultisnips' "unistalled for debuging of issue
"Plug 'ludovicchabant/vim-gutentags' "unistalled for debug of issue
call plug#end()

let g:latex_viewer='SumatraPDF'
let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options
	\ = '-reuse-instance -forward-search @tex @line @pdf'
let g:vimtex_view_general_options_latexmk = '-reuse-instance'

 if !exists('g:ycm_semantic_triggers')
    let g:ycm_semantic_triggers = {}
  endif
  let g:ycm_semantic_triggers.tex = g:vimtex#re#youcompleteme

nmap <F2> :VimtexCompile
nmap <F3> :VimtexView<CR>
```

And a `minimal.tex`:

```tex
\documentclass[oneside,a4paper,12pt,fleqn,english,french,spanish,brazil]{abntex2}
\include{meta}

\begin{document}

\frontmatter
\pagenumbering{arabic}
\include{pre}   % Capa, prefácio e afins

\textual

\mainmatter
\pagenumbering{arabic}
\include{cap_1}
\include{cap_2}
\include{cap_3}
\include{cap_4}
\emph{compileTest}
% Arquivo .bib
\bibliography{referencias}

% Fim do texto
\end{document}
```

**Comment by lervag** [comment] 2018-08-16 18:51
Ok, first, some basics: Can you please provide which OS you are on (obviously Windows, but which version)? And which version of Vim?

I honestly don't know much about Windows systems, but I searched around and I found some things that might help:

1. Someone had a [similar issue](https://github.com/mattn/gist-vim/issues/48#issuecomment-12916349), my link should take you to a possible solution:

    ```vim
    set shell=cmd
    set shellcmdflag=/c
    ```

    Please read the thread and see if this might be related to your issue. In particular, it seems like doing `:echo system('dir')` should be enough to reproduce your issue. It also seems to be due to your `shell` settings or similar.

2. Another thing that might be related is [this vim.wikia.com post](http://vim.wikia.com/wiki/Fix_errors_that_relate_to_reading_or_creating_files_in_the_temp_or_tmp_environment_on_an_MS_Windows_PC). It says that the problem might be due to read/write permissions, and that you might need to change the `$TMP` and `$TEMP` variales.

PS! I took the liberty of updating your post with proper formatting.

**Comment by lervag** [comment] 2018-08-16 19:52
Thanks for new input!

I think you should try to strip down to a real minimal example. I.e., create a minimal vimrc file such as this:

```vim
set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options
  \ = '-reuse-instance -forward-search @tex @line @pdf'
let g:vimtex_view_general_options_latexmk = '-reuse-instance'
```

As well as a minimal tex file, such as this:

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

Now, from a cmd prompt, you can go to the directory where you've put the files, then do `gvim -u minivimrc minimal.tex`. Does the problem still persist?

**Comment by hicsuntdragons** [comment] 2018-08-16 21:14
I made several tests using minimal vimrc and minimal .tex, and the problem persisted. 

minimal _vimrc:

`set nocompatible
let &rtp = '~/.vim/plugged/vimtex,' . &rtp
let &rtp .= ',~/.vim/plugged/vimtex/after'
filetype plugin indent on
syntax enable

"added necessary folders to path.

let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options
  \ = '-reuse-instance -forward-search @tex @line @pdf'
let g:vimtex_view_general_options_latexmk = '-reuse-instance'
`
minimal .tex:

`\documentclass{minimal}
\begin{document}
test compiler 2
\end{document}`

**Comment by lervag** [comment] 2018-08-17 06:39
I updated your formatting again. Please take the opportunity to learn the formatting syntax yourself, it is pretty straightforward, and properly formatted posts are much easier to read.

So, what does `"added necessary folders to path." mean? How is this related to your `_vimrc` file?

Further, I assume the problem persist if you remove the vimtex options as well, they should not be relevant here. Can you verify that? I would also suspect that you can remove the second `let &rtp .= ...` line.

All in all, it seems you can reproduce the problem with a minimal vimrc file, which is good. And if I'm right, you should be able to reproduce with the following even more minimal vimrc file:

```vim
set nocompatible
let &rtp = '~/.vim/plugged/vimtex,' . &rtp
filetype plugin indent on
syntax enable
```

Please confirm.

Next step, after doing `gvim -u minivimrc minimal.tex` from a terminal, please provide the output of `:scriptnames`, which should show the various scripts that have been loaded. This should be a relatively short list.

**Comment by lervag** [comment] 2018-08-18 10:42
> Yes, it persists. but initially gives the "selected viewer is not executable!" warning.

I see, in this case you could set the first option just to prevent this warning.

From your `:scriptnames` output, it seems that things are as they should be.

> I got angry and just clean reinstalled vim due to other weird behavior. It was as painful as it sounds. In the end, I reinstalled vim-plug and vimtex, got hopeful, same problem, got frustrated again.

I'm sorry about this, and I wish I was able to solve your problem more easily!

> Also tested with admin rights (which I shoud have tried before, right?), same thing.

That seems sensible, I agree. And strange that things still do not work.

> Noticed that the command \lc also returns the temp file error. Despite that, the command works. The error message is: ...

> Small edit: I ran through the compiler.vim and noticed some abort funcionalities that call for the stop command, which I believe should close the perl interpreter and latexmk.exe. Also not working. In reality I've been conducting all these tests and closing Perl.exe by hand.

> Small Rant
> I really dont know why I'm bothering so much with this, since I'm changing from windows to arch linux in the near future... windows is full of telemetry, BSOD's and this type of nonsense.

If you search through previous issues, you will quickly see that I have my share of rants for Windows related issues. Unfortunately, I have still not had a user that has enough understanding of how things work on Windows to help me make vimtex fool proof. My own understanding and knowledge is not enough, and I am not interested in spending too much time on such issues. I don't use Windows myself for anything but Word and Excel at work.

Although I don't think it will help, you should read `:help vimtex-faq-windows`.

----

So, what do we do? I have no idea what more to try. I see nothing wrong with your configuration or system (except that it is not running Linux), and I can't find anything else than what I've already suggested. As such, I want to close the issue as unresolved, unless you have some other ideas yourself.

**Comment by hicsuntdragons** [comment] 2018-08-18 18:37
> Unfortunately, I have still not had a user that has enough understanding of how things work on Windows to help me make vimtex fool proof.

As I investigate this, I am starting to deduce the problem is on a lower level on my installation. Now i get errors while running `vim-plug` and when using `utisnips,` but never with built-in features, which suggests the interaction between `vim` and `vim-plug` is broken.

> If you search through previous issues, you will quickly see that I have my share of rants for Windows related issues...

I use windows at this point only because of tradition. I got to a point where even my editing software is open source and initially developed for linux xD, I'm just waiting on a new ssd I bought to make the final change.

> So, what do we do? I have no idea what more to try.

Well, is not a fatal error, since everything is (somewhat) usable, although preceeded of these strange errors.... also I have another machine with a working installation of `neovim` and the `vimtex` plugin. Also, this problem will soon desappear of my life xD. Finally, this seems to be a very rare occurence, since I found no docummented issue. I say we rest for now.

### Final Thanks

lervag, thanks for taking your time to try and troubleshoot this with me. Your dedication to this project is quite amazing, as I saw when I read the other posts. Keep up the good work! :)

**Comment by lervag** [comment] 2018-08-18 19:16
Thank you for the kind words. I enjoy working with this project, and it makes me happy that other people find it useful. :)

So, I'm closing this. If you should learn something that might help solve the issue, then please feel free to reopen!

**Closed by lervag** 2018-08-18 19:16 UTC
