### ISSUE TITLE
Windows 8 - Latexmk PID 

### ISSUE THREAD

**Issue by jbkopecky** [lervag/vimtex#154] opened 2015-04-14 12:23 UTC
Hello!

Thank you for this great plugin !

I am not sure about this one, but I get some errors when I start Latexmk compilation from my Gvim on Windows 8.

![vimtex_error_pid](https://cloud.githubusercontent.com/assets/9846459/7136253/453be38c-e2af-11e4-9488-ced76c3c8a84.png)

It looks like latexmk still can compile the .tex but I think it creates a new latexmk process instead of catching an existing one (when I stop and start continuous compiling several times, I end up with mutliple latexmk processes running)

I did have a look at the function that I think caused this error: ```s:latexmk_set_pid()``` at line 428 in latexmk.vim.

Could the bug come from the line 431 ?:

```vim
let pidinfo = systemlist(pidcm)[-1] 
```

I tried to run the command ```qprocess latexmk.exe``` from my windows command prompt (if I understand well, maybe it should have been something like ```system(pidcm)``` instead of ```systemlist(pidcmd)``` but I am afraid this doesnt get me any pid info output from any latxmk process.

Then, should I try to run something like:
```vim
let pidcmd = 'tasklist /v /fo csv | findstr /i "latexmk.exe"'
let pidinfo = system(pidcmd)
```
and then parse the answer to get latexmk process pid ?

I am not very good at vimscript or windows commands, but do you think this could be the issue I am having ?

Thank you for your help !

JB

**Comment by lervag** [comment] 2015-04-14 13:09
Hi. It seems you are experiencing two different problems. The first one is related to the viewer settings, while the second is related to the PID. The latter seems to be the important one. I think the first one may arise if you for instance have disabled the viewer module?

I don't personally use windows, and so windows debugging is difficult for me. I rely on other users to make this work. However, I will try to help: It seems to me that you are right that `qprocess latexmk.exe` is the problem here. It should be easy to verify: In a cmd shell, first start latexmk for a tex project, then in a separate cmd shell test the output of `qprocess latexmk.exe`. It should return the pid. If it does not, then this is indeed your problem.

If `qprocess` does not work, and if you find another windows shell command that does work, similar to what you suggest, then please let me know. Also see #15.

I'll be rude enough to notify @petobens and @Konfekt, who was very helpful in implementing support for windows.

**Comment by jbkopecky** [comment] 2015-04-14 13:28
Yep, I have disabled the viewer module. 

I was more worried about the PID issue as well. I am sorry I just saw the #15 issue. 

I do not get any result from the cmd shell when running ```qprocess latexmk.exe```. 

I do not know if this is because of my computer config or a Windows 8 issue. 

I have had better results with ```Tasklist```, running: ``` tasklist /v /fo csv | findstr /i "latexmk.exe"``` that gives me an output that includes a latexmk PID (but haven't  figured out how to properly parse it in vimcscript to isolate the PID).

I don't know if ```tasklist``` is compatible with all windows versions though and it seems this command is a little slow...

Also, is the function systemlist() a vim builtin function ?

**Comment by petobens** [comment] 2015-04-14 16:39
@lervag @jbkopecky Unfortunately I cannot provide any help since I don't use the latexmk functionality (because I use [arara](https://github.com/cereda/arara) to compile my documents).

**Comment by Konfekt** [comment] 2015-04-14 17:29
Hm. It's me who changed the command line to obtain the process ID to use `qprocess` whereas before it was  `wmic process` and not working correctly for me under Windows 7 (as still existant in LaTeX BoX, see https://github.com/LaTeX-Box-Team/LaTeX-Box/blob/64eeb2dd9a0afd33ed8610a2d07416d126d5a2ef/ftplugin/latex-box/latexmk.vim#L333). One reason for `qprocess` was that it is compatible with more Windows versions, starting from Windows XP Home.

**Comment by lervag** [comment] 2015-04-14 18:02
@Konfekt Do you have any idea why `qprocess` does not work for @jbkopecky on Windows 8.1?

It is difficult to find any information on `qprocess`, but [this](http://ss64.com/nt/query-process.html) seems to be related. @jbkopecky Does `query process latexmk.exe` provide any output?

`systemlist()` is an internal vim function, yes. You can read the docs with `:h systemlist`. I think, though, that this function was introduced in a relatively recent version of vim, so it is interesting to know which version of vim you are using.

**Comment by lervag** [comment] 2015-04-14 18:03
Btw: Could you please verify that my fix for the `viewer` related error message works?

**Comment by jbkopecky** [comment] 2015-04-15 07:47
So here are the results:

- [x] Viewer issue: Seems to be fixed.

![pid_issue](https://cloud.githubusercontent.com/assets/9846459/7154065/59d36ee8-e352-11e4-8e8a-3513c0183897.png)

- [x] ```query process latexmk.exe``` is not recognized as a command. Do you think I am missing something in my path ?

- [x] about ```systemlist```: I do not have a help for this function on my windows vim (version 7.4 - Aug 10 2013) but I get it at home on my Linux more recent version. I am going to have to look for a more recent version I guess.

**Comment by lervag** [comment] 2015-04-15 08:13
First, could you check what happens when you in vim on windows do the following?
```vimL
:echo systemlist('echo Hello World')
```
If `systemlist` is not available, then this should give a similar error as before.

Regarding `query process`, could the problem be that you do not have administrator access? [Here](https://technet.microsoft.com/en-us/library/bb490798.aspx) it says "Administrators have full access to all query process functions", which could imply that query process is not available without administrator rights. See also [here](https://technet.microsoft.com/en-us/library/cc788046.aspx) and [here](https://support.microsoft.com/en-us/kb/186592) and [here](http://unlockforus.blogspot.no/2012/08/how-to-display-all-processes-from.html).

I'm sorry to say that I have no idea why this does not work for you. Perhaps the problem is mainly or only the lack of `systemlist`?

**Comment by jbkopecky** [comment] 2015-04-15 08:36
Ok, so in fact I have two issues I guess:

- Running:
```vim
:echo systemlist('echo Hello World')
```
leads me to an Unknown function error. I tried to reinstall vim from [here](http://www.vim.org/download.php) but it was compiled in 2013 so I guess no ```systemlist``` function yet.

- It seems that when I run Cmd in admin mode, ```qprocess latexmk.exe``` and ```query process latexmk.exe``` do work...

The problem is that even when I fire up vim in admin mode, and run
```vim
:echo system('qprocess latexmk.exe') 
```
it doesn't seem to run this command with admin rights...

**Comment by jbkopecky** [comment] 2015-04-15 09:28
- I found a vim windows version with systemlist
- I have just not figured out yet how to bypass this admin rights issue.

**Comment by jbkopecky** [comment] 2015-04-15 10:06
Last Update: In fact, having ```systemlist``` working made the error disappear as you said. I can now compile without seeing any issue. I guess Vimtex is only compatible with latest windows Gvim then.

However, I think that it did not fix the PID catch problem (due to admin rights limitations on Windows8) because everythime I toggle continuous compilation using ```<leader>ll ```, it only starts it (and never stops it) and creates a new latexmk process every time.

**Comment by lervag** [comment] 2015-04-15 10:45
Good to hear that things are starting to work.

Does your windows user generally have admin rights? If not, perhaps giving yourself admin rights will fix this problem?

@Konfekt @petobens Do you guys understand this thing? I'm really not very good with such kinds of windows issues...

**Comment by Konfekt** [comment] 2015-04-15 17:23
For explanation: I switched from `wmic process` to `qprocess` because the former would not return a PID correctly on Windows 7, so that the second LatexMk instance would override the first. That is, with `wmic` only a single `LatexMk` instance would work. 

Unfortunately there's little documentation about `qprocess`. Perhaps it has been abandoned in Windows 8 together with the switch from `cmd` to `PowerShell` as default shell?

**Comment by lervag** [comment] 2015-04-16 06:09
@jbkopecky has confirmed that `qprocess` (an alias to `query process`) is available, but only when it is run as administrator. The question is then how to ensure that the command is run as administrator.

However, this issue also raises the question if there should be a fallback method to get the PID. I.e. if `qprocess` fails, then perhaps I should add a second method that does not need administrator rights?

**Comment by jbkopecky** [comment] 2015-04-16 08:43
How about ```tasklist``` see [here](http://commandwindows.com/tasklist.htm) and [here](http://en.wikipedia.org/wiki/Tasklist) and [here](https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/tasklist.mspx?mfr=true)? Is it compatible with all windows versions ? It works for me ! 
A ```wmic``` fallback sounds good, I have had a look at Tpope Vim Dispatch and it looks like he is using [wmic](https://github.com/tpope/vim-dispatch/blob/master/autoload/dispatch/windows.vim#L38) too.

**Comment by lervag** [comment] 2015-04-16 10:49
Does `wmic` work for you?

Does `tasklist` have the same problem as that mentioned by @Konfekt?

**Comment by jbkopecky** [comment] 2015-04-16 12:34
I did a quick revert to try ```wmic``` and it works for me (except that the cmd windows steals focus for a moment) I can start and stop compilation (i.e. it catches the appropriate PID)

About ```tasklist```, I am not sure to undesrtand the problem mentioned, so I can't really say. Are we trying to get several compilations cohexist without stealing each others latexmk processes ?

**Comment by Konfekt** [comment] 2015-04-16 16:07
Yes. If `wmic` works on Windows 8 but `qprocess` not, than better revert to `wmic`. However, under Win 7 the code as it used to be, would steal latexmk processes (as it did not read the PID correctly).

**Comment by lervag** [comment] 2015-04-17 20:53
Ok, then I will add fallback code to use `wmic` if `qprocess` fails. I think this should work in most cases.

**Comment by lervag** [comment] 2015-04-17 21:13
I just realized I have no way of testing. I think the following lines should work:
```vimL
let pidcmd = 'wmic process where '
      \ . '(CommandLine LIKE "latexmk\%' . a:data.tex . '\%") '
      \ . 'get ProcessId /value | find "ProcessId"'
let a:data.pid = strpart(systemlist(pidcmd)[0], 10)
```
It would be very helpful if someone could test this. @jbkopecky 

Also, @jbkopecky, it would be interesting to see if an alternative with `tasklist` also works. Could you test and if needed modify the lines you suggested earlier, that is,
```vimL
let pidcmd = 'tasklist /v /fo csv | findstr /i "latexmk.exe"'
let pid = split(systemlist(pidcmd)[-1], '\s\+')[-2]
```
so that the above code correctly gets the PID. This might lead to two possible fallbacks, which is better than one.

Also: It would be very helpful if you could let me know what the return value of `systemlist(pidcmd)[-1]` is for the original `qprocess` that does not work.

**Comment by jbkopecky** [comment] 2015-04-18 08:18
All right I'll have a look at it as soon as I get back on my Windows machine (monday)

**Comment by jbkopecky** [comment] 2015-04-22 11:44
Hello, sorry for the wait:

- The following code:
```vim
let pidcmd = 'wmic process where '
      \ . '(CommandLine LIKE "latexmk\%' . a:data.tex . '\%") '
      \ . 'get ProcessId /value | find "ProcessId"'
let a:data.pid = strpart(systemlist(pidcmd)[0], 10)
```

does not work for me. It gives me the following error (not very helpfull though):

![error1](https://cloud.githubusercontent.com/assets/9846459/7273249/1330dffc-e8f2-11e4-86bc-f9c3a2689199.png)

The previous vimtex wmic command works for me though. I am not sure why this one fails.

- Using Tasklist, here is the command that returns me correctly the last latexmk pid:
```vim
let pidcmd = 'tasklist /fi "imagename eq latexmk.exe"'
let pid = split(systemlist(pidcmd)[-1], '\s\+')[1]
```
For example:
In cmd console, the pidcmd returns:

1. For one latexmk process running:
![tasklist_on_process](https://cloud.githubusercontent.com/assets/9846459/7273339/02a98354-e8f3-11e4-8436-4890ad255a86.png)
The vim commands returns the only PID: `1172`
2. For two processes running:
![tasklist_two_processes](https://cloud.githubusercontent.com/assets/9846459/7273374/5b25943c-e8f3-11e4-814c-2de2e72960ef.png)
The vim command returns the last line pid: `7820` in this case.

I guess the lines are ordered by time of process creation so It works fine with me when I use tasklist command in vimtex. Could it be possible to test this pid command with different versions of windows ?

- The command `qprocess latexmk.exe`
gives me: 

![qprocess_error](https://cloud.githubusercontent.com/assets/9846459/7273587/6fda2436-e8f5-11e4-9c33-d5cfc52bf2ac.png)

in cmd console.
Therefore, the resulting output for `systemlist(pidcmd)[-1]` in vim is:
`operable program or batch file.`

Hope it helps !

**Comment by jbkopecky** [comment] 2015-04-26 09:35
Also, is it ok to replace
```vim
systemlist(pidcmd)
```

by:
``` vim
split(system(pidcmd), '\n')
```

to avoid breaking compatibility with older vim versions ?

**Comment by lervag** [comment] 2015-04-29 13:06
Please test if the latest commit fixes the compatibility issue and that it doesn't break anything.

**Comment by lervag** [comment] 2015-04-29 13:17
> The previous vimtex wmic command works for me though. I am not sure why this one fails.

Could you please be explicit on which `wmic` command works for you? I don't think there was ever committed any `wmic` commands to vimtex...

@Konfekt @jbkopecky Regarding qprocess: If I understand correctly from the earlier discussion, qprocess is only available when run as administrator. Could you please verify this? If this is the case, then qprocess is probably a bad choice for the default program to get the PID, since normal users should probably not generally have administrator rights?

@Konfekt I've pushed a change from qprocess to tasklist. Does the tasklist version work for you? Do you know a reason why not to use tasklist (if it works)?

**Comment by Konfekt** [comment] 2015-04-29 17:35
For my part, `tasklist` is just fine and I chose `qprocess` only because it was the most prevalent among tasklist et al. (available from XP Home edition and above); to boot the previous wmprocess command  was as cryptic as nonfunctional .

Since then I switched to OpenSuse, thus I cannot confirm that qprocess requires administrator rights because all online documentation was not clear on this.

**Comment by lervag** [comment] 2015-04-29 20:50
@Konfekt OK. Thanks for your input, anyway. If the latest version fixes the issue for @jbkopecky, and if it does not introduce any problems for other users, then I think this issue may be resolved.

**Comment by jbkopecky** [comment] 2015-05-05 08:20
It works for me ! Thanks !

**Comment by lervag** [comment] 2015-05-05 10:23
Great!

**Closed by lervag** 2015-05-05 10:23 UTC
