### ISSUE TITLE
Matching parentheses with brackets

### ISSUE THREAD

**Issue by ZackSylvan** [lervag/vimtex#1833] opened 2020-10-16 22:34 UTC
**Is your feature request related to a problem? Please describe it.**
A common mathematical notation for half-open intervals is [a, b) or (a, b], but these are not compatible with the usual delimiter pairs (a, b) and [a, b].

**Describe the solution you'd like**
I'd like vimtex to treat all of the above as valid delimiter pairs.

**Describe alternatives you've considered**
I tried setting
```vimscript
let g:vimtex_delim_list = {
      \ 'delim_math' : {
      \   'name' : [
      \     ['(', ')'],
      \     ['(', ']'],
      \     ['[', ']'],
      \     ['[', ')'],
      \   ],
      \   're' : [
      \     ['(', '[)\]]'],
      \     ['(', '[)\]]'],
      \     ['\[', '[)\]]'],
      \     ['\[', '[)\]]'],
      \    ]
      \  } 
      \}
```
However, this failed to correctly match `$ ( a [ b ) c ) $`:
- `tsd` at `b` gives `$ ( a \left[ b \right) c ) $` as expected.
- `tsd` at `a` gives `$ \left( a [ b \right) c ) $` instead of `$ \left( a [ b ) c \right) $`.
- `tsd` at `c` does nothing at all.

I also tried `'[(\[]'` for the open delimiter, which didn't work at all.

Sorry if I've missed an obvious solution here.

**Comment by lervag** [comment] 2020-10-17 10:12
Thanks for the clear issue description.

Unfortunately, I'm not sure that there exists a (straightforward) solution to this. The topic has been discussed before, e.g. in #592. I remember a more detailed discussion, but could not find it now.

So, the problem is that it is very hard to avoid that the `()` in `( a [ b )` is recognized as the current delimiter pair. And this is indeed what is happening. The delimiter features are based on regexes, and I can't see a very good way to achieve what you want here without somethings being messed up. Sorry!

Conclusion: I won't try to fix this, because I don't have a good idea of how to make this work. It does not mean there is no way, and I would be happy to consider good ideas and/or PRs!

**Comment by gustaphe** [comment] 2020-10-28 14:54
Not only is this difficult, I think it would be bad to implement this. Unmatched parentheses are a good debugging tool. And some people use ``[ a, b [`` for the same concept, which would be even harder to sort out.

I see that this is marked as won't fix, so I won't hammer on, just wanted to express support, and suggest a more editor-friendly alternative to @ZackSylvan : [the interval package](http://tug.ctan.org/macros/latex/contrib/interval/interval.pdf)

**Comment by lervag** [comment] 2020-10-28 15:05
Thanks for pitching in. I think the idea of "hiding" the details in a package is quite good and obviously very editor friendly.

I'll close this issue, but I don't mind hearing more opinions or that the discussions continues, of course.

**Closed by lervag** 2020-10-28 15:05 UTC
Labels: enhancement, won't fix
