### ISSUE TITLE
vimtex throws errors despite successfully compiling

### ISSUE THREAD

**Issue by mrb1358** [lervag/vimtex#2473] opened 2022-08-31 16:15 UTC
### Description

When attempting compilation vimtex throws errors and fails to open the document viewer despite compilation succeeding (a correct PDF is outputted).

This only occurs when using nvim, everything works as expected with vim.

p.s. Thanks for your work on this plugin and for taking the time to look over this issue.

### Steps to reproduce

Files used are below.

1. `nvim -u minimal.vim minimal.tex`
2. Begin continuous compilation: `\ll`

**minimal.vim**

```vim
set nocompatible
filetype plugin indent on
syntax enable

call plug#begin(stdpath('data').'/plugged')
  Plug 'lervag/vimtex'
call plug#end()

let g:vimtex_view_method = 'zathura'
```

**minimal.tex**

```tex
\documentclass{article}

\begin{document}
 Hello World!
\end{document}
```

### Expected behavior

I expect compilation to succeed and the document viewer to open.

### Actual behavior

Compilation succeeds but vimtex throws the following errors and fails to open the document viewer.

```
Error detected while processing function vimtex#compiler#compile[4]..vimtex#compiler#start[25]..vimtex#log#info[1]..184[24]..185[5]..vimtex#ui#echo:
line    2:
E121: Undefined variable: #
E116: Invalid arguments for function extend
E15: Invalid expression: extend(#{indent: 0}, a:0 > 0 ? a:1 : {})
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 20.04.4 LTS
  Vim version: NVIM v0.4.3
  Has clientserver: true
  Servername: /tmp/nvimedYhYS/0

VimTeX project: minimal
  base: minimal.tex
  root: /home/buckm
  tex: /home/buckm/minimal.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 5
      output: /tmp/nvimedYhYS/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'minimal.tex'
      pid: 29740
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```

**Comment by mrb1358** [comment] 2022-08-31 16:19
For completeness, here is my VimtexInfo output when running vim:

```
System info:
  OS: Ubuntu 20.04.4 LTS
  Vim version: VIM 8.1 (1-2269, 3612, 3625, 3669, 3741)
  Has clientserver: false

VimTeX project: minimal
  base: minimal.tex
  root: /home/buckm
  tex: /home/buckm/minimal.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 30136 run
      output: /tmp/vC1lJnP/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode 
      pid: 30136
  viewer: Zathura
    xwin id: 0
    cmd_start: zathura  -x "/usr/bin/vim.basic -T dumb --not-a-term -n -c \"VimtexInverseSearch %{lin
  qf method: LaTeX logfile
```

**Comment by lervag** [comment] 2022-08-31 16:56
The problem is simply that you are using [an ancient version of neovim](https://github.com/neovim/neovim/tags?after=v0.7.2) — specifically, the version you are using was released november 2019, whereas the latest current release was released june this year (v0.7.2). Furthermore, neovim is _still_ a young project, so it does not really make any sense to use an old version.

If I'm right, you should not see this problem with regular Vim (version 8.0 and later).

----

But OK, I realize that I've stated a minimum version of v0.4.3 for neovim in the vimtex docs. I looked into this a little bit more, and I notice that the feature I use that breaks things for you is the literal dict (`:help literal-Dict`) - it was introduced to Vim in version 8.1. Thus, I'll revert this and use regular dicts. That will probably avoid future similar issues for other unsuspecting users.

I still _strongly_ recommend you to update neovim. My first paragraph is still very much true. If you want to use neovim, you should not stay at old versions.

**Comment by lervag** [comment] 2022-08-31 17:00
I believe this should be  fixed now; please update and test again.

**Comment by lervag** [comment] 2022-08-31 17:00
> p.s. Thanks for your work on this plugin and for taking the time to look over this issue.

My pleasure; and thanks for raising the issue.

**Comment by mrb1358** [comment] 2022-08-31 17:21
Many thanks, again.

> you are using an ancient version of neovim

 Unfortunately I do not have sudo privileges on the machine which I encountered this problem on (due to it being a work laptop), so I do not have direct control over updating the system-wide neovim. I will speak to the sysadmin and enquire though.

I will update and test tomorrow morning (BST) when I next have access to the machine.

**Comment by clason** [comment] 2022-08-31 17:22
> Unfortunately I do not have sudo privileges on the machine which I encountered this problem on (due to it being a work laptop), so I do not have direct control over updating the system-wide neovim.

You can just download an appimage from https://github.com/neovim/neovim/releases

**Comment by mrb1358** [comment] 2022-08-31 17:24
Good to know. Thanks @clason .

**Comment by clason** [comment] 2022-08-31 17:26
(I'm exaggerating only slightly by saying that 0.4.2 vs. 0.7.2 is like using Windows 95 instead of Windows XP. Almost a different editor.)

**Closed** 2022-08-31 20:24 UTC
Labels: bug

**Comment by mrb1358** [comment] 2022-09-01 10:19
>I believe this should be fixed now; please update and test again.

Confirmed that this patch is working with neovim v0.4.3.

**Comment by lervag** [comment] 2022-09-01 10:22
Cool, thanks for confirming that it works!
