### ISSUE TITLE
latexmk started multiple times - does not close upon closing vim

### ISSUE THREAD

**Issue by vsilv** [lervag/vimtex#159] opened 2015-04-26 21:30 UTC
Dear lervag,

Me and also my colleagues experienced the problem that the perl latexmk does not close upon closing vim and in order not to create buggy behavior we have to kill those instances individually, since they interfere with each other. Sometimes even the pdfviewer does not work anymore as long as not all instances of latexmk are killed and pdflatex is run. Latexmk can be revoked after being killed with vimtex and the normal behavior is recovered.

maybe you have an idea how to fix this problem?

with best regards

**Comment by lahwaacz** [comment] 2015-04-27 07:23
Under ideal circumstances, vimtex manages latexmk fine on my system, but on several occasions I have also experienced multiple instances of latexmk spawned by vimtex. The precise conditions are unclear to me, one sure way is when vim segfaults, but sometimes it happened even when vim did not segfault.

**Comment by nasenatmer** [comment] 2015-04-27 21:33
vim segfaults?

@vsilv: Which OS are you using? I'm on Arch Linux and have not witnessed several instances of latexmk spawning recently.

**Comment by lervag** [comment] 2015-04-29 13:00
Sorry for taking so long to reply! I've been very busy lately. :\

In general I don't experience the same issue, except in the case when vim segfaults. This also happens with me from time to time. As @nasenatmer, I'm on Arch Linux. And except for the segfaults, I don't experience several instances of latexmk spawning.

Unfortunately, I don't have any idea on how to fix this problem. I've implemented functionality that should stop any running latexmk process whenever you close a LaTeX file or quit vim. This should work as expected, and on my end it seems like it does. However, there might be a bug that occurs for rare cases, and I would of course be happy to fix this.

I don't think there is anything to do when vim is segfaulting.

@vsilv Could you provide me some more info on your OS, vim version, and similar. And if you should ever be able to find a reproducible way to reproduce this problem, let me know. If we can't reproduce this issue, then I don't really have any clue how to improve anything. In that case I propose to close the issue.

**Comment by vsilv** [comment] 2015-04-29 14:30
@nasenatmer @lervag : I am using Arch Linux and my colleague who is having the same issue is using Ubuntu. Which details you need with respect to the vim version? Obviously it is 7.4, but which information you need? 

Actually I am not quite sure how it is possible that there are multiple instances of latexmk. Since I am not having problems with segfaults, the origin of the problem might be somewhere else.

**Comment by nasenatmer** [comment] 2015-04-29 14:45
@vsilv: your exact version of vim is important: is it the same as we have or a git one, for instance. Also, can you reproduce the behaviour with a minimal example and a minimal vimrc (@lervag has one in his repo) and tell us the steps to do reproduce the problem? These kinds of things.

**Comment by lervag** [comment] 2015-04-29 16:39
@vsilv Vim on Arch Linux should be version 7.4.712 (as of today, 2015-04-29).

As @nasenatmer said, it will help VERY much if you are able to create a minimal working example with a minimal vimrc (feel free to use [mine](https://github.com/lervag/dotvim/blob/master/minivimrc)).

And again as @nasenatmer asks (thanks, btw, for getting involved!): Make sure you are on the latest version of vimtex. I'm updating quite often and trying to fix bugs as they are reported. Lately I've been quite busy, but I try to keep the issue count low in general.

**Comment by nasenatmer** [comment] 2015-06-02 21:18
It seems I'm also experiencing `latexmk` staying active although `vim` has exited. I haven't experienced any crasehs yet, but if I re-open the same document and do `\ll`, I get a second `perl` process started. The info I get with `\li` also correctly corresponds to the second process, not the old one.

**Comment by lervag** [comment] 2015-06-03 05:43
If any `latexmk` process stays active when vim quits, then vimtex will not know about it on restart. However, this should in principle never occur, and if it does, then it is a bug. If anyone is able to provide me with a reproducible example, then I could investigate the problem and hopefully fix it.

Note: I do not experience this issue myself, except in rare cases when vim crashes. Even when vim crashes, this issue does not always happen.

**Comment by lervag** [comment] 2015-06-05 20:41
I suspect this problem might be related to #176, which I just solved. It seems I pushed a bug in February. Please let me know if the problem persists. In the meantime, I take the liberty of closing this issue.

**Closed by lervag** 2015-06-05 20:41 UTC
