### ISSUE TITLE
%!TEX program crashes latexmk with neovim

### ISSUE THREAD

**Issue by ebarojas** [lervag/vimtex#1607] opened 2020-02-25 01:51 UTC
I get the error

```Latexmk: Need to specify exactly one filename for preview-continuous mode  but 2 were specified```

when using

```%!TEX program = latex```

on my main.tex with neovim

I'm also using the ```%!TEX root``` directive

**The only way I've managed to make it work is removing that first line (```%!TEX program = latex```), which is undesirable because it provides some compatibility issues with my other environments.**

I've tried to change some config, but unsure if this is an ```nvr```problem or is easily configurable, related but not solved by #1251 

My min config file:
```
" Config latex
let g:tex_flavor = "latex"
let g:tex_conceal = ''
```

EDIT: Update minimal config file

**Comment by lervag** [comment] 2020-02-25 07:21
Could you please provide a minimal example?

**Comment by lervag** [comment] 2020-02-25 16:49
To be more specific:

> I get the error
>
> `Latexmk: Need to specify exactly one filename for preview-continuous mode but 2 were specified`
>
> when using
>
> %!TEX program = latex
>
> on my `main.tex` with neovim
>
> I'm also using the `%!TEX root` directive
>
> The only way I've managed to made it work is removing that first line (`%!TEX program = latex`), which is undesirable because it provides some compatibility issues with my other environments.
>
> I've tried to change some config, but unsure if this is an nvrproblem or is easily configurable, related but not solved by #1251
>
> My min config file:

This description leaves a lot unspecified. Could you provide

1. A minimal LaTeX file that produces your issue, perhaps something like this:

   ```tex
   %! TeX program = latex
   %! TeX root = ...
   \documentclass{minimal}
   \begin{document}

   Hello World!

   \end{document}
   ```

   Althoug, since the `TeX root` directive is relevant you probably need somewhat more complexity here.

2. A minimal config file/vimrc file with the relevant options, something like this:

   ```vim
   set nocompatible
   let &rtp = '~/.vim/bundle/vimtex,' . &rtp
   let &rtp .= ',~/.vim/bundle/vimtex/after'
   filetype plugin indent on
   syntax enable

   let g:tex_flavor = "latex"
   let g:tex_conceal = ''
   ```

3. Steps to reproduce. E.g.: i) start neovim with `nvim -u minimal.vim minimal.tex`, ii) more steps to reproduce the issue.

You also refer to compatibility issues, but nothing about what those are.

Note that the above was also specified/suggested in the issue template. When I have to repeat things like this, it takes time that I'd rather spend on actually trying to fix/improve things.

PS! Your config is dated. First, you no longer need to set `g:vimtex_compiler_progname = nvr` because it is set by default, and `g:vimtex_latexmk_continuous` is not a valid vimtex option.

**Comment by ebarojas** [comment] 2020-02-27 17:05
Hi, minimal example:

main.tex as follows
```
%!TEX program = latex
\documentclass{minimal}
\begin{document}
  \input{sections/coverpage}
\end{document}
```

And running neovim on content.tex running - starting compilation with ```\ll```  command
```
%!TEX root = ../main.tex
\section Try me out
Hello world
```

What I mean with the compatibility issues, (on hindsight probably not the right word) is that the short term solution to allow ```\ll``` is removing the ````%!TEX program = latex``` on my main.tex file and that would not work on my other dev environments.

I’ll update my min file and settings

**Comment by lervag** [comment] 2020-02-27 22:02
What do you want to achieve with `!% TeX program = latex`? This line is read by vimtex and the value will correspond to an option for latexmk according to `:help g:vimtex_compiler_latexmk_engines`.

**Comment by lervag** [comment] 2020-02-27 22:07
I found a minor bug in the code. Does it work for you now?

But again, your value `latex` for the `%! TeX program` directive is "invalid". It would be useful to know what you want to achieve with it.

**Comment by ebarojas** [comment] 2020-03-03 16:19
Hi, yes, **it works now.** Thanks, this really helps!

Answering your question, my other latex environment requires the ```%! TEX program = latex``` directive to choose the appropriate engine. I assume its not a default setting over there and needs me to specify. However, the general idea of that is that the tex code is agnostic to the environment and is able to operate as _self contained_ as possible.

PS: Should I close the issue?

**Comment by ebarojas** [comment] 2020-03-03 16:21
Another quick q, how do you make your github editor recognize latex code and color code?

**Comment by lervag** [comment] 2020-03-03 16:45
> Answering your question, my other latex environment requires the `%! TEX program = latex` directive to choose the appropriate engine. I assume its not a default setting over there and needs me to specify. However, the general idea of that is that the tex code is agnostic to the environment and is able to operate as self contained as possible.

Yes, this directive is only for editors and IDEs. I know that other editors respect them as well. However, it is not necessarily a one-to-one correspondance between how different editors interprate the values, as you can see from your own issue.

I'm curious: What is your other latex environment?

> Another quick q, how do you make your github editor recognize latex code and color code?

It is specified in the documents for [github flavored markdown](https://guides.github.com/features/mastering-markdown/#syntax-highlighting), see the "Syntax highlighting" section. More details [are available here](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks). An example, the following fenced code block:

````
```tex
%!TEX program = latex
\documentclass{minimal}
\begin{document}
  \input{sections/content}
\end{document}
```
````

results in:

```tex
%!TEX program = latex
\documentclass{minimal}
\begin{document}
  \input{sections/content}
\end{document}
```

**Comment by lervag** [comment] 2020-03-03 16:46
Yes, I think we can close this issue.

**Closed by lervag** 2020-03-03 16:46 UTC

**Comment by ebarojas** [comment] 2020-03-07 14:28
Thanks @lervag 

My other latex env is MacTex with Sublime 3, [latex tools](https://github.com/SublimeText/LaTeXTools) and Skim. I sometimes push to an overleaf remote to get collaborations from non git-savvy user sand my code has always worked there too.

**Comment by lervag** [comment] 2020-03-07 16:10
Thanks for the info. Note, it does not really seem like "latex" is a valid choice for LaTeXtools for Sublime text either, see e.g. [here](https://github.com/SublimeText/LaTeXTools/blob/45376f12449e32c4ad769f5baa0a75c1fa72194d/docs/features.md#tex-engine-selection). That is, using `%!TeX program = latex` is not documented as being a valid choice, ref.:

> If the first line of the current file consists of the text %!TEX program = <program>, where program is pdflatex, lualatex or xelatex, the corresponding engine is selected.

**Comment by ebarojas** [comment] 2020-03-10 14:21
@lervag looking into this, and it is quite possible. 

The template I’m using was written for ```xelatex``` and at some point I switched (a VERY late night as I recall), I assume this was carried over and the switch was done incorrectly, with the directive defaulting to pdflatex. I totally see your previous point. Thanks for the review.

**Comment by lervag** [comment] 2020-03-10 14:42
You're welcome, and no problem. Feel free to raise new isssues if you should have any!
