### ISSUE TITLE
Enhanced `gf` broken

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1646] opened 2020-03-29 02:38 UTC
**Issue**
The Enhanced `gf` command does not work and produces an error message 
`E447: Cannot find file "input" in path`

Git bisect reveals  that the offending commit is f21f4ae3d

```
commit f21f4ae3db24990fbeb07841cdfcbf008ff8ffc8
Author: Karl Yngve Lervåg
Date:   Tue Nov 19 17:42:03 2019 +0100

    Fix failing 'gf' on \bibliography macro

autoload/vimtex/include.vim | 4 ++++
1 file changed, 4 insertions(+)
```

**minimal.vim**

  ```vim
  set nocompatible
  let &runtimepath  = '~/.vim/plugged/vimtex,' . &runtimepath
  let &runtimepath .= ',~/.vim/plugged/vimtex/after'
  filetype plugin indent on
  syntax enable
  ```

**minimal.tex**
  ```tex
  \documentclass{minimal}
  \begin{document}
  Hello world!
  \input{my_special_research/my_special_research.tex}
  \end{document}
  ```

**Commands/Input**
Place file on the beginning of line `4` and press `gf`. 

**Observed Behaviour**
`E447: Cannot find file "input" in path`

**Expected Behaviour**
Opens up the file `my_special_research.tex` in the window

**Output from VimtexInfo**
```
System info
  OS: Mac OS X 10.15.3 (19D76)
  Vim version: NVIM v0.4.3
  Has clientserver: true
  Servername: /var/folders/lq/3qgr399x5bv_fzzvvf2vytg40000gn/T/nvimW7lxOE/0

vimtex project: main
  base: main.tex
  root: /Users/krishna/Documents/work_related_rsrch_codes_tutorials_papers_projects/clustering_algorithm_paper
  tex: /Users/krishna/Documents/work_related_rsrch_codes_tutorials_papers_projects/clustering_algorithm_paper/main.tex
  out: /Users/krishna/Documents/work_related_rsrch_codes_tutorials_papers_projects/clustering_algorithm_paper/main.pdf
  log: /Users/krishna/Documents/work_related_rsrch_codes_tutorials_papers_projects/clustering_algorithm_paper/main.log
  aux: /Users/krishna/Documents/work_related_rsrch_codes_tutorials_papers_projects/clustering_algorithm_paper/main.aux
  fls: /Users/krishna/Documents/work_related_rsrch_codes_tutorials_papers_projects/clustering_algorithm_paper/main.fls
  source files:
    main.tex
    my_special_research.tex
  compiler: latexmk
    backend: nvim
    output: /var/folders/lq/3qgr399x5bv_fzzvvf2vytg40000gn/T/nvimW7lxOE/108
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -synctex=1
        -interaction=nonstopmode
        -shell-escape
      latexmk engine: -pdf
  viewer: Skim
  qf: LaTeX logfile using pplatex
    setqflist: 5502
    set_errorformat: 5501
  document class: 
  packages:
    amsbsy
    amsfonts
    amsgen
    amsmath
    amsopn
    amssymb
    amstext
    array
    atbegshi
    atveryend
    auxhook
    babel
    bigintcalc
    bitset
    bookmark
    booktabs
    calc
    caption
    caption3
    cas-common
    catchfile
    cite
    cleveref
    color
    colortbl
    datatool-base
    datatool-fp
    dcolumn
    defpattern
    diffcoeff
    epstopdf-base
    etexcmds
    etoolbox
    everysel
    everyshi
    expl3
    fixltx2e
    flafter
    fontaxes
    fontenc
    footmisc
    fp
    fp-addons
    fp-basic
    fp-eqn
    fp-eval
    fp-exp
    fp-pas
    fp-random
    fp-snap
    fp-trigo
    fp-upn
    geometry
    gettitlestring
    glossaries
    glossaries-compatible-307
    glossaries-extra
    glossaries-extra-bib2gls
    glossaries-extra-stylemods
    glossary-hypernav
    glossary-list
    glossary-long
    glossary-super
    glossary-tree
    graphics
    graphicx
    hycolor
    hypcap
    hypdestopt
    hyperref
    hyperxmp
    ifluatex
    ifmtarg
    iftex
    ifthen
    ifvtex
    ifxetex
    infwarerr
    inputenc
    intcalc
    jabbrv
    keyval
    kvdefinekeys
    kvoptions
    kvsetkeys
    l3keys2e
    labelschanged
    letltxmacro
    libertinus
    libertinus-type1
    lineno
    longtable
    ltcaption
    ltxcmds
    makecell
    mathfixs
    mathtools
    mfirstuc
    mhsetup
    microtype
    mleftright
    moreverb
    multirow
    nag
    nameref
    natbib
    nowidow
    pdfcolmk
    pdfescape
    pdftexcmds
    pgf
    pgfcomp-version-0-65
    pgfcomp-version-1-18
    pgfcore
    pgffor
    pgfkeys
    pgfmath
    pgfrcs
    pgfsys
    placeins
    ragged2e
    refcount
    rerunfilecheck
    siunitx
    stfloats
    stix
    stringenc
    substr
    supertabular
    textcase
    textcomp
    tikz
    todonotes
    totpages
    tracklang
    translator
    trig
    trimspaces
    uniquecounter
    url
    verbatim
    wrapfig
    xcolor
    xfor
    xkeyval
    xparse
    xspace
    xstring
    xtemplate
    xurl
```

**Comment by lervag** [comment] 2020-03-29 07:18
I assume that the `my_special_research.tex` file also exists and is in the same directory as the minimal TeX file?

For me, things work well and your example does not give any errors.

**Comment by krishnakumarg1984** [comment] 2020-03-29 12:28
Ah no. It's in a folder called `my_special_research` (folder with same as the Tex file). I shall edit the minimal example to correctly reflect this.

**Comment by lervag** [comment] 2020-03-29 20:32
I still can't reproduce this. I now have the following:

```
> tree
.
├── minimal.tex
├── minimal.vim
└── my_special_research
    └── my_special_research.tex
```

```vim
" minimal.vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

let g:tex_flavor = 'latex'

let g:vimtex_view_automatic = 0

silent edit minimal.tex
```

Same `minimal.tex` file as you report, and an empty `my_special_research.tex` file. When I try to reproduce, I do `nvim -u minimal.vim`, navigate to the `\input` line and press `gf`. The `my_special_research.tex` file then opens as expected.

Could you try to remove cache files under `~/.cache/vimtex`?

**Comment by krishnakumarg1984** [comment] 2020-03-29 23:44
That is surprising. I am able to easily replicate this issue. i.e. `gf` does not work!

My `minimal.tex`, `minimal.vim` are exactly identical to yours except for the replacement to neovim path. Somehow, could that be the one making the difference?

```
" minimal.vim
set nocompatible
let &runtimepath  = '~/.local/share/nvim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.local/share/nvim/plugged/vimtex/after'
filetype plugin indent on
syntax enable

let g:tex_flavor = 'latex'

let g:vimtex_view_automatic = 0

silent edit minimal.tex
```

[Here](https://www.overleaf.com/read/ndnxnzwfpygd) is the link to my complete minimal project which includes the above files as well as  `my_special_research/my_special_research.tex`

**Comment by lervag** [comment] 2020-03-31 20:27
I agree, this is very strange. Does it fail for you with both Vim and neovim?

Does it work if you revert the bad commit? If so, would you be able to do some echo debugging on your side? I.e., comment out these lines:

https://github.com/lervag/vimtex/blob/3d548b1d032371e3affefd4a392b70965a320b69/autoload/vimtex/include.vim#L71-L73

If it works, then try something like this:

```vim
  unsilent echo l:file "\n"
  unsilent echo a:type "\n"
  if strpart(l:file, -3) !=# a:type
    let l:file .= '.' . a:type
  endif
```

This could help explain why things fail.

**Comment by krishnakumarg1984** [comment] 2020-04-01 19:48
@lervag  Yes, commenting out https://github.com/lervag/vimtex/blob/master/autoload/vimtex/include.vim#L71-73 works and solves the issue completely.

But your suggested fix below does not work.

```vim
  unsilent echo l:file "\n"
  unsilent echo a:type "\n"
  if strpart(l:file, -3) !=# a:type
    let l:file .= '.' . a:type
  endif
```

I still get the same error `E447: Cannot find file "input" in path`.

**Comment by lervag** [comment] 2020-04-01 19:54
> But your suggested fix below does not work.

It is not a fix, it is meant as a method of debugging. The idea was to get some more information that could help understand what is happening.

**Comment by lervag** [comment] 2020-04-01 19:55
Could we chat on [gitter](https://gitter.im/vimtex-chat/community)?

**Comment by krishnakumarg1984** [comment] 2020-04-01 19:57
Yes. Just joined the gitter chatroom.

**Comment by lervag** [comment] 2020-04-01 20:18
Sorry, I was away for some minutes and didn't notice the notification. I've responded in gitter, but now it seems you are away. Perhaps you did not see the notification as well? :p

**Comment by lervag** [comment] 2020-04-01 21:30
Ok, I think this is fixed now. Could you test?

**Closed** 2020-04-01 21:29 UTC
Labels: bug

**Comment by krishnakumarg1984** [comment] 2020-04-01 22:51
Yes. This works now. Thanks a lot for your incredible support.

**Comment by lervag** [comment] 2020-04-02 06:41
You're welcome :)
