### ISSUE TITLE
Text objects do not include beamer overlay specification

### ISSUE THREAD

**Issue by languitar** [lervag/vimtex#1206] opened 2018-09-03 11:06 UTC
The current definition of text objects for commands seems to lack support for the overlay specifications of beamer (angle brackets). With the cursor on `only`, `dac` does not work as expected in the following example:

```tex
\only<1>{
     test
}
```

It works (hypothetically) on this example:

```tex
\only{
     test
}
```

**Comment by lervag** [comment] 2018-09-22 21:46
Thanks! Sorry for taking so long, but I think this should be fixed now.

**Closed by lervag** 2018-09-22 21:46 UTC

**Comment by Aster89** [comment] 2018-09-23 11:10
I fear the later commit has introduced an unintended behavior which could annoy someone else, so please verify whether you can reproduce it or not.

Using the command `dsc` with the cursor on `\command{argument}` does the right job, but echoes a two line message which triggers the press-enter-to-continue prompt
```
start \command
{}
Press ENTER or type command to continue
```
This has the undesired effect of  moving the file view 2 lines up. Since `dsc` is a command that one can type lightningly fast while editing, having the view on the file move is really like hitting a transparent wall during a sprint race.

**Comment by clason** [comment] 2018-09-23 14:10
The same happens with `tse` and `cse`

**Comment by lervag** [comment] 2018-09-23 15:27
Sorry about that, fixed now!
