### ISSUE TITLE
Zathura doesn't open when called

### ISSUE THREAD

**Issue by liamd101** [lervag/vimtex#2391] opened 2022-05-14 14:54 UTC
### Description

I am trying to set up Zathura to view pdfs when working with Vimtex, but I cannot get it to work. When I run `:VimtexCompile` or `:VimtexView`, nothing seems to happen and I cannot figure out why. I am very new to this, so I apologize if I am missing something obvious.

### Steps to reproduce

minimal.vim
```
set nocompatible
let &runtimepath  = '~/.vim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
let g:vimtex_view_method = 'zathura'
```
minimal.tex
```
\documentclass{minimal}

\begin{document}
Hello world!
\end{document}
```

1. vim -u minimal.vim minimal.tex
2. Compile with `\ll` or `:VimtexCompile`
3. Get VimtexInfo
4. `\lv` or `:VimtexView`

### Expected behavior

Zathura to open up with a pdf preview of the document.

### Actual behavior

Nothing happens.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 12.3.1 (21E258)
  Vim version: VIM 8.2 (1-3455)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: minimal
  base: minimal.tex
  root: /Users/liamdodds
  tex: /Users/liamdodds/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: process 5030 run
      output: /var/folders/kc/pj12l0192gg4ljyhsk5y9w1h0000gn/T/v0Fason/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ;
      pid: 5030
  viewer: Zathura
    xwin id: Failed creating new xdo instance.
    cmd_start: zathura  -x "/usr/local/Cellar/macvim/8.2-172_1/MacVim.app/Contents/MacOS/Vim -T dumb --not-a-term -n -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward
  qf method: LaTeX logfile
```
```

**Comment by lervag** [comment] 2022-05-14 16:49
Did you read `:help vimtex-faq-zathura-macos`?

**Comment by liamd101** [comment] 2022-05-14 17:25
Yes, I followed those directions when installing initially. I am/was following [this](https://ejmastnak.github.io/tutorials/vim-latex/pdf-reader.html#setting-up-zathura-on-macos) guide to set everything up, and I don't think I missed any steps.

**Comment by lervag** [comment] 2022-05-14 17:31
Great. Have you tested that Zathura works when you start it from the terminal?

Next, if it works: Can you repeat your initial test steps until `\lv`. Then do `\li` to see VimtexInfo. Copy the `cmd_start` from the viewer and see what happens if you run that from a terminal.

**Comment by liamd101** [comment] 2022-05-14 17:40
When I run it from my terminal, a Zathura black window opens up with the title "org.pwmt.zathura" with text saying "[No name]" in the bottom of the window.

Copying my `cmd_start` into a terminal outputs

```
Liams-MBP:~ liamdodds$ zathura  -x "/usr/local/Cellar/macvim/8.2-172_1/MacVim.app/Contents/MacOS/Vim -T dumb --not-a-term -n -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 1:1:'minimal.tex' 'minimal.pdf'&
[1] 5521
Liams-MBP:~ liamdodds$ error: Could not connect to session bus: Cannot autolaunch D-Bus without X11 $DISPLAY
error: Got no usable data from SyncTeX or D-Bus failed in some way.

[1]+  Exit 255                zathura -x "/usr/local/Cellar/macvim/8.2-172_1/MacVim.app/Contents/MacOS/Vim -T dumb --not-a-term -n -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 1:1:'minimal.tex' 'minimal.pdf'
Liams-MBP:~ liamdodds$ 
```

**Comment by lervag** [comment] 2022-05-14 20:29
So, for some reason, there's a problem with dbus (the man topic of the faq section). I don't use MacOS and can't be of much help. Sorry. There have been several related issues, perhaps you can find some hints in one of them?

**Comment by ejmastnak** [comment] 2022-05-15 02:34
Hey @liamd101! Sorry you are having trouble even though you followed the guide's instructions. Working with Linux programs like Zathura on macOS can be very finicky, so I'm not surprised dbus and Zathura are causing problems.

I just tried updating to your version of macOS (12.3.1) and can confirm Zathura is working properly on my machine, which makes me think---at least on principle---we can get it to work for you too. 

Can you check the output of `brew info zathura`, `brew info dbus`, and `brew services info dbus` and paste them here? I want to make sure we have the same versions.

Here is what I get on my end (some irrelevant parts omitted):
```
$ brew info zathura
zegervdv/zathura/zathura: stable 0.4.8, HEAD
https://pwmt.org/projects/zathura/
/usr/local/Cellar/zathura/HEAD-87989da (51 files, 749.1KB) *
  Built from source on 2022-03-14 at 18:38:42 with: --with-synctex
From: https://github.com/zegervdv/homebrew-zathura/blob/HEAD/zathura.rb
==> Dependencies
Required: pkg-config ✔, libmagic ✔, gettext ✔, girara ✔, gnome-icon-theme ✔, glib ✔, desktop-file-utils ✔, intltool ✔, sphinx-doc ✔, meson ✔, gtk-mac-integration ✔
Optional: synctex ✔
==> Options
--with-synctex
        Build with synctex support
--HEAD
        Install HEAD version
```

```
$ brew info dbus
dbus: stable 1.14.0 (bottled), HEAD
Message bus system, providing inter-application communication
https://wiki.freedesktop.org/www/Software/dbus
/usr/local/Cellar/dbus/1.14.0 (77 files, 2.5MB) *
  Poured from bottle on 2022-03-14 at 18:17:51
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/dbus.rb
License: AFL-2.1 or GPL-2.0-or-later
==> Dependencies
Build: pkg-config ✔, xmlto ✘
==> Options
--HEAD
        Install HEAD version
```

```
$ brew services info dbus
dbus (org.freedesktop.dbus-session)
Running: ✔
Loaded: ✔
Schedulable: ✘
```
Note that I am no macOS expert---I use Linux on my main machine---so I can't guarantee a solution. But I'll do what I can to help; I definitely don't want to have a tutorial that is misleading users/doesn't work, especially since new VimTeX users might be reading it.

On that note, @lervag, I think I might add a sort of "Caveat: your mileage may vary warning, use at your own risk" warning to the macOS/Zathura section of the guide, since I don't daily-drive macOS, Apple has been known to break things unexpectedly, and there are so many moving parts with getting dbus playing nicely with Zathura and VimTeX on mac. What do you think?

**Comment by lervag** [comment] 2022-05-15 16:50
Thanks for pitching int, @ejmastnak! For your question: I agree, but let's wait until we've (hopefully) resolved this issue first. It may bring more useful information on the table that can be relevant for an update to the docs.

**Comment by TornaxO7** [comment] 2022-05-15 16:55
Interestingly `sioyek` doesn't work "anymore" as well.

```vim
let g:vimtex_view_method = 'sioyek'
```
I have this line in my config. It used to work but it didn't work anymore for some days (or even weeks) now.
`zathura` is working instead interestingly.

**Comment by lervag** [comment] 2022-05-15 17:01
Sorry, @TornaxO7, but now you are being very off topic. Please open a new issue if something is not working as expected, and please, provide the relevant and necessary details when you do.

**Comment by TornaxO7** [comment] 2022-05-15 17:05
> Sorry, @TornaxO7, but now you are being very off topic.

oh sorry, I thought that this might suit here

**Comment by lervag** [comment] 2022-05-15 20:52
I hope I did not come off too aggressive. I just didn't understand how your obvservation was relevant to this thread. The topic is Zathura; MacOS; D-Bus. Why is Sioyek relevant? And why is it relevant that Zathura works for you? (It works for me as well; and last I tried, Sioyek worked for me.)

**Comment by liamd101** [comment] 2022-05-16 01:43
> Can you check the output of brew info zathura, brew info dbus, and brew services info dbus and paste them here? I want to make sure we have the same versions.

Here are the outputs:
```
Liams-MBP:~ liamdodds$ brew info zathura
zegervdv/zathura/zathura: stable 0.4.8, HEAD
https://pwmt.org/projects/zathura/
/usr/local/Cellar/zathura/HEAD-72f3ce1 (51 files, 625.4KB) *
  Built from source on 2022-05-14 at 09:54:09 with: --with-synctex
From: https://github.com/zegervdv/homebrew-zathura/blob/HEAD/zathura.rb
==> Dependencies
Required: pkg-config ✔, libmagic ✔, gettext ✔, girara ✔, gnome-icon-theme ✔, glib ✔, desktop-file-utils ✔, intltool ✔, sphinx-doc ✔, meson ✔, gtk-mac-integration ✔
Optional: synctex ✔
==> Options
--with-synctex
	Build with synctex support
--HEAD
	Install HEAD version
```

```
Liams-MBP:~ liamdodds$ brew info dbus
dbus: stable 1.14.0 (bottled), HEAD
Message bus system, providing inter-application communication
https://wiki.freedesktop.org/www/Software/dbus
/usr/local/Cellar/dbus/1.14.0 (77 files, 2.5MB) *
  Poured from bottle on 2022-05-14 at 09:42:56
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/dbus.rb
License: AFL-2.1 or GPL-2.0-or-later
==> Dependencies
Build: pkg-config ✔, xmlto ✘
==> Options
--HEAD
	Install HEAD version
==> Caveats
To start dbus now and restart at login:
  brew services start dbus
==> Analytics
install: 31,103 (30 days), 130,003 (90 days), 319,854 (365 days)
install-on-request: 975 (30 days), 4,945 (90 days), 10,885 (365 days)
build-error: 5 (30 days)
```
```
Liams-MBP:~ liamdodds$ brew services info dbus
dbus (org.freedesktop.dbus-session)
Running: ✘
Loaded: ✔
Schedulable: ✘
```
The only differences I notices in our two outputs were the "Running" line and the caveat in dbus. Since I was actually given steps/prompt for the caveat, I started with that.

I ran `brew services start dbus`, and the output was this:
```
Bootstrap failed: 5: Input/output error
Try re-running the command as root for richer errors.
Error: Failure while executing; `/bin/launchctl bootstrap gui/501/Users/liamdodds/Library/LaunchAgents/org.freedesktop.dbus-session.plist` exited with 5.
```

So I ran `sudo brew services start dbus`, which gave me 
```
Warning: Taking root:admin ownership of some dbus paths:
  /usr/local/Cellar/dbus/1.14.0/bin
  /usr/local/Cellar/dbus/1.14.0/bin/dbus-daemon
  /usr/local/opt/dbus
  /usr/local/opt/dbus/bin
  /usr/local/var/homebrew/linked/dbus
This will require manual removal of these paths using `sudo rm` on
brew upgrade/reinstall/uninstall.
Warning: dbus must be run as non-root to start at user login!
/Library/LaunchDaemons/org.freedesktop.dbus-session.plist: service already bootstrapped
Bootstrap failed: 37: Operation already in progress
Error: Failure while executing; `/bin/launchctl bootstrap system /Library/LaunchDaemons/org.freedesktop.dbus-session.plist` exited with 37.
```
I am assuming that I should just run `sudo rm /usr/local/Cellar/dbus/1.14.0/bin`, etc for those, but I don't want to accidentally remove something I shouldn't have.

**Comment by liamd101** [comment] 2022-05-16 13:36
`echo $DBUS_SESSION_BUS_ADDRESS` has no output.

And `grep "<auth>" /usr/local/opt/dbus/share/dbus-1/session.conf`:
```
Liams-MBP:~ liamdodds$ grep "<auth>" /usr/local/opt/dbus/share/dbus-1/session.conf
  comment out the <auth> element to allow fallback to DBUS_COOKIE_SHA1. -->
  <auth>DBUS_COOKIE_SHA1</auth>
```

**Comment by ejmastnak** [comment] 2022-05-16 13:58
> And grep "<auth>" /usr/local/opt/dbus/share/dbus-1/session.conf:

This looks good! Clearly you've followed `:help vimtex-faq-zathura-macos`, since you're using `DBUS_COOKIE_SHA1`.

> `echo $DBUS_SESSION_BUS_ADDRESS` has no output.

Interesting, perhaps this is the problem. How are you currently going about setting this environment variable? 

Perhaps relevant: are you using `zsh` or `bash` (or something else) as your shell?

I'm realizing now that I had only tested the guide on macOS when running `bash`, in which case I had set `export DBUS_SESSION_BUS_ADDRESS="unix:path=$DBUS_LAUNCHD_SESSION_BUS_SOCKET"` in my `.bashrc`, which I in turn had sourced from my `.bash_profile`. Let me play around a bit and get back to you.

**Comment by m-zheng** [comment] 2022-05-16 14:04
> 

This [link](https://github.com/zegervdv/homebrew-zathura/issues/50#issuecomment-622484861) might be helpful.

**Comment by liamd101** [comment] 2022-05-16 17:50
> How are you currently going about setting this environment variable?

Sorry, but I don't fully understand. Like I said before, I'm still very new to all of this. I am currently using `bash` as my shell, but when I open a terminal it says

```
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
```
Manually setting `export DBUS_SESSION_BUS_ADDRESS="unix:path=$DBUS_LAUNCHD_SESSION_BUS_SOCKET"` got it to work in the same shell session. I checked my .bashrc file though and I had that line already in there, so I don't know why it didn't work. I may have just formatted it improperly.

**Comment by ejmastnak** [comment] 2022-05-16 18:34
> Manually setting export DBUS_SESSION_BUS_ADDRESS="unix:path=$DBUS_LAUNCHD_SESSION_BUS_SOCKET" got Zathura to work in the same shell session.

Excellent, I promise we are almost at a solution now. 

No worries about being to the shell stuff. And you're right---there are quite a few concepts to wrap your head around here.

First let me give you a TLDR solution:

- Double check you are using Bash by running `echo $0` in a terminal---this is a nifty command to print your current shell. I'll assume you are indeed using Bash.
- If it does not already exist, create the file `.bash_profile` in your home directory. You can create this file manually, e.g. `vim ~/.bash_profile` (the `~` character is shorthand for your home directory)
- Inside the `.bash_profile` file, write the same command you've been using so far: 

   ```sh
   export DBUS_SESSION_BUS_ADDRESS="unix:path=$DBUS_LAUNCHD_SESSION_BUS_SOCKET"
   ```
  Bash will then run this command automatically for you, and you won't need to type it manually like you did above. Placing this `export` statement in one of your shell's startup files is what I meant when I was asking about setting environment variables earlier---`DBUS_SESSION_BUS_ADDRESS` is an environment variable, and, loosely, you are "setting" it with the `export` statement.
   Save the file and exit Vim.

- Open a new terminal, run `exec bash -l` (which ensures Bash will run as a login shell and read the `.bash_profile` file) and check the output of `echo DBUS_SESSION_BUS_ADDRESS`, which should no longer be blank.
- Try reproducing the original issue. Zathura should now open without you having to manually run the `export` command.

**Comment by liamd101** [comment] 2022-05-16 20:34
That worked! Thanks so much for your help and your guide!

As for the details, they are both helpful and overwhelming haha

**Comment by ejmastnak** [comment] 2022-05-17 07:56
> That worked! Thanks so much for your help and your guide!

Great, glad to here! In that case you can probably close the issue. 

And I'll add a few more lines to the guide about making sure the `DBUS_SESSION_BUS_ADDRESS` environment variable is properly set.

**Comment by lervag** [comment] 2022-05-17 11:11
Thanks, @ejmastnak! You could do a PR, or just suggest a change here and I'll add it.

**Closed** 2022-05-17 11:11 UTC
Labels: bug

**Comment by ejmastnak** [comment] 2022-05-17 15:52
> Thanks, @ejmastnak! You could do a PR, or just suggest a change here and I'll add it.

Aha, I meant I would add a few more lines to the guide on my website. I think `:help vimtex-faq-zathura-macos` looks good as is, but I suppose it wouldn't hurt to stress the importance of setting `DBUS_SESSION_BUS_ADDRESS` in step two, e.g.

```diff
2. Add this to your `.bashrc` or `.zshrc` file (or similar):
export DBUS_SESSION_BUS_ADDRESS="unix:path=$DBUS_LAUNCHD_SESSION_BUS_SOCKET"
+ The `DBUS_SESSION_BUS_ADDRESS` environment variable must be set for Zathura to work with VimTeX; see [2] for details.

[0]: https://github.com/lervag/vimtex/issues/1737#issuecomment-759953886
[1]: https://brew.sh
+ [2]: https://github.com/lervag/vimtex/issues/2391

```

**Comment by lervag** [comment] 2022-05-17 19:52
Thanks!

**Comment by TornaxO7** [comment] 2022-05-17 20:34
Sorry for the late reply @lervag !

> I hope I did not come off too aggressive.

Don't worry, nothing happened :)

> I just didn't understand how your obvservation was relevant to this thread. The topic is Zathura; MacOS; D-Bus. Why is Sioyek relevant? And why is it relevant that Zathura works for you?

I can understand your points. I thought that my current issue with sioyek might
be related with zathura, that's why I wrote this message.

**Comment by lervag** [comment] 2022-05-17 21:40
Great, and no problem. I'm happy that you chose to act with those good intentions, and I hope I did not scare you from doing the same in the future. :)

**Comment by TornaxO7** [comment] 2022-05-17 21:41
Hihi, don't worry c(^-^)c

**Comment by ucasyfp** [comment] 2022-06-15 12:48
I have a very similar problem with OP, but instructions above cannot fix mine. I followed vimtex-help to set up zathura and dbus. I have added `export` statement to bashrc,bash_profile,zshrc,zsh_profile.  Echo in terminal shows that environment variable have been set up correctly, and output for `grep "<auth>" /usr/local/opt/dbus/share/dbus-1/session.conf` is also correct, still dbus is not running.  And the error message for `brew services start dbus` and `sudo brew services start dbus` are just the same as OP's. 

I use neovim and zsh, with iterm2. Do you guys have any clues?

**Comment by ejmastnak** [comment] 2022-06-15 15:49
Hey @ucasyfp, I'm not immediately sure how to solve your issue. It would probably be a good idea to open a separate issue with your system information and complete steps to reproduce your issue.

I would start by uninstalling and re-installing the relevant software: run `brew unlink` and then `brew uninstall` for each of the following Homebrew packages: 
- `dbus`, 
- `zathura-pdf-poppler` (or `zathura-pdf-mupdf` if you use that instead of `zathura-pdf-poppler`),
-  `zathura` 
- and `girara`. 

Then, once you have a clean slate, try exactly repeating the steps in  `:help vimtex-faq-zathura-macos`.

**Comment by lervag** [comment] 2022-06-16 06:49
@ucasyfp Unless the tips from @ejmastnak works, please open a new issue with a full description.
