### ISSUE TITLE
Support `\RequirePackage` completion

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#1172] opened 2018-07-22 20:48 UTC
Quote from #1166:

> Although I did notice that the package completion doesn't trigger on `\RequirePackage{`?

This should be fixed and must be fixed both in the `g:vimtex#re#...` and in the completer code.

**Comment by clason** [comment] 2018-07-23 20:08
While you're at it, could you change the first `#cmds` regex from `'\\[A-Za-z]*'` to `'\\[A-Za-z]+'` as discussed? (It's not worth it to open a pull request for this since I can't easily sync your upstream repo with my fork for some reason.) 

And thanks for merging that PR!

**Comment by lervag** [comment] 2018-07-24 10:32
Strange. But you could always just delete your fork completely and fork again?

And yes, I'll make the requested change! Probably later today.

**Comment by clason** [comment] 2018-07-24 10:43
I think the issue is that you didn't actually merge my pull request but (if I understand correctly) directly merged the branch on your own, so git doesn't recognize my commits as identical. I could delete and refork, but that seemed overkill for a one-character change ;))

**Closed** 2018-07-25 21:22 UTC
