### ISSUE TITLE
vimtex does not compile in Windows 8

### ISSUE THREAD

**Issue by IbnSaeed** [lervag/vimtex#153] opened 2015-04-14 07:46 UTC
Hello

I have perl installed with Starberryperl and i also have TexLive 2014 which comes with latexmk.

When i do :VimtexCompile it shows
```latexmk compile: started continuous mode```

But in the output directory, nothing gets output, no pdf or auxiliary files etc.

But when i run ```latexmk.exe -pvc``` in windows command prompt, it succesfully compiles the same latex file and produces the pdf with continuous mode

I tried the same file in TexStudio and it compiles there as well.

but vimtex does not output at errors at all, so i dont know what issues it is facing. Vimtex is the only plugin i am using in vim to work with latex. 

Here is my .vimrc code for vimtex
```
" =======================================
" vimtex {
" =======================================

" Set default tex file format to latex
let g:tex_flavor = "latex"

let g:vimtex_enabled = 1
let g:vimtex_view_enabled = 1
let g:vimtex_fold_enabled = 0
let g:vimtex_fold_preamble = 0
let g:vimtex_indent_enabled = 1
let g:vimtex_view_method = 'sumatrapdf'
let g:vimtex_latexmk_continuous = 1
let g:vimtex_latexmk_options ='xelatex -shell-escape -synctex=1 -src-specials -interaction=nonstopmode $*'

let g:vimtex_view_sumatrapdf_viewer = 'SumatraPDF -reuse-instance -inverse-search -a +\%l \%f\""'

" }
```

and here are the contents of ~/.latexmkrc

```
$pdf_mode = 1;
$pdflatex = "xelatex --shell-escape -src-specials -synctex=1 -interaction=nonstopmode %O %S";
$recorder = 1;
$pdf_previewer = "SumatraPDF -reuse-instance -inverse-search -a %O %S";
```

**Comment by lervag** [comment] 2015-04-14 07:55
Minor comments to your `vimrc`:
1. No need for `...fold_preamble` when folding is disabled.
2. Continuous mode is default.
3. `...general_viewer` option is only relevant when `view_method = 'general'`.

To get some output to help debug this issue, could you please give me the output after you press
1. `<leader>li` (should give some basic info of variables set for vimtex)
2. After you've tried to started compilation, press `<leader>lo` (should show the `latexmk` output, useful for debugging)

I suspect the problem is due to your latexmk options. Could you try without them (also inspect the output with `<leader>lo`)? You could also try to set the options through a `.latexmkrc` file (not sure what this file is on Windows, but I guess it should be easy to find out through the latexmk manual).

**Comment by IbnSaeed** [comment] 2015-04-14 08:09
i tried <leader>li, its not responding. It just goes into Insert mode

So i tried :VimtexInfo
ill post the results here.

**Comment by lervag** [comment] 2015-04-14 08:11
FYI: `<leader>` is also a key, usually `\`, thus `<leader>li` is typically `\li`.

**Comment by IbnSaeed** [comment] 2015-04-14 08:12
Yes, my leader key is Spacebar. I know about that.

**Comment by lervag** [comment] 2015-04-14 08:13
Ah. Then I should probably have been more specific. The mappings all use `<localleader>`, so perhaps `<localleader>` is something else?

**Comment by IbnSaeed** [comment] 2015-04-14 08:14
Your suggestion of using ```\``` worked, my global leader is different. Anyway, the output is show above for the ```\li``` command

**Comment by IbnSaeed** [comment] 2015-04-14 08:14
Here are the results of ```\li```

```
ill post the results here.

b:vimtex
  id: 0

g:vimtex#data[0] : book
  pid : 0
  out : ' '
  aux : ' '
  log : ' '
  root : 'C:\latex_project'
  text : 'C:\latex_project\book.tex'
  base : 'book.tex'
  viewer 
    init : function('159')
    view : function('160')
```
This is all what the buffer line shows.

**Comment by IbnSaeed** [comment] 2015-04-14 08:16
I see that when i run the latexmk command in my commadn prompt, it uses the settings defined in my .latexmkrc file

```
and here are the contents of ~/.latexmkrc

$pdf_mode = 1;
$pdflatex = "xelatex --shell-escape -src-specials -synctex=1 -interaction=nonstopmode %O %S";
$recorder = 1;
$pdf_previewer = "SumatraPDF -reuse-instance -inverse-search -a %O %S";
```

And these work in command prompt.

**Comment by lervag** [comment] 2015-04-14 08:17
Great, that looks fine.

When you start compilation from vim, either with `VimtexCompile` or with `\ll`, then the output of the `latexmk` command is redirected to a temporary file that should be viewable by pressing `\lo` (or `VimtexCompileOutput`. Could you provide this output as well?

**Comment by lervag** [comment] 2015-04-14 08:20
Also, FYI: vimtex allows the usage of a user `.latexmkrc` file, which that the options you've defined and displayed above should be respected. Thus you don't need to have
```vimL
let g:vimtex_latexmk_options ='xelatex -shell-escape -synctex=1 -src-specials -interaction=nonstopmode $*'
```
in your vimrc file.

**Comment by IbnSaeed** [comment] 2015-04-14 09:31
i did ```\ll``` and then i did ```lo``` , it opened a totally empty tmp buffer. it has not contents in it.

By that time, i read you last message, so i removed the ```let g:vimtex_latexmk_options ='xelatex -shell-escape -synctex=1 -src-specials -interaction=nonstopmode $*'``` line from my .vimrc.

I tried the ```\ll and \lo ``` again, and this time it worked. i really dont know why it worked. Since in the initial install of vimtex, i had not added the following line to .vimrc
```let g:vimtex_latexmk_options ='xelatex -shell-escape -synctex=1 -src-specials -interaction=nonstopmode $*'````

One thing is that i was also adding a few packages via TeX live Manager. Maybe, some update worked.

But now the file compiles successfully and the sumatrapdf is opened and i can edit the latex file and upon saving the final result is shown in the opened pdf file.

Though the speed at which the file shows the changes is a bit slow compared to the previous vim plugin i was using ```vim-latex-live-preview```. The issue with this plugin was that it did not create a final pdf, it only showed live preview of the changes and did not output any file. 

So in this regard, vimtex so far is the best plugin for laTeX right now. 

Is there a way to speed up the live update preview of the pdf file ?

**Comment by lahwaacz** [comment] 2015-04-14 09:52
The reason why your `g:vimtex_latexmk_options` did not work is probably because it did not contain the `-pdflatex` argument, only its value.

latexmk runs pdflatex multiple times to solve the problems with bibliography, toc etc. but in my experience it runs it multiple times _always_, not only when necessary. Obviously this has bad impact on performance, but it's latexmk's issue.

**Comment by IbnSaeed** [comment] 2015-04-14 10:00
But i am using xelatex to compile to pdf unless latex is using pdflatex in the background

**Comment by lahwaacz** [comment] 2015-04-14 10:14
Then I think it runs `xelatex` multiple times...

**Comment by lervag** [comment] 2015-04-14 10:33
Thanks for your input, @lahwaacz!

@IbnSaeed To clarify, the option `g:vimtex_latexmk_options` is passed directly to `latexmk`. So you should rather have used something like the following:
```vimL
let g:vimtex_latexmk_options ='-pdflatex="xelatex -shell-escape -synctex=1 -src-specials -interaction=nonstopmode $*"'
```
Note that I did not test the above, so there is probably some escaping issue. However, since you already specify this in your `.latexmkrc` file, it is not necessary to add it to your `vimrc` file. And in that regard I'm glad to hear that the problem is solved.

Regarding the speed, I think @lahwaacz is right that it is slow much because `latexmk` is very conservative and insists on compiling several times. This is particularly noticable on large documents. However, it does also mean that the document is (almost) always properly compiled. Personally I'm fine with this, although I would also be happy if we could find a way to speed things up! If you have any ideas, please feel free to open a new issue or pull request.

Note also that `vim-latex-live-preview` uses an autocommand to compile the document "in real time", that is, whenever you leave insert mode (or something like that). `vimtex` through `latexmk` only compiles after each write to file.

Also thanks for your kind words about the plugin! :)

PS! I'm closing this, as it seems to resolved.

**Closed by lervag** 2015-04-14 10:33 UTC
