### ISSUE TITLE
\begin{document} and \end{document} have inconsistent highlighting

### ISSUE THREAD

**Issue by Krasjet** [lervag/vimtex#1466] opened 2019-08-28 00:49 UTC
**Issue**
The highlighting of `\begin{document}` and `\end{document}` appears to be different from other `begin`, `end` environments.
![pic-selected-190827-2044-07](https://user-images.githubusercontent.com/5229241/63817758-c5b04e80-c90b-11e9-8cd0-0ee8645ca342.png)

**minimal.tex**
  ```tex
\documentclass[12pt]{article}
\usepackage{amsmath}

\begin{document}
\begin{align*}
    \sigma_{\vec{u}} = \sqrt{\sum_{i=1}^N (u_i - \mu_u)^2}
\end{align*}
\end{document}
  ```

**Expected Behaviour**
The highlighting should be consistent with other `begin` and `end` environments.

**Comment by clason** [comment] 2019-08-28 07:14
I think this is related to the fact that `\begin{document}` does not trigger an indent (which I assume is by design in order to avoid extraneous indentation levels) and does not get selected for, e.g., `dae` (also by design)?

So, `document` is not a standard environment. (Although I agree that the different highlight for the `\begin`...`\end` pair (the commands, not the environment) is a bit weird.)

**Comment by lervag** [comment] 2019-08-28 08:30
@clason It is actually unrelated, since the syntax highlighting is a separate beast. And in fact, highlighting of the `\begin{document} ... \end{document}` pair is not done by vimtex, but by the internal syntax plugin.

I could override and add an improved rule for this, but I wonder: Is it necessary? I personally find it OK to easily distinguish these boundaries from other environments.

**Comment by clason** [comment] 2019-08-28 09:03
@lervag Not technically, but spiritually: You don't consider these as "normal" equations, so you didn't implement any of the usual properties :)

I don't have a strong opinion on this; the weird highlight for the `\begin`...`\end` pair is purely cosmetic, but I have on one or two occasions tried to use standard mappings on the `document` environment (`vie`, `%`) before I remembered they don't work here.

**Comment by lervag** [comment] 2019-08-28 09:06
> Not technically, but spiritually

Ok, agreed :)

> but I have on one or two occasions tried to use standard mappings on the document environment (vie, %) before I remembered they don't work here.

I don't have any strong feelings here either, except I think that ignoring them make some sense, since it is very rare that one wants to operate on them. Including these would make it easier to make mistakes. At least, that's what I've hypothesized.

**Comment by clason** [comment] 2019-08-28 09:13
> Including these would make it easier to make mistakes. At least, that's what I've hypothesized.

That's what I had assumed. (Although mistakes are usually easily fixed with an `u`, and I make more than enough mistakes with normal environments...)

Let's see if other people feel strongly about this?

**Comment by lervag** [comment] 2019-08-28 15:35
> Let's see if other people feel strongly about this?

Agreed. My 0-hypothesis is that the current implementation is OK. Anyone who disagrees: Convince me otherwise. I'll be happy to implement a change if I'm convinced.

**Closed as completed** 2019-09-12 12:38 UTC
Labels: bug
