### ISSUE TITLE
label completion and supertab

### ISSUE THREAD

**Issue by nilsbecker** [lervag/vimtex#324] opened 2016-01-12 18:29 UTC
i am using supertab, and label completion seems to work, e.g. on `\ref{fig:` i press `<tab>` and get a list of options. however, i then tried also the method in the docs, `<c-x><c-o>`, and this did not only not work but then also prevented the `<tab>` method from working until vim was restarted. is this expected?

**Comment by lervag** [comment] 2016-01-12 20:57
No, this is not expected. Could you create a minimal working example (including a minimal vimrc file)? I've added a template [here](https://github.com/lervag/vimtex/tree/master/test/template).

**Comment by nilsbecker** [comment] 2016-01-13 15:07
ok, in this file :+1: 
```
\documentclass{minimal}
\begin{document}

\begin{equation}
	\label{eq:eq}
	x = y
\end{equation}

Hello World, behold eq.~\ref{eq:

\end{document}
```
i see the same behavior. relevant sections from by `.vimrc`:

```
" SuperTab and completion
"
" complete options
set completeopt=menu,preview
" this tries omnifunc first if defined and then the default
au FileType *
			\ if &omnifunc != '' |
			\   call SuperTabChain(&omnifunc, "<c-p>") |
			\   call SuperTabSetDefaultCompletionType("<c-x><c-u>") |
			\ endif
```
this uses some chaining functionality, i think i got it from the supertab docs.

i have no other completion plugin.

**Comment by lervag** [comment] 2016-01-14 21:28
As you can see i've added test files according to the info you've supplied. I first make sure to compile the LaTeX example once to get the `aux` file (which is necessary for label completion). The I go to `vimtex/test/issue/324`, do `gvim -u vimrc minimal.tex`, and when I try to complete the reference it works as expected both with `<c-x><c-o>` and with `<tab>`.

**Comment by nilsbecker** [comment] 2016-01-14 21:30
hmm. will try it with the  minimal .vimrc to see if if i can reproduce it. until now i used my own .vimrc...

**Comment by nilsbecker** [comment] 2016-02-05 15:51
ok, i finally got around to  trying it using you minimal `vimrc` and `minimal.tex`. 

the behavior is the same: using `<tab>` to complete, i get a bunch of completion options but those are actually generic completions. the existing label is also offered and happens to be the default choice. i don't know if this is by accident. then, when typing `<c-x><c-o>`, i get the message `Omni completion (^O^N^P) Pattern not found`. After that, if i try the `<tab>` method again, is now always get that same message.

**Comment by nilsbecker** [comment] 2016-02-05 16:11
i found this in the supertab documentation. relevant?
```
Note: If the |completefunc| or |omnifunc| use vim's |complete_add()| instead
of returning completion results as a list, then Supertab's completion chaining
won't work properly with it since Supertab uses the function result to
determine if it should fallback to the next completion type.
```

**Comment by nilsbecker** [comment] 2016-02-05 16:54
it gets weirder. i removed any reference to supertab. so i now have the file vimrc like so:
```
set nocompatible
filetype plugin indent on
syntax enable

set completeopt=menu,preview

let &rtp = '~/.vim/bundle/vimtex,' . &rtp
let &rtp = '~/.vim/bundle/vimtex/after,' . &rtp
```

and minimal.tex like above. I compile once with the correct label inserted in the `\ref{eq:eq}` which produces correct output. so the .aux file should be there. i then edit back to `\ref{eq:` and press `<c-x><c-o>`.  `Pattern not found`!

it appears the problem is with the basic omnifunc?!?

**Comment by nilsbecker** [comment] 2016-02-05 17:27
ok, confirmed after uninstalling supertab. basically, omnicompletion does not seem to work at all.

**Comment by lervag** [comment] 2016-02-06 19:42
Strange. I still can't reproduce. The `aux` file has the following content:

```tex
\relax 
\newlabel{eq:eq}{{1}{1}}
```

I use the same `tex` file and `vimrc` as you specified above, and I open with `gvim -u vimrc minimal.tex`. My vim version is 7.4.1190.

**Comment by nilsbecker** [comment] 2016-02-07 18:39
ok, i tried again on another mac. vim 7.4.1265. here everything works. something seems to be wrong with vim installation on the first mac. will try to fix.

**Comment by lervag** [comment] 2016-02-07 20:03
I'll take the liberty and close this issue as well. Feel free to reopen if there is anything you can pinpoint on the vimtex side.

**Closed by lervag** 2016-02-07 20:03 UTC
Labels: non-reproducible

**Comment by nasenatmer** [comment] 2016-02-09 11:03
FWIW, I am not using any 3rd party completion engine at all, just basic `c-x c-o` omnicompletion by vim (mapped to `F4`) and it works without problems using your minimal example, as well as all my other projects where I complete bibtex entries, and references on a daily basis. So really seems a problem with supertab integration or a local issue…

**Comment by nilsbecker** [comment] 2016-02-09 11:08
yes, it was a misconfiguration of latexbox which somehow prevented the completion from working as well. it's fixed for me now.
