### ISSUE TITLE
Async Compilation

### ISSUE THREAD

**Issue by mm-crj** [lervag/vimtex#2806] opened 2023-10-06 09:54 UTC
Firstly, thank you for writing and maintaining such a wonderful plugin. I have been using it as my daily latex driver for my thesis and papers for the past 1.5 years. Now I can't even think of going back to TeXstudio. :)

**Is your feature request related to a problem? Please describe it.**

So while compiling large documents (80-100 pages) with large bibliographies, the compilation time is significant. I can't move my cursor while it is being compiled.  It's not a problem of Vimtex per se, latexmk and specially BibTeX takes a while to compile. 

**Describe the solution you'd like**

But now I think there is async feature in nvim I think, so I would like to compile documents in async mode. So I can keep editing the document while the document is being compiled. 

**Describe alternatives you've considered**

An alternative would be to write an async compiler myself like [ejmastnak](https://www.ejmastnak.com/tutorials/vim-latex/compilation/#compiler) using [neovim jobs()](https://neovim.io/doc/user/job_control.html). However, as ejmastnak points out it is not just writing the compilation commands, it is also writing how to look at the error logs and stuff.  

**Additional context**

Profile of the compilation.

|count|total (s)|self (s) |function                           |
|-----|---------|---------|-----------------------------------|
|492  |10.684024|10.671074|238()                              |
|552  |10.815105|0.220289 |240()                              |
|2    |11.017224|0.109345 |236()                              |
|4    |0.054093 |0.053453 |vimtex#qf#u#caddfile()             |
|2    |11.096464|0.016666 |vimtex#qf#setqflist()              |
|1    |0.016022 |0.015661 |18()                               |
|492  |0.01295  |0.012828 |237()                              |
|1    |0.009988 |0.009626 |68()                               |
|2    |0.009046 |0.007698 |vimtex#debug#stacktrace()          |
|1    |0.027834 |0.006666 |vimtex#compiler#start()            |
|2    |0.007367 |0.002678 |85()                               |
|60   |0.00374  |0.002565 |<SNR>92_fix_paths_hbox_warning()   |
|64   |0.091395 |0.002187 |241()                              |
|2    |         |0.00141  |<SNR>91_qf_has_errors()            |
|10   |         |0.001348 |vimtex#util#command()              |
|88   |         |0.001166 |vimtex#util#count()                |
|1    |0.001312 |0.001105 |<SNR>144_register_packages()       |
|2    |0.010551 |0.000977 |210()                              |
|64   |         |0.000956 |242()                              |
|58   |         |0.000949 |<SNR>92_fix_paths_invalid_bufname()|

```
FUNCTION  240()
    Defined: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/qf/bibtex.vim:127
Called 552 times
FUNCTION  238()
    Defined: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/qf/bibtex.vim:93
Called 492 times
FUNCTION  236()
    Defined: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/qf/bibtex.vim:50
Called 2 times
```

**Comment by mm-crj** [comment] 2023-10-06 12:33
Never mind, I had copied a bunch of text from a recent paper and there were many broken references, this made the latexmk call up bibtex many times to fix or write error messages. Nevertheless This would be a great feature to have.

**Comment by ejmastnak** [comment] 2023-10-06 13:26
@mm-crj how are you currently compiling documents? E.g. are you doing something like this?

- nvim foo.tex
- Make some changes
- :VimtexCompile

I'm curious because VimTeX should provide async compilation out of the box, i.e. if you're using :VimtexCompile you should be able to edit the document while it is compiling. It's unusual, I believe, that your cursor would freeze.

PS: I definitely would not recommend rolling your own compiler plugin, unless you're doing so as a learning exercise—I tried to make that clear at the [start of the article](https://www.ejmastnak.com/tutorials/vim-latex/compilation/#what-to-read-in-this-article) but am very open to any suggestions for clarifications.

**Comment by lervag** [comment] 2023-10-08 12:05
> Firstly, thank you for writing and maintaining such a wonderful plugin. I have been using it as my daily latex driver for my thesis and papers for the past 1.5 years. Now I can't even think of going back to TeXstudio. :)

Glad to hear it! <3

> So while compiling large documents (80-100 pages) with large bibliographies, the compilation time is significant. I can't move my cursor while it is being compiled.

That's strange. The compiler should _not_ block Vim and VimTeX.

> **Additional context** Profile of the compilation. …
>
> count 	total (s) 	self (s) 	function
> 492 	10.684024 	10.671074 	238()
> 
> FUNCTION 238() Defined: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/qf/bibtex.vim:93 Called 492 times

This seems to indicate that it is not the compilation that is blocking for you, but the parsing of the latex log. This happens _after_ a compilation cycle is finished. You could verify this by disabling the quickfix feature with `let g:vimtex_quickfix_enabled = 0`.

It would be interesting to investigate this further, but it is hard without being able to repriduce. Would you be able to create a sample project based on your current work that has a similar issue? Or perhaps just share your entire work with me in a private channel? Of course, I understand if you are not comfortable with the latter!

Also, after doing the profiling step, it would be useful to see the profile info of the `238()` function. Be aware that if you repeat the profiling you may get a different number here. I'm curious to see which line of code is the main problem here.

One hypothesis is that you are using a _huge_ bibliography file, probably shared between a lot of your projects. If so, it may help a lot to use a reduced bibliography file for your project with only the relevant entries. I personally always use dedicated bibliography files for each project as I want to contain it in my Git log of my projects.

**Comment by lervag** [comment] 2023-10-08 12:07
> Never mind, I had copied a bunch of text from a recent paper and there were many broken references, this made the latexmk call up bibtex many times to fix or write error messages. Nevertheless This would be a great feature to have.

Ah, ok. Does this mean that you don't really have a problem any more? VimTeX does not run the compiler in a blocking manner, as explained - it uses the neovim jobs api for neovim and the corresponding jobs api for Vim.

**Comment by mm-crj** [comment] 2023-10-24 12:47
> @mm-crj how are you currently compiling documents? E.g. are you doing something like this?
> 
>     * nvim foo.tex
> 
>     * Make some changes
> 
>     * :VimtexCompile

Exactly that!
> 
> I'm curious because VimTeX should provide async compilation out of the box and uses (at least on Neovim) the async jobs api that you mention under the hood (e.g. https://github.com/lervag/vimtex/blob/master/autoload/vimtex/jobs/neovim.vim#L65). In other words if you're using :VimtexCompile you should be able to edit the document during compilation. It's unusual, I believe, that your cursor would freeze.
> 
> Edit: just a thought—any chance you're using a outdated Neovim?

I don't think so, its `NVIM v0.9.1` it's the stable version from the snap store.  
> PS: I definitely would not recommend rolling your own compiler plugin, unless you're doing so as a learning exercise—I tried to make that clear at the [start of the article](https://www.ejmastnak.com/tutorials/vim-latex/compilation/#what-to-read-in-this-article) but am very open to any suggestions for clarifications.

I mean, after it became clear to me that :VimtexCompile is async, there is no point. And now that the freezing doesn't occur any more, first I have to get a "broken" minimum example to investigate this further. But my hunch was it's the `.log` file that was supposed to be written by `latexmk` that was not being written and was causing the delay. And this may have been further aggravated by the large number of broken citations and references.

**Comment by lervag** [comment] 2023-10-24 15:51
> I don't have a problem any more. I think fixing the broken references fixed the issue. Thanks for the prompt reply and clarifying the issue. And you are right, its not the compilation that is freezing the screen. Its the writing of the log as you suspect.

Great, I'm glad to hear that. I'll close the issue, then.

> > This seems to indicate that it is not the compilation that is blocking for you, but the parsing of the latex log. This happens _after_ a compilation cycle is finished. You could verify this by disabling the quickfix feature with `let g:vimtex_quickfix_enabled = 0`.
> 
> I will try that, however I would like to point out that no `.log` file is being generated. Maybe its trying to write one and failing and hence was taking a long time.

It's hard to say without a reproducible example. I would expect the log files to be generated and that the problem was due to very long log files or something similar, but I'm not sure. I don't think the code should have hangups due to missing log files.

> > It would be interesting to investigate this further, but it is hard without being able to repriduce. Would you be able to create a sample project based on your current work that has a similar issue? Or perhaps just share your entire work with me in a private channel? Of course, I understand if you are not comfortable with the latter!
> 
> If I were to reproduce this, essentially the way would be to use a very large `.bib` file and then use wrong citation keys in the `.tex` file. However, I can only be sure after I test this strategy, I will keep you updated.

Sounds good!

> > Also, after doing the profiling step, it would be useful to see the profile info of the `238()` function. Be aware that if you repeat the profiling you may get a different number here. I'm curious to see which line of code is the main problem here.
> 
> I am not entirely sure, how I can profile a specific function.

You already presented profiling information, so I would have guessed you know this? What did you do to generate the initial profiling information?

> > One hypothesis is that you are using a _huge_ bibliography file, probably shared between a lot of your projects. If so, it may help a lot to use a reduced bibliography file for your project with only the relevant entries. I personally always use dedicated bibliography files for each project as I want to contain it in my Git log of my projects.
> 
> Yes, you are right, I use a master bibliography file for essentially all my projects. I know it makes it rather bulky, but at this stage the time it will take to make the bibliography leaner far outweighs the time I lose in compiling. :) Probably I have to do this some time in the future.

I would not suggest you to do this manually. There's a tool called [bibtool](https://ctan.org/pkg/bibtool) that's perfect for this kind of stuff.

Also, I would advice you to look into things like Zotero for managing your personal bibliography. It has a nice export feature for bibtex. If you search online, I think you will find some nice resources and examples of how to combine Zotero within a LaTeX workflow with some simple addons.

> Also I don't get the comment about the "Git log".

I'll assume you know Git already and that I was just being unclear. What I mean, is that I find it useful to have the history of the reference file also as part of my Git history of a paper/project.

**Closed** 2023-10-24 15:52 UTC
Labels: enhancement
