### ISSUE TITLE
Vimtex does not load in plain text .tex files and creation of an unwanted directory when cleaning

### ISSUE THREAD

**Issue by luigipertoldi** [lervag/vimtex#820] opened 2017-05-04 20:25 UTC
I'm experiencing two issues with my multi-file project. First of all, my settings (macOS Sierra 10.12.4):

### `~/.vimrc`
```vim
" vim-plug settings
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
Plug 'vim-scripts/Colour-Sampler-Pack'
Plug 'vim-scripts/ScrollColors'
Plug 'Valloric/YouCompleteMe'
call plug#end()

set mouse=a
set number
set autoindent
set list
set listchars=eol:¬,tab:>-,trail:~,extends:>,precedes:<
"
" Color Scheme settings
syntax on
if has("autocmd")
  " Highlight TODO, FIXME, NOTE, INFO, BUG etc.
  if v:version > 701
    autocmd Syntax * call matchadd('Todo',  '\W\zs\(TODO\|FIXME\|CHANGED\|XXX\|BUG\|HACK\)')
    autocmd Syntax * call matchadd('Debug', '\W\zs\(NOTE\|INFO\|IDEA\)')
  endif
endif

colorscheme solarized
highlight NonText ctermfg=black
highlight SpecialKey ctermfg=black
"
" in normal mode F2 will save the file
nmap <F2> :w<CR>
" in insert mode F2 will exit insert, save, enters insert again
imap <F2> <ESC>:w<CR>i

" YouCompleteMe settings
let g:ycm_server_python_interpreter                 = '/usr/bin/python'
let g:ycm_global_ycm_extra_conf                     = "/Users/luigipertoldi/.vim/.ycm_extra_conf.py"
let g:ycm_confirm_extra_conf                        = 0
let g:ycm_add_preview_to_completeopt                = 1
let g:ycm_seed_identifiers_with_syntax              = 1
let g:ycm_min_num_of_chars_for_completion           = 99
let g:ycm_autoclose_preview_window_after_completion = 1

" configuration file for c++ is ~/.vim/ftplugin/cpp.vim
" configuration file for tex in ~/.vim/ftplugin/tex.vim
```
### `~/.vim/ftplugin/tex.vim`
```vim
filetype indent on
set tabstop=4
set shiftwidth=4
"set expandtab
set grepprg=grep\ -nH\ $*

let g:tex_flavor = 'latex'
let g:vimtex_complete_enabled = 1
let g:vimtex_compiler_method = 'latexmk'
let g:vimtex_fold_enabled = 1
let g:vimtex_view_method = 'skim'
let g_vimtex_motion_enabled = 0
let g:vimtex_compiler_latexmk = {
\				 'backend'    : 'process',
\				 'background' : 1,
\				 'build_dir'  : 'log',
\				 'callback'   : 1,
\				 'continuous' : 1,
\				 'executable' : 'latexmk',
\				 'options'    : [
\				 		'-pdf',
\				 		'-verbose',
\				 		'-file-line-error',
\				 		'-interaction=nonstopmode',
\				 		],
\				}
if !exists('g:ycm_semantic_triggers')
	let g:ycm_semantic_triggers = {}
endif
let g:ycm_semantic_triggers.tex = [
\					're!\\[A-Za-z]*cite[A-Za-z]*(\[[^]]*\]){0,2}{[^}]*',
\					're!\\[A-Za-z]*ref({[^}]*|range{([^,{}]*(}{)?))',
\					're!\\hyperref\[[^]]*',
\					're!\\includegraphics\*?(\[[^]]*\]){0,2}{[^}]*',
\					're!\\(include(only)?|input){[^}]*',
\					're!\\\a*(gls|Gls|GLS)(pl)?\a*(\s*\[[^]]*\]){0,2}\s*\{[^}]*',
\					're!\\includepdf(\s*\[[^]]*\])?\s*\{[^}]*',
\					're!\\includestandalone(\s*\[[^]]*\])?\s*\{[^}]*',
\					're!\\usepackage(\s*\[[^]]*\])?\s*\{[^}]*',
\					're!\\documentclass(\s*\[[^]]*\])?\s*\{[^}]*',
\					're!\\[A-Za-z]*',
\					]
```
### `.latexmkrc`
```vim
$pdf_previewer = "open -a Skim.app %S";
$xelatex = "xelatex -syntex=1 -shell-escape -interaction nonstopmode %O %S";
$pdflatex = "pdflatex -syntex=1 -shell-escape -interaction nonstopmode %O %S";
$lualatex = "lualatex --shell-escape --interaction nonstopmode %O %S";
```
### Vim
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May  4 2017 21:13:36)
MacOS X (unix) version
Included patches: 1-596
Compiled by Homebrew
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     -gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        -toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python          +vreplace
+cscope          +lispindent      -python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            +ruby            +X11
+digraphs        +mksession       +scrollbind      +xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: clang   -L. -L/usr/local/lib  -L/usr/local/lib -o vim    -lXt -lX11 -lSM -lICE  -lm  -lncurses -liconv -framework Cocoa   -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level/CORE -lperl -framework Python   -lruby.2.0.0 -lobjc
```
### LaTeX project
The directory tree is
```
main.tex
src/intro.tex
src/chap.tex 
```
`main.tex`:
```latex
%! TEX root = /Users/luigipertoldi/LaTex/test-proj/main.tex
%! TEX program = pdflatex
\documentclass{article}
\usepackage{lipsum}
\begin{document}
\include{src/intro}
\include{src/chap1}
\end{document}
```
`intro.tex`:
```latex
%! TEX root = /Users/luigipertoldi/LaTex/test-proj/main.tex
\section{test}
\lipsum{1}
```
`chap.tex`:
```latex
%! TEX root = /Users/luigipertoldi/LaTex/test-proj/main.tex
\begin{equation}
i\mathcal{M}=iG^2_FV^2_{ud}[\bar{u}(p_1)\gamma^\mu(1-\gamma_5)v(q_1)][\bar{u}(p_2)\gamma^\nu(1-\gamma_5)v(q_2)]J_{\mu\nu}-(p_1\leftrightarrow p_2)
\end{equation}
```

The issues:
1. `intro.tex` seems not to be recognized as a .tex file (e.g. vimtex is not active when modifying it), instead for `chap.tex` everything works fine. This is related to the fact that in `intro.tex` there's only plain text, while in `chap.tex` there's an `equation` environment which triggers vimtex. I don't know if this is actually related to vimtex or not.
2. When I type `\lc` an empty folder named `logmain.tex` appears in the project directory. I tested this also on Linux. Something wrong in my settings?

Questions (can be ignored):
1. Is completion provided also for environments' names? I mean then typing `\begin{...`, because I don't have it.
2. Is there someone who knows how to do the window title thing mentioned [here](https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt#L2324) in macOS? Unfortunately `xdotool` works only for X11 windows. I know how to change the title of the current terminal window, as explained for example [here](https://superuser.com/questions/105499/change-terminal-title-in-mac-os-x), but I don't have ideas on how to find a specific window and do so.

P.S.: great plugin. As an (ex-)user of LaTeX-Suite I totally love it!

**Comment by lervag** [comment] 2017-05-05 13:46
The first issue should be solved with `let g:tex_flavor = 'latex'`. See `:h g:tex_flavor`. Note that you can't put this in `ftplugin/tex.vim`, because that will only work for files that have already been marked as `tex` filetype. It should go in your vimrc file (or similar).

For the second issue: What is the output of `:map \lc`?

For  the first question: No, sorry: there is not completion of environment names at the moment. I don't really think this is an important feature, since I think most of the "important" environments should be snippets from a suitable snippet plugin, in order to speed up TeX typing.

Finally, regarding window titles on macOS, I'm sorry to say I can't help. I don't use macOS/OSX and have no experience with it. Feel free to post a solution here if you find one, though.

Finally, thanks for the kind words! :)

**Comment by luigipertoldi** [comment] 2017-05-05 15:06
1. Thanks!
2. `n  \lc        @<Plug>(vimtex-clean)` with many spaces between the strings:
![f](https://cloud.githubusercontent.com/assets/20358192/25751386/1ae6a912-31b5-11e7-867b-7737242ac303.png)
I forgot to mention that the contents of `log/` are not removed when cleaning.

**Comment by lervag** [comment] 2017-05-09 09:16
Hi! Could you show the output of `\li` / `:VimtexInfo` after you have issued the `\lc`?

**Comment by luigipertoldi** [comment] 2017-05-11 07:02
```
vimtex project: main
  base: main.tex
  root: /Users/luigipertoldi/GoogleDrive/Università/Magistrale/Tesi/tex
  tex: /Users/luigipertoldi/GoogleDrive/Università/Magistrale/Tesi/tex/main.tex
  out: /Users/luigipertoldi/GoogleDrive/Università/Magistrale/Tesi/tex/log/main.pdf
  log: /Users/luigipertoldi/GoogleDrive/Università/Magistrale/Tesi/tex/log/main.log
  aux: /Users/luigipertoldi/GoogleDrive/Università/Magistrale/Tesi/tex/log/main.aux
  engine: -lualatex
  source files:
    main.tex
    src/intro.tex
    src/chap1.tex
  packages:
    microtype
    tikz
    fontenc
    bm
    indentfirst
    inputenc
    babel
    hyperref
    subfigure
    mhchem
    standalone
    ebgaramond
    xcolor
    pgfplots
    titlesec
    booktabs
    graphicx
    caption
    newtxmath
    multicol
    libertine
    multirow
  compiler: latexmk
    backend: process
    output: /var/folders/v9/1qz37mm91n1b4xkzd6y2378w0000gn/T/vXcvEF5/1
    configuration:
      continuous: 1
      callback: 1
      build_dir: log
      latexmk options:
        -pdf
        -verbose
        -file-line-error
        -interaction=nonstopmode
  viewer: Skim
  qf: LaTeX logfile
    config:
      fix_paths: 1
      packages:
        default: 1
      default: 1
```

**Comment by lervag** [comment] 2017-05-11 13:01
Found a minor bug that I think caused this. I think it works now.

**Closed** 2017-05-11 13:00 UTC

**Comment by luigipertoldi** [comment] 2017-05-11 22:40
It works, thank you. However there's a little detail: with my directory structure (see above) a `log/src/` folder with the `.aux` of the files contained in `src/` is also created. The cleaning procedure does not empty or delete that directory. Is this a `latexmk`-related issue?

**Comment by lervag** [comment] 2017-05-12 10:47
That's strange. When I try, the contents of the `src` folder is emptied, but the directory structure remains. I.e., the `out` and `out/src` directories are there after cleaning. This is entirely due to latexmk, which does not delete directories.

I could add a test to see if the build_dir directory is empty after clean up, and then remove the directory (and subdirectories) after latexmk cleanup. Do you think this is a necessary/interesting feature?

**Comment by lervag** [comment] 2017-05-13 08:39
I've added this now, so a full clean should also remove empty directories.

**Comment by luigipertoldi** [comment] 2017-05-13 10:04
Thanks, I think it's a matter of personal preferences. but wouldn't it be nice to delete the whole `log` folder in this case?

However after your last commit I think a new bug has been introduced: after full cleaning a new compilation process creates folders inside `log` without the first character. For example, with my directory structure, a `log/rc` instead of `log/src` is created. Obviously then the `.aux` files cannot be find by the compiler.

**Comment by lervag** [comment] 2017-05-13 18:35
That's strange. I added a minimal example to the `test/issues/820` directory in the vimtex repo. If you go there, then du `nvim -u minivimrc main.tex`, then `\l` to compile. This creates the `out` and `out/src` directories. Further, the `\lC` command now cleans everything and removes the directories as expected.

Thus I can't reproduce your mentioned bug..?

**Comment by luigipertoldi** [comment] 2017-05-13 20:22
The issue was related to the fact that $PWD was containing an accented character (à), weird! Renamed the folder and now everything works. I don't know if this is something fixable/you-want-to-fix, however there are millions of good reasons to avoid strange characters in paths.

What do you think about deleting the `log` folder with a full clean `\lC`?

**Comment by lervag** [comment] 2017-05-13 20:43
`\lC` does delete the log folder now. I think it is good.

I think the accented character issue was with latexmk, not with vimtex. It is latexmk that compiles the document and thus creates the subdirs.
