### ISSUE TITLE
Problem with compilation in multi file projects

### ISSUE THREAD

**Issue by AlekseiSmirnov** [lervag/vimtex#669] opened 2017-01-22 22:03 UTC
I face strange error when I work on multi-file projects (with subfiles)
If I wand to compile specific file I toggle it using `\ls` binding and everything seems to be okay.

But if I close the file `(:wq)`, then reopen it again and toggle by `\ls` I see the following error:

```Error detected while processing function vimtex#toggle_main:
line    7:
E716: Key not present in Dictionary: 2
vimtex: Changed to main.tex' [local]
```

The problem can be reproduced using simple multi-file project:
main.tex

```
\documentclass{minimal}
\usepackage{subfiles}

\begin{document}

Hello World!
\subfile{subfile}

\end{document}
```

subfile.tex
```
\documentclass[main.tex]{subfiles}

\begin{document}

This is subfile

\end{document}
```

The problem can be reproduced using simple .vimrc file from the guideline

**Comment by lervag** [comment] 2017-01-23 08:59
Interesting. Could you elaborate on the steps you do to reproduce? When you say `:wq`, I immediately think you fully close Vim, but based on the context it seems you only close a window. This again implies that you have several windows, which you did not mention.

**Comment by clason** [comment] 2017-01-23 12:29
I think it might refer to tabs (e.g., in gvim or macvim); I sometimes see similar errors when opening (and closing) a second tex file in a new tab (something about `vimtex#reverse_search`, which I can't reproduce now).

**Comment by AlekseiSmirnov** [comment] 2017-01-23 13:36
yes. It can be reproduced using both - tabs or vertical split. Suppose we have two windows in vertical split - main.tex and subfile.tex. 
We toggle (\ls) subfile.tex and then close it by :wq 

Then we reopen it again in the vertical split. And if I try to toggle it again I see this error

**Comment by lervag** [comment] 2017-01-23 15:08
Ok, so:

1. I open `main.tex`
2. I go to the line `\subfile{subfile}` with the cursor on the filename and do `CTRL-W_CTRL-F`, which opens the subfile in a split window
3. I do `\ls` to toggle the subfile
4. I do `:wq`
5. I Repeat steps 2-4

I do not observe any errors or problems. I use a minimal vimrc file.

**Comment by AlekseiSmirnov** [comment] 2017-01-23 22:18
Just checked with cl version of vim and I can reproduce problems. Slightly clarified sequence of steps:

1. `vim --servername VIM main.tex`
2. I go to the line \subfile{subfile} with the cursor on the filename and do `CTRL-W_CTRL-F`, which opens the subfile in a split window
3. I do `\ls` to toggle the subfile and see `vimtex: Changed to subfile.tex' [local]` at the bottom of the window
4. I do `:wq`
5. I repeat step 2
6. I do `\ls` to toggle main.tex. First time I see a message `vimtex: Changed to `main.tex' [local]`
7. I do `\ls` to toggle the subfile again. Now I see the error

![2017-01-24_01-16-22](https://cloud.githubusercontent.com/assets/10200871/22225236/c13b7cd0-e1d2-11e6-957b-1688ffd21892.png)

**Comment by lervag** [comment] 2017-01-24 19:48
Ah, there it is. I missed the second `\ls`. Investigation as we speak.

**Closed** 2017-01-24 20:37 UTC

**Comment by lervag** [comment] 2017-01-24 20:38
Thanks, this was actually quite tricky, but I think my final solution should work satisfactory. Let me know if it works and solves your problems.

**Comment by AlekseiSmirnov** [comment] 2017-01-25 00:35
Just checked, now it works perfectly. Thanks

**Comment by lervag** [comment] 2017-01-25 12:52
No problem :)
