### ISSUE TITLE
General auto-unindent not working for a minimal install

### ISSUE THREAD

**Issue by abhijit-c** [lervag/vimtex#2332] opened 2022-02-17 01:14 UTC
### Description

Hello,

First off, thank you. I've been using this plugin for many years and it's been fantastic.

That being said, recently I've run into an issue where my environments are refusing to auto-unindent on a `\end{env}` line. This is present on both of my Fedora workstations, but doesn't seem to happen on my MacOS install. I'm wondering if there were any tweaks to how indentation works that you recall might affect this?

### Steps to reproduce

With `minimal.vim` being
```vim
set nocompatible "No vi compatible
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex' "latex syntax highlighting, ToC view, synctex, etc.
call plug#end()
filetype plugin indent on "Load plugins + file specific indent
syntax on
```
and `minimal.tex`
```tex
\documentclass{minimal}
\begin{document}
Hello, work!
\begin{equation}
  \end{equation}
\end{document}
```
I'm running my test with `vim -u minimal.vim minimal.tex`.

### Expected behavior

When I type `\end{equation}` on line 5, I expect that the line should auto-unindent to match the indentation of \begin{equation}.

### Actual behavior

Upon typing the last `}` on line 5, the indentation remains one level higher than the `\begin{equation}` line.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: Fedora release 35 (Thirty Five)
  Vim version: VIM 8.2 (1-4314)
  Has clientserver: false

VimTeX project: minimal
  base: minimal.tex
  root: /home/trostaft/Documents/vimtex-testing
  tex: /home/trostaft/Documents/vimtex-testing/minimal.tex
  main parser: current file verified
  document class: minimal
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```
```

**Comment by abhijit-c** [comment] 2022-02-17 01:21
If it helps, here's the VimtexInfo from my Macbook on which indentation works as expected.

```yaml
System info
  OS: macOS 12.1 (21C52)
  Vim version: VIM 8.2 (1-2671, 3402, 3409, 3428, 3489)
  Has clientserver: false

vimtex project: minimal
  base: minimal.tex
  root: /Users/trostaft/Documents/vimtex-testing
  tex: /Users/trostaft/Documents/vimtex-testing/minimal.tex
  out:
  log:
  aux:
  fls:
  main parser: current file verified
  compiler: latexmk
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    config:
      packages:
        default: 1
      default: 1
  document class: minimal
```

**Comment by clason** [comment] 2022-02-17 07:14
> This is present on both of my Fedora workstations, but doesn't seem to happen on my MacOS install.

Some package managers insist on installing vim plugins system-wide, which homebrew doesn't. These may change the indent options. Check `:scriptnames` for unexpected scripts outside the standard runtime and your user directory. You can also do `:verbose set indent?` (and similarly for other indentation-related options) to check if they were changed by those.

**Comment by lervag** [comment] 2022-02-17 07:20
> First off, thank you. I've been using this plugin for many years and it's been fantastic.

Thanks for the kind words! :)

> That being said, recently I've run into an issue where my environments are refusing to auto-unindent on a `\end{env}` line. This is present on both of my Fedora workstations, but doesn't seem to happen on my MacOS install. I'm wondering if there were any tweaks to how indentation works that you recall might affect this?

Three _have_ been recent tweaks. Although I'm surprised if they break anything. But it is not impossible.

> I'm running my test with `vim -u minimal.vim minimal.tex`.

Thanks, I'm glad to hear you've tested with a proper minimal example!

----

So, let's troubleshoot. Before I go deeper myself: Can you confirm that you are using the latest version of VimTeX on all of your computers, both the one where it works and where it fails?

Also, @clason's suggestion is good, so feel free to inspect `:scriptnames` on both setups and compare.

**Comment by lervag** [comment] 2022-02-17 07:23
FYI: The minimal example works as expected on my end. Also, when you use `vim-plug`, you don't need the `filetype` and `syntax`, so you can simplify. This would suffice and should be equivalent to your specified minimal vimrc:

```vim
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()
```

**Comment by abhijit-c** [comment] 2022-02-17 18:22
Per your advice, I simplified the `minimal.vim` down to:
```vim
set nocompatible
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()
```
I found that I needed the `set nocompatible` line on both installs otherwise vimtex throws a host of errors at me, most of the form
```
Error detected while processing /home/trostaft/.vim/plugged/vimtex/plugin/vimtex.vim:
line   13:
E10: \ should be followed by /, ? or &
```
Anyway, I think those are aside the point so I'm leaving the nocompatible line the minimal for both. Regarding @clason's suggestion, I ran scriptnames on both installs and found the following results (see [scriptnames_fedora.txt](https://github.com/lervag/vimtex/files/8091142/scriptnames_fedora.txt)
[scriptnames_mac.txt](https://github.com/lervag/vimtex/files/8091143/scriptnames_mac.txt)). I didn't spot anything surprising, but your eye may be more trained than mine.

Next, regarding version of vimtex, how might I check that? My apologies, I'm not very well trained in vim's ecosystem so I'm not sure if there's a variable I can echo for that. I was, however, able to get an estimate by looking at the git-log in the vimtex directory for both installs. In particular, my fedora installation's last log entry was

```git
commit 5659e6ac5ffc3ae43bd401d78b3a62653a28b750 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Karl Yngve Lervåg <karl.yngve+git@gmail.com>
Date:   Tue Jan 25 12:37:50 2022 +0100

    doc: fixed doc references
    
    refer: #2306
```

and for my macbook it was

```git

```

Somehow it's a 2 year difference (apparently I haven't touched this .vimrc for a while?). I'll try updating it and seeing what happens.

**Comment by lervag** [comment] 2022-02-17 21:46
> I found that I needed the `set nocompatible` line

Yes, sorry, my mistake. You _don't_ need it in your regular vimrc file, but you do need it with the `-u` option as in `vim -u test.vim`.

> Regarding @clason's suggestion, I ran scriptnames on both installs and found the following results (see [scriptnames_fedora.txt](https://github.com/lervag/vimtex/files/8091142/scriptnames_fedora.txt) [scriptnames_mac.txt](https://github.com/lervag/vimtex/files/8091143/scriptnames_mac.txt)). I didn't spot anything surprising, but your eye may be more trained than mine.

The main difference I noticed was that it seemed like you have two different versions of VimTeX. Except for that I did not notice anything in particular.

> Next, regarding version of vimtex, how might I check that?

Checking the Git version is the only good way, and it is what you did.

> Somehow it's a 2 year difference (apparently I haven't touched this .vimrc for a while?). I'll try updating it and seeing what happens.

> Indeed after running a git-pull in the vimtex repository on my Macbook and another `:PlugInstall` (not sure if that was necessary), indentation is no longer working on my Macbook. Perhaps that narrows things down a tad (though I can barely contain my tears at now having 0 properly indenting machines).

I'm sorry for moving you into "the dark" here. But notice that this is not really so bad. It means you see the same behaviour on two different setups with a minimal vimrc and minimal file.

I mentioned earlier that the minimal example worked as expected on my end. But then I noticed that you did not talk about doing `=`, but about auto indenting after typing `\end{equation}`, and I can now confirm this does not work on my end either. I'll look into it asap!

**Comment by lervag** [comment] 2022-02-17 21:55
I did a bisection and found that the commit that introduces the problem is f9d07de70711933337a224d8c2e3623da5127701. It was suggested in #2227 by @BertrandSim. I thought it looked good then, but missed this problem.

@BertrandSim It would be useful with a comment by you if you're available.

**Comment by lervag** [comment] 2022-02-17 21:56
I believe it can be fixed by reverting slightly and removing the 0 from the `0}` in the indentkeys option.

**Comment by lervag** [comment] 2022-02-17 21:58
@abhijit-c I hope you don't mind that I leave some time for @BertrandSim to comment on this before I make any changes. Feel free to manually fix this on your end by removing the 0 from `0}` in this line:

https://github.com/lervag/vimtex/blob/cc7ff32d064107dc1b4c199633e49a94a0b95ebc/indent/tex.vim#L23

**Comment by abhijit-c** [comment] 2022-02-18 01:47
Thank you, indeed this works. Likewise, I noticed that similar occurs when working in the display math mode denoted by `\[` and `\]` Say with the MWE:
```tex
\documentclass{minimal}
\begin{document}
Hello, work!
\[
  \]
\end{document}
```
Removing the 0 from the `0]` in said changes the above behavior so that it auto indents back to the same indentation level as the `\[`.

**Comment by lervag** [comment] 2022-02-18 23:12
Yes, I agree. I've pushed the fix now.

**Closed** 2022-02-18 23:12 UTC
Labels: bug
