### ISSUE TITLE
ToC: Match counting to latex defaults: parts in roman & no reset for chapt. numbers

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#811] opened 2017-04-28 15:11 UTC
```tex
\documentclass{book} % or scrbook, memoir

\begin{document}
\part{First part}

\chapter{Hello}
\chapter{World}

\part{Second part}

\chapter{Hello}
\chapter{Mars}

\end{document}
```
will give you following toc
```
      Preamble                                                                                                                                    0
1     First part                                                                                                                                  0
1.1   Hello                                                                                                                                       1
1.2   World                                                                                                                                       1
2     Second part                                                                                                                                 0
2.1   Hello                                                                                                                                       1
2.2   Mars                                                                                                                                        1
```
However, I would like to match the setting of my document which are the default settings of book.cls, scrbook.cls and memoir.cls.
```
      Preamble                                                                                                                                    0
I     First part                                                                                                                                  0
1   Hello                                                                                                                                       1
2   World                                                                                                                                       1
II     Second part                                                                                                                                 0
3   Hello                                                                                                                                       1
4   Mars                                                                                                                                        1
```

The option could be called something like `g:vimtex_toc_number_style_book` or `g:vimtex_toc_number_style_latex_default` with a description. I would expect that this could be enabled by default or even no option at all for this and just change it. If someone wants the old style, a setting for this case has to be added.

**Comment by kiryph** [comment] 2017-04-28 17:02
Following diff changes the parts
```diff
@@ -462,13 +462,23 @@ function! s:toc.print_number(number) abort dict " {{{1
         \ ]

   " Remove unused parts
-  while number[0] == 0
-    call remove(number, 0)
-  endwhile
   while number[-1] == 0
     call remove(number, -1)
   endwhile

+  " Return roman numerals for parts
+  let roman =  [ 'i', 'ii', 'iii', 'iv', 'v', 'vi', 'vii', 'viii', 'ix', 'x',
+          \      'xi', 'xii', 'xiii', 'xiv', 'xv', 'xvi', 'xvii', 'xviii',
+          \      'xix', 'xx' ]
+  if len(number) == 1 && number[0] > 0
+    return roman[number[0]-1]
+  endif
+
+  " Remove always part
+  call remove(number, 0)
+
+  " TODO add chapter number of previous part (not available here)
+
   " Change numbering in frontmatter, appendix, and backmatter
   if self.topmatters > 1
         \ && (a:number.frontmatter || a:number.backmatter)
```
The toc looks like this
```
      Preamble                                                                                                                                    0
I     First part                                                                                                                                  0
1   Hello                                                                                                                                       1
2   World                                                                                                                                       1
II     Second part                                                                                                                                 0
1   Hello                                                                                                                                       1
2   Mars 
```

Changing the chapter number requires knowledge of previous numbers of sections.

**Comment by kiryph** [comment] 2017-04-28 17:20
### Revised Feature Request

Actually, this is how I want it for my current document.
However, in general it should be as described in my first post.
I guess I like to have optional chapter counting per part and I should reformulate my feature request as follows:
1. add option `g:vimtex_toc_count_parts_in_roman = 0/1`
2. add option `g:vimtex_toc_reset_chapter_count_per_part = 0/1`

### Change vimtex settings for specific files
The remaining question for me is, how can I change this seamlessly for different documents. modelines cannot change global vim variables. An autocommand would be possible to detect this special document. However, I am not a fan of adding to my vimrc document specific code.

To achieve it in latex I have added following
```tex
\makeatletter
\@addtoreset{chapter}{part}
\makeatother
```
and in part two I have added
\renewcommand{\thechapter}{%
  P\arabic{chapter}%
}
```
the latex toc looks like:
```
i Part I
1 chapter one
2 chapter two
...
ii Part II
P1 Chapter One in Part II
P2 Chapter Two in Part II
```
Since this quite specific. I would stick to the two variables above mentioned

**Comment by lervag** [comment] 2017-05-29 20:55
Ok, I've pushed changes that partly addresses your comments and suggestions.

I'm now wondering if we really need to add more options? To me, the current version looks good, and it seems pointless to have as a goal that the vimtex TOC should mimic the LaTeX TOC style for all documents. The current version seems to mimic the default style, and since the main point is to provide a means of navigation, I think it perhaps that adding more option only leads to unnecessary complications. But feel free to convince me otherwise.

@DelusionalLogic As you see, I've moved the discussion about further customization back here. Feel free to join with your opinions.

**Comment by kiryph** [comment] 2017-05-30 08:47
@lervag: thanks for your update. I appreciate the consistency between vimtex-toc and the latex-toc.

I do not feel the urge to convince you to add an option to customize it 😄 . I guess someone else has to raise the voice for this.

**Comment by kiryph** [comment] 2017-05-30 08:49
However, I encounter following error message when I press `<CR>` on an toc entry
```
Error detected while processing function 111[58]..112:
line    7:
E94: No matching buffer for -1 
```

**Comment by lervag** [comment] 2017-05-30 09:09
I can't reproduce that. Here everything works...

**Comment by kiryph** [comment] 2017-05-30 09:19
I get only the error with `let g:vimtex_index_split_pos = 'full'`. If comment this, the error is gone.

**Comment by lervag** [comment] 2017-05-30 09:24
Ok, reproduced.

**Comment by lervag** [comment] 2017-05-30 09:29
This was a regression from earlier and as such not related to the current issue. But it should be fixed now.

**Closed by lervag** 2017-05-30 09:29 UTC

**Comment by kiryph** [comment] 2017-05-30 09:35
Yes, it is fixed. Thanks again.

**Comment by lervag** [comment] 2017-05-30 09:36
No problem, happy to hear it works :)
