### ISSUE TITLE
nvim + vimtex + which-key + remote-tab + mapping = trouble 

### ISSUE THREAD

**Issue by Rmano** [lervag/vimtex#3057] opened 2024-12-16 11:12 UTC
### Description

This is a follow-up of #2869 and it is *very low priority*. Moreover, it can well be a problem of `nvim` and have nothing to do with `vimtex`. So don't rush and have a nice 'season 😉

The basic problem is that some key mappings, like for example input-mode `]]`, stops working in nvim with the `which-key.nvim` extension if the [Lua file suggested in the wiki](https://github.com/lervag/vimtex/wiki/which%E2%80%90key.nvim-support) is loaded and the file is opened as a remote tab.

### Steps to reproduce

The step to reproduce it are quite complex, so bear with me. I have a directory `~/software/bugs/vimtex/nvim` with the following files: 

```bash
[romano:~/software/bugs/vimtex/nvim] % ls
base.tex  ftplugin/  nvim-wk.vim  other.tex 
[romano:~/software/bugs/vimtex/nvim] % ls ftplugin 
tex.lua
```

where the `tex.lua` is the one found in the wiki.

The files' contents are

**base.tex**

```latex
\documentclass{article}
\begin{document}
This is "base.tex"
    \begin{center}
    \end{center}
\end{document}
```

**other.tex**

```latex
\documentclass{article}
\begin{document}
This is "other.tex"
    \begin{center}
    \end{center}
\end{document}
```

**nvim-wk.vim**

```vim
set nocompatible
set runtimepath^=~/.config/nvim/plugged/vimtex
set runtimepath^=~/.config/nvim/plugged/which-key.nvim
set runtimepath+=~/.config/nvim/plugged/vimtex/after
set runtimepath^=~/software/bugs/vimtex/nvim/
filetype plugin indent on
syntax enable
```

Now, open a terminal in the directory and run:

    nvim --clean -u ./nvim-wk.vim --listen ./nvim.pipe base.tex

This will open the file `base.tex` and start a server for the `nvim` instance listening on the pipe specified. Now, open another terminal on the same directory and issue:

    nvim --clean -u ./nvim-wk.vim --server ./nvim.pipe --remote-tab other.tex

the command will return immediately and another tab is opened in the previous terminal which have the `nvim` running:

![image](https://github.com/user-attachments/assets/752bc252-9b5e-40d9-83aa-2eea012edb5a)

Here, the Lua file is loaded because you can see the specification of the commands: 

![image](https://github.com/user-attachments/assets/40b9704a-9c56-4f14-ac48-fe9c3d177d1d)

Now, delete the line with `end{center}`, enter in input mode there, and type `]]`. You have: 

![image](https://github.com/user-attachments/assets/96959600-e1fa-4f75-9898-bde33948755d)

...instead of the expected `end{center}`. Notice that this happens only on tabs opened with `--remote-tabs` (!), and **does not** happen if I remove the `tex.lua` file.

### Do you use a latexmkrc file?

Not relevant

### VimtexInfo

```yaml
System info:
  OS: Ubuntu 24.04.1 LTS
  Vim version: NVIM v0.10.2
  Has clientserver: true
  Servername: ./nvim.pipe

VimTeX project: base
  base: base.tex
  root: /home/romano/software/bugs/vimtex/nvim
  tex: /home/romano/software/bugs/vimtex/nvim/base.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```

**Comment by Rmano** [comment] 2024-12-16 11:27
Workaround: remove the `]]` stanza:

```lua
 -- {
    --   "]]",
    --   "<plug>(vimtex-close-delimeter)",
    --   desc = "Close delimeter",
    --   icon = { icon = "󰅩", color = "green" },
    --   mode = "i",
    -- },
```

...and be happy ;-), but still the problem is interesting.

**Comment by Rmano** [comment] 2024-12-18 10:22
Maybe related: https://github.com/folke/which-key.nvim/issues/886 ?  The symptoms are, well, identical.

**Comment by lervag** [comment] 2024-12-18 20:58
> This is a follow-up of #2869 and it is _very low priority_. Moreover, it can well be a problem of `nvim` and have nothing to do with `vimtex`. So don't rush and have a nice 'season 😉

Thanks! ♥️ 🎄

> The basic problem is that some key mappings, like for example input-mode `]]`, stops working in nvim with the `which-key.nvim` extension if the [Lua file suggested in the wiki](https://github.com/lervag/vimtex/wiki/which%E2%80%90key.nvim-support) is loaded and the file is opened as a remote tab.

In fact, it seems to me that I can reproduce this even _without_ going through the extra hoops. That is, given the setup you describe, the following reproduces it for me:

1. `nvim --clean -u nvim-wk.vim base.tex`
2. Delete `\end{center}` and enter insert mode
3. Type `]]`

Thus, the `--remote-tab` was not necessary for me to reproduce this.

Now, this only happens when we load which-key.nvim, so I would humbly claim that this must be a bug with that plugin. Of course, I have a lot of respect for @folke, and I may be wrong! I'll see if I can understand it better before I leave this.

**Comment by lervag** [comment] 2024-12-18 21:09
Ok, I can now reproduce with the following `ftplugin/tex.lua`:

```lua
local wk = require "which-key"
wk.add {
  buffer = vim.api.nvim_get_current_buf(),
  {
    "]]",
    "<plug>(vimtex-close-delimeter)",
    desc = "Close delimeter",
    icon = { icon = "󰅩", color = "green" },
    mode = "i",
  },
}
```

So, notice that I think things should work well for you if you just remove that mapping from your config.

**Comment by lervag** [comment] 2024-12-18 21:11
Ok, there seems to be a typo: It should be `<plug>(vimtex-delim-close)`. It seems that's the main issue here. I'll update the wiki, and I'll close the issue since I think this is the correct solution.

**Closed by lervag** 2024-12-18 21:11 UTC
Labels: bug

**Comment by Rmano** [comment] 2024-12-19 06:43
🤐 what a fuss for a typo.... Thanks for spotting it. And Merry Christmas again 🎄

**Comment by lervag** [comment] 2024-12-19 22:11
Merry christmas! :)
