### ISSUE TITLE
table of contents E716

### ISSUE THREAD

**Issue by stegzzz** [lervag/vimtex#1892] opened 2020-12-11 08:57 UTC
When using \lt on this minimal tex file
```
\documentclass[12pt,floatsintext, a4paper]{article}
\begin{document}
\section{Introduction}
blah blah
\subsection{another}
Today...
\subsubsection{methods}
Pigeons are my best friends
\end{document}
```
I get
```
Error detected while processing function 58[12]..63[6]..vimtex#parser#toc#get_topmatters:
line    1:
E716: Key not present in Dictionary: frontmatter
```
It seems to be related to issue #1124

I have
```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Oct 18 2020 17:01:09)`
MS-Windows 64-bit console version
Included patches: 1-1860
vimtex 2.1
```

$MYVIMRC is [here](http://spgxyz.com/minimalMinimalVimtex.vim)

**Comment by lervag** [comment] 2020-12-12 14:16
Your example works perfectly fine on my end. Can you give a proper minimal example including a minimal vimrc file? See [the issue emplate](https://github.com/lervag/vimtex/blob/master/.github/ISSUE_TEMPLATE/issue_report.md) for hints on how to do that.

**Comment by stegzzz** [comment] 2020-12-12 17:01
> Your example works perfectly fine on my end. Can you give a proper minimal example including a minimal vimrc file? See [the issue emplate](https://github.com/lervag/vimtex/blob/master/.github/ISSUE_TEMPLATE/issue_report.md) for hints on how to do that.

OK, the file minimalVimtex.vim is at the link above. I run
```
vim --servername VIM -u c:\users\admin\vim\minimalVimtex.vim temp1.tex
```
where temp1.txt contains the minimal tex file above and the error message persists

**Comment by lervag** [comment] 2020-12-13 11:23
I'm trying to reproduce. I do this: `vim --servername VIM -u test.vim test.tex`, where

```vim
" test.vim
set nocompatible
set encoding=utf-8
let &runtimepath  = '~/.vim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
```

and

```tex
% test.tex
\documentclass[12pt,floatsintext, a4paper]{article}
\begin{document}
\section{Introduction}
blah blah
\subsection{another}
Today...
\subsubsection{methods}
Pigeons are my best friends
\end{document}
```

Now I do `\lt` to open the ToC, and it works as expected. I do `\ll` to compile the document, then try `\lt` again; still works as expected.

As long as I can't reproduce the error it is very difficult to fix anything. Sorry!

Note: The servername `VIM1` is expected. Vim automatically appends the number.

Note 2: Please don't be afraid of adding file contents verbatim to your posts, especially when the files are small. It is more of a hassle to click the links than to just see the contents directly.

**Comment by patricknraanes** [comment] 2021-05-05 15:12
I get a similar error (screenshot), but only with `vim-plug` and `vimtex>1.6`.

![Screenshot from 2021-05-05 17-05-27](https://user-images.githubusercontent.com/7222967/117163730-3c316f00-adc4-11eb-8e87-019ac4de01ac.png)

With this as my `vimrc`
```vim
set nocompatible
set encoding=utf-8
let &runtimepath  = '~/.vim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
```

everything is fine. But with the following, I get the above error:
```vim
call plug#begin('~/.vim/plugged')
	Plug 'lervag/vimtex'
call plug#end()
```

Viminfo output:
```

System info
  OS: Ubuntu 18.04.5 LTS
  Vim version: VIM 8.2 (1-2539)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: test
  base: test.tex
  root: /home/pnr/tmp
  tex: /home/pnr/tmp/test.tex
  out: /home/pnr/tmp/test.pdf
  log: /home/pnr/tmp/test.log
  aux: /home/pnr/tmp/test.aux
  fls: /home/pnr/tmp/test.fls
  main parser: current file verified
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    addqflist: 51
    fix_paths: 52
    set_errorformat: 50
  document class: article
```

**Comment by lervag** [comment] 2021-05-05 19:12
I'm sorry, but I still can't reproduce this. As long as I can't reproduce I find it very hard to debug the issue...

**Comment by lervag** [comment] 2021-05-05 19:15
Do you have any VimTeX configuration, e.g. for the `g:vimtex_toc_config`?

**Comment by lervag** [comment] 2021-05-05 19:18
@patricknraanes Could you do some manual debugging on your side; it seems your error comes from here:

https://github.com/lervag/vimtex/blob/fffa1d7b168cde3af1f175dbf926757af6bae03d/autoload/vimtex/toc.vim#L90-L94

Can you add something like `unsilent echom get(self, 'name', '---')` above the return statement and what the name key is set to?

**Comment by patricknraanes** [comment] 2021-05-06 08:23
> Do you have any VimTeX configuration, e.g. for the `g:vimtex_toc_config`?

Found the culprit! The error goes away without:

```vim
let g:vimtex_toc_config = {'split_pos': 'full'}
```

Apologies for not remembering that I also have plenty of configuration `~/.vim/ftplugin/tex.vim` and so didn't zero in on it myself.

**Comment by lervag** [comment] 2021-05-06 20:19
> > Do you have any VimTeX configuration, e.g. for the `g:vimtex_toc_config`?
> 
> Found the culprit! The error goes away without:
> 
> ```viml
> let g:vimtex_toc_config = {'split_pos': 'full'}
> ```

Does this mean you can show me some configuration in which this error can be reproduced? It might still be a bug...?

**Comment by patricknraanes** [comment] 2021-05-07 13:09
Actually, I can no longer reproduce it myself... I don't know why. I reverted my dotfiles to before the fix, but now there's no error.

**Comment by lervag** [comment] 2021-05-07 13:22
Ok. Then I think I'll take my freedom to close this issue.

**Closed by lervag** 2021-05-07 13:22 UTC
