### ISSUE TITLE
environments with blank lines not recognized

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#386] opened 2016-03-03 13:44 UTC
```tex
\begin{equation}
  a

  c

e
\end{equation}
```
(`vie`)

Expected:
```
a

c

e
```
selected.
What happens instead: Noting selected.

**Comment by Konfekt** [comment] 2016-03-03 13:56
Hmm.. cannnot reproduce it reliably. Sometimes it works, sometimes not.

**Comment by Konfekt** [comment] 2016-03-03 14:00
Well the only exerpt that reliably reprocues it is
```tex
\begin{proof}
  The inclusion holds because $\iota_n (\cR^+) \subseteq \dB_\dR^+$ for all $n$ , and equality holds because more exactly
  \[
    \cap_n \iota_n^{-1} \dB_\dR^+ =
  \]
  and therefore, as by assumption the lowest filtration jump of $\rD_\cris(V)$ is $-h$, for all $n$ in $\N$,
  \[
    \cR_{\Q_{1/p^n}}^{+, r_0} \ox_{\varphi^{-n}_\rst{\cE^+}} \rN(V) \subseteq \Fil^0 ( t^{-h} \cdot \cR_{\Q_{1/p^n}}^{+, r_0} \ox_{\Q_p} \rD_\cris(V) ).
  \]
  where the left-hand side tensor product $\ox_{\varphi_{\rst{\cE^+}}}$ is given by the restriction
  \[
    \varphi^{-n} \from \cE^+ \to \cR^+_{\Q_{1/p^n}}
  \]
  of $\varphi^{-n} \from \cR^{+, r_n}_{\Q_{1/p^n}} \to \cR^{+, r_0}_{\Q_{1/p^n}}$ to $\cE^+$.

  Because the left-hand side and right-hand side module have the same rank and the same elementary divisors as submodule of $ t^{-h} \cdot \cR_{\Q_{1/p^n}}^{r_0} \ox_{\Q_p} \rD_\cris(V) $, the modules are equal for all $n$ in $\N$.

  By \cref{prop:NVoxRpInDcrisVoxRp},
  \[
    \cR^+ \ox_{\cE^+} \rN(V) \subseteq (t/X)^{-h} \cdot \cR^+ \ox_{\Q_p} \rD_\cris(V)
  \]
\end{proof}
```

**Comment by Rmano** [comment] 2016-03-03 14:36
I have the same problem. I can't reliably `vae` this `table` environment: 

```
\begin{table}[htb]
    \centering\small
    \pgfplotstabletypeset[zerofill, fixed,
        column type={r},
        %multicolumn names={c},
        %dec sep align,
        %begin table={\begin{tabular}[b]},
        columns/kr/.style={precision=1, column name={Kryptorad},
            column type/.add={>{\bfseries\boldmath}}{}},
       every head row/.style={before row=\toprule,
            after row={
                \null & (real) & (lin) & (ideal) & (calc) & (calc) & (meas) & (meas) \\
                (\si{\krypt}) & (\si{k\ohm})& (\si{k\ohm}) & (\si{V}) 
                              & (\si{V}) & (\si{V}) & (\si{V}) & (\si{V}) \\
            \midrule}
        },
        every last row/.style={after row=\bottomrule},
        every row no 2/.style={before row={\rowcolor{red!10}}},
        every row no 8/.style={before row={\rowcolor{red!10}}},
    ]{\fullA}
    \vfill
\end{table}
```

The strange thing is that it's a bit of an Heisenbug. Deleting some of the constructs make the `vae` selection working again, and then  after one `undo` it works, but just once --- then it stops working again. 

Did not report before because I am unable to find a reliable example....

**Comment by Konfekt** [comment] 2016-03-03 14:41
Exactly the same Happening over here.

**Comment by lervag** [comment] 2016-03-03 20:33
Neither of the examples reproduce the issue on my end. I copied the environments into an empty `.tex` file and then tested `vie` and `vae`; both works as expected for both of the above environment examples.

**Comment by Konfekt** [comment] 2016-03-03 20:51
This is the `.vimrc`
```vim
set nocompatible
filetype plugin indent on
syntax enable

let &rtp = '~/.vim/plugged/vimtex,' . &rtp

nnoremap g` :lopen<cr>
call plug#begin('~/.vim/plugged')
  Plug 'https://github.com/lervag/vimtex'
call plug#end()
```

**Comment by lervag** [comment] 2016-03-03 21:06
Thanks, I can reproduce it now. I've added test files that work for me.

**Comment by lervag** [comment] 2016-03-03 21:09
Ah, I think I see what the problem is: I think the issue happens whenever the environment spans more than the visible region of the current window.

**Comment by Konfekt** [comment] 2016-03-03 21:19
Oh... never would have expected that this had anything to do with it.

**Comment by lervag** [comment] 2016-03-03 21:21
Yeah, it's because I'm using `line('w0')` and similar for the stopline option to the `searchpos` calls. This is done in order to make things fast enough.

I'll have to investigate how to best solve this, because I don't want to make things too slow either...

**Comment by Konfekt** [comment] 2016-03-03 21:31
Ok. That's too restrictive. Best practice for version control in TeX is putting every sentence on a line. (http://rhodesmill.org/brandon/2012/one-sentence-per-line/)

**Comment by lervag** [comment] 2016-03-03 21:33
I know, though I don't always do that myself. I think I'm going to use 200 lines in each direction. It should suffice for most cases, I think. I'll test if it is fast enough.

**Comment by lervag** [comment] 2016-03-03 21:46
It seems to work well here. Please let me know if you experience lags after the latest update. In that case I can consider some tweaks to make things faster.

**Comment by Konfekt** [comment] 2016-03-03 21:51
Yep, it's working fine.

**Comment by Konfekt** [comment] 2016-03-03 21:51
Thanks!

**Comment by lervag** [comment] 2016-03-03 22:17
No problem!

**Comment by Konfekt** [comment] 2016-03-04 06:37
Perhaps add a FAQ entry to put line breaks for >200 characters  in case people stumble on it. Some colleagues just don't break lines in prose, but only for formulas.

**Comment by lervag** [comment] 2016-03-04 06:57
Ah, no, I think you misunderstood. This has nothing to do with the length of individual lines. It has to do with the number of lines the search performs in each direction. In the previous version, it only searched all lines in the current window. See `:h line(` and read about `w$` and `w0` to see what I mean.

**Comment by Rmano** [comment] 2016-03-04 08:49
Yes, now it's better. It is still a bit surprising sometime --- I mean, I would be quite useful to `vae=` when you're on a `\begin{document}` to reformat all of it without touching the macro definition parts that are sometime tricky...

**Comment by lervag** [comment] 2016-03-04 10:55
@Rmano I've actually excluded `\begin...\end{document}`. My thought was that one never really wants to select the entire document part... perhaps I'm wrong?

I can understand how you find `vae=` useful, but in this case (reformatting everything), can you not do `gg=G`?

**Comment by lervag** [comment] 2016-03-04 10:56
Hmm... I could let the tolerance be an option. If you work on many large tikz pictures, then you could increase it.

**Comment by Rmano** [comment] 2016-03-04 11:40
@lervag --- the problem is that sometime the "macro definition part" is tricky to get indented well... for example when you finish the lines with comments to avoid spaces in the expansion and similar things, so that I normally don't  reformat the preamble part. But yes, it's a matter of going to the `\begin{document}` and then `VG=`... not worth the hassle for a thing used once in a blue moon. 

But I agree for the parameter... I would probably ramp it up a bit. It is possible to add a warning if the motion fails, like a temporary "Closing environment not found in 200 lines" to help discoverability?

**Comment by lervag** [comment] 2016-03-04 12:03
@Rmano Perhaps we could improve the indent rules? Feel free to open an issue for this.

I'll look into the option and perhaps adding a warning.

**Comment by Rmano** [comment] 2016-03-04 14:19
Ok, will open issues when finding... (I have a non-related indent one I'll open in a moment).

**Comment by Konfekt** [comment] 2016-03-04 16:24
Ok, got it. The smaller the window the less likely it used to be. Now it bails out for enviroment bigger than 400 lines.

**Comment by lervag** [comment] 2016-03-05 21:22
Exactly. I'll add an option for this when I get the time. Do either of you experience any lags with the current setting? In particular during insert mode and writing long lines (in large documents)?

**Comment by Konfekt** [comment] 2016-03-05 21:26
Nope, its' instantaneous

**Comment by lervag** [comment] 2016-03-05 21:35
Ok. I'll try to increase to +- 500 lines, then, for the default setting.

**Closed** 2016-03-05 21:44 UTC

**Comment by lervag** [comment] 2016-03-05 21:45
I'll be glad to adjust the default. I don't work on many large documents at the time; the current version seems to work well for me. Please let me know if you think the current default of 500 lines leads to lags.
