### ISSUE TITLE
Help: Getting "Viewer cannot find Zathura window ID" error on MacOS

### ISSUE THREAD

**Issue by lutalli** [lervag/vimtex#2581] opened 2022-11-25 15:47 UTC
### Description

I'm still facing the `Viewer cannot find Zathura window ID` problem when executing the command `\lv` (or `:VimtexView`). I'm working on **MacOS Monterey 12.4**.

I followed [this tutorial](https://www.ejmastnak.com/tutorials/vim-latex/pdf-reader.html#zathura-on-intel-macs) to setup `zathura`, but it's basically the same as what [this comment](https://github.com/lervag/vimtex/issues/1737#issuecomment-759953886) summarises, since the tutorial actually refers to it.

Recall that I installed `zathura` with `--HEAD --with-synctex` and it is able to open PDF files normally (like `$ zathura "xxx.pdf"`) but not with `VimTeX`.

Two problems that could be relevant:

## Problem with `dbus`

`dbus` can get **started** but **not running**. After installing `dbus` using Homebrew
```
$ brew install dbus
```
I tried starting it first by the command
```
$ brew services start dbus
```
where I got the following error:
```
Bootstrap failed: 5: Input/output error
Try re-running the command as root for richer errors.
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/lutalli/Library/LaunchAgents/org.freedesktop.dbus-session.plist` exited with 5.
```
Then I checked `brew services info dbus`, which returned
```
dbus (org.freedesktop.dbus-session)
Running: ✘
Loaded: ✔
Schedulable: ✘
```
which meant that it was loaded already. So my guess was that I can't start it when it's already started. To verify this, I stopped `dbus`:
```
$ brew services stop dbus
Stopping `dbus`... (might take a while)
==> Successfully stopped `dbus` (label: org.freedesktop.dbus-session)
```
and tried starting it again, which succeeded:
```
$ brew services start dbus
==> Successfully started `dbus` (label: org.freedesktop.dbus-session)
```
In addition, I also tried **restarting** it (which is supposed to do the same thing):
```
$ brew services restart dbus
Stopping `dbus`... (might take a while)
==> Successfully stopped `dbus` (label: org.freedesktop.dbus-session)
==> Successfully started `dbus` (label: org.freedesktop.dbus-session)
```
Anyway, it **looks like** that `dbus` can be started normally. However, everytime I run `brew services info dbus` it shows that `dbus` is **not running** even though it's loaded:
```
$ brew services info dbus
dbus (org.freedesktop.dbus-session)
Running: ✘
Loaded: ✔
Schedulable: ✘
```
I suppose it should be running, as [the tutorial](https://www.ejmastnak.com/tutorials/vim-latex/pdf-reader.html#zathura-on-intel-macs) suggests:

<img width="790" alt="image" src="https://user-images.githubusercontent.com/47910890/203330639-23f423b3-9ed4-4ed9-a1f3-8fb84dc70161.png">

Rebooting MacOS and restarting the terminal (iTerm2 in my case) didn't work.

I tried the command `brew services run dbus` but I got a similar error as above:
```
$ brew services run dbus
Bootstrap failed: 5: Input/output error
Try re-running the command as root for richer errors.
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /usr/local/opt/dbus/org.freedesktop.dbus-session.plist` exited with 5.
```
[This discussion](https://github.com/Homebrew/discussions/discussions/2318) describes a similar case but it didn't mention how to get it running.

I also tried some solutions from the answers to [this question](https://stackoverflow.com/questions/68975769/brew-services-cant-start-service-get-bootstrap-failed-5-input-output-error) on StackOverflow but so far none of them worked for me.

## Problem with `xdotool`

`xdotool` doesn't work at all. I installed it with `Homebrew` as well as `XQuartz`. Although the installation seemed successful, almost none of its functions is working - for example, `xdotool search` never returns anything and `xdotool type` does nothing (also notice that no errors nor warnings are returned):
```
$ xdotool search discord
Defaulting to search window name, class, classname, and role

$ xdotool type "hello"

$
```
[This issue](https://github.com/jordansissel/xdotool/issues/257) very likely describes the same case. The description is relatively short but the issue has got a couple of thumb-ups so I guess it's a common issue. I haven't found any solution yet.

I assume `xdotool` is necessary because, as this thread mentioned before, as well as in [the tutorial](https://www.ejmastnak.com/tutorials/vim-latex/pdf-reader.html#zathura-on-intel-macs), `VimTeX` uses `xdotool` to get the window ID of `zathura`.

---

Any idea how to solve these?

### Steps to reproduce

Minimal test `.tex` file:
```tex
\documentclass{article}

\begin{document}
    Test
\end{document}
```

Steps to reproduce:

1. `nvim minimal.tex`
2. `\lv` or `:VimtexView`
3. Seeing it shows the error `VimTeX: Viewer cannot find Zathura window ID!`

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  OS: macOS 12.4 (21F79)
  Vim version: NVIM v0.8.1
  Has clientserver: true
  Servername: /var/folders/zx/08zvm7jx3k70j_1_nyt1lc_80000gn/T/nvim.lutalli/Q5PK1q/nvim.30467.0

VimTeX project: textest
  base: textest.tex
  root: /Users/lutalli/Workspace/TeXTest
  tex: /Users/lutalli/Workspace/TeXTest/textest.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 0
    executable: latexmk
  viewer: Zathura
    xwin id: 0
    cmd_start: zathura  -x "/usr/local/Cellar/neovim/0.8.1/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 1:1:'/Users/lutalli/Workspace/TeXTest/textest.tex' 'textest.pdf'&
  qf method: LaTeX logfile
```

**Comment by lervag** [comment] 2022-11-26 10:18
First, thanks for a thorough and good issue description!

Now, just to be clear: I don't use Macs and I require user assistance for properly helping with "advanced" issues affecting Macs. @ejmastnak and @clason (and others) have been very friendly and have often stepped in to help; I hope they may also comment here if they have any useful input or insights.

----

> I followed [this tutorial](https://www.ejmastnak.com/tutorials/vim-latex/pdf-reader.html#zathura-on-intel-macs) to setup `zathura`, but it's basically the same as what [this comment](https://github.com/lervag/vimtex/issues/1737#issuecomment-759953886) summarises, since the tutorial actually refers to it.

I'm curious: did you notice the warning in the tutorial about Macs with Apple Silicon processors? That is, do you have an Intel processor or an AS processor?

> `dbus` can get **started** but **not running**. After installing `dbus` using Homebrew

This does seem similar to the symptoms reported in #2424 where the Apple Silicon issue was raised first.

> ## Problem with `xdotool`
> 
> `xdotool` doesn't work at all. I installed it with `Homebrew` as well as `XQuartz`. Although the installation seemed successful, almost none of its functions is working - for example, `xdotool search` never returns anything and `xdotool type` does nothing

`xdotool` only works with X windows, which means it will not have any effect unless there are active X windows available. Can you do this:
* Run `xdotool search --class zathura`. It should likely not output anything (and will return with an exit code not 0).
* Open Zathura in a terminal (e.g. `zathura test.pdf&`).
* Then again run `xdotool search --class zathura`. Does it output anything now?

**Comment by lutalli** [comment] 2022-11-27 12:31
Thanks for the reply.

Yes, I did notice the warning that the section is written for Intel Macs and not for Apple Silicon. **My Macbook uses an Intel processor** so I assume it's the right section for me.

I've tried running `xdotool search --class zathura` after opening `zathura` in a terminal (I had to open up a new terminal window to run `xdotool` since `zathura` blocked the input) and it returned nothing like when I didn't open `zathura`.

```
(zathura not running)
$ xdotool search --class zathura

$ zathura test.pdf

(zathura running)
(new terminal window)
$ xdotool search --class zathura

$
```

In the issue description I mentioned that **none** of the features of `xdotool` is functioning, not only `search` (for example, key input doesn't work as well). But just now I tested a little more and here's the result:

- Key input through `xdotool` didn't work in `iTerm2` (the major terminal I'm using), but it worked in the `XTerm` terminal from `XQuartz`. (Key input isn't relevant to our issue though.)
- Common applications running on my Mac (like Discord, Google Chrome) as well as `zathura` can't be found by `xdotool`, neither in `iTerm2` nor in `XTerm`. However, I just noticed that `XTerm` itself can be detected in both `iTerm2` and `XTerm`:
```
$ xdotool search --class xterm
6291468
```
- It doesn't help to run `zathura` from `Xterm`. `xdotool` still can't find it.
- The same situation holds for `xprop`. That is, `xprop` doesn't seem to detect any window but `XTerm`.

Thus the `search` command of `xdotool` is actually not broken. The real problem might be that `zathura` isn't running as an X window on my Mac, like other usual applications, that's why it can't be caught by `xdotool`. So I think I should look for a way to run `zathura` on X server.

**Comment by ejmastnak** [comment] 2022-11-28 10:02
I'm afraid I don't have anything useful to offer here; why the instructions in `vimtex-faq-zathura-macos`/the linked article seem to work in some cases and not others is beyond the scope of my macOS knowledge. Perhaps the non-starting dbus is not an Apple Silicon issue after all.

@lutalli seems to be very thorough about checking all possibilities and previous related issues, so I doubt the problem is something we've already solved, e.g. a missing environment variable in #2391.

 In any case, @lutalli, I'm sorry to be spreading unpredictable information about Zathura working with VimTeX on macOS; probably Skim is the most reliable route in this case.

**Comment by lutalli** [comment] 2022-11-28 14:13
Hi @ejmastnak, I can guarantee that I have defined the `DBUS_SESSION_BUS_ADDRESS` variable, as I followed the tutorial on your website. I use `fish` as shell and in `config.fish` I added the line
```fish
set -x DBUS_SESSION_BUS_ADDRESS "unix:path=$DBUS_LAUNCHD_SESSION_BUS_SOCKET"
```
(`set -x` basically means `export`)

Output of `echo`:
```
$ echo $DBUS_SESSION_BUS_ADDRESS
unix:path=/private/tmp/com.apple.launchd.SFe0NEmqcf/unix_domain_listener
```

> ...; probably Skim is the most reliable route in this case.

Yes, Skim must be a feasible option for MacOS. Yet I would like to try my best to make `zathura` in use. I'm a fan of its simplicity and Vim style operations, rather than GUI buttons and menus.

**Comment by lutalli** [comment] 2022-11-28 14:14
I'm not sure if this is relevant but I have also seen issue [#744](https://github.com/lervag/vimtex/issues/744), which is asking how to force `zathura` to use X11. Without understanding it fully I tried the command `$ GDK_BACKEND=x11 zathura` but I got the following error:

```
$ GDK_BACKEND=x11 zathura

(zathura:32498): Gtk-WARNING **: 15:04:02.253: cannot open display: /private/tmp/com.apple.launchd.TSRvBvZs9k/org.xquartz:0
```

**Comment by lervag** [comment] 2022-11-29 22:24
Thanks for pitching in, @ejmastnak; it is useful just knowing that you do not have any better ideas yourself.

And I'm sorry, @lutalli, that I can't be of much more help here. It seems like you are doing a good job investigating on your own, although I'm sorry to see that you are not really finding any good solutions.

I'll allow the issue to stay open for now, but if it ends up open without activity I may close it as unresolved. Please note that I don't mind if you should reopen in that case, as long as you bring new information to the thread.

**Comment by lutalli** [comment] 2022-11-29 22:34
@lervag Let's do so. Thanks!

**Comment by lervag** [comment] 2023-02-21 20:03
You may be interested in #2639.

I'll close this one as I don't see any way to contribute more here.

**Closed by lervag** 2023-02-21 20:03 UTC
Labels: bug
