### ISSUE TITLE
]] can't close an inline equation's dollar if it appears in a command

### ISSUE THREAD

**Issue by Aster89** [lervag/vimtex#1231] opened 2018-09-25 06:23 UTC
(During the following troubleshooting, the **syntax coloring is meaningful**.)

**Reproduce the problem.**
- Open a new `hello.tex` file, write the following lines in it
```
\begin{document}
\somecommand{Can the following $x be closed by hitting twice the closing square bracket?}
```
where there's no closing dollar in the command.
- Now put the cursor in insert mode anywhere in the command's argument, but *after* the opening dollar, and hit `]]`. The dollar will be correctly closed.
- Change `\begin{document}` to `\chapter{mychap}` or `\section{anything}`, ... The `]]` will still do the job.
- Finally do a typo in `begin`, `document`, `chapter`, or whatever (to simulate a custom environment or command), or simply remove that line (a file to be `input`ed or `include`d can be like that, indeed). After this, the `]]` will mistakenly close the brace instead of the dollar.

**Hypothesis**
I've investigated a bit and it seems to me that `s:get_delim` returns a wrong `l:result.match` in the case of the last bullet point, specifically the mistaken closing character appears at the line 447 of `autoload/vimtex/delim.vim` at the time of writing (commit `d16ae14`); but I could not go further since lines 427-445, in which I think the problem is located, would require too much time for me to understand.

**Minimal `~/.vimrc`**
```
" load here vimtex with your plugin manager
syntax enable
let g:tex_flavor = 'latex'
```

**Comment by lervag** [comment] 2018-09-25 06:39
> Finally do a typo in begin, document, chapter, or whatever (to simulate a custom environment or command), or simply remove that line (a file to be inputed or included can be like that, indeed). After this, the ]] will mistakenly close the brace instead of the dollar.

I do not quite understand how the example should look. Can you please write out an example of how things look when `]]` behaves unexpectedly?

**Comment by Aster89** [comment] 2018-09-25 06:49
If the content of the tex file is
```
\somecommand{Can the following $x be closed by hitting twice the closing square bracket?}
```
hitting `]]` after the x, produces
```
\somecommand{Can the following $x} be closed by hitting twice the closing square bracket?}
```

**Comment by Aster89** [comment] 2018-09-25 07:06
The minimal `~/.vimrc` is
```
" load here vimtex with your plugin manager
syntax enable
let g:tex_flavor = 'latex'
```

**Comment by lervag** [comment] 2018-09-25 21:38
The reason this breaks is because I rely on syntax groups to match the inline math. This is because it is really hard to match delimited stuff without unique left/right delimiteres, and since the problem is already solved for syntax highlighting, it becomes much easier to simply check the syntax group to determine if `$` is a closing or opening delimiter.

So, in which case is this issue a real issue for you? Can you give an example where you would expect things to work, but they don't?

**Comment by Aster89** [comment] 2018-09-25 21:57
Oh, so the syntax is definitely more than meaningful, it is the reason for the "bug".

For what concerns the example, it is the one in my preceding message: that single line could be the first line in a file that is `input`ed or `include`d in the main file.

Another example, which didn't come to my mind when I posted this issue, is the following. Put these lines in a file
```
\chapter{Hello}
\begin{figure}[h]
    \centering
    \includegraphics{name.ext}
    \caption{Name}
    \label{fig:name}
\end{figure}
```
then try to add `[width=\textwidth]` to the `\includegraphics` command. If you try to close the option hitting `]]`, a `}` will be inserted instead, and the line is indented back 1 tab. Note that in this case, unlike the one with the `$`, the problem is affecting a closing delimiter (`]`) which does not coincide with its opening counterpart (`[`).

This is really a minor problem, sure, it just costs a few keystrokes (in the `figure` example I just have to hit <kbd>Esc</kbd>, <kbd>R</kbd>, <kbd>]</kbd> to correct the mistaken closing character, and <kbd>></kbd>, <kbd>></kbd> to re-indent the line), but maybe it could be solved somehow.

**Comment by lervag** [comment] 2018-09-27 19:05
Ok, I think this is fixed. I have to admit I am not 100% sure there are no bad side effects to this, but I'm thinking it's worth a shot. If anyone should experience a problem due to this, we can revert and either ignore this problem or build a new logic.

**Closed** 2018-09-27 19:04 UTC
