### ISSUE TITLE
question about map of vimtex

### ISSUE THREAD

**Issue by Freed-Wu** [lervag/vimtex#1783] opened 2020-08-23 15:51 UTC
In `autoload/vimtex.vim` Line 35, there is
```{.vim}
silent execute a:mode . 'map <silent><nowait><buffer>' a:lhs a:rhs
```

In some case, i just only need to read other one's tex files and not need to edit them, some plugin allows me to use some maps of less: they map <kbd>d</kbd> to <kbd>Ctrl</kbd>+<kbd>d</kbd> and <kbd>u</kbd> to <kbd>Ctrl</kbd>+<kbd>u</kbd> to help user read file more convenient.

however, the `<nowait>` in this line make every time user presses <kbd>d</kbd>, they need to wait a short time because some keymaps (i.e. `dse`) has been maped. Even if i manually use `<nowait>` map, it also need wait because these map of vimtex is also nowait.

so, can i know the nowait in this line has any necessary reason, please? or user can have some method to avoid a short-time waiting?

thanks! i am truly glad to know this splendid plugin and acknowledge you.

**Comment by lervag** [comment] 2020-08-23 17:17
> In some case, i just only need to read other one's tex files and not need to edit them, some plugin allows me to use some maps of less: they map d to Ctrl+d and u to Ctrl+u to help user read file more convenient.

I personally find such mappings a little bit disturbing. Vim motions are already very accessible, and IMHO it feels better to just master the default motions.

However, I don't mind people having different opinions, and I'll be happy to try and find a solution here.

> so, can i know the nowait in this line has any necessary reason, please? or user can have some method to avoid a short-time waiting?

I can't really say a specific reason, other than that _removing_ `<nowait>` can lead to unexpected behaviour when users have partly conflicting mappings. I might be convinced to remove the `<nowait>` as a default and instead apply it specifically where it may be necessary. I'm curious if someone else have a suggestion/opinion here (@Konfekt @kiryph comes to mind as people with experience with vimscript).

A simple way to prevent mappings right now is to remap them yourself. E.g. something like this: `nnoremap <nop>123 <plug>(vimtex...)`. However, you would need to modify it so it only occurs in your "read only mode".

> thanks! i am truly glad to know this splendid plugin and acknowledge you.

Thanks!

**Comment by Konfekt** [comment] 2020-08-23 19:19
From how I understand `<nowait>`, the less plug-in should add `<nowait>` to the `d` mapping to avoid the delay. The delay occurs if there is any other map starting with `d`, independent of vimtex adding it for those mappings.

**Comment by Freed-Wu** [comment] 2020-08-24 07:40
> From how I understand `<nowait>`, the less plug-in should add `<nowait>` to the `d` mapping to avoid the delay. The delay occurs if there is any other map starting with `d`, independent of vimtex adding it for those mappings.

this is a simple test:

```{.vim}
nmap <nowait> d <C-d>
nmap <nowait> dse <nop>
```

vim will wait for a short time after user presses <kbd>d</kbd> because they both have `<nowait>`...

**Comment by Freed-Wu** [comment] 2020-08-24 07:54
> I can't really say a specific reason, other than that removing <nowait> can lead to unexpected behaviour when users have partly conflicting mappings. I might be convinced to remove the <nowait> as a default and instead apply it specifically where it may be necessary. I'm curious if someone else have a suggestion/opinion here

perhaps can provide a variable which name looks like `g:vimtex_mappings_nowait_enable` to contol it? like

```{.vim}
silent execute a:mode . 'map <silent>' . (get(g:, 'vimtex_mappings_nowait_enable', 0) ? '' : '<nowait>') . '<buffer>' a:lhs a:rhs
```

just a rough advice...

**Comment by Konfekt** [comment] 2020-08-24 12:07
> > From how I understand `<nowait>`, the less plug-in should add `<nowait>` to the `d` mapping to avoid the delay. The delay occurs if there is any other map starting with `d`, independent of vimtex adding it for those mappings.
> 
> this is a simple test:
> 
> ```
> nmap <nowait> d <C-d>
> nmap <nowait> dse <nop>
> ```
> 
> vim will wait for a short time after user presses d because they both have `<nowait>`...

This looks like a Vim issue that could be discussed at [vim/vim](https://github.com/vim/vim) because `:help nowait` says that the shorter map should not wait for the longer.

**Comment by lervag** [comment] 2020-08-24 16:18
@Konfekt I think the behaviour of `<nowait>` is more complex. In particular, it only matters in "conflicts" between buffer local and global mappings. E.g.:

```vim
" These two mappings work as "expected", in that the buffer mapping for "e"
" will be executed immediately
nmap ese <nop>
autocmd FileType tex nmap <buffer> <nowait> e <C-d>

" These two mappings do not work as expected, because they are of "equal rank".
" So, "e" now has to wait since "ese" is also defined locally.
autocmd FileType tex nmap <buffer> ese <nop>
autocmd FileType tex nmap <buffer> <nowait> e <C-d>

" Again, the <nowait> does not do anything, because it only works from the
" "local" side
nmap <nowait> e <c-d>
autocmd FileType wiki nmap <buffer> ese <nop>
```

I still partly agree that this behaviour is unexpected. I think I've added `<nowait>` because it "felt" right, but now I think perhaps I should just remove it altogether from the main mappings.

@Freed-Wu I don't want to add an option, because I feel like this should be possible to solve without options.

So, I'm still looking for a reason why _not_ to remove `<nowait>`.

**Comment by Konfekt** [comment] 2020-08-25 07:55
If there is a built-in mapping of no use where the plug-in mapping is meant to be used. For example, `q:` and `q` to close the TOC.

**Comment by lervag** [comment] 2020-08-25 08:10
I've searched the history and found that the addition of `<nowait>` is due to @lacygoill from #1254 and commit (6e41c537a90195c6c4f6cd20ce270eb9d30a6d67). I then thought this would always make sense, but I now see that it might not make sense in all cases.

I'll partly reverse it and only apply the `<nowait>` where it seems to make sense.

**Comment by lacygoill** [comment] 2020-08-25 08:20
> this is a simple test:

>     nmap <nowait> d <C-d>
>     nmap <nowait> dse <nop>

> vim will wait for a short time after user presses d because they both have <nowait>...

I don't understand the issue, but – in this example – Vim waits even without `<nowait>`.

    vim -Nu NONE -S <(cat <<'EOF'
        set showcmd timeoutlen=3000
        nmap d <C-d>
        nmap dse <nop>
    EOF
    )

**Comment by lervag** [comment] 2020-08-25 08:26
The `<nowait>` keyword only applies on conflicts between a local mapping and a global mapping. Essentially, between a mapping with `<buffer>` and one without. As far as I can see, it only affects the behaviour if a `<buffer>` mapping matches the keys at a certain point where a global mapping also matches, in which case `<nowait>` will immediately activate the `<buffer>` mapping. However, `<nowait>` does not matter on "conflicts" between two or more `<buffer>` mappings or between two or more non-`<buffer>` mappings.

I'm curious if the original issue would really be resolved by removing the `<nowait>`, though, since, as shown in my previous comment:

```vim
autocmd FileType tex nmap <buffer> ese <nop>
autocmd FileType tex nmap <buffer> <nowait> e <c-d>
```

`e` still waits for `ese`, because both mappings are buffer local. @Freed-Wu?

**Comment by lacygoill** [comment] 2020-08-25 08:29
> The <nowait> keyword only applies on conflicts between a local mapping and a global mapping. Essentially, between a mapping with <buffer> and one without. As far as I can see, it only affects the behaviour if a <buffer> mapping matches the keys at a certain point where a global mapping also matches, in which case <nowait> will immediately activate the <buffer> mapping. However, <nowait> does not matter on "conflicts" between two or more <buffer> mappings or between two or more non-<buffer> mappings.

Yes, `<nowait>` only works for local mappings, and only if the mapping was installed after the global ones:

    vim -Nu NONE -S <(cat <<'EOF'
        set showcmd timeoutlen=3000
        nno <nowait> <c-b>  :echo "c-b was pressed"<cr>
        nno          <c-b>x <nop>
    EOF
    )

    " press C-b: you need to wait 3s for the message to be printed

    vim -Nu NONE -S <(cat <<'EOF'
        set showcmd timeoutlen=3000
        nno          <c-b>x <nop>
        nno <nowait> <c-b>  :echo "c-b was pressed"<cr>
    EOF
    )

    " press C-b: the message is printed immediately

**Comment by lervag** [comment] 2020-08-25 08:47
Ah, so my understanding was not complete: You _can_ use `<nowait>` between two global mappings. Perhaps a full rule is more like this: `<nowait>` implies that a mapping will be executed immediately, unless

1. There exists a `<buffer>` mapping that conflicts.
2. A conflicting mapping has been added _after_ the `<nowait>` mapping.

This again explains why we should not add `<nowait>` as a default option for all buffer local maps, since it makes it impossible for users to customize on top. We should only add `<nowait>` to explicitly avoid delays on existing conflicts. Here it seems `nnoremap <buffer><nowait> q ...` is a good example. I don't see other examples right now, but I'll make sure to check every map before I remove the `<nowait>`.

Or am I wrong?

**Comment by lacygoill** [comment] 2020-08-25 09:47
I've deleted my previous comment because I thought it was irrelevant to the current issue, and introduced confusion; sorry if I was wrong.

I just don't understand this issue.  I have been using `<nowait>` in all my buffer-local mappings for years, and never had any issue.  On the contrary, it *fixed* issues.

I've re-read the OP.  It seems the issue is that the user has a global mapping which is triggered by `d`, and when they press `d`, they have to wait because vimtex has installed a mapping on `dse`.  If that's the issue, then removing `<nowait>` will not fix anything.  You'll still have a timeout.  I've just checked after applying this patch:
```diff
diff --git a/autoload/vimtex.vim b/autoload/vimtex.vim
index 4780f67e..bf202ea6 100644
--- a/autoload/vimtex.vim
+++ b/autoload/vimtex.vim
@@ -336,7 +336,7 @@ function! s:map(ftype, mode, lhs, rhs, ...) abort " {{{1
         \ && (a:0 > 0
         \     || g:vimtex_mappings_override_existing
         \     || empty(maparg(a:lhs, a:mode)))
-    silent execute a:mode . 'map <silent><nowait><buffer>' a:lhs a:rhs
+    silent execute a:mode . 'map <silent><buffer>' a:lhs a:rhs
   endif
 endfunction
```
And starting Vim with this shell command:

    vim -Nu /tmp/vimrc /tmp/tex.tex

With this minimal vimrc:
```vim
set rtp-=~/.vim
set rtp-=~/.vim/after
set rtp^=~/.vim/plugged/vimtex
set rtp+=~/.vim/plugged/vimtex/after

nno <nowait> d :echom 'hit d'<cr>
let g:tex_flavor = 'latex'

set showcmd timeoutlen=3000
filetype plugin on
```
When I hit `d`, I still have to wait for the timeout.
If the user wants `d` to be triggered immediately, the only solution I can think of is to remove all local mappings starting with `d`.

Unless someone posts a minimal example showing that `<nowait>` introduces an undesirable timeout, I would like `<nowait>` to remain; it prevents an undesirable timeout when the user has a conflicting global mapping.

**Comment by lervag** [comment] 2020-08-25 09:56
> I've re-read the OP. It seems the issue is that the user has a global mapping which is triggered by d, and when they press d, they have to wait because vimtex has installed a mapping on dse. If that's the issue, then removing <nowait> will not fix anything. You'll still have a timeout. I've just checked after applying this patch:

Yes, I have been thinking the same thing. I think, however, that the OP is using a _buffer_ mapping, in which case his point is valid.

Note, I won't remove the `<nowait>` arguments unless it is clear that removing them actually fixes something. But I'm not properly convinced that they should be used as a default argument just because

> it prevents an undesirable timeout when the user has a conflicting global mapping.

That is, unless the global mapping is a default one or something that one should expect a user to do. Also, it would be very nice to get one or more examples of _actual_ conflicts.

**Comment by lacygoill** [comment] 2020-08-25 10:23
> I think, however, that the OP is using a buffer mapping, in which case his point is valid.

I still can't reproduce the issue.  I've restored `<nowait>` in vimtex, and used this vimrc:
```vim
set rtp-=~/.vim
set rtp-=~/.vim/after
set rtp^=~/.vim/plugged/vimtex
set rtp+=~/.vim/plugged/vimtex/after

let g:tex_flavor = 'latex'

set showcmd timeoutlen=3000
filetype plugin on

au VimEnter * nno <buffer><nowait> d :echom 'hit d'<cr>
```
When I press `d`, the mapping is triggered immediately.

> But I'm not properly convinced that they should be used as a default argument just because

>    it prevents an undesirable timeout when the user has a conflicting global mapping.

> That is, unless the global mapping is a default one or something that one should expect a user to do. Also, it would be very nice to get one or more examples of actual conflicts.

I think we'll just have to disagree; I find it unexpected that a local mapping suffers from a timeout because of a global mapping, no matter its origin.  But it's your plugin, and if you think `<nowait>` causes an issue, I won't argue against its removal anymore.

**Comment by lacygoill** [comment] 2020-08-25 10:27
Ah my bad.  The example I provided shows that indeed, removing `<nowait>` could help the user if they have buffer-local mappings.

**Comment by lacygoill** [comment] 2020-08-25 10:28
Actually no, it does not.

**Comment by lacygoill** [comment] 2020-08-25 10:36
Ah my bad.  The example I provided shows that indeed, removing `<nowait>` could help the user if they have buffer-local mappings.

Actually no, it does not.

Yes, even if the OP uses buffer-local mappings, `<nowait>` still does not cause a timeout; the timeout is caused by the existence of mappings which start with `d`.  And if they do use local mappings, then they can avoid the timeout by using `<nowait>`:

    nnoremap <buffer><nowait> d :echom 'I hit d'<cr>
                     ^------^

Again, the fact that vimtex uses `<nowait>` has nothing to do with the timeout.

**Comment by lervag** [comment] 2020-08-25 21:37
Thanks, @lacygoill, I think you are right. I've updated my [previous comment where I've tried to summarize how `<nowait>` works](https://github.com/lervag/vimtex/issues/1783#issuecomment-679892935). Let's wait for a response from @Freed-Wu before closing, though.

> Again, the fact that vimtex uses <nowait> has nothing to do with the timeout.

As of now, I think you are right about this. Merely the fact that vimtex defines `dse` will override the `<nowait>` of any mapping that is already defined.

**Comment by Konfekt** [comment] 2020-08-26 07:00
As a side note, the Vim doc on `:help nowait` would be clearer by including this discussion; in particular @lervag 's summary https://github.com/lervag/vimtex/issues/1783#issuecomment-679892935.

**Comment by lervag** [comment] 2020-08-26 07:10
Yes, I agree with that. Perhaps I should raise a PR for Vim?

**Comment by lacygoill** [comment] 2020-08-26 07:43
> Perhaps I should raise a PR for Vim?

I regularly see the documentation be improved or fixed on the Vim's bug tracker.  You could either submit a PR or open an issue to discuss your observations further.  FWIW, I think your analysis is correct.  IMO, the most important part is the fact that the chronological order of the mappings installation matters, and that `<nowait>` can only suppress the timeout of an *existing* conflicting mapping; not future conflicting mappings.
```vim
set showcmd timeoutlen=3000
nno <buffer><nowait> cda :echom 'I hit cda'<cr>
nno <buffer><nowait> cd :echom 'I hit cd'<cr>
```
Here `cd` is instantaneous – even though both mappings were defined with `<nowait>` – because it was installed last.
```vim
set showcmd timeoutlen=3000
nno <buffer><nowait> cd :echom 'I hit cd'<cr>
nno <buffer> cda :echom 'I hit cda'<cr>
```
And here `cd` is no longer instantaneous, because this time the conflicting mapping was installed later.  It doesn't matter whether the latter was defined with `<nowait>`.  What matters is that it was installed later.

**Comment by Konfekt** [comment] 2020-08-26 15:14
If I follow @lacygoill correctly, then @lervag 's observation that execution is delayed if

>     It [the mapping] is global and there exists a conflicting <buffer> mapping.

is subsumed by later addition of a conflicting mapping. That is, execution of a <nowait> mapping is delayed if a conflicting mapping is added later on, if added before its execution immediate.

**Comment by Konfekt** [comment] 2020-08-26 15:21
One could ask at `vim/vim` if this behavior is considered a feature to be documented or better be fixed.

**Comment by lervag** [comment] 2020-08-30 09:54
I've opened an issue: https://github.com/vim/vim/issues/6810

With that I think we can close this issue.

**Closed by lervag** 2020-08-30 09:54 UTC
Labels: enhancement
