### ISSUE TITLE
Changing PDF viewer to Skim (Part II)

### ISSUE THREAD

**Issue by cmarshak** [lervag/vimtex#204] opened 2015-07-17 13:15 UTC
Dear Dr. Lervag and VimTex,

This is a continuation of https://github.com/lervag/vimtex/issues/175.  I am using MacVim on Yosemite.

I am trying to get Skim to work with vimtex, and have not succeeded.  The documentation seems contradictory to some of the bug fix above, at least it appears that way to a new vim-user like myself.

In the docs, it suggests:

(1) To paste the code in the .vimrc:

    let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
    let g:vimtex_view_general_options = '@line @pdf @tex'`

(2) And add the following to the .latexmkrc:

    $pdflatex = 'pdflatex -synctex=1 %O %S';

When I do this, the command `<leader>ll` does not open anything (normally preview is opened).

When I remove the above and include the following as suggested in #175:

    let g:vimtex_view_general_viewer = 'open' 
    let g:vimtex_view_general_options = '-a Skim'

Preview opens upon hitting `<leader>ll`.  I have been trying a bunch of different combinations of the above without any luck.  I like this vim-tex extension because of the exceptional documentation.  The site hosting vim-latex-suite was down yesterday, too.

I got this answer for the latex-suite:

    map ,ls :w<CR>:silent !make <CR>:silent !/Applications/Skim.app/Contents/SharedSupport/displayline -r <C-r>=line('.')<CR> %<.pdf %<CR><CR>

and this always works.  The above is courtesy of:

https://skyuuka.wordpress.com/2014/07/11/setup-synctex-with-vim-pdflatex-and-skim/
http://molecularclouds.blogspot.sg/2012/01/latex-vim-skim.html

I guess I could map `<leader>ll` to a combination of the above and it's current status, but thought I would let you know about the obstacle.

Any suggestions on how to fix it would be appreciated.  Even tangential comments about the framework of this bundle would be awesome because I want to learn more about vim and how it works.

**Comment by lervag** [comment] 2015-07-17 21:00
Dear @cmarshak,

Since #175, I've made some updates and simplifications to the viewer code. In particular, I've implemented a placeholder scheme where `@pdf`, `@tex`, and `@line` indicates that the viewer should insert the current pdf file name, tex file name and line number (respectively).

I would like you to try a couple of things:

1. Try to set

     let g:vimtex_view_general_options = '-r @line @pdf @tex'`

2. Remove settings in your `.latexmkrc` file, in particular remove these: `$pdf_previewer` and `pdf_update_method`.

If things still are not working, please do the following:

1. Provide me with the content of your `latexmkrc` file.
2. Provide me with your vimtex settings.
3. Open a LaTeX file with the suggested options according to the documentation.
4. Do `<leader>ll` (if things are not working, then the viewer should not open now).
5. Provide me the output from `<leader>li`.
6. Provide me the output from `<leader>lo`.

This will probably generate a lot of information, but that will help me to locate the problem. Unfortunately, I don't use OSX, and so it is difficult to debug such problems for me.

**Comment by pdf** [comment] 2015-07-17 22:01
`Code tags` please.  Do not want notifying.

**Comment by cmarshak** [comment] 2015-07-17 22:30
Working great now!  Thank you.

Just to recap because I am still learning the Plugin's "intended" workflow.  Once I save using `:w`, latexmk is by default in continuous mode and will automatically compile.

Then, to view the pdf, I type `<leader>lv` and the pdf is shown in skim highlighting and pointing where the current cursor is in the .tex file.

When I type `<leader>ll`, either it compiled successfully and read `latexmk compile: success (FILENAME.tex)`.  OR it read `latexmk compile: stopped (FILENAME.tex)`.  Either way Skim did *not* open.  If this is not intended then, I can give the requested information.

So far this is awesome and I am really thankful!

For others wishing to use this Plugin, my `~/.latexmkrc` file has:
   $pdflatex = 'pdflatex -synctex=1 %O %S';
And my `.vimrc` has:
   let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
   let g:vimtex_view_general_options = '-r @line @pdf @tex'
   let g:vimtex_fold_enabled = 0 "So large files can open more easily

**Comment by lervag** [comment] 2015-07-18 08:34
Your recap of the work flow seems mostly good. Except for one thing: `<leader>ll` will first start background compilation with `latexmk`. When the document has successfully compiled once, `latexmk` will then automatically open the previewer for us. Note that this is NOT done by vimtex directly, although vimtex does pass some settings to latexmk for it to choose the correct pdf viewer.

If the document is already compiling, then `<leader>ll` will stop the  compilation.

So, to investigate why the viewer is not automatically opening, could you please provide the output from `<leader>li` and `<leader>lo` after opening a document and after starting the compilation?

**Comment by cmarshak** [comment] 2015-07-18 20:50
Thank you for all your help, Dr. Lervåg.

<img width="877" alt="screen shot 2015-07-18 at 1 46 08 pm" src="https://cloud.githubusercontent.com/assets/5975894/8763496/81801f68-2d53-11e5-91de-1e0ffda0ce92.png">
<img width="847" alt="screen shot 2015-07-18 at 1 47 25 pm" src="https://cloud.githubusercontent.com/assets/5975894/8763497/8f6bce1a-2d53-11e5-9e11-ea24d177133a.png">

**Comment by lervag** [comment] 2015-07-18 21:00
Thanks. Could you repeat `<leader>li` _after_ you have started compilation? (The output provided in the last post was before you started compilation, which I see because `pid : 0` says that the PID for the latexmk process is 0, i.e., not existing.

**Comment by cmarshak** [comment] 2015-07-18 21:02
No problem.
<img width="1431" alt="screen shot 2015-07-18 at 2 02 03 pm" src="https://cloud.githubusercontent.com/assets/5975894/8763529/abe603c4-2d55-11e5-8f24-6017151da58d.png">

**Comment by lervag** [comment] 2015-07-18 21:07
I can't see exactly what is wrong, but I see that `start` appears twice in the `pdf_previewer` setting (from the `<leader>lo` output). Could you try again with the latest patch?

**Comment by lervag** [comment] 2015-07-18 21:09
Also, could you open a terminal and try to open the pdf directly with the command

```sh
start /Applications/Skim.app/Contents/SharedSupport/displayline  "test.pdf"
```

This should open the pdf file.

**Comment by cmarshak** [comment] 2015-07-18 21:14
<img width="561" alt="screen shot 2015-07-18 at 2 14 14 pm" src="https://cloud.githubusercontent.com/assets/5975894/8763550/4fe0f60e-2d57-11e5-8be3-bc72aa2fca4a.png">

**Comment by cmarshak** [comment] 2015-07-18 21:19
This should help!
<img width="563" alt="screen shot 2015-07-18 at 2 18 55 pm" src="https://cloud.githubusercontent.com/assets/5975894/8763562/fb528b38-2d57-11e5-9cda-e878d1535a5d.png">

**Comment by lervag** [comment] 2015-07-18 21:23
I think the `start` specifier is something from perl (I do not know perl myself). Thus I think the error `17:22: syntax error ...` is the correct error here.

Perhaps the `-r` option is strictly necessary. In that case, you should try to change your settings to

```vimL
let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline -r'
let g:vimtex_view_general_options = '@line @pdf @tex'
```

**Comment by cmarshak** [comment] 2015-07-18 21:57
Actually this gives an error with Mac.

    let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline -r'
    let g:vimtex_view_general_options = '@line @pdf @tex'

Here is the error:

<img width="746" alt="screen shot 2015-07-18 at 2 54 06 pm" src="https://cloud.githubusercontent.com/assets/5975894/8763663/428120c8-2d5d-11e5-9c0c-31aa216db8d6.png">


However, putting the `-r` command in the second line as before does not have difficulty loading the `/.vimrc`:

    let g:vimtex_view_general_options = '-r @line @pdf @tex'

So, it's working the same as before: perfectly with `<leader>lv` and no output `<leader>ll`.

**Comment by lervag** [comment] 2015-07-18 22:00
Ah, yes. Try instead

```vimL
let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '-r @line @pdf @tex'
let g:vimtex_view_general_options_latexmk = '-r'
```

**Comment by cmarshak** [comment] 2015-07-18 22:11
I believe this working the same as before.  What should I expect to see?

**Comment by lervag** [comment] 2015-07-31 08:39
Thanks, @cmarshak. I'm glad to hear things are (mostly) working!

I've [found some documentation](http://sourceforge.net/p/skim-app/wiki/TeX_and_PDF_Synchronization/#setting-up-your-editor-for-forward-search) on Skim. Here the `-r` option is explained, and I see here that it does not make sense to pass `-r` to Skim when it is opened by `latexmk`. Thus the `g:vimtex_..._latexmk = '-r'` is not necessary. I was hoping that the `-r` option was necessary.

Let's take a step back. If you clear all instances of MacVim and Skim and use the recommended options from the documentation, then both `<leader>ll` and `<leader>lv` does not work. If you prepend `-r` to the recommended options, the `<leader>lv` does work, but `<leader>ll` still does not work.

That is, start from a clean desktop (no MacVim or Skim running), open a LaTeX file in MacVim, then issue `<leader>ll`. The expected output is now:

1. Status message in MacVim, first "latexmk compile: started continuous mode", then "latexmk compile: success".
2. After the final message, the pdf viewer (Skim) should open (although, it does not necessarily open at the "correct" page/position).

But the Skim viewer is not opening for you. Is that right?

**Comment by lervag** [comment] 2015-08-04 06:29
Good. Let's ignore `<leader>lv` for a while (it works, anyway). What we want now is to find why the viewer does not open automatically after the first successful compilation.

Let's consider a minimal example:

```tex
% Save as mwe.tex
\documentclass{minimal}
\begin{document}
Hello World
\end{document}
```

And a minimal vimrc file:

```vimL
" Save as minivimrc
set nocompatible

" Ensure the path below is correct on your end
let &rtp = '~/.vim/bundle/vimtex,' . &rtp

filetype plugin indent on
syntax enable
let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '-r @line @pdf @tex'
```

Now open with `mvim -u minivimrc mwe.tex`. This should give you the most minimal setup I can think of. What happens when you now do `<leader>ll`: Does the viewer open?

**Comment by cmarshak** [comment] 2015-08-10 03:25
Sorry this took so long to respond...  still doesn't open Skim, Dr. Lervag.

But like I said, I really appreciate this work so far.  The fact that it compiles latex *and* bibtex upon `<leader>ll` is a big bump up from TexShop.

Still happy to do tests if you want to try to get this sorted out.

**Comment by lervag** [comment] 2015-08-10 10:54
Good, now we are sure that no other setting or plugin is relevant. Could you try the example again, and this time provide some output. That is, after you have started compilation for the above minimal working example with `mvim -u minivimrc mwe.tex`, could you please copy and paste the output of `<leader>lo` and `<leader>li`? The first will provide the output from `latexmk` directly, which might provide some explanation for why the viewer does not open. The latter will show the command that was actually used to start `latexmk`.

The next step will be to start `latexmk` manually from the command line with only the relevant options.

**Comment by cmarshak** [comment] 2015-08-11 01:24
`<leader>lo`:
<img width="810" alt="screen shot 2015-08-10 at 6 22 11 pm" src="https://cloud.githubusercontent.com/assets/5975894/9188078/e649e14a-3f8c-11e5-900e-44ad57bd40ad.png">

`<leader>li`
<img width="816" alt="screen shot 2015-08-10 at 6 22 43 pm" src="https://cloud.githubusercontent.com/assets/5975894/9188081/ed7d7efe-3f8c-11e5-83cc-73dac1312a57.png">

Thank you!

**Comment by lervag** [comment] 2015-08-11 06:29
Thanks. Could you give the `<ledaer>lo` again but this time with the option `g:vimtex_latexmk_options = -verbose` set? I think the syntax error is the problem, but I do not immediately understand what the error is.

**Comment by lervag** [comment] 2015-08-11 06:30
Also, I understand it is easy to paste the screenshots, but if you are able, it would be better for me if you could simply copy the text directly. That makes it easy for me to copy the text and experiment a little bit with the commands.

**Comment by lervag** [comment] 2015-08-11 06:50
I've studied the output, and there is one thing I can't understand: In the `cmd_latexmk_compile` string, the relevant option is the following:

```
-e ''$pdf_previewer = "start ... "''
```

Here the keyword `start` should not be present. When I search the source to find where this comes from, I can not see it. I am wondering if you might not be on the latest version. What is the output of running `git show -q` on the command line inside the vimtex folder? I suspect you are on an older version.

I see now that I removed the "start" keyword in a commit where I referenced this issue. I assumed you would automatically update vimtex. Sorry. Could you please get the latest version of vimtex and try again. I am still interested in the `<leader>lo` output.

**Comment by cmarshak** [comment] 2015-09-11 03:59
Sorry for the wait!

Here is the output of `leader<lo>` with:

(1) The option `g:vimtex_latexmk_options = '-verbose'` added to the minivimrc
(2)  The new vimtex update

     Latexmk: This is Latexmk, John Collins, 30 March 2012, version: 4.31.
    **** Report bugs etc to John Collins <collins at phys.psu.edu>. ****
    Viewing dvi
    Rule 'latex': Rules & subrules not known to be previously run:
       latex
    Rule 'latex': The following rules & subrules became out-of-date:
          'latex'
    ------------
    Run number 1 of rule 'latex'
    ------------
    ------------
    Running 'latex  -recorder  "mwe.tex"'
    ------------
    Latexmk: applying rule 'latex'...
    This is pdfTeX, Version 3.1415926-2.4-1.40.13 (TeX Live 2012)
     restricted \write18 enabled.
    entering extended mode
    (./mwe.tex
    LaTeX2e <2011/06/27>
    Babel <v3.8m> and hyphenation patterns for english, dumylang, nohyphenation, german-x-2012-05-30, ngerman-x-2012-05-30, afrikaans, ancientgreek, ibycus, arabic, armenian, basque, bulgarian, catalan, pinyin, coptic, croatian, czech, danish, dutch, ukenglish, usenglishmax, esperanto, estonian, ethiopic, farsi, finnish, french, friulan, galician, german, ngerman, swissgerman, monogreek, greek, hungarian, icelandic, assamese, bengali, gujarati, hindi, kannada, malayalam, marathi, oriya, panjabi, tamil, telugu, indonesian, interlingua, irish, italian, kurmanji, latin, latvian, lithuanian, mongolian, mongolianlmc, bokmal, nynorsk, polish, portuguese, romanian, romansh, russian, sanskrit, serbian, serbianc, slovak, slovenian, spanish, swedish, turkish, turkmen, ukrainian, uppersorbian, welsh, loaded.
    (/usr/local/texlive/2012/texmf-dist/tex/latex/base/minimal.cls
    Document Class: minimal 2001/05/25 Standard LaTeX minimal class
    ) (./mwe.aux) [1] (./mwe.aux) )
    Output written on mwe.dvi (1 page, 216 bytes).
    Transcript written on mwe.log.
    Latexmk: Log file says output to 'mwe.dvi'
    Rule 'latex': File changes, etc:
       Changed files, or newly in use since previous run(s):
          'mwe.aux'
    ------------
    Run number 2 of rule 'latex'
    ------------
    ------------
    Running 'latex  -recorder  "mwe.tex"'
    ------------
    Latexmk: applying rule 'latex'...
    This is pdfTeX, Version 3.1415926-2.4-1.40.13 (TeX Live 2012)
     restricted \write18 enabled.
    entering extended mode
    (./mwe.tex
    LaTeX2e <2011/06/27>
    Babel <v3.8m> and hyphenation patterns for english, dumylang, nohyphenation, german-x-2012-05-30, ngerman-x-2012-05-30, afrikaans, ancientgreek, ibycus, arabic, armenian, basque, bulgarian, catalan, pinyin, coptic, croatian, czech, danish, dutch, ukenglish, usenglishmax, esperanto, estonian, ethiopic, farsi, finnish, french, friulan, galician, german, ngerman, swissgerman, monogreek, greek, hungarian, icelandic, assamese, bengali, gujarati, hindi, kannada, malayalam, marathi, oriya, panjabi, tamil, telugu, indonesian, interlingua, irish, italian, kurmanji, latin, latvian, lithuanian, mongolian, mongolianlmc, bokmal, nynorsk, polish, portuguese, romanian, romansh, russian, sanskrit, serbian, serbianc, slovak, slovenian, spanish, swedish, turkish, turkmen, ukrainian, uppersorbian, welsh, loaded.
    (/usr/local/texlive/2012/texmf-dist/tex/latex/base/minimal.cls
    Document Class: minimal 2001/05/25 Standard LaTeX minimal class
    ) (./mwe.aux) [1] (./mwe.aux) )
    Output written on mwe.dvi (1 page, 216 bytes).
    Transcript written on mwe.log.
    Latexmk: Log file says output to 'mwe.dvi'
    Latexmk: I have not found a previewer that is already running. 
       So I will start it for 'mwe.dvi'
    ------------
    ------------
    Running 'NONE  "mwe.dvi"'
    ------------
    Latexmk: Program not implemented for this version.  Command line:
       'NONE  "mwe.dvi"'
    
    ------------
    Latexmk: I could not run previewer.
    -- Use the -f option to force complete processing.
    Latexmk: All targets (mwe.dvi) are up-to-date
    For rule 'view', running '&if_source(  )' ...

**Comment by lervag** [comment] 2015-09-11 05:53
Could you repeat this, but use the following? (I'm sorry, I forgot to add the `-pdf` part in my last post.)

```tex
g:vimtex_latexmk_options = '-pdf -verbose'
```

**Comment by cmarshak** [comment] 2015-09-11 15:21
Latexmk: This is Latexmk, John Collins, 30 March 2012, version: 4.31.
    **** Report bugs etc to John Collins <collins at phys.psu.edu>. ****
    Viewing dvi
    Latexmk: I have not found a previewer that is already running. 
       So I will start it for 'mwe.dvi'
    ------------
    ------------
    Running 'NONE  "mwe.dvi"'
    ------------
    Latexmk: Program not implemented for this version.  Command line:
       'NONE  "mwe.dvi"'
    
    ------------
    Latexmk: I could not run previewer.
    -- Use the -f option to force complete processing.
    Latexmk: All targets (mwe.dvi) are up-to-date
    For rule 'view', running '&if_source(  )' ...

**Comment by abspoel** [comment] 2015-09-17 09:32
I'm running into the same issue. Perhaps you've discovered this already, but I've captured the command line calls to Skim's displayline, and it seems that even though `<Leader>lv` calls

    <...>/displayline <line> <full pdf path> <full tex path>

like it's supposed to, `<Leader>ll` only results in a command line of

    <...>/displayline <relative pdf path>

and no other parameters. This results in the error

    17:21: syntax error: A unknown token can’t go after this identifier. (-2740)`

**Comment by abspoel** [comment] 2015-09-17 10:45
I think the problem is that `displayline` can only be used in conjunction with a line number and a source TeX. Whereas other viewers support forward search and a regular open on the same command with different parameters, Skim doesn't. A fix would be to have a different variable for the `<Leader>lv` command to use. Alternatively, setting `g:vimtex_view_general_viewer` to an executable shell script with the following contents:

    #!/bin/sh
    if [ "$#" -gt 1 ]; then
        /Applications/Skim.app/Contents/SharedSupport/displayline $*
    else
      /usr/bin/osascript <<EOF
          set theFile to POSIX file "$1" as alias
          tell application "Skim"
          activate
          set theDocs to get documents whose path is (get POSIX path of theFile)
          if (count of theDocs) > 0 then revert theDocs
          open theFile
          end tell
    EOF
    fi

will also take care of it without modifying the source. (This is what [Skim recommends](http://sourceforge.net/p/skim-app/wiki/TeX_and_PDF_Synchronization/) for allowing reloads.)

**Comment by lervag** [comment] 2015-10-01 11:15
```vimL
let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '-r @line @pdf @tex'
let g:vimtex_view_general_options_latexmk = '-r 1'
```

To expand upon @abspoel's idea, you could create an executable script similar to the one suggested by @abspoel. Then you could do instead use the following options:

```vimL
let g:vimtex_view_general_viewer = '/path/to/my/script'
let g:vimtex_view_general_options = '-r @line @pdf @tex'
```

Could any of you please test if this works?

**Comment by lervag** [comment] 2015-11-07 20:31
I like to keep the list of issues as short as possible. Since this has not had any activity, and since my last post is a proposed fix for the problem, I'll take the liberty to close the issue. Feel free to reopen if the issue persists.

**Closed by lervag** 2015-11-07 20:31 UTC

**Comment by tnull** [comment] 2017-10-20 11:51
@lervag Hello,
I'm running into a very similar problem when compiling after setting `let g:vimtex_view_method = 'skim'` in the `.vimrc` or `ftplugin/tex.vim`:

```
Latexmk: This is Latexmk, John Collins, 19 Jan. 2017, version: 4.52c.
Viewing pdf
Latexmk: I have not found a previewer that is already running. 
   So I will start it for 'master.pdf'
------------
------------
Running 'start /Applications/Skim.app/Contents/SharedSupport/displayline  "master.pdf"'
------------
Latexmk: All targets (master.pdf) are up-to-date
For rule 'view', running '&if_source(  )' ...
------------
Running '/Applications/VimR.app/Contents/Frameworks/SwiftNeoVim.framework/Versions/A/PlugIns/NeoVimServer --servername /var/folders/76/w433cm8d655cznw1qmd866gc0000gn/T/nvimERy9GM/0 --remote-expr "vimtex#compiler#callback(1)"'
------------
17:24: 
syntax error: A unknown token can’t go after this identifier. (-2740)
```

This happens with and without my .latexmkrc. Curiously, I can use Skim via `\lv` just fine.
Do you have any suggestions what could be the problem here?

**Comment by lervag** [comment] 2017-10-20 22:26
@tnull This issue is very old, so I would be glad if you could open a new issue with a full description and preferably a minimal example. Then it will be easier for me to understand the problem and perhaps find a solution. I hope that's OK.

**Comment by cmarshak** [comment] 2017-10-22 16:42
I was trying to get this in order before my thesis, but was unsuccessful despite Dr. Lervag's very helpful discussions. I hope to revisit on the new issue thread.

**Comment by andportnoy** [comment] 2018-02-27 01:45
@lervag 
Dear Dr. Lervåg,

Just to give you some feedback, your suggestion in https://github.com/lervag/vimtex/issues/204#issuecomment-144699878 works perfectly for me (opens Skim on `<leader>ll` and points with a red dot).

Thank you for creating Vimtex!

**Comment by lervag** [comment] 2018-02-27 07:07
I'm happy you like it and that it works! :)

**Comment by lervag** [comment] 2018-02-27 07:08
However, it should also work with simply

```vim
let g:vimtex_view_method = 'skim'
```

This _should_ even be better, I think.

**Comment by andportnoy** [comment] 2018-02-27 20:23
Thank you, this is better, since it's one line instead of three!
