### ISSUE TITLE
RFC: Improve integration with the match-up plugin

### ISSUE THREAD

**Issue by andymass** [lervag/vimtex#1009] opened 2017-11-27 17:24 UTC
By match-up, I mean my plugin https://github.com/andymass/vim-matchup, which aims to replace matchit, and importantly provide matchparen-style highlighting for the % words.  This is a spin-off plugin of vimtex, but still many non-trivial changes had to be made to support middle words, and it would not be easy to re-implement this in vimtex.  As @kiryph hints at in #525, there is motivation for the user to use match-up's matching, motions, and highlighting instead of vimtex's where appropriate.

In truth, both match-up and vimtex have strengths and weaknesses in this area.  vimtex cannot support middle words, whereas match-up cannot support the `|` in `|x|`.  vimtex does not provide `g%`, `[%`, `]%`, etc., but match-up does not "understand" tex environments or delimiters like vimtex does.  Ideally, with small changes, both plugins can be made to operate together without the user noticing a major disconnect or having to make major configurations.

I think there are a few low-hanging fruits:

### What match-up can do

If match-up provides a super-set of vimtex's highlighting and `%`, match-up should not disable itself but instead should override vimtex for these features by setting `g:vimtex_matchparen_enabled=0` and disabling vimtex's `%`.  On the other hand, I do not intend to  replace `csd` and similar.  `ad`/`id` can co-exist freely with `a%`/`i%`.

### What vimtex can do

There is a clean way to disable vimtex's matchparen, but there is no way to disable its `%` mappings.   If vimtex does not support this, match-up will have to unmap them in `after/ftplugin/tex.vim`.

vimtex can provide a compatible `b:match_words` to allow match-up to operate peacefully with vimtex.

### What @kiryph can do

cf. [your comment](https://github.com/lervag/vimtex/issues/525#issuecomment-347234675), it would be good to figure out exactly what match-up is capable of and come up with an acceptable `b:match_words` (and/or suggest possible extensions for the user).  Coming up with good regexes is somewhat tricky.  As a starting point, here is the `b:match_words` from `ftplugin/plaintex.vim` and `ftplugin/tex.vim`:

```vim
let b:match_skip = 'r:\\\@<!\%(\\\\\)*%'
let b:match_words = '(:),\[:],{:},\\(:\\),\\\[:\\],\\{:\\}'
let b:match_words .= ',\\begin\s*\({\a\+\*\=}\):\\end\s*\1'
```

From a cursory test, these appear to work in match-up.

**Comment by lervag** [comment] 2017-11-27 21:00
I would not really mind handling over the responsibility of the `%` command, as well as the highlight matching pairs feature. I think it makes sense to separate this, as I agree that the functionality is in a way more general.

However, I am not quite sure how to do this properly, and I would greatly appreciate help in doing this.

Would matchup be able to match complex stuff like `$\bigl\lvert \frac 1 2 \bigr\rvert$`, i.e. highlight the matching pair `\big[lr]\[lr]vert`?

If we were to find a way to properly integrate vim-matchup with vimtex so that matchup handles the `%` family of motions, as well as highlighting of matching pairs, then I would be glad to add matchup specific options to (vim)tex buffers and to suggest to the users of vimtex that they use vim-matchup to get these features.

However, if handling this responsibility over to vim-matchup would make things worse, then obviously I won't do that.

**Comment by andymass** [comment] 2017-12-02 15:28
> Would matchup be able to match complex stuff like $\bigl\lvert \frac 1 2 \bigr\rvert$, i.e. highlight the matching pair \big[lr]\[lr]vert?

Generally, yes, you can have arbitrary capture groups matched with back-references; e.g., `\(\\big\)l:\1r`.  However, there are differences, which if deemed important, would likely need source changes to match-up.

#### (1) match-up allows overlapping delimiters

This is intentional, to allow e.g., matching of `<` and `>` in HTML while also matching whole tags.  Here is what this looks like with a naïve `b:match_words` (i.e., without look-behind assertions): [gif demo](https://i.imgur.com/zMpENqS.gif).  I suppose it makes some logical sense, and some would prefer it, but it is divergent from vimtex.

#### (2) with look-behinds, mis-matches are ignored

I added look-behinds to prevent overlapping delimiters (my current match_words implementation is [here](https://gist.github.com/andymass/370543c3853b473be099cad7ea548f1c)).  This has the side-effect of never matching anything in this example:
```tex
\[     \bigl(       )    \]
```
vimtex will still at least try to match the `( )`.  The other potential concern with `\@<!` look-behinds is performance, but I haven't noticed a problem.  I don't know of a way in match-up to prevent situation (1) and simultaneously handle (2), without greatly increasing regex complexity.  I could make source changes as necessary, although this would probably create a `b:match_words` which is not compatible with matchit (that's okay though).

#### vimtex doesn't completely handle mis-matched either

While testing, I noticed vimtex has problems with the following:
```tex
\[    \bigl(    \Biggr)   \]
```
vimtex highlights either one individually, but does not match them together.  I'm not sure if this is intended.  `%` on the first delimiter also produces an actual error; this is probably a bug.  With*out* `\Big` in `g:vimtex_delim_list.mods`, the parens are not even matched.  *With* `\Big` in `g:vimtex_delim_list.mods` (vimtex default), parens are matched, but it strangely highlights just the `\Big` when the cursor is over it.

So maybe these are very minor corner-cases and the goal shouldn't be to act identically to vimtex always.  Still, a decision would need to be made regarding (1) and (2), or if they are both unacceptable, I will need to make some type of enhancement to match-up.

**Comment by lervag** [comment] 2017-12-04 21:41
First, thanks for pointing out the minor issues with mis matches. Should be fixed now.

So, regarding the points: I think the behaviour of vim-matchup is OK. I find the differences between vim-matchup and vimtex to be quite minor. However, there is one important difference: In vimtex, the modifiers are actually not matched as separate delimiters. Instead, they are only matched as part of other delimiters. This makes it possible to operate on them directly, e.g. by toggling between different modifiers.

As the delimiter matching system in vimtex is used for a lot of things, I don't think it will make sense to remove it. As such, I don't really see a good point in removing it. However, if you think vim-matchup can provide a full substitute for the `%` motion, as well as the matchparen feature, then I think it could it would be nice to keep things on both ends to make our plugins behave well towards one another.

First, if vim-matchup should get to a point where we can say it is superior, then I feel it makes sense to assume the user wants to use vim-matchup. That is, I will detect vim-matchup during vimtex init, then set defaults based on this.

Until then, I think there will be no change in vimtex except perhaps in the docs. Exactly which change in the docs is most proper is so far a little bit unclear.

**Comment by kiryph** [comment] 2017-12-05 15:55
@andymass I've tried your config for `b:match_words` from `https://gist.github.com/andymass/370543c3853b473be099cad7ea548f1c`. I've placed the code in `~/.vim/after/ftplugin/tex.vim`:
```viml
let s:not_bslash = g:matchup#re#not_bslash

function! s:gen_match_words()
  let l:delims = [
        \ [ '\\l\(angle\|floor\|ceil\|[vV]ert\)\>', '\\r\1\>'],
        \ [ '\\ulcorner\>', '\\urcorner\>' ],
        \ [ '(', ')' ],
        \ [ s:not_bslash.'\[', s:not_bslash.']' ],
        \ [ '\\{', '\\}' ]
        \]

  let l:mods = [
        \ ['\\left', '\\right'],
        \ ['\(\\[bB]igg\?\)l', '\1r'],
        \ ['\(\\[bB]igg\?\)', '\1'],
        \ ['\%(\\left\|\\[bB]igg\?l\?\)\@<!',
        \  '\%(\\right\|\\[bB]igg\?r\?\)\@<!'],
        \]

  let l:match_words = ''
  for l:d in l:delims
    for l:m in l:mods
      let l:match_words .= (empty(l:match_words) ? '' : ',')
            \ . l:m[0].l:d[0].':'.l:m[1]
            \ . (l:m[1] =~# '\\1'
            \      ? substitute(l:d[1], '\\1', '\\2', 'g') : l:d[1])
    endfor
  endfor

  let l:match_words .= ',{:},\\(:\\),\\\[:\\]'
  let l:match_words .= ',\\begin\s*\({[^}]*}\):\\end\s*\1'

  return l:match_words
endfunction
let b:match_words = s:gen_match_words()
```

However, match-up complains with following error:
```
match-up: backref \ 1 requested but no matching capture group provided 
```
I've tried to identify the offending generated entry in `b:match_words` by assigning the result of `s:gen_match_words()` explicitly to a variable:
```viml
let b:match_words = ''
        \.'\\begin\s*\({[^}]*}\):\\end\s*\1,'
        \.'{:},'
        \.'\\(:\\),'
        \.'\\\[:\\],'
        \.'\\left(:\\right),'
        \.'\\left\\{:\\right\\},'
        \.'\\left\\l\(angle\|floor\|ceil\|[vV]ert\)\>:\\right\\r\1\>,'
        \.'\\left\\ulcorner\>:\\right\\urcorner\>,'
        \.'\\left\v%(\\@<!%(\\\\)*)@<=\m\[:\\right\v%(\\@<!%(\\\\)*)@<=\m],'
        \.'\(\\[bB]igg\?\)(:\1),'
        \.'\(\\[bB]igg\?\)\\ulcorner\>:\1\\urcorner\>,'
        \.'\(\\[bB]igg\?\)\\{:\1\\},'
        \.'\(\\[bB]igg\?\)l(:\1r),'
        \.'\(\\[bB]igg\?\)l\\ulcorner\>:\1r\\urcorner\>,'
        \.'\(\\[bB]igg\?\)l\\{:\1r\\},'
        \.'\%(\\left\|\\[bB]igg\?l\?\)\@<!\\ulcorner\>:\%(\\right\|\\[bB]igg\?r\?\)\@<!\\urcorner\>,'
        \.'\%(\\left\|\\[bB]igg\?l\?\)\@<!(:\%(\\right\|\\[bB]igg\?r\?\)\@<!),'
        \.'\%(\\left\|\\[bB]igg\?l\?\)\@<!\v%(\\@<!%(\\\\)*)@<=\m\[:\%(\\right\|\\[bB]igg\?r\?\)\@<!\v%(\\@<!%(\\\\)*)@<=\m],'
        \.'\%(\\left\|\\[bB]igg\?l\?\)\@<!\\{:\%(\\right\|\\[bB]igg\?r\?\)\@<!\\},'
        \.'\(\\[bB]igg\?\)l\v%(\\@<!%(\\\\)*)@<=\m\[:\1r\v%(\\@<!%(\\\\)*)@<=\m],'
        \.'\(\\[bB]igg\?\)\v%(\\@<!%(\\\\)*)@<=\m\[:\1\v%(\\@<!%(\\\\)*)@<=\m],'
        \.'\(\\[bB]igg\?\)\\l\(angle\|floor\|ceil\|[vV]ert\)\>:\1\\r\2\>,'
        \.'\(\\[bB]igg\?\)l\\l\(angle\|floor\|ceil\|[vV]ert\)\>:\1r\\r\2\>,'
        \.'\%(\\left\|\\[bB]igg\?l\?\)\@<!\\l\(angle\|floor\|ceil\|[vV]ert\)\>:\%(\\right\|\\[bB]igg\?r\?\)\@<!\\r\1\>,'
``` 

When I remove the combination
```viml
'\%(\\left\|\\[bB]igg\?l\?\)\@<!\\l\(angle\|floor\|ceil\|[vV]ert\)\>:\%(\\right\|\\[bB]igg\?r\?\)\@<!\\r\1\>,'
```
(last line), the error disappears.

Any clue what is going on?

Just as a quick shot, I've tried following modification:
```
        \.'\\left\\l\(angle\|floor\|ceil\|[vV]ert\)\>:\\middle|:\\right\\r\1\>,'
```
Now it is possible to reach `\middle|` with `%` or `g%`:

![screen shot 2017-12-05 at 16 50 16](https://user-images.githubusercontent.com/371756/33616157-68c031b0-d9dc-11e7-820e-a4d17bde6beb.png)

Thanks for your help!

**Comment by andymass** [comment] 2017-12-05 15:57
@kiryph , do you have the most recent version of match-up (i.e., not the vimscripts version).  I think this is related to a bug I squashed.

**Comment by kiryph** [comment] 2017-12-05 19:24
@andymass Yes, you were right: I missed the most recent updates of match-up. Sorry.

However, I still cannot reproduce entirely your gif:
![screen shot 2017-12-05 at 17 31 30](https://user-images.githubusercontent.com/371756/33618210-31d721ee-d9e2-11e7-9295-454ec68925ed.png)
When the cursor is located on the delimiter not on the modifier, it still highlights delimiter+modifier in contrast to your gif.

I am torn about giving you a simple yes/no answer to your two raised issues.

First of all, can you clarify for me the following:

Lervag:
>However, there is one important difference: In vimtex, the modifiers are actually not matched as separate delimiters. Instead, they are only matched as part of other delimiters. This makes it possible to operate on them directly, e.g. by toggling between different modifiers.

Is this true for match-up? I think that modifiers are also only matched together with the delimiters. Only the opposite is not true for match-up: you can match delimiters on their own regardless if they have modifiers as prefixes.

Back to your questions:

### (1)  *match-up allows overlapping delimiters*

My first intuition is that this sounds as a good idea.
However, I think your html comparison does not fit perfectly:
```
        +-----------------+
     |-----|           |-----|
\left\langle a+b \right\rangle
|---|            |----|
  +-----------------+

 +-----+       +------+
 |     |       |      |
 <title>My Hero</title>
 |-----|       |------|
    +-------------+
```

Another first remark is:
some people write `\big(a+b\big)` and other `\bigl(a+b\bigr)`. In the first case, the modifier does not specify if it is the left or right. I would always advise against the first version but the plugin cannot assume this. Consider also math intervals where the delimiter can be used in the opposite direction which also means that the delimiter is not a safe pick to decide on which side the partner is located:
![screen shot 2017-12-05 at 20 09 11](https://user-images.githubusercontent.com/371756/33625537-314f45b0-d9f8-11e7-920c-17f262042c97.png)



If I got lervag right, his motivation **not** being in favour of this is: vimtex can toggle between `(a+b)` and `\left(a+b\right)` with `tsd` which can be triggered from the modifier, the delimiter or the inner text. This would not be possible if `()` in `\left(a+b\right)` are matched without modifier and you would add a second `\left \right` when pressing `tsd` on `a+b`. I would argue that the behavior of `tsd` should work independently of the choice of matchparen highlighting or how `%` works.

Please note, adding/changing/deleting modifiers can also be done with the plugin `sandwich` e.g. with `cs(m(` and `csm((`. Of course typing `tsd` is a more convenient shortcut for toggling but also overwrites the builtin motion `till next s`.

I also use the plugin `https://github.com/bootleq/vim-cycle` which allows me to cycle modifiers with `ctrl-a/x`. My current config for vim-cycle looks like (not final):
```vim
call cycle#reset_b_groups()
call cycle#add_b_groups([
        \   [['tiny', 'scriptsize', 'footnotesize', 'small', 'normalsize', 'large', 'Large', 'LARGE', 'huge', 'Huge'], 'hard_case', 'match_case'],
        \   [['\left(:\right)',   '\mleft(:\mright)',   '\bigl(:\bigr)',   '\Bigl(:\Bigr)',   '\biggl(:\biggr)',   '\Biggl(:\Biggr)'],   'sub_pairs', 'hard_case', 'match_case'],
        \   [['\left[:\right]',   '\mleft[:\mright]',   '\bigl[:\bigr]',   '\Bigl[:\Bigr]',   '\biggl[:\biggr]',   '\Biggl[:\Biggr]'],   'sub_pairs', 'hard_case', 'match_case'],
        \   [['\left\{:\right\}', '\mleft\{:\mright\}', '\bigl\{:\bigr\}', '\Bigl\{:\Bigr\}', '\biggl\{:\biggr\}', '\Biggl\{:\Biggr\}'], 'sub_pairs', 'hard_case', 'match_case'],
        \   [['\left|:\right|', '\mleft|:\mright|', '\bigl|:\bigr|', '\Bigl|:\Bigr|', '\biggl|:\biggr|', '\Biggl|:\Biggr|'], 'sub_pairs', 'hard_case', 'match_case'],
        \   [['\left\lvert:\right\rvert', '\mleft\lvert:\mright\rvert', '\bigl\lvert:\bigr\rvert', '\Bigl\lvert:\Bigr\rvert', '\biggl\lvert:\biggr\rvert', '\Biggl\lvert:\Biggr\rvert'], 'sub_pairs', 'hard_case', 'match_case'],
        \   [['\left\lVert:\right\rVert', '\mleft\lVert:\mright\rVert', '\bigl\lVert:\bigr\rVert', '\Bigl\lVert:\Bigr\rVert', '\biggl\lVert:\biggr\rVert', '\Biggl\lVert:\Biggr\rVert'], 'sub_pairs', 'hard_case', 'match_case'],
        \   [['\left\lfloor:\right\rfloor', '\mleft\lfloor:\mright\rfloor', '\bigl\lfloor:\bigr\rfloor', '\Bigl\lfloor:\Bigr\rfloor', '\biggl\lfloor:\biggr\rfloor', '\Biggl\lfloor:\Biggr\rfloor'], 'sub_pairs', 'hard_case', 'match_case'],
        \   [['\left\lceil:\right\rceil', '\mleft\lceil:\mright\rceil', '\bigl\lceil:\bigr\rceil', '\Bigl\lceil:\Bigr\rceil', '\biggl\lceil:\biggr\rceil', '\Biggl\lceil:\Biggr\rceil'], 'sub_pairs', 'hard_case', 'match_case'],
        \   [['\left\langle:\right\rangle', '\mleft\langle:\mright\rangle', '\bigl\langle:\bigr\rangle', '\Bigl\langle:\Bigr\rangle', '\biggl\langle:\biggr\rangle', '\Biggl\langle:\Biggr\rangle'], 'sub_pairs', 'hard_case', 'match_case'],
        \   [['\left:\right', '\mleft:\mright', '\bigl:\bigr', '\Bigl:\Bigr', '\biggl:\biggr', '\Biggl:\Biggr'], 'sub_pairs', 'hard_case', 'match_case'],
        \   [['\big', '\Big', '\bigg', '\Bigg'], 'hard_case', 'match_case'],
        \ ])
```
Previously, I had also configured it to cycle through delimiter types, but I figured that there is no logical order for delimiter types and it is a better idea to use surround-like functionality to change the delimiter type, e.g. `csd`.

A similar functionality to vim-cycle exists also in vimtex with the additional keybinding `tsD` which is not enabled by default:
>*<plug>(vimtex-delim-toggle-modifier)*
*<plug>(vimtex-delim-toggle-modifier-reverse)*
 When |g:vimtex_delim_toggle_mod_list| is set to contain more than one set of
  modifiers, these mappings iterate through the list instead of just toggling.
  For example, one may alternate between `(...)`, `\bigl(...\bigr)`,
  `\Bigl(...\Bigr)`, and so on.

I prefer the keybindings `<C-A/X>` from vim-cycle to change modifiers which, however, require that your cursor is on the modifier or in my configuration on the delimiter which has a modifier. Adding or removing the modifier requires vimtex or sandwich.

I have installed all four plugins:
-  `matchup` providing motions `%`, `g%`, `[%`, `]%`, text objects `i%` and `a%` and highlighting
- `sandwich` providing operators and text objects
- `vim-cycle` by bootleq extending `<C-A/X>` (my config: cycle through modifiers)
- `vimtex` motion `%`, text objects `id` and `ad`, operator `dsd`/`csd`/`tsd` and highlighting

As you have seen they have overlapping features which makes it challenging to get things consistent and settling which plugin does what.

In short, I think having functions which can understand the latex concept of modifier+delimiter is a good thing and do not treat them always as a single unit. Of course, some functions should be sensible; e.g. if there is already a modifier to a delimiter, a second does not make any sense and a modifier does not exist without a delimiter.

**Highlighting**
Therefore the highlighting could work as you have shown in your gif.
As an alternative:
One could use two shades of one color to highlight modifier and delimiter slightly different and to make clear that the cursor is either on delimiter or modifier.

### (2) with look-behinds, mis-matches are ignored

```
\[     \bigl(       )    \]
```

**My answer**
I do not know an example where people want to use pairs of different sized delimiters. From this perspective it would make sense that they are not matched at all.

### Virtual dot delimiters
What are your thoughts about following latex construct?
```tex
\left.\vphantom{largest math symbol from previous line}\right)
```
How should this be matched?

BTW: I have not found a situation where I am forced to use the virtual dot delimiter. Usually, I switch to manual sizing and e.g. do not worry about updating the content of \vphantom. Do you know an example where you have to use the virtual do delimiter?

**Comment by andymass** [comment] 2017-12-05 20:17
Thank you for your input!  It will greatly help me converge on a good set of match_words.  A few comments:

1. I wasn't clear, my gif was using a different match_words than in my gist.  The gist is the "non-overlapping" version.  The gif is the "overlapping" version.  Your point about HTML is a very good one.  However, your diagram should look like this:

                +-----------------+
             |-----|           |-----|
        \left\langle a+b \right\rangle
        |----------|     |-----------|
          +-----------------+

2.  > Is this true for match-up?

Depending on the regexes, match-up sees `\big(` as one delimiter (as in my gist) or two overlapping delimiters (as in my gif).  If two, it's `\big(` and `(` (see diagram above).

I'm not sure I fully understood lervag's point.  My best understanding is that he just wants to emphasize that match-up will not replace vimtex's "delimiter," and I completely agree (if for no other reason than it's much less work).  So, csd, tsd, etc will continue to function exactly as they do now.  The only change will be match-up will take priority for `%` and matchparen.  This means crucially, that match-up's `a%` and vimtex's `ad` will be technically different, but we can set match_words so they are a super-set, for the best possible user experience.  I think this is within close reach for match-up.  I am OK with `va%`/`vi%` being slightly different from `vad`/`vi%`.

I agree about the difficulty managing overlapping features, but this moment, I would prefer not to discuss "toggling" or "cycling" delimiters, since it's outside the scope of match-up.  I'm not planning to change any functionality in that area.  The only challenge is to sensibly "synchronize" match-up and vimtex.

3.  > One could use two shades of one color to highlight modifier and delimiter slightly different and to make clear that the cursor is either on delimiter or modifier.

This is a fascinating idea, and I will think about it.  It would certainly require a change to match-up.  Plus, no color schemes would support it.

4. delimiter can be used in the opposite direction 

Yes, matching `) (` is a very difficult problem, which I think can't be solved in general.  What does vimtex do?

5. What are your thoughts about `\left.\vphantom{largest math symbol from previous line}\right)`

Ignoring the vphantom, the best example of this is for bar evaluations:

      \int_a^b f = \left. F(x) \right|_a^b

I personally think they should be matched, but as far as I can tell vimtex doesn't.

6. Finally, I will come up with another match_words (or perhaps two) which incorporates this feedback for you both to try.  My goal here was to have as much discussion as possible, therefore as little coding as possible :smile:  Thanks!

**Comment by clason** [comment] 2017-12-06 07:52
@kiryph Re virtual dot delimiters: I very frequently write
```
\begin{equation}
    \left\{
        \begin{aligned}
            lhs1 &= rhs1 \\
            lhs2 &= rhs2 \\
        \end{aligned}
    \right.
\end{equation}
```
to refer to a system of, e.g., PDEs with a single equation number.

**Comment by kiryph** [comment] 2017-12-06 08:52
1. I agree that the picture should look like:
```
         +-----------------+
      |-----|           |-----|
 \left\langle a+b \right\rangle
 |----------|     |-----------|
   +-----------------+
```
  
2. Toggling/changing modifier:
@andymass Thanks anyhow for reading through my lengthy comment including my excursion about functionality which is irrelevant for match-up.

3. Two shades of color for modifier and delimiter:
I was afraid that this is technically not easily possible.

4. I think if the modifier contains information about its intended side, this should take priority and it should be correctly matched:
    ```
    \left]a,b\right[
    \bigl]a,b\bigr]
    \Bigl]a,b\Bigr]
    \biggl]a,b\biggr]
    \Biggl]a,b\Biggr]
    ```

5. @clason @andymass also thanks for giving good examples for the usage of the virtual dot delimiter. I should have thought of them myself.

6. You are welcome and thanks for improving match-up w.r.t. latex. I am glad to see this.

**Comment by andymass** [comment] 2017-12-19 16:39
Hi all, I have come up with a set of regexes that seem to work.  We may track development and issues here: andymass/vim-matchup#14.  Note that currently you must use `let g:matchup_override_vimtex = 1` in your vimrc.  Any feedback is much appreciated!

@lervag, I found that it was actually not too difficult to just `unmap <buffer> %` in `after/ftplugin/tex.vim`.  I am not sure if load-order is a potential issue here, but it WFM.  Regardless, any changes to vimtex (if necessary at all) are clearly minimal.  I will try to write some brief documentation for vimtex and then we can close this issue before it becomes too old :relaxed:.

**Comment by lervag** [comment] 2017-12-20 22:23
I'm sorry for not responding! It's quite busy these days, and there is so much content here to grasp so I've avoided this until I have the time to consider it in more depth.

However, I am happy to hear that you will try to contribute some relevant docs for vimtex, @andymass!

As for load-order, there are two cases:

1. Vimtex loads first, then your code should work as is.

2. vim-matchup loads first and maps the `%` key. In this case, vimtex will override the mapping. This is an exception to the rule "don't overwrite user mappings", because I want to overwrite mappings by vim-matchit. However, it should be simple to update this if/when necessary. I would propose to search for `g:matchup_override_vimtex`, and if it is defined and set to 1, then vimtex will not force the `%` mappings as is done right now. The relevant code is in `autoload/vimtex.vim` lines 432--434.

**Closed** 2018-02-21 16:19 UTC

**Comment by lervag** [comment] 2018-02-21 16:36
Thanks, I think you are right that this can be closed. :)
