### ISSUE TITLE
No such group or event: QuitPre

### ISSUE THREAD

**Issue by 2sev** [lervag/vimtex#273] opened 2015-11-10 21:58 UTC
With the latest updates I get the following error messages when trying to open latex files.
```
Error detected while processing function vimtex#init..<SNR>47_init_buffer:
line  108:
E216: No such group or event: QuitPre     <buffer> silent! doautocmd User VimtexEventQuit
```

**Comment by lervag** [comment] 2015-11-10 22:01
Which Vim version are you on?

**Comment by 2sev** [comment] 2015-11-10 22:03
It's the standard one from Mac OS X El Capitan (VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Aug 22 2015 15:38:58). It worked just fine with your plugin a couple of days ago.

**Comment by lervag** [comment] 2015-11-10 22:06
Yes, I think the problem is that your Vim version does not have the `QuitPre` autocommand. It first appeared in patch 7.3.544. Could you open Vim and do `:echo exists('#QuitPre')`? The result should be 1 if you have `QuitPre`.

**Comment by 2sev** [comment] 2015-11-10 22:08
Sure. It says ```0```.

**Comment by lervag** [comment] 2015-11-10 22:12
Is it an option to get a newer version of Vim installed? Your version is starting to get relatively old (a LOT has happened since before 7.3.544). Perhaps you could install [MacVim](http://www.macupdate.com/app/mac/25988/macvim)?

**Comment by 2sev** [comment] 2015-11-10 22:13
OK, thanks for the explanation! It is not a problem to install a newer version, yes. However, it would be really nice to have some information about this lower bound restriction for the VIM version in the README. :) Thank you.

**Comment by lervag** [comment] 2015-11-10 22:26
The reason there is none, is simply that I do not know the actual lower bound. But, I agree, I should add a lower bound. I'll add a warning message to start up.

**Comment by 2sev** [comment] 2015-11-10 22:33
Thanks for that! This warning is enough I guess.

**Comment by lervag** [comment] 2015-11-11 10:40
Good. I'll close this, then. Thanks for reporting.

**Closed** 2015-11-11 10:40 UTC
