### ISSUE TITLE
vimtex slows vim startup extremly down since 48e387b76445916e57bb7d888b12f01eb139d970

### ISSUE THREAD

**Issue by heiderich** [lervag/vimtex#874] opened 2017-06-13 13:52 UTC
### Explain the issue

Since commit 48e387b76445916e57bb7d888b12f01eb139d970 vim startup became MUCH slower than before. It would be very nice if the startup times could be improved again.

1. Steps to reproduce

I have a bit LaTeX document. Using commit e6417ff48dedce9c3f79b29147f0ebcbd41a5e8b vim startuptimes reports:

`1809.264  1590.986  1583.413: sourcing /home/florian/.vim/bundle/vimtex/ftplugin/tex.vim`

2. Expected behaviour

I would hope for similar startup times with current versions of vimtex.

3. Observed behaviour

Starting with commit 48ccd68e9d21eabcb95bedc21728ce97d57b1cd2 vim startuptimes reports:

`10326.616  10104.393  10096.911: sourcing /home/florian/.vim/bundle/vimtex/ftplugin/tex.vim`

**Comment by andymass** [comment] 2017-06-13 14:10
Could you report the output of :VimtexInfo?  Also, can you delete any `.fls` file and repeat the startuptime experiment again?

**Comment by andymass** [comment] 2017-06-13 14:10
l

**Comment by heiderich** [comment] 2017-06-13 18:05
After having deleted the `.fls` files the startup time remains comparable. It is even slightly higher:

`12261.309  12008.142  12000.816: sourcing /home/florian/.vim/bundle/vimtex/ftplugin/tex.vim`

**Comment by lervag** [comment] 2017-06-13 18:09
Could you post a minimal working example? Based on the `:VimtexInfo` you sent by email, I would suspect that this problem would not be noticable on small examples. Is that right?

Would you be able to create a "dummy" LaTeX project that reproduces this, i.e. a collection of files that have enough content for the startuptime to be noticable?

**Comment by heiderich** [comment] 2017-06-14 15:05
It find it difficult to come up with a minimal working example. I observed the following:

1) The startup time seems to be correlated to the mount of LaTeX code in the file opened together with all the files that are recursively inputed/included from it. Probably all the files in the tree (roughly: vertices the tex/sty files and edges the includes/inputs/...) are parsed. This would explain this correlation. I did not test whether this correlation did exist previously, but I always had that impression. In any case, now everything is much slower. 

2) I produced some big tex files that only contain plain text and that are included in a main .tex file. In this case I get these timings:
For commit e6417ff48dedce9c3f79b29147f0ebcbd41a5e8b I have
`7827.486  7708.794  7701.425: sourcing /home/florian/.vim/bundle/vimtex/ftplugin/tex.vim`
while for commit 48e387b76445916e57bb7d888b12f01eb139d970
`7857.759  7736.467  7728.936: sourcing /home/florian/.vim/bundle/vimtex/ftplugin/tex.vim`
The project I worked on in my initial post contained a lot of maths and many references and the above mentioned tree was deeper.

3) In projects containing multiple files this delay does not only occur during the startup of vim but also when opening a new file (say with gf or :e) when this file (together with the files inputed/included within it) is big. If a file is opened for a second time (it was opened in the current session, then closed and finally reopened), then this long delay does not occur (maybe something is cached).

**Comment by andymass** [comment] 2017-06-14 17:30
I believe the slowness is in large part due to the complex regular expression
```vim 
    let l:pat = g:vimtex#re#not_comment . g:vimtex#re#not_bslash
        \ . '\v\\usepackage\s*(\[[^[\]]*\])?\s*\{([^{}]+)\}'
```
(I must take some responsibility for this :cry:).  This regex is slow even on lines that have nothing to do with `\usepackage`.  You can create a file which demonstrates the issue as follows
```bash
yes '\foo\foo\foo\foo\foo\foo\foo\foo\foo\foo\foo\foo\foo\foo\foo\foo\foo\foo' | head -1000 > slow.tex
```
For me, it takes about a second to open, even though the [first `match`](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/state.vim#L437) never passes.  An obvious fix would be to filter out lines that do not contain the string `usepackage` at all before calling `match` on `l:pat` (will write something up shortly).

**Comment by andymass** [comment] 2017-06-14 17:54
How about this?
https://github.com/andymass/vimtex/commit/885323fbe6ce1d637220d61a08d513478c781a4d

@heiderich you can try my branch if you want, https://github.com/andymass/vimtex/tree/issue/874
This seems to improve efficiency on files with many long lines, but not on files with very many lines.

**Comment by heiderich** [comment] 2017-06-15 09:38
With 885323f the startup time is reduced from

`22397.897  22177.389  22169.982: sourcing /home/florian/.vim/bundle/vimtex/ftplugin/tex.vim`

to

`2981.163  2760.863  2753.600: sourcing /home/florian/.vim/bundle/vimtex/ftplugin/tex.vim`

**Comment by lervag** [comment] 2017-06-15 21:00
I can sort of reproduce this. However, for me, the difference between the changes mentioned here and older versions is not really that big. Vimtex seems to load slowly for large files/big projects.

**Comment by heiderich** [comment] 2017-06-18 18:21
The difference between 885323f and older versions is not that big anymore. But the startup times with 48ccd68 are not bearable for me. I do not oversee the changes in andymass/vimtex@885323f, but in terms of startup times it seems to be better than 48ccd68, at least for my use cases.

**Comment by lervag** [comment] 2017-06-18 18:33
I'm working on this, but it is challenging to find a good example that reproduces the problem in a good manner. I tried my own thesis, where I do reproduce a relatively large startup time, but not on the order you report. Also, the fix by @andymass does not change the startuptime too much.

**Comment by lervag** [comment] 2017-06-20 18:51
@heiderich I've merged a pull request by @andymass that addresses the slow startups. I'm curious what the current status is regarding this issue. Do you still have bad startup times?

**Comment by lervag** [comment] 2017-06-20 21:48
Ok, I've done some more refactoring and improvements. I hope it works better now. Let me know what you think!

**Comment by lervag** [comment] 2017-07-03 21:20
I'm closing this due to no activity. Feel free to reopen or continue the discussion. I will gladly try to improve the efficiency more if you feel the need for it.

**Closed** 2017-07-03 21:19 UTC
