### ISSUE TITLE
indentation and gq (once more)

### ISSUE THREAD

**Issue by nilsbecker** [lervag/vimtex#577] opened 2016-09-28 14:59 UTC
the new `gq` is generally working nicely. i just noticed a glitch however.
 
starting with this caption inside a figure environment:
```
	\caption{\label{fig:scheme}%
		xxxxxxxxxx xxxxxx xxxxxxxxxxx. xxxxxxxxxxx xxxxxxx xxxxxxxxxx xxx xxxxx
		xxxxx xxxx xxx xxxxxx xxx xxx xxxxx xxxxxxxxx xx $\xxxx=+,-$. xx xxxxxxxx,
		xx xxxxxxxx xxxxxxx xx xxx xxxxxxx xxxxxx, $x=xx,\xxxx,xx,x$. }
```

i do `vip` then `gq` and get this:

```
	\caption{\label{fig:scheme}%
		xxxxxxxxxx xxxxxx xxxxxxxxxxx. xxxxxxxxxxx xxxxxxx xxxxxxxxxx xxx xxxxx
		xxxxx xxxx xxx xxxxxx xxx xxx xxxxx xxxxxxxxx xx $\xxxx=+,-$. xx xxxxxxxx,
	xx xxxxxxxx xxxxxxx xx xxx xxxxxxx xxxxxx, $x=xx,\xxxx,xx,x$. }
```

somehow the last line is flush with the starting command which does not seem correct?

**Comment by lervag** [comment] 2016-10-01 11:55
This is actually "by design". The reason is that the `{` and `}` start and stop an indented region, and I've not found a way to reliable keep the closing `}` indented unless I unindent on the same line.

I could consider the problem once more, if you insist that this is annoying and unexpected.

**Comment by nilsbecker** [comment] 2016-10-10 08:37
ah ok. i guess i can get used to it, or otherwise i will put the `}` on the new line. not a big deal.

**Comment by lervag** [comment] 2016-10-10 20:44
I actually often do just that; put the `}` on the new line.

Thanks!

**Closed by lervag** 2016-10-10 20:44 UTC
