### ISSUE TITLE
(N)vim freezing after :VimtexView with Zathura

### ISSUE THREAD

**Issue by Djoop** [lervag/vimtex#2231] opened 2021-11-04 16:32 UTC
### Description

After running :VimtexView, the viewer opens the file to visualize (as expected), but the vim interface is not responsive at all (until the pdf viewer is closed). I have not tried with vim so I cannot say if it is specific to nvim or not. The problem seems to disappear if I don't explicitly set g:vimtex_view_method in the configuration (although zathura is my default pdf viewer, i.e. in this case zathura will open but the interface will not freeze).

### Steps to reproduce

# Minimal init.vim

```
call plug#begin()
Plug 'lervag/vimtex'
call plug#end()
let g:vimtex_view_method = "zathura" 
```

# minimal.tex

```
\documentclass[]{article}
\begin{document}
Test
\end{document}
```

# Steps
1. nvim minimal.tex
2. :VimtexCompile
3. close the pdf viewer and re-open it with :VimtexView

### Expected behavior

nvim should not freeze

### Actual behavior

The interface does not respond anymore (until I close the pdf viewer)

### Do you use a latexmkrc file?

Yes (but not relevant)

### VimtexInfo

```yaml
System info
  OS: Linux 5.14.14-arch1-1
  Vim version: NVIM v0.5.1
  Has clientserver: true
  Servername: /tmp/nvimrJBIUE/0

VimTeX project: main
  base: main.tex
  root: /home/XXX
  tex: /home/XXX/main.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: Zathura
    xwin id: 0
  qf method: LaTeX logfile
```

**Comment by Djoop** [comment] 2021-11-05 07:54
I just updated again to the last version, but the problem still appears. I also noted that it does not happen when the viewer is opened automatically at the end of :VimtexCompile, I don't know if it can help…

**Comment by lervag** [comment] 2021-11-05 08:09
Ok. If you close the viewer after it opens from `:VimtexCompile`, then do `\lv` to open it. Then do `:VimtexInfo` again and show me the output, specifically the `viewer: ... cmd_start` part. It should have a `&` at the end.

**Comment by lervag** [comment] 2021-11-05 08:10
On my end, everything works with both neovim and Vim on Linux with the specified minimal example.

**Comment by lervag** [comment] 2021-11-05 08:11
Note, btw, that the reason for the change that might be problematic here is #2203; see also [my comment here](https://github.com/lervag/vimtex/issues/2203#issuecomment-942635022).

**Comment by Djoop** [comment] 2021-11-05 10:16
```
System info
  OS: Linux 5.14.14-arch1-1
  Vim version: NVIM v0.5.1
  Has clientserver: true
  Servername: /tmp/nvimP8tPi3/0

VimTeX project: main
  base: main.tex
  root: /home/XXX
  tex: /home/XXX/main.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 3
      output: /tmp/nvimP8tPi3/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e '$new_viewer_always = "0"' -e '$pdf_previewer = "zathura  -x \"nvr --servername /tmp/nvimP8tPi3/0 --remote-expr \"\\\"\"vimtex#view#reverse_goto(\%{line}, '"'"'\%{input}'"'"')\"\\\"\"\" \%S"' -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'main.tex'
      pid: 2898200
  viewer: Zathura
    xwin id: 104857603
  qf method: LaTeX logfile

```
Here you go, but I'm not sure it really includes anything regarding viewer except "zathura"? Should I do something else to include more information?

**Comment by lervag** [comment] 2021-11-05 10:24
Sorry, you need to close Zathura, then open it with `\lv`.

**Comment by Djoop** [comment] 2021-11-05 10:51
```
System info
  OS: Linux 5.14.14-arch1-1
  Vim version: NVIM v0.5.1
  Has clientserver: true
  Servername: /tmp/nvimBSUi8a/0

VimTeX project: main
  base: main.tex
  root: /home/XXX
  tex: /home/XXX/main.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 3
      output: /tmp/nvimBSUi8a/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e '$new_viewer_always = "0"' -e '$pdf_previewer = "zathura  -x \"nvr --servername /tmp/nvimBSUi8a/0 --remote-expr \"\\\"\"vimtex#view#reverse_goto(\%{line}, '"'"'\%{input}'"'"')\"\\\"\"\" \%S"' -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'main.tex'
      pid: 2906113
  viewer: Zathura
    xwin id: 102760451
    cmd_forward_search: zathura --synctex-forward 1:1:'main.tex' 'main.pdf'
  qf method: LaTeX logfile

```
Here it is, I closed the window, reopened with `\lv`, and closed again before doing `:VimtexInfo` (because I cannot do anything before closing it). Is it better?

**Comment by lervag** [comment] 2021-11-05 10:56
Ah, great; this explains the issue! Thanks. The problem is that the forward search command now opens the viewer. I believe there are _two_ issues here. I'll look into it.

**Comment by lervag** [comment] 2021-11-05 21:52
I think this is fixed now. But I don't quite understand why this happens for you. On my end, things just work. In any case, let me know if my commit fixed it for you and let me know if you have should have other related problems.

**Closed by lervag** 2021-11-05 21:52 UTC
Labels: bug

**Comment by Djoop** [comment] 2021-11-08 18:12
Thank you for the quick fix! I sadly cannot try on the original machine right now but I tried with the last version on another computer and it seems to work. I let you know if it happens again.

**Comment by lervag** [comment] 2021-11-08 21:08
My pleasure. If you still have the issue let me know and we'll figure it out.
