### ISSUE TITLE
Using vimtex "in_mathzone()" in .tid files

### ISSUE THREAD

**Issue by n-simplex** [lervag/vimtex#2132] opened 2021-08-13 17:55 UTC
### Description

I am writing files with the extension ".tid" for a piece of software called TiddlyWiki whose syntax is pretty similar to that of markdown. In these files, I want to be able to write down latex and I used to use UltiSnips and vimtex for this; the problem is that I can't seem to get the traditional `context "math()"` to work.

I read issue #1937, where a similar issue was had, but I can't seem to be able to resolve it using the ideas listed there (although I have literally copied and pasted code from there).

### Steps to reproduce

I have a file called "tid.snippets", which has the following minimal contents:
```
global !p
def math():
    return vim.eval('vimtex#syntax#in_mathzone()') == '1'
endglobal

context "math()"
snippet vec "Vector" iA
\frac{${1:numer}}{${2:denom}}${0}
endsnippet

snippet happy "Happy" iA
$1 is such a happy person!
$0
endsnippet
```
My minimal `.vimrc` simply loads UltiSnips and vimtex while also adding the `.tid` file extension:
```
set nocompatible
call plug#begin()

Plug 'sirver/ultisnips'
    let g:UltiSnipsExpandTrigger = '<tab>'
    let g:UltiSnipsJumpForwardTrigger = '<tab>'
    let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'

Plug 'lervag/vimtex'
    let g:tex_flavor='latex'
    let g:vimtex_view_method='skim'
    let g:vimtex_quickfix_mode=0
call plug#end()

autocmd BufRead,BufNewFile *.tid setfiletype tid
```
Then perform `vim happy.tid` and type `happy` on a line: the snippet expands. If we then type on another line `$ $` and inbetween the $s type `vec`, no expansion happens. If we remove the `context "math()"` it works again.

### Expected behavior

We expect it detect the math context using the vimtex function.

### Actual behavior

The snippet does not expand and the math context appears to fail.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
n/a
```

**Comment by lervag** [comment] 2021-08-14 21:57
> I am writing files with the extension ".tid" for a piece of software called TiddlyWiki whose syntax is pretty similar to that of markdown. In these files, I want to be able to write down latex and I used to use UltiSnips and vimtex for this; the problem is that I can't seem to get the traditional `context "math()"` to work.

The problem is that your `tid` syntax plugin does not support nested syntax highlighting of `$...$` latex inline math regions. In your minimal example, you don't load any plugins for your wiki filetype. Do you use any third party plugins? It seems to me as if there is not really any built-in syntax scripts (i.e., I can't find anything with `:edit $VIMRUNTIME/syntax/tid.vim`).

A simple solution is to add the `$...$` syntax support in your custom config. To do it, create a file like `~/.vim/after/syntax/tid.vim` with the following content:

```vim
syntax include @tidWikiNestedTex syntax/tex.vim
syntax region tidWikiEq
      \ start="\$" skip="\\\\\|\\\$" end="\$"
      \ contains=@tidWikiNestedTex keepend
```

**Comment by lervag** [comment] 2021-08-14 21:58
(When I say "simple solution", I don't mean simple in the sense that I expect people to know how to do this! I only mean it is a small amount of vimscript code that should work.)

**Comment by lervag** [comment] 2021-08-14 22:15
Also, I'm closing this issue, as it is not really a VimTeX issue. I hope and believe my previous reply may be helpful, though.

**Closed by lervag** 2021-08-14 22:15 UTC
Labels: bug

**Comment by n-simplex** [comment] 2021-08-14 22:59
@lervag thank you very much! Yet another example of where I see how little I actually know of Vim! I was aware that Vim had built-in syntax highlighting and so must have some ability to parse different types but had no idea that this could be programmable nor that vimtex might rely on this. Wonderful stuff!

**Comment by lervag** [comment] 2021-08-15 13:33
I'm glad you find it useful and helpful!

There's a lot to learn about Vim and how to do things. And considering the evolution of neovim with Lua, it's safe to say one can probably always learn new stuff! It's a cool journey to be part of! :)
