### ISSUE TITLE
Delay with matchparen feature for large files

### ISSUE THREAD

**Issue by tbrazel** [lervag/vimtex#1532] opened 2019-11-05 19:37 UTC
I have a large LaTeX file, and while I love the delimiter matching features of vimtex for small documents, they become burdensome when the document gets too large, and I'd like to know if it would be possible to disable them. For example:

1. If I accidentally type `}` then vimtex searches back through the entire document for a matching right brace (which doesn't exist) and this completely halts the document for a few seconds.

2. When I have mismatching delimiters, for example restrictions of functions `\left. f \right|_{A}`, then vimtex replaces `]]` with `\right.`, that is, it doesn't recognize mismatched delimiters.

Is it possible to entirely disable delimiter matching? I wasn't able to find anything in the documentation that directly does this, although I may have overlooked something. Thanks!

**Comment by lervag** [comment] 2019-11-05 20:48
I think 1. and 2. are really unrelated features. If I understand you correctly.

1. You are talking about the highlighting of the matching delimiter, right? I.e., if you move the cursor to a paranthesis, then the corresponding paranthesis is highlighted. Am I right? If so, then you can disable it with `g:vimtex_matchparen_enabled` (set it to 0). See `:help vimtex_matchparen_enabled`.

2. In this case I think you are talking about the insert mode mapping `]]`, which is supposed to close the "current" delimiter/environment. And your point is that it fails for some examples? If so, then it might be a bug and I can look into it.

**Comment by tbrazel** [comment] 2019-11-07 23:31
Hi, thanks for your reply! For #1 you are exactly right, that is the issue.

For example - try typing `$\left. x \right|$` and then hitting `]]`. I believe that this does not recognize that `\left.` is supposed to be matched with `\right|` since the delimiters don't match.  As a result, pressing `]]` returns `\right.`

Can you replicate this? Or is it just a local issue for me? Thanks!

**Comment by lervag** [comment] 2019-11-08 22:12
Ok, so it is already confusing. As mentioned, my points 1. and 2. are unrelated. Can we please focus one issue per thread?

Thus:

* Please open a new issue for the problem with `]]`.
* Let's continue the discussion about the issue with matchparen here.

----

I understand that delays with the matchparen feature will make you want to turn it off. But if possible, I would like to try and improve/fix it. But to do that, I would need to reproduce your lag. Would you by any change be willing/able to share one of you large LaTeX files where this is a problem and then describe how to reproduce? If not, are you able to create a temporary file that you can share?

**Comment by tbrazel** [comment] 2019-11-10 20:08
Absolutely! I have opened a new issue for the closing delimiters: https://github.com/lervag/vimtex/issues/1534

As far as the matchparen issue, when I open [this file](https://github.com/stacks/stacks-project/blob/master/criteria.tex), scroll to the bottom (for example, line 3390) and then type `}`, I get a delay since presumably vimtex is searching through the rest of the file to close a matching left brace. This delay gets more severe the longer the file size becomes.

When I put `let g:vimtex_matchparen_enabled = 0` in my .vimrc, the delay does not occur.

Thanks for your help!

**Comment by lervag** [comment] 2019-11-10 21:38
The lag is due to the search for the matching paranthesis, as already explained/established. There is another semi-obscure option that is relevant here: `:help g:vimtex_delim_stopline`. If you reduce this to e.g. 250 or 100 (default 500), then you should be able to observe that the lag is reduced.

**Comment by lervag** [comment] 2019-11-10 21:41
I'm curious if that might suffice as a "solution" for this issue. I could spend time on trying to find ways to improve the efficiency, but I personally don't really notice this lag and don't have an issue with it. Thus, it feels like not the most important issue to address.

**Comment by clason** [comment] 2019-11-11 09:25
@lervag It seems to depend quite a lot on the specific document (single vs. multi file project, nesting of delimiters etc.); subjectively, it seems to have gotten significantly worse over the last weeks or months (but that might not be due to vimtex but neovim internals or other plugins changing). So this can definitely be a "pain point" (in fact, I would say it is currently the biggest one for me -- but this should also be taken as a statement on how smooth vimtex runs otherwise!)

I'll play around with `g:vimtex_delim_stopline`; this seems like a good option (no need to try to match parentheses that are off the screen). Does this option also influence the auto-closing of delimiters?

**Comment by clason** [comment] 2019-11-11 12:44
To be more precise, `vimtex#delim#get_matching()` frequently shows up at the very top of the log whenever I profile slowdowns, so if(!) there is anything that can be done to speed it up (there may not be), I think it could be worth it.

Specifically, all time is spent in this line: https://github.com/lervag/vimtex/blob/906792f9db5be7513dbec9fae03a568c5cef8181/autoload/vimtex/delim.vim#L812

For reference, I also tested https://github.com/andymass/vim-matchup (which has a different implementation, see https://github.com/andymass/vim-matchup/blob/master/autoload/matchup/delim.vim), and there I don't see a slowdown. So maybe one could ~steal~ get inspired by some ideas from there (or just to bite the bullet and officially punt to it).

But it seems you are already aware of it, as it was discussed in #1051. (I'd be curious to understand how our TeX files differ -- it can't be the size -- so that you don't see the slowdowns we do.)

**Comment by lervag** [comment] 2019-11-11 21:23
@clason Thanks for pitching in. I'm also curious to understand why I don't observe these slowdowns/lags. It would of course be much easier to address them if I experience them similar to how you and @tbrazel report.

I am not surprised that the problem is the `searchpairpos` function. It is an advanced/complex operation, and in a big document, I would expect it to be slow. But perhaps not that slow.

@tbrazel Shared a relatively big document with me, with which I made the following minimal vimrc file for testing:

```vim
set nocompatible
let &rtp = '../../..,' . &rtp
let &rtp .= ',../../../after'
filetype plugin indent on
syntax enable

nnoremap q :qall!<cr>

" let g:vimtex_matchparen_enabled = 0
" let g:vimtex_delim_stopline = 25
silent edit minimal.tex

normal! 3390G
normal! o}
call feedkeys(":qa!\<cr>")
```

If I do `nvim --headless -u minimal.vim` (or `vim -u minimal.vim`), then this allows me to reproduce the lag at least somewhat. With the file supplied by @tbrazel, I experience a lag of about 0.75 s with default settings, and 0.35 s with the matchparen feature disabled. If I increase the stopline setting to 1000, then I get a lag of about 1.45 s.

I've been experimenting, and I've pushed an update with a new option `g:vimtex_delim_timeout` (default = 300 ms). This _should_ improve things in the sense of ensuring a maximum of 300 ms for the search. You can also adjust this number to your liking.

Please let me know what you think about this, and if you should come across new bugs as a result of me being sloppy... :p

**Comment by clason** [comment] 2019-11-11 21:33
@lervag Thanks! That does help -- I'm only observing a .6s lag (which is two times the timeout as expected, although I'm not sure why the function is called twice on `O}`).

And I understand it's a complex operation; that's what I meant by "punting": make a FAQ "Q: Matching parens is slow! A: Vimtex uses syntax to ensure correct matching, which is expensive; if it's too slow for you, install matchup."

**Comment by andymass** [comment] 2019-11-11 21:52
@clason I am curious, are you using `g:matchup_matchparen_deferred` or the default matching strategy with match-up?  If the former, that is by design, if the latter, that's very interesting.

**Comment by lervag** [comment] 2019-11-11 22:01
> @lervag Thanks! That does help -- I'm only observing a .6s lag (which is two times the timeout as expected, although I'm not sure why the function is called twice on O}). Out of curiosity, what's the number of } in that document @tbrazel shared?

According to `count()`, I find 23 `}`s. For me, the function is only called a single time. I checked with the above minimal vimrc file where I added `profile start ...` for the profiling.

It would be nice to have an example file generated explicitly to test this lag that I could add to the test suite. I think it could be good to add a test to ensure the lag does not increase.

> And I understand it's a complex operation; that's what I meant by "punting": make a FAQ "Q: Matching parens is slow! A: Vimtex uses syntax to ensure correct matching, which is expensive; if it's too slow for you, install matchup."

The word "punting" is/was not in my vocabulary. Thanks, I've added a faq entry on this as you suggest.

I also notice that matchup (and the "original" matchparen) uses a separate timeout for insert mode. That seems like a good idea, I think, and something I should probably add to vimtex as well. Should not be too hard.

**Comment by lervag** [comment] 2019-11-11 22:11
> I also notice that matchup (and the "original" matchparen) uses a separate timeout for insert mode. That seems like a good idea, I think, and something I should probably add to vimtex as well. Should not be too hard.

Done.

**Comment by lervag** [comment] 2019-11-11 22:14
I think that should solve this issue. I don't see any more ways to improve upon this (which obv. does not mean there are none!). I think the updated timeouts should at least partially ensure that things do not slow down too much, especially when in insert mode. And as discussed, if one still thinks it is too slow, then vim-matchup might be a very good alternative!

**Closed by lervag** 2019-11-11 22:14 UTC
Labels: enhancement

**Comment by clason** [comment] 2019-11-11 23:06
@andymass That's vanilla matchup (with `override_vimtex`, of course). I do see some slight slow-down when highlighting not in insert mode, but nothing on the order of the `searchpairpos`. 

@lervag OK, that would explain it then -- I have 3000 `}`s... I'll see about "donating" a stress test example, but I think ~1000 `{}` pairs in a single(!) line followed by `o}` should be enough to measure slowdown.

The additional function call might be after leaving insert mode to try to highlight the matching paren on which the cursor ended (I'm profiling manually rather than from a vimrc).

And yes, it feels much snappier now (although matchup is still faster); I agree that this is an acceptable situation. As always, thank you so much for being so open and helpful on these issues! The support you put into your plugin is really outstanding and appreciated.

**Comment by lervag** [comment] 2019-11-12 21:42
> As always, thank you so much for being so open and helpful on these issues! The support you put into your plugin is really outstanding and appreciated.

Thanks, that's very kind of you! :)

> The additional function call might be after leaving insert mode to try to highlight the matching paren on which the cursor ended (I'm profiling manually rather than from a vimrc).

That makes sense, yes.

> And yes, it feels much snappier now (although matchup is still faster); I agree that this is an acceptable situation.

Great, happy to hear it.

> OK, that would explain it then -- I have 3000 }s... I'll see about "donating" a stress test example, but I think ~1000 {} pairs in a single(!) line followed by o} should be enough to measure slowdown.

Hah, that's a lot of `}`s. I would be very happy if you (or anyone else) would be willing/able to construct this stress test example. I don't know if having the pairs on the same line is important for reproducing or not. I wouldn't really think it should matter, but of course, it could.

**Comment by clason** [comment] 2019-11-12 22:11
> Hah, that's a lot of }s. 

Tell me about it, I had to type them :) (on a German keyboard layout, to boot!)

> I would be very happy if you (or anyone else) would be willing/able to construct this stress test example. 

It's a fairly typical example; not sure how I'd feel if it ended up in the vimtex test suite... But otherwise I'd be happy to share them; most of them are available from arXiv, anyway. 

> I  don't know if having the pairs on the same line is important for reproducing or not. I wouldn't really think it should matter, but of course, it could.

I think it does; 1000 pairs on a line each leads to much less of a slowdown (not so noticeably -- any more! -- with 1000, but for >5000 you should see a difference).

**Comment by lervag** [comment] 2019-11-18 21:22
> not sure how I'd feel if it ended up in the vimtex test suite

Yes, I understand and respect that, and I don't want to add other peoples real work to the test suite. I'm adding an example/a test based on your idea now. I want to at least ensure that things do not get slower by future updates. Thanks for the suggestion!
