### ISSUE TITLE
vimtex breaks v_g_CTRL-G

### ISSUE THREAD

**Issue by brianbuccola** [lervag/vimtex#1143] opened 2018-06-15 15:11 UTC
`v_g_CTRL-G` allows you to select some text and then see some basic info about your selection, such as how many words you've selected.

Loading vimtex breaks this functionality: pressing `v_g_CTRL-G` seems to *very quickly* print the relevant info, but then it immediately disappears, way too quickly to read what it says.

I can confirm that after disabling vimtex, there is no issue.

1. A minimal `vimrc` file:

    ```vim
    set nocompatible
    let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
    let &rtp .= ',~/.vim/bundle/vimtex/after'
    filetype plugin indent on
    syntax enable
    ```

2. A minimal `mwe.tex` file:

    ```tex
    \documentclass{minimal}
    \begin{document}
    Hello World!
    \end{document}
    ```

3. Run `vim -u vimrc mwe.tex`, visually select the word `Hello`, and press `g_CTRL-G`.

    - Expected behavior: Print the following for at least a few seconds.

            Selected 1 of 4 Lines; 1 of 5 Words; 5 of 70 Bytes

    - Actual behavior: Info disappears immediately.

**Comment by andymass** [comment] 2018-06-15 17:19
I believe this is caused by the 50ms popup menu check timer.  With the MWE you can `call timer_stop(1)` to verify the behavior goes away.  I guess timers clear certain messages even when they don't do anything.  For a few reasons, match-up never seemed to have the issue #493 which led to that hack and does not require a constant timer.

A possible workaround is to use my plugin match-up for the purpose of highlighting matches instead of vimtex's built-in one (see [discussion here](https://github.com/lervag/vimtex/blob/8b441e530b0b3c26b46fd411a1e5fffad2904b3b/doc/vimtex.txt#L271)), although I admit it has much greater effects than just this, so it's not appropriate for everyone.

**Comment by lervag** [comment] 2018-06-17 13:49
Interesting. I think @andymass is correct that this happens because of a timer loop. I think @andymass's plugin is good, and so it is a viable choice to use that instead of vimtex's built in match highlighter.

**Comment by lervag** [comment] 2018-06-17 13:58
I've added the minimal example. I can confirm the bug with Vim, but it works as expected in neovim. I also confirm that the problem is due to the timer, regardless of what the timer callback actually does.

My understanding is that this is a bug in Vim internals, not with vimtex. There are two working "solutions": Use neovim or use @andymass's plugin. I will not be able to solve this bug myself, and so I am deciding to close the issue as `won't fix`. Sorry, and I hope someone might create a minimal example and open an issue with the Vim devs.

**Closed by lervag** 2018-06-17 13:58 UTC
Labels: won't fix

**Comment by brianbuccola** [comment] 2018-06-18 07:40
Thanks, both. matchup looks like a very nice plugin, which I hadn't known about. I've just switched over.

**Comment by lervag** [comment] 2018-06-18 09:06
No problem, and I'm sorry about the minor inconvenience.

**Comment by brianbuccola** [comment] 2018-06-19 08:03
I've found that when using matchup, my cursor movement is seriously delayed, even on a relatively small paper (6 page report), and even after adding

```vim
let g:matchup_matchparen_deferred = 1
```

So, I think I will just stick with vimtex's built-in matching, and if I need `v_g_CTRL-G`, I will just

```vim
call timer_stop(1)
```

or maybe make a keybinding that toggles

```vim
call timer_pause(1, 1)
```

and

```vim
call timer_pause(1, 0)
```

or something.

**Comment by lervag** [comment] 2018-06-19 08:15
A third option is to switch to neovim, where it seems everything works as expected.

**Comment by brianbuccola** [comment] 2018-06-19 08:30
True. I may at some point, but just don't have the time right now  -- too many projects that need finishing without any major disruption/change in my workflow. Perhaps in August, once things settle down a bit.

Anyway, thanks again.

**Comment by lervag** [comment] 2018-06-19 08:56
No problem. I hope things work out well.

**Comment by lervag** [comment] 2018-06-28 20:28
I've updated to use `TextChangedP` when possible, since this should improve the latency somewhat (I think) and avoid running the callback loop in the background when idle. I think this should also solve the present issue as long as you use a recent Vim version.

**Comment by brianbuccola** [comment] 2018-06-29 08:31
Can confirm this resolves the issue -- thanks!
