### ISSUE TITLE
Equation indentation

### ISSUE THREAD

**Issue by Eisfreak7** [lervag/vimtex#342] opened 2016-02-05 13:32 UTC
Hi,
Equations with Arrows aren't correctly indented. Auto indentation gives:
```
\begin{something}
    \begin{equation}
        \Rightarrow
\end{equation}
\end{something}
```
```
\begin{something}
    \begin{equation}
        \Leftarrow
        \end{equation}
\end{something}
```
And `\Leftrightarrow` gives the same result as leftarrow.
These errors propagate through the rest of the file, where the indentation level is then off by one.

**Comment by lervag** [comment] 2016-02-05 13:36
Hmm. I think it is because the `\left` and `\right` part is erroneously matched as a delimiter. I'm currently working on a huge refactoring of how delimiters, including environment begin/end and math modifiers (`\left`, `\right`, etc), are handled and parsed. I think this issue should be resolved when I finish that work, which I think will be in not too long. I'll try to remember to notify you when I push the refactored code.

**Comment by Eisfreak7** [comment] 2016-02-05 14:10
Thank you for your work, no need to hurry of course

**Comment by nhooyr** [comment] 2016-02-06 23:18
@lervag I see a commit for refactoring delimiter engine. So is this fixed?

**Comment by lervag** [comment] 2016-02-07 08:33
Thanks, @nhooyr, I think you are right: It seems fixed for me as well.

**Closed by lervag** 2016-02-07 08:33 UTC

**Comment by Eisfreak7** [comment] 2016-02-07 09:48
Its fixed for me too.
Weired behaviour I noticed when I auto-indented the problematic file now:
```
Wenn ..., $f(x) \ge 0 \fa x$, $f(x_0 > 0$ für ein $x_0$ ...
    test
```
Apparently the unclosed '(' in 'f(x_0 > 0' causes this.
It's not really issue-worthy, since it is an semantic error from me. But syntactically there's nothing wrong so I thought it can't hurt to report it.

Another change I noticed where I'm not sure wether it's intentional:
```
$\norm{v_i} = 1$, $v_i \bot v_j$ für $i \ne j$ \quad $\left(\spr{v_j, v_j} =
	\begin{cases}
		0 & i \ne j \\
		1 & i = j
	\end{cases}
	=
\delta_{ij}\right)$
```
Here the `cases` is indented, the `\delta...` is not. Might be that this is intentional, since the cases is enlclosed by left and right.

Altogether diffing the file showed many improvements in the indentation. Thanks again.

**Comment by lervag** [comment] 2016-02-07 11:54
Comments, replies to the two things you've noticed:

1. I don't understand why this is surprising or weird at all. An unclosed paranthesis will obviuosly lead to increased indentation?

2. This is actually as expected. The reason is that the current version will de-indent the line that contains the end delimiter. I know this is somewhat surprising and perhaps not the expected behaviour for most people, but at the moment, it is the only way I've managed to make the indentation consistent for delimiters. If you join the `\delta...` with the preceding line, then you should notice that the preceding line will be de-indented.

I'm happy to consider to change this behaviour, so if you feel it should be changed, then open a new issue. I can't promise that I'll be able to, but I can certainly try.

**Comment by Eisfreak7** [comment] 2016-02-08 08:18
No, Im happy with how things are.
Those were just things where I was not entirely sure if it was intentional, so better report it than keep silent.
To the first point: I'd expect this behaviour for `\left(` parenthesis. For `(` parenthesis it's debatable because according to latex syntax you don't *have* to close them and in theory something with an open, but not an closed parenthesis could come up.
But as I said, I don't think it has to be changed. Its quite unlikely that somebody needs to have just an opening parenthesis without an closing one (and if so, maybe `\phantom )` would do it) and as I described this behavior even helped me catch errors in my file.

**Comment by lervag** [comment] 2016-02-08 08:24
I've actually talked to someone who used an unclused paranthesis deliberately, so I am aware of this being a possible issue. However, I've made the same conclusion as you just did: This happens so rarely, that it seems more intuitive to include them in the indent items. If someone opens an issue and wants this specific feature to allow unmatched parantheses, then I might consider to add an option for it. If not, then I'm happy with the current version.

In any case, the new delimiter engine might still have some bugs (I fixed a few yesterday). Let me know if you find anything.
