### ISSUE TITLE
Getting Pretty Bad Lag

### ISSUE THREAD

**Issue by cabellicar123** [lervag/vimtex#209] opened 2015-07-31 10:14 UTC
I am using `vimtex` with the following options:
```
let g:tex_flavor='latex'
182 let g:vimtex_fold_enabled=0
```
For some reason I am getting pretty bad lag when the two options that create lag seem to be disabled. I do not get bad lag on any other filetype so this appears to be caused by `vimtex`.

**Comment by lahwaacz** [comment] 2015-07-31 11:11
Try to disable `vimtex` completely to see if the problem is with `vimtex` or with vim's default `tex` plugin:

    let g:vimtex_enabled = 0

See `:h tex` for more info about the vim's `tex` plugin.

**Comment by cabellicar123** [comment] 2015-07-31 21:08
Definitely a bit faster without `vimtex` but that's to be expected I suppose. LaTeX files are definitely still slower than others. Is there a way to trim back of disable the default plugin and let `vimtex` take over to try to max out the speed I can get?

**Comment by lahwaacz** [comment] 2015-08-01 06:36
`vimtex` does not provide everything that `tex` does, it only adds new features and changes others (e.g. folding). See #168 for information about profiling vim plugins and the [last post](https://github.com/lervag/vimtex/issues/168#issuecomment-108019496) for suggested settings for the `tex` plugin.

**Comment by lervag** [comment] 2015-08-01 09:59
As @lahwaacz has mentioned, the lag you are experiencing is probably mostly due to the underlying (La)TeX plugin that ships with vim. I think his comment in #168 should help you to increase the speed.

I'm closing this. If you can provide a specific example where vimtex actually does introduce a noticable lag, then feel free to reopen. Note that you should make sure that it is really vimtex that does introduce the lag, either through a minimal vimrc file, or by e.g. turning off syntax highlighting.

**Closed by lervag** 2015-08-01 09:59 UTC
