### ISSUE TITLE
Pressing q in vimtex-toc with g:vimtex_index_split_pos='full' closes my split window

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#1082] opened 2018-03-10 10:40 UTC
1. A minimal `vimrc` file, for instance:

    ```vim
    set nocompatible
    let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
    let &rtp .= ',~/.vim/bundle/vimtex/after'

    filetype plugin indent on
    syntax enable

    " Vimtex option:
    let g:vimtex_index_split_pos='full'
    ```

2. `minimal.tex` 
    ```tex
    \documentclass{minimal}
    \begin{document}

    Hello World!

    \end{document}
    ```

3. Steps to reproduce:
```
$ vim minimal.tex
:vertical help vimtex
<C-w>w (refocus on minimal.tex split)
<leader>lt
q to close toc.
```
`q` closes the split window and I am back in the help window which I do not want.
I would like to keep my current window/split setup.

For illustration:
```
$ vim minimal.tex
+-------------+
| tex         |
|             |
|             |
|             |
+-------------+

:vertical help vimtex
+------+------+
| help | tex  |
|      |      |
|      |      |
|      |      |
+------+------+


<C-w>l
<Leader>lt
+------+------+
| help | toc  |
|      |      |
|      |      |
|      |      |
+------+------+

Press q to close toc

Current behavior
+-------------+
| help        |
|             |
|             |
|             |
+-------------+

Expected behavior
+------+------+
| help | tex  |
|      |      |
|      |      |
|      |      |
+------+------+

```

**Comment by lervag** [comment] 2018-03-12 14:35
I think it is fixed now.

**Closed** 2018-03-12 14:35 UTC

**Comment by kiryph** [comment] 2018-03-12 14:48
Thanks for the update. Now my given example works as expected.

**Comment by kiryph** [comment] 2018-03-12 14:57
However, there is another issue.
Following sequence replaces the vimtex help with the buffer of minimal.tex:
```
$ vim minimal.tex
:vert h vimtex
:winc l
<Leader>lt
<CR>
```
This should not replace the help in the left window with the buffer of minimal.tex. The help should stay open.

Again an illustration:
```
$ vim minimal.tex
+-------------+
| tex*        |
|             |
|             |
|             |
+-------------+

:vert h vimtex
+------+------+
| help*| tex  |
|      |      |
|      |      |
|      |      |
+------+------+


:winc l
<Leader>lt
+------+------+
| help | toc* |
|      |      |
|      |      |
|      |      |
+------+------+

<CR>

Current Behavior
+------+------+
| tex  | tex* |
|      |      |
|      |      |
|      |      |
+------+------+

Expected Behavior
+------+------+
| help | tex* |
|      |      |
|      |      |
|      |      |
+------+------+

```

**Comment by lervag** [comment] 2018-03-15 21:51
Hmm, strange. I can't reproduce this one. Could you give me a minimal vimrc file?

**Comment by kiryph** [comment] 2018-03-16 11:07
Did you press `<CR>` on `Preamble` or `q`?

**Comment by lervag** [comment] 2018-03-16 19:08
Ok, I've reproduced it. Looking in to it now.

**Comment by lervag** [comment] 2018-03-16 19:17
Done. I think... :)

**Comment by lervag** [comment] 2018-03-16 19:42
No problem!
