### ISSUE TITLE
After compile focus is on the pdf viewer not on vim + pdf viewer closed after second compilation

### ISSUE THREAD

**Issue by DrShiva** [lervag/vimtex#1495] opened 2019-09-19 20:38 UTC
**Issue**
When I compile a `.tex` file with `<leader>ll` the viewer (SumatraPDF) appears with the correct pdf. The problem is that I lost the focus on vim, I need to type `ALT+TAB` to go back on vim. The second time I compile (typing `\ll`), the viewer closes. In a way I obtain the opposite of #180  request.

**minimal.vim**
```vim
let g:vimtex_latexmk_options="-pdf -pdflatex='pdflatex -file-line-error -shell-escape -synctex=1'"
let g:latex_viewer = 'SumatraPDF'
let g:vimtex_quickfix_open_on_warning = 1
let g:vimtex_indent_enabled = 1
let g:vimtex_latexmk_enabled = 1
let g:vimtex_fold_enabled = 0
let g:vimtex_quickfix_mode = 2
let g:vimtex_quickfix_open_on_warning = 1
let g:vimtex_toc_resize = 0
let g:vimtex_toc_hide_help = 1
let g:vimtex_latexmk_callback = 1
let g:vimtex_complete_recursive_bib = 0
let g:vimtex_view_automatic = 1
let g:tex_flavor = 'latex'
let g:vimtex_compiler_method = 'latexmk'
let g:vimtex_compiler_progname = v:progname
let g:vimtex_view_method = 'general'
let g:vimtex_view_general_viewer = 'SumatraPDF'
" I also tested with mupdf and the issue was the same
let g:vimtex_view_general_options
                \ = '-reuse-instance -forward-search @tex @line @pdf'
let g:vimtex_view_general_options_latexmk = '-reuse-instance'
let g:vimtex_view_general_options
                \ = '-reuse-instance -forward-search @tex @line @pdf'
                \ . ' -inverse-search "gvim --servername ' . v:servername
                \ . ' --remote-send \"^<C-\^>^<C-n^>'
                \ . ':drop \%f^<CR^>:\%l^<CR^>:normal\! zzzv^<CR^>'
                \ . ':execute ''drop '' . fnameescape(''\%f'')^<CR^>'
                \ . ':\%l^<CR^>:normal\! zzzv^<CR^>'
                \ . ':call remote_foreground('''.v:servername.''')^<CR^>^<CR^>\""'

let mapleader=","
let maplocalleader=","
```

**Steps to reproduce**
1. I open the `.tex` file
2. I type `<leader>ll`, the compilation is ok (no error).
3. The viewer (SumatraPDF) opens.
4. I need to type `ALT-TAB` to go back on vim.
5. I type again `<leader>ll`, the viewer close and vimtex messages: "Compiler stopped."
6. I can repeat the procedure from step 2. to step 5.

**Observde vs expected Behaviour**
Observed: After compile (`\ll`), the focus goes on the viewer,
Expected: After compile (`\ll`), the focus remains on vim.

**Output from VimtexInfo**
```
System info
  OS: Microsoft Windows 10 Professionnel (10.0.17763 N/A version 17763)
  Vim version: VIM 8.1 (1-2027)
  Has clientserver: true
  Servername: GVIM

vimtex project: test
  base: test.tex
  root: C:/test
  tex: C:/test/test.tex
  out: C:/test/test.pdf
  log: C:/test/test.log
  aux: C:/test/test.aux
  fls: C:/test/test.fls
  compiler: latexmk
    backend: jobs
    output: C:/Users/dumas/AppData/Local/Temp/VIA102E.tmp
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
    job: process 17756 dead
    cmd: set max_print_line=2000 & latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e "$pdf_previewer = 'SumatraPDF -reuse-instance'" -e "$success_cmd = 'echo vimtex_compiler_callback_success'" -e "$failure_cmd = 'echo vimtex_compiler_callback_failure'" "test.tex"
  viewer: General
    process: 
      pid: -
      cmd: start /b cmd /s /c "SumatraPDF -reuse-instance -forward-search "C:/test/test.tex" 25 "C:/test/test.pdf" -inverse-search "gvim --servername GVIM --remote-send \"^<C-\^>^<C-n^>:drop \%f^<CR^>:\%l^<CR^>:normal\! zzzv^<CR^>:execute 'drop ' . fnameescape('\%f')^<CR^>:\%l^<CR^>:normal\! zzzv^<CR^>:call remote_foreground('GVIM')^<CR^>^<CR^>\"" >nul"
  qf: LaTeX logfile
    config: 
      packages: 
        default: 1
      default: 1
  document class: article
```

**Nota Bene**
Thanks a lot to Karl Yngve Lervåg for his wonderful work!
Perl backend is Strawberry.
I'm a beginner.

**Comment by lervag** [comment] 2019-09-20 06:33
Hi @DrShiva. Thanks for the kind words!

Before we address the issue: your set of vimtex configuration is not very good. It can be reduced without any loss of generality/specifics to the following:

```vim
let g:tex_flavor = 'latex'

" I don't think you need to set this; it is set automatically
let g:vimtex_compiler_progname = v:progname

" I also tested with mupdf and the issue was the same
let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options_latexmk = '-reuse-instance'
let g:vimtex_view_general_options
                \ = '-reuse-instance -forward-search @tex @line @pdf'
                \ . ' -inverse-search "gvim --servername ' . v:servername
                \ . ' --remote-send \"^<C-\^>^<C-n^>'
                \ . ':drop \%f^<CR^>:\%l^<CR^>:normal\! zzzv^<CR^>'
                \ . ':execute ''drop '' . fnameescape(''\%f'')^<CR^>'
                \ . ':\%l^<CR^>:normal\! zzzv^<CR^>'
                \ . ':call remote_foreground('''.v:servername.''')^<CR^>^<CR^>\""'
```

I.e., most of your settings were either deprecated or just repeating a default setting.

So, to the issue at hand. It is unfortunately not so easy to help, since I don't use Windows myself. However, I believe it may be something to do with how processes on Windows work. I.e., Vim spaws a latexmk process (a perl process), which spawns SumatraPDF. When you stop latexmk, it seems it for some reason stops its child process SumatraPDF as well.

I understand that it may be complicated, but I would again suggest that you provide a full minimal example as was indicated in the [issue template](https://raw.githubusercontent.com/lervag/vimtex/master/.github/ISSUE_TEMPLATE/issue_report.md). I.e., provide a *minimal.vim* and a *minimal.tex* file, preferably similar to those suggested in the template. Further, you should let one of the initial steps for reproducing be something like `vim --servername vim -u minimal.vim minimal.tex`.

Since you are using gvim on Windows, one way of doing the above is to copy your `_vimrc` file to someplace safe, then create a new one which is the minimal one. Then open `minimal.tex` any way desired.

**Comment by leonorbert** [comment] 2019-10-03 19:55
I'm also having this issue with the focus on SumatraPDF and not on gVim. I use Win 8.1, have Strawberry for my Perl, and use latexmk for compilation. I'm basing my comment here on the default Command Prompt use by Vim, though ideally I want to use PowerShell instead. See my link at the bottom.

**minimal.vim**
This is from the help documentation, and as noted above.
```vim
source $VIMRUNTIME/vimrc_example.vim
let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options_latexmk = '-reuse-instance'
let g:vimtex_view_general_options
	\ = '-reuse-instance -forward-search @tex @line @pdf'
	\ . ' -inverse-search "gvim --servername ' . v:servername
	\ . ' --remote-send \"^<C-\^>^<C-n^>'
	\ . ':drop \%f^<CR^>:\%l^<CR^>:normal\! zzzv^<CR^>'
	\ . ':execute ''drop '' . fnameescape(''\%f'')^<CR^>'
	\ . ':\%l^<CR^>:normal\! zzzv^<CR^>'
	\ . ':call remote_foreground('''.v:servername.''')^<CR^>^<CR^>\""'
```

**minimal.tex**
```tex
\documentclass{article}

\begin{document}
	This is my minimal .tex example.
\newpage
    Here's a second page of text.
\end{document}
```

**Steps to reproduce**

1) From PowerShell or (Command Prompt) change the directory to where the example files are, then run: 
`vim --servername vim -u minimal.vim minimal.tex`
2) Type "\ll" to start compilation.
3) Double click on second page for inverse search.
4) Alt-Tab back to terminal.
5) Type "\lk" to stop compilation.

**Observed behavior**
* When compilation is completed focus remains on the new SumatraPDF window.
* Forward search works but focus remains on SumatraPDF. Not sure if this is expected or not. It's probably more convenient to have focus come back to Vim.
* SumatraPDF closes when compilation stops. I don't really mind this, and I guess it's a Windows feature according to the comment from @lervag. I usually work with continuous updating anyway.
* Inverse search works even when ``--servername vim`` is not specified for **gVim** both in PowerShell and Command Prompt. Focus remains on vim or gVim (which is probably desirable).
* Inverse search does not work for Vim running inside the terminal (again, either PowerShell or Command Prompt) unless ``--servername gvim`` is added. It says: `E247: no registered server named "GVIM": Send failed.`

**Desired behavior**

* Return focus to terminal or gVim after compilation
* Automatically select server for inverse search from terminal mode.
* Enable forward and inverse search for PowerShell. I'm going to add this to #1507 because I saw that my vimrc PowerShell settings break searching, not just VimCountWords.

**Comment by lervag** [comment] 2019-10-04 21:47
> Desired behavior
>
> * Return focus to terminal or gVim after compilation

I'm sorry, but I don't know how to do this on Windows. When a new window opens, it is focussed, AFAIK. I'll be glad to review and accept PRs, though.

> * Automatically select server for inverse search from terminal mode.

Yes, the server really has to be specified in terminal mode. I think the best advice is to make an alias. I don't know how to do this in command prompt or powershell, but I assume it is possible. Alternatively, you could use something like msys2 or similar, which allows to use a bash shell and `.bashrc`.

> * Enable forward and inverse search for PowerShell. I'm going to add this to #1507 because I saw that my vimrc PowerShell settings break searching, not just VimCountWords.

I prefer to keep the issues very atomic, so please don't raise more than a single point in each issue. I try my best to keep the issue count low (by constructively solving them, if I can), but I don't have much time, and so it helps a lot if the issues are concise and simple/atomic. If #1507 is about searching, then open a new one for forward/inverse search.

I'll close this present issue, as I don't quite see any real actions as of now.

**Closed by lervag** 2019-10-04 21:47 UTC
Labels: bug

**Comment by lervag** [comment] 2019-10-04 21:49
> **minimal.vim**
> This is from the help documentation, and as noted above.
> ```vim
> source $VIMRUNTIME/vimrc_example.vim
> ...
> ```

By the way, I don't have this `vimrc_example.vim`. To me, it seems your vimrc does not load vimtex. Did you imply that vimtex is installed directly into your runtime files instead of the now more common approach of using either a package or standard plugin installation (e.g. vim-plug)?

**Comment by leonorbert** [comment] 2019-10-05 08:22
I agree there's not much to be done here. The focus is a small problem, since return is easy and the window automatically updates without focusing when the .tex file is written. I might look into possibilities for returning the focus, though, in the future.

I modified the minimal.vim to only have the ft plugin enabled. Yes, I do load vimtex automatically in the runtimepath, which has been working well.

**Comment by DrShiva** [comment] 2019-10-06 07:48
Thanks to you Lervag! I agree with you. After the first compilation it is easy to ALT-TAB just one time.
The Sumustra document stays open. After each backup the modifications done in the latex file on gvim are instantly updated on the Sumatra, the focus remaining on gvim. 
I've key-mapped the F2 to write the file (:w) on gvim. So it is perfect for me!

**Comment by lervag** [comment] 2019-10-06 12:55
> So it is perfect for me!

Great, I'm happy to hear it. Let me know if you should happen to have more/other problems!
