### ISSUE TITLE
feature wish: custom paragraph definition

### ISSUE THREAD

**Issue by nilsbecker** [lervag/vimtex#226] opened 2015-09-16 15:38 UTC
for re-wrapping text the `gqip` command is very useful. unfortunately, when editing a paragraph that includes commented lines (ie. without an empty line which is not always possible to add, because if would start a new paragraph), `gqip` garbles everything, breaking into the commented lines. the same happens when an equation environment begins and/or ends within a paragraph without a paragraph break. 

so, for latex use, it would be very helpful if custom paragraphs borders could be defined not only at emply lines but also at new environments and at comments. this may be hardcoded in vim and thus not feasible, but still it's quite annoying. feel free to close if impossible, obviously.

it may also be that another text object can be used or defined instead of the paragraph, with the same effect?

**Comment by lervag** [comment] 2015-09-17 06:49
This should be relatively simple. The problem is only in the precise definition of the paragraph borders. That is, we need to have a precise definition of what the beginning of a paragraph should look like, and for what the end of the paragraph should be.

The feature requires:
- [ ] Text object `ip`
- [ ] Text object `ap`
- [ ] Motion `}`
- [ ] Motion `{`

**Comment by lervag** [comment] 2015-09-17 08:21
I made a first version, please test.

**Comment by nilsbecker** [comment] 2015-09-17 09:14
thanks! it looks quite good already. i tried `gqip` in paragraphs with commented lines and eqn environments where it worked just fine most of the time. if a paragraph looks like this:

    lfakjasd jalkdsfj jdfkjs af  
    % sdf
    aldkfj jsdkf
    akldfjjfksdjl jaksdj lksadjf

invoking it on first line will not justify the second part, which i think is the desired behavior.

the following things did not go as expected:

- `gqap` before an equation environment joined the first two lines of the equation
- lines that end in % were joined to the next line. 

example:

     \somecommand{%
     contents that are not allowed to have a paragraph break 
     on 
     several lines that i would like to justify
     }
results in commenting out 'contents that are...'

- paragraphs that are fully commented are garbled

ex

    % lala aldfj lkjasdf
    % skd
    % alkdf aksdlfj asfkja asdlfl alsdkjf alk

the last one is arguably less important?

**Comment by lervag** [comment] 2015-09-17 09:18
I'll look into this more later. Thanks for providing good feedback and good examples.

The last one is not a vimtex issue, but rather due to your vim settings. In particular, take a look at `:h formatoptions` and `:h fo-table`. Note that you need `q` in `formatoptions` to format them with `gq` and similar.

**Comment by nilsbecker** [comment] 2015-09-17 09:39
ah, thanks for the `formatoptions` info. i had them set but with surrounding quotation marks...

**Comment by lervag** [comment] 2015-09-17 11:45
I've made an update that at least fixed a problem on my end. It does not fix the problem with the comments at end of lines, but I think it might fix the problem with `gqap` before equation environments.

Could you test, and give a brief summary of the remaining problems?

**Comment by nilsbecker** [comment] 2015-09-17 12:15
yes, `gqap` seems to work now before equations. also, paragraphs of the form 

    % skdjf 
    % skldfj
    kdfjdsjf
    fksjdf

work both inside the comment and inside the non-comment.

problems i still see:

- commented paragraphs in succession

    % aldfj
    % akdfjl aslkdfj alkjas df

    % sjdjf k 
    % fsjkdfa  fldfs fjksf

here, invoking `gqip` in the first commented paragraph also affects the second (and vice versa)

- % at end of line

one could argue if inside an equation or figure environment `gqip` should do anythin at all. it generally makes little sense. but then one can also just not use it. other than that it seems fine!

**Comment by lervag** [comment] 2015-09-17 13:57
The first problem was easy to solve (try latest version).

The second seems more difficult, as I am not sure I agree that in general, `\command{%` should mark a paragraph boundary. That is, I think the problem here is not with the paragraph motion and text object, but with the formatter, e.g. `gq`. If you agree with me, then I don't think I know how to solve this.

**Comment by nilsbecker** [comment] 2015-09-17 14:04
well, i don't know either about `\command{%`. normally the `%` at the end of a line would actually join the lines for tex, by commenting out the line break, correct? in that sense it's more like the opposite of a paragraph break. however in practice, it is used to make code more readable, and usually joining this line is not desired.

i think this is not a very important use case compared to others. what is a bit inconvenient is that just using `gqip` on a paragraph that contains such a line, actually produces wrong output. it would be less severe if the `%` were just deleted upon joining lines. i guess this is what you are suggesting: that `gq` should handle the tralining `%` in some meaningful way when joining lines?

**Comment by nilsbecker** [comment] 2015-09-17 14:08
also see here. probably too much information... http://tex.stackexchange.com/questions/7453/what-is-the-use-of-percent-signs-at-the-end-of-lines

**Comment by nilsbecker** [comment] 2015-09-17 14:14
also, there are a number of line breaking options: http://www.personal.ceu.hu/tex/breaking.htm

one could argue the e.g. when someone does this:

    skdfj fjj fkj\\
    kdfj jfkd
    skdjf fjdk fjfj jskf dfj 

they also do now want the first two lines joined? of course one can argue that making everything work is an open-ended problem and some limitations have to be accepted. also, again i don't know if this is best fixed by the `p` text object or by the actual justification...

**Comment by lervag** [comment] 2015-10-01 11:58
I do know the usage of the percent at end of lines. But I think the issue we are now discussing is not the same as the original issue. That is, we are now discussing the problem that formatting a paragraph that uses `%` or `\\` at end of line leads to erroneous formatted paragraphs with the standard format expression.

I actually think a possibility is to implement a custom format expression. If this is a feature you really want, then I propose that you open a new issue where you explain (as you have done here) what is required from such a custom format expression. I think it could be possible to implement a formatter that takes into account `%` and `\\` at end of lines, but I might not be able to start work on that immediately (that is why I want you to open this as a new issue with explanation if you are interested, so that I can read the explanation when I get to it).

So: regarding this particular issue, I think it is solved. I'll leave it to you to close the issue if you agree.

**Comment by nilsbecker** [comment] 2015-10-03 11:22
ok. i will open a new one about end-of-line problems. thanks for fixing this one.

**Comment by lervag** [comment] 2015-10-04 20:38
No problem!

**Closed by lervag** 2015-10-04 20:38 UTC
Labels: enhancement
