### ISSUE TITLE
`VimtexToggleMain` to preserve root folder.

### ISSUE THREAD

**Issue by maxfl** [lervag/vimtex#630] opened 2016-11-30 13:46 UTC
According to current behavior `VimtexToggleMain` changes the root folder to the base directory of the included file.

When the subfiles package is used with included files located in subdirectories this behavior is undesired. The problem is that subfiles package includes the main file's preample. The preamble may include `usepackage/include' calls that refer to the local files in the same folder with the main file. In this case the compilation of the included file in its own directory will crash since latex will not be able to find the files to include/use.

I suggest to either change the default behavior of the `VimtexToggleMain` in order to preserve root folder, or introduce `VimtexToggleMain!` version which does this.

**Comment by lervag** [comment] 2016-12-01 09:20
I might just have read this too fast, but I am not quite sure I understand. Could you create a minimal example and explain in steps what is happening and what should happen? That would make it easier for me to fix this (if it is a bug/problem with the code).

**Comment by maxfl** [comment] 2016-12-01 10:42
Here it is.
```tex
%%test.tex
\documentclass{article}
\usepackage{filecontents}
\usepackage{subfiles}
\usepackage{localpackage}

\begin{document}
\subfile{sub/sub.tex}

b
\end{document}

%%localpackage.sty
\ProvidesPackage{localpackage}
\endinput

%%sub/sub.tex
\documentclass[test.tex]{subfiles}

\begin{document}
a
\end{document}
```

1. main.tex may be compiled from the root folder
2. sub/sub.tex may be compiled from the root folder as well
3. sub/sub.tex can not be compiled from within sub/ folder, it can not find neither test.tex nor localpackage.sty

In vimtex:
1. open main.tex
2. navigate to \subfile{sub/sub.tex}
3. gf - go to the file
4. \ls - switchmain
5. \ll - compile
6. \lo - check output: file is not compiled.

**Comment by maxfl** [comment] 2016-12-01 10:43
for a some reason I was focused on the `localpackage.sty` and forgot the fact that main file can not be found from the sub folder as well.

**Comment by lervag** [comment] 2016-12-04 12:01
Ok, I've begun to look at this. It is not as straightforward as I hoped. I've implemented subfiles feature with the assumption that subfiles use relative or absolute path names for the main file specifications, e.g. set `\documentclass[../test.tex]{subfiles}`. This also follows the convention defined in the documentation. And it makes everything pretty straightforward.

However, if you need to include local packages, then things get difficult. And instead of doing a lot of change to vimtex, I would ask if it could be viable that you instead symlink the local packages into the necessar subfile directories. Then I could solve this and #632 pretty easily. What do you say?

**Comment by lervag** [comment] 2016-12-04 12:09
I've pushed a fix for #632 now. My proposal is that you use the relative paths as suggested above, and to symlink the local packages. If you do, then I think everything should work correctly.

Let me know what you think.

**Comment by maxfl** [comment] 2016-12-04 16:20
Naively it seems to me that solution should be easy:
1. Check where is the main file: test path relatively to the subfile and relatively to the main file.
2. Set the correct folder.

Also I've already patched vimtex to set the main files folder and update viewer_info afterward and the solution works just file. Of course I lack a lot of insight in vimtex, so I do not know what actually may be broken.

I'm currently using vimtex on my thesis. There are 79 tex files in 11 folders + some .sty files. Most of them are included via `\subfile`. Some files are included via`\include` before the `\begin{document}`. From my experience compiling subfiles in the same root folder is the most natural thing that works perfectly. It also ensures that all the garbage is located in the same folder and not scattered around the project. Under this circumstances I dislike the idea of making links to the common files in each folder, it's very brute force way.

Since I do not know how difficult it is to modify `vimtex` correctly, I can not suggest the right way. In any case, `vimtex` is a great plugin and I will continue using it even if it will require patching.

**Comment by lervag** [comment] 2016-12-30 22:12
Ok, I've implemented a solution that might work. Please test it. Note that I've pushed this to a separate branch for testing, as I am not sure it works quite as intended yet. Thus you have to do

```
git pull
git checkout issue-630/feature/improved-subfiles
```

to apply the patches.

**Comment by maxfl** [comment] 2017-01-09 07:44
@lervag, thank you, I will check in in a few days.

**Comment by lervag** [comment] 2017-01-09 07:46
Great, looking forward to your feedback.

**Comment by maxfl** [comment] 2017-01-10 13:57
I repeat the steps from the first message and compilation doesn't work. The output is the following:

```txt
Latexmk: This is Latexmk, John Collins, 22 April 2016, version: 4.45.

------------
Latexmk: Could not find file [ome/gonchar/tmp/mwe/sub/sub.tex].
-- Use the -f option to force complete processing.
```

**Comment by lervag** [comment] 2017-01-10 19:46
When I follow the steps in the first message (or, actually, the second one), everything works. Are you sure you checked out the working branch?

```
git pull
git checkout issue-630/feature/improved-subfiles
```

**Comment by maxfl** [comment] 2017-01-11 08:10
I'm sure, that I did it. I actually did switch several times to be sure. 
Ok, give me one more try.

**Comment by lervag** [comment] 2017-03-14 10:03
*bump* Have you had time to try? I just rebased the branch on top of master; I think it could be merged and that it should solve our problem.

Let me know if you need help pulling the branch. I did a force push after rebase.

**Comment by maxfl** [comment] 2017-03-14 12:14
@lervag, I did try again several times. I've switched to the issue-630/feature/improved-subfiles and back to master several times and did not succeed. I have experience with git and I'm quite sure that I did checked out the correct version.

I will look into the code and debug the issue next month. Unfortunately currently I have no time for this. Please, keep the issue, I will update as soon as I can.

**Comment by lervag** [comment] 2017-03-14 12:16
Ok, thanks.

Den tir. 14. mar. 2017, 13.14 skrev maxfl <notifications@github.com>:

**Comment by lervag** [comment] 2017-03-27 19:13
Just an FYI: I've just pushed some pretty huge updates. It required a rebase of this. Let me know if you need help in how to pull the updated branch (it will probably require a `git reset --hard` type command).

Also, note that due to the amount of work, it is more likely that I've made some mistakes. I'll be happy to work on it, though, so let me know when you've time to test.

**Comment by lervag** [comment] 2017-03-27 19:14
I suggest that we continue the discussion at #742.

**Closed** 2017-03-28 09:08 UTC

**Comment by lervag** [comment] 2017-04-04 19:07
I took a new look at #742, and I found an error. After updating, rebasing and testing, I think it now works as intended. Could you please verify?

I took the liberty to merge the PR, because it should have not side effects, and I think it solves our issue.

**Comment by maxfl** [comment] 2017-04-05 07:43
@lervag, thank you. I will check today.

(offtopic) Still busy with finalizing my thesis. `vimtex` did help me a lot, so I put a couple of words in 'acknowledgements' section for you.

**Comment by lervag** [comment] 2017-04-05 07:47
@maxfl Thanks, that's kind of you! I've been through two theses periods, and I understand the stress involved. So don't stress about testing things with vimtex until you feel you have the time. :)

**Comment by maxfl** [comment] 2017-04-06 14:17
@lervag, works like a charm, thank you. (Also the performance became smoother in general)

**Comment by lervag** [comment] 2017-04-06 14:46
Great! :)
