### ISSUE TITLE
vim blank screen lag when launching viewer

### ISSUE THREAD

**Issue by chakravala** [lervag/vimtex#989] opened 2017-10-29 13:51 UTC
When I open a LaTeX file using vimtex, it immediately displays all the text and highlighting.

However, once I press `\ll` or `\lv` to launch and display the PDF viewer (using zathura) for the first time, the vim screen goes completely blank and displays nothing. It takes quite a few seconds for the screen to reload itself after that and to display the text and highlighting again.

One way around this is to switch back to the vim window and to simply move the cursor position from left or right or up or down, doesn't matter what direction. this causes the screen to redraw immediately

This issue does not happen once (zathura) is already loaded and then press `\ll` or `\lv` to compile. It only happens on the very first compile when opening up the viewer.

So it seems that when the vimtex launches the viewer, it empties the vim screen buffer and does not immediately refill it. It's not a huge issue, but slightly annoying.

Could this be fixed?

**Comment by lervag** [comment] 2017-10-29 20:47
I appreciate the issue description, but I would be happy if you could add some more detail. Specifically, could you provide a fully minimal example that I can use to reproduce? Please see the [issue template](https://github.com/lervag/vimtex/blob/master/ISSUE_TEMPLATE.md) for more info.

**Comment by chakravala** [comment] 2017-10-29 20:51
Sure, you can use any `tex` file you want, so I don't need to provide one.

My `.vimrc` looks like

```vim-script
execute pathogen#infect()
call pathogen#helptags()
syntax on
filetype plugin indent on

set undodir=~/.vim/undodir
set undofile nocompatible number
set completeopt=menuone,longest,preview complete+=k
set linebreak breakindent breakindentopt=shift:2
set tabstop=4 shiftwidth=4
autocmd FileType julia set expandtab softtabstop=4

colo slate
autocmd FileType tex colorscheme lucius
autocmd FileType tex hi Normal guibg=NONE ctermbg=NONE
autocmd FileType tex hi LineNr guibg=NONE ctermbg=NONE
autocmd FileType tex exec("setlocal dictionary+=".$HOME."/.vim/dictionaries/".expand('<amatch>'))

let g:vimtex_matchparen_enabled = 0
let g:vimtex_view_method = 'zathura'
```
Is this not a reproducible issue for you?

**Comment by lervag** [comment] 2017-10-29 20:56
Perhaps, but I'm not going to install `pathogen` and `lucius` unless these are necessary for reproducing the issue. Please remove anything from your vimrc that is not necessary for reproducing the issue.

Also: Please specify your system info, including OS, Vim version, terminal or gui, and similar. As specified in the issue template.

Oh, and no: I'm using Vim and neovim in terminal (urxvt) on Arch Linux with Zathura, and I do not experience the same issue.

Please understand that I am happy to help figure out your problem, but that it makes me happy if you can make as clear as possible exactly what I must do to reproduce your issue. By providing a full minimal example, with a list of steps to reproduce, you are enabling me to approach your issue in a very efficient manner, which makes it much more likely that I will solve it.

**Comment by chakravala** [comment] 2017-10-29 21:05
Okay, this is all I have in my `.vimrc` now

```vim-script
execute pathogen#infect()
filetype plugin indent on
let g:vimtex_view_method = 'zathura'
```
The `patheogen` is what I use to use load the `vimtex` plugins.

My OS is Arch Linux, my terminal is xfce-terminal, and I'm using standard vim in the terminal (the one that installs with the gvim package on arch)

Is that enough information?

**Comment by lervag** [comment] 2017-10-29 21:06
Yes, I'll look into it. Thanks.

**Comment by lervag** [comment] 2017-10-29 21:16
Are you starting Vim with the `--servername` option? If not, could you try? I think this might be the issue.

**Comment by chakravala** [comment] 2017-10-29 21:18
Yes, indeed, you are correct! If i launch without it, no problem.

So can this be solved, while still using the `--servername` ?

**Comment by lervag** [comment] 2017-10-29 21:27
Huh. I was thinking you started Vim without it, and that adding this would solve the issue, not the opposite. So:

Could you confirm that:

1. This works as expected: `vim --servername VIM file.tex` + `\ll`

2. This doest _not_ work: `vim file.tex` + `\ll`

**Comment by andymass** [comment] 2017-10-29 21:28
I actually see a similar thing, not sure if it's the same as OP- when spawning the viewer vimtex briefly shows the prior terminal contents (the alternate screen) and then `redraws!`.  It has never been a serious issue for me though.  The root cause is https://github.com/lervag/vimtex/blob/280d487ef45aef68cdb362b2360cc768a73adc64/autoload/vimtex/process.vim#L105 and see the `redraw!` two lines down.

It isn't clear to me why the `silent execute '!'` pattern is being here used instead of `system()` (or even `job_start()` is supported).  Without messing with `t_te` and `t_ti`, the brief flash is unavoidable on my terminal.  I'm not sure why @lervag you don't see it.

**Comment by chakravala** [comment] 2017-10-29 21:31
Case 1 is when I have the redraw problem. Case 2 is when I do not have the problem.

**Comment by lervag** [comment] 2017-10-29 21:33
Can you confirm that Case 2 also gives you some information echoed about the missing `v:servername`?

Thanks, @andymass. I suspect you might be close to the problem. However, I don't understand why I don't have the same problem. I'll test with `xfce4-terminal`.

**Comment by chakravala** [comment] 2017-10-29 21:35
Yes, in Case 2 there is an information about the servername when I press `\ll`.

**Comment by lervag** [comment] 2017-10-29 21:38
@chakravala That's good, at least.

**Comment by lervag** [comment] 2017-10-29 21:48
Ok, I still can't repeat this. Everything works fine for me with Vim and with my minimal example. I'm uploading it, so you can see what I'm doing, i.e.:

```sh
~/.vim/bundle/vimtex/test/issues/989> vim --servername VIM -u minivimrc minimal.tex
```

**Comment by andymass** [comment] 2017-10-29 22:10
@lervag If you were to put a `sleep 500m` after line `process.vim:105` but before the `redraw!`, would you then see any kind of flash/blank?

**Comment by lervag** [comment] 2017-10-30 21:02
@andymass This changes nothing for me. However, I'm curious, does it solve the problem if you add `{'silent': 1}` as a second argument to `zathura.vim:45`:

```vim
let self.process = vimtex#process#start(l:cmd, {'silent': 1})
```

Also, I've updated the test and added a new mapping: `<space>lv`. I've tried to extract the essentials:

```vim
nnoremap <silent> <space>lv :call Start()<cr>

function! Start()
  silent execute '!zathura -x "/usr/bin/vim --servername VIM --remote +\%{line} \%{input}" --synctex-forward 1:1:minimal.tex minimal.pdf >/dev/null 2>&1 &'
  redraw!
endfunction
```

With this mapping, I still do not experience the problem stated by @chakravala, but the screen does flicker just barely.

**Comment by andymass** [comment] 2017-10-30 21:49
Just to be precise: there are at least two observations here
   1. terminal alternate screen is shown briefly (junk that was there before you started vim) which is not what OP sees.
   2. screen goes blank (similar to OP's problem).

I always see (1) in the form of a brief flicker, but it is not even a minor annoyance.

If I remove the `redraw!`, I see (2), which is fairly similar to @chakravala's reported behavior.  Of course, it is unclear why this issue would exist with the `redraw!`, plus @chakravala says it redraws eventually or when typing, which doesn't happen when removing the `redraw!`.

Using the updated `test/issues/989`, everything is the same.  I see a flicker of (1), but I have to remove the `redraw!` to see (2).

Regarding your question; using `{'silent': 1}` in the second argument in `zathura.vim:45` removes both issues (1) and (2) (in the sense that it eliminates the need for a `redraw!` at all.)  The `process.silent` flag causes the `silent call system(self.prepared_cmd)` branch to be taken instead of the `silent execute '!' . self.prepared_cmd` branch.

**Comment by chakravala** [comment] 2017-10-31 00:50
Thanks for trying to work this issue out, I wish I could be of more assistance on it, but I am not very familiar with vim scripts.

I pulled your new changes from git and now I don't experience this issue anymore! I do get the flickering that @andymass has talked about, but I do not have the blank screen issue anymore.

**Comment by chakravala** [comment] 2017-10-31 00:53
Thanks for trying to work this issue out, I wish I could be of more assistance on it, but I am not very familiar with vim scripts.

After I pulled the new changes from git, I no longer get the blank screen issue for `\lv` but it still has the issue for `\ll`. However, it still gives the flicker that @andymass talked about on `\lv`.

**Comment by chakravala** [comment] 2017-10-31 01:04
Another thing I just noticed:

When I press `\ll`, the vim screen goes blank and zathura is opened with the PDF. Then if I press `q` to quit zathura and then wait for vim to eventually redraw the screen after a few seconds, a new window of zathura is re-opened (but this time it highlights text, as if I pressed `\lv`.

So it seems that after the blank screen is redrawn, there is another call to launch zathura.

**Comment by lervag** [comment] 2017-10-31 07:00
Again: I am not able to reproduce the issues here. So, the most helpful thing now is for you to isolate the problem(s), make minimal examples and explicit lists of steps that I should do to reproduce the problems.

I've tried to help by extracting the main parts as much as possible, so it would help much to hear if my minimal example with the `<space>lv` mapping works similar to the vimtex `\lv` mapping.

Btw: The last issue you mention looks similar to problems I've had sometimes where I have multiple `latexmk` or `pdflatex` instances. I propose that you do `ps aux|grep latexmk` or `pgrep -f latexmk` (and similar for `pdflatex`) to verify that there are no "spurious" processes.

**Comment by lervag** [comment] 2017-11-21 21:27
One thing: When you press `\ll`, then `latexmk` will open `zathura` directly as specified in options forwarded to the `latexmk` process. This should not in itself lead to any flickering. Which version of Vim are you on? On Vim 8 or neovim, you will be using modern job handlers that should work in the background, so starting `latexmk` should not flicker. However, on older Vims you will be using the old system, which might give some flickering.

**Comment by lervag** [comment] 2017-11-21 21:28
Also, I'm closing this issue now as I don't really see how to fix it. Feel free to reopen if you should find new/more information that may help solve it.

**Closed by lervag** 2017-11-21 21:28 UTC

**Comment by andymass** [comment] 2017-11-21 21:35
@lervag, sorry to add more noise to this, but would you consider adding the `{'silent': 1}` flag to `zathura.vim:45` as you mentioned before (and maybe line 60 too)?  Is there any downside to doing that?

For me, it eliminates any flash when pressing `\lv` (note: I use let `g:vimtex_view_forward_search_on_start = 0`, so both places are necessary).

**Comment by lervag** [comment] 2017-11-21 21:44
Ok, I've been bad: I just switched to use `silent` by default. This _might_ break some things unexpected, but I couldn't think of what. And if something breaks, then I think it might be more "correct" to explicitly "unsilence" those situations.

I think this should fix the issues in this thread. Can you confirm, @chakravala?

**Comment by haoyun** [comment] 2017-11-27 18:44
>  This might break some things unexpected

Yes it breaks something. But I am not able to find out why it does.

Till #412c309, everything works fine. Once #1bc2ab2 is checked out, the forward search
and backward search break.

I am working on Windows.

.vimrc
    " use SumatraPDF viewer
    let g:vimtex_view_general_viewer="SumatraPDF"
    let g:vimtex_view_general_options
        \ = ' -forward-search @tex @line @pdf'
        \ . ' -inverse-search "gvim --servername ' . v:servername
        \ . ' --remote-silent '
        \ . '\"+\%l|normal zv|'
        \ . 'call remote_foreground('''.v:servername.''')^<CR^>\"'
        \ . ' \"\%f\""'
    let g:vimtex_view_general_options_latexmk = '-reuse-instance'

Error for forward search (VIM ---> SumatraPDF)

    Error detected while processing function 403[26]..vimtex#process#start[3]#run[5]..573[5]..578:
    line    2:
    E484:  Can't open file C:\Users\...\AppData\Local\Temp\VIo764E.tmp
    Press ENTER or type command to continue.

Error for backward search (SumatraPDF ---> PDF)

    :if !exists('+acd')||!acd|if haslocaldir()|cd -|lcd -|elseif getcwd() ==
    E10: \ should be followed by /, ? or &
    Press ENTER or type command to continue.

**Comment by lervag** [comment] 2017-11-27 18:52
Please update and try now. If it does not work, then please open a new issue with a full description.

**Comment by chakravala** [comment] 2018-02-23 12:45
Fantastic! you fixed it, the silent option did it for me. I've been studying mathematics, so I've not been able to focus on issues with the computer recently, was mostly focusing on using the LaTeX to get my work done,  but it all works fine now.

Sorry for not responding sooner, but I confirm this issue is closed indeed.

**Comment by chakravala** [comment] 2018-02-23 12:51
The only other Issue I have is that when I open a new instance of vim and do `\ll` then now it does not flicker, but it still resets the horizontal scrolling of my document.

However, when I launch zathura from another program, lets say ranger file browser, then it opens the file with the previous scroll configuration (centered in the screen, zoomed in). In vimtex it does so initially as well, but after a few seconds when it is done loading the centering is offset and reset so that the view starts at the left margin and the right side is partially cut off due to the zoom level.

Now, I'm not sure what the cause of this reset in zathura is, possibly due to latexmk being called or something like that?

**Comment by chakravala** [comment] 2018-02-23 12:58
Never mind! I've also fixed that issue now by adding this to `.vimrc`:
```vim
let g:vimtex_compiler_progname = 'nvr'
```
This would probably also have bypassed the flicker issue, I believe.

**Comment by lervag** [comment] 2018-02-23 13:29
Great! Happy to hear it :)

**Comment by chakravala** [comment] 2018-02-23 13:34
Hm. but now the problem is that zathura no longer communicates back to vimtex, with that option.

**Comment by lervag** [comment] 2018-02-23 13:37
Strange. If you can't figure it out, please open a new issue and describe the problem in more detail.
