### ISSUE TITLE
Multi-file documents not compiling

### ISSUE THREAD

**Issue by samhaney** [lervag/vimtex#198] opened 2015-07-04 16:31 UTC
I'm trying to compile the subfile of a multi file project, and I'm getting errors as if only the current file is being compiled. I've tried putting the main file name in a comment at the top, as suggested. The main file is in the same directory as the file I'm trying to compile. I've tried setting b:vimtex_main explicitly and this still doesn't work.

I've tried some tests:
- b:vimtex_main shows the correct value
- :echo exists('b:vimtex_main') && filereadable(b:vimtex_main) returns 1
- :echo fnamemodify(b:vimtex_main, ':p') returns the correct path to the main file
- g:vimtex_data contains only one blob, with the incorrect subfile that I'm compiling from

Compiling from within the main file works perfectly.

**Comment by Konfekt** [comment] 2015-07-05 12:36
Same over here: In a project with a `main.tex` and a `realmain.tex` together with a `realmain.tex.latexmain` to ensure that `realmain.tex` is compiled, `VimtexCompileToggle` always compiles `main.tex` in the buffer displaying main.tex instead of `realmain.tex`.

**Comment by Konfekt** [comment] 2015-07-05 12:37
Same over here: In a project with a main.tex and a realmain.tex together with a realmain.tex.latexmain to ensure that realmain.tex is compiled, VimtexCompileToggle always compiles main.tex in the buffer displaying main.tex instead of realmain.tex.

**Comment by lervag** [comment] 2015-07-06 21:11
Hi @samhaney! In most cases, multi file projects should just work. However, in a few cases it is necessary to tell Vimtex which file is the main file. This should also work (with both of the methods you mention). If this does not work, then you might have found a bug, and I will be very glad to fix it!

In order to fix it, I want to be able to reproduce your problem. Could you please provide a minimal example of the case where things are not working, e.g.
```tex
\documentclass{...}
...
\begin{document}
...
\end{document}
```
Please indicate the file names and what the content in each file is. The smaller the example, the better.

Please also let me know the output of `\li` (or `<leader>li` if you have set a custom mapleader) for the case where you open and start to compile from the subfile.

@Konfekt The `latexmain` method is not implemented in Vimtex. Please see `:h vimtex-multi-file` for how multi file projects are recognized. TL;DR - there are three methods: Buffer variable `b:vimtex_main`, `%! TEX root = ...` specifier, and a recursive search for the `\documentclass` command.

**Comment by Konfekt** [comment] 2015-07-07 13:35
Oh, ok, then it incidentally worked before. I remember discussing this issue on the LatexBox issue tracker, where the plugin would ask for a main file and create a latexmain file accordingly; but perhaps that functionality was not ported. 

In case Vimtex compiles the current buffer despite absence of a  document class command would it not be reasonable to ask the user about it ?

**Comment by Konfekt** [comment] 2015-07-07 13:44
Checked `:h vimtex-multi-file` and problem is:

The recursive search is NOT for the `\documentclass` command but for `\begin{document}`.

But the first is preferable since the first comes before the latter and thus only `\documentclass` is ensured to be in the main file !

Rather than decorating all TeX files of my collaborate workers with `%! TEX root =` comments, a `.latexmain` file would be the cleaner solution.

**Comment by lervag** [comment] 2015-07-07 17:51
@Konfekt You're right, the recursive method searches for `\begin{document}`. I think my assumtion was that `\begin{document}` always appears in the main file. Is this assumption wrong?

Personally, I don't like the `.latexmain` method. In particular I think it should be possible to use a simple recursive search in almost all cases. I do see the point that the texroot markers may be "annoying" for collaborative documents, and so I could consider adding the `.latexmain` method. But first I want to understand why the recursive method fails in your case.

**Comment by Konfekt** [comment] 2015-07-07 20:29
It fails because the main file only contains 

\documentclass... 
\input{main.tex} 

and the \begin{document}... part is in main.tex.Thus compiling main.tex as main file gives the missing documentclass error.

**Comment by lervag** [comment] 2015-07-07 20:51
I see. But is there any reason to do that? I'm asking, because I'm curious. If there is a reason, then I agree I should change the detection to search for `\documentclass`.

That is, is there any reason not to use `\documentclass` as the main file detection search?

**Comment by lervag** [comment] 2015-07-07 20:54
I don't think there is...

**Comment by samhaney** [comment] 2015-07-07 21:13
Mine was not working even with \begin{document} in the main file. I'm not sure what is causing it. I'll try out the new version which searches for \documentclass when I get chance and see if that is working.

**Comment by samhaney** [comment] 2015-07-07 21:14
Searching for \begin{document} seems reasonable to me. I'm not sure what the reason is to have \begin{document} outside of the main tex file.

**Comment by ff2000** [comment] 2015-07-08 07:39
Sam Haney wrote:
> Searching for \begin{document} seems reasonable to me. I'm not sure what the reason is to have \begin{document} outside of the main tex file.

It's handy if you need different versions of the pdf.
E.g. in Germany you usually have to send specially formatted documents to the publisher. Google for "Normseite". I had to do it once and I also split the actual content and most of the preamble out into seperate files and joined them back to the "Normseite"-layout and the final nice-looking one ;)

I currently work on a book where I have to create a colored and a gray document. Running the colored one through ghostscript to create the gray one results in some bad-looking pictures, so I might end up with optimized gray-images. Having the preamble seperated from the content might also be a good solution in this case.

**Comment by lervag** [comment] 2015-07-08 07:48
Yes, I agree it might make sense to split the preamble from the main content. Though I think one could keep `\begin{document}` in the preamble.

In any case, I've changed the code so it now instead uses `\documentclass` to detect the main file. Based on this discussion, it seems to be a better solution.

**Comment by Konfekt** [comment] 2015-07-08 07:49
There are no good reasons for using markers other than `\documentclass[...]` because it is the only marker ensured to be in the main file as it always comes first.

To add to ff2000's comment's my reason above was that ...

in the collaborate project over here the main file only contains
```tex
\documentclass[...]]
\include{main.tex}
```
 to ensure that every coworker can compile its proper preamble, according to his (scrarctl, article, font settings..) taste (at least while in draft).

**Comment by lervag** [comment] 2015-07-08 07:51
Ok. It's not up to me how people work together, and that way seems as sensible as many others. In any case, as mentioned, I now agree `documentclass` is the correct marker, and I've updated the code accordingly.

**Comment by lahwaacz** [comment] 2015-07-08 07:53
I've been using the opposite layout with `preamble.tex` containing `\documentclass` and `main.tex` with `\input{preamble.tex}` and `\begin{document}`. This layout is now unsupported by vimtex...

**Comment by Konfekt** [comment] 2015-07-08 07:54
:+1:  Thanks! Works as expected over here.

Now the `.latexmain` solution still has its value: There can be two main files (that is, containing `\documentclass[...]` and the one chosen by vimtex may not be the one intended by the author.

This happens in a collaborate project where there's the common main file and the author's main file (ignored by git). Then the only solution to ensure that Vimtex choses author's main file is decorating all collaborate TeX files by ` %! TEX root = ...`.

**Comment by lervag** [comment] 2015-07-08 07:57
@Konfekt That's a good point! You could of couse set the buffer variable, but I do agree that the `.latexmain` method is much easier. I'll add it within a couple of days (I hope).

**Comment by Konfekt** [comment] 2015-07-08 07:58
@lahwaacz, you can add a single `\documentclass[...]` line to your `main.tex`. 

And this organization is the more flexible approach because only in this way you can change `documentclass` from your `main.tex`. Putting `\documentclass[...]` into the preamble is very rigid because it is the only option that you cannot override afterwards (coming to my mind).

**Comment by lervag** [comment] 2015-07-08 08:05
@lahwaacz I didn't notice your comment, sorry. I think I agree with @Konfekt that your approach is less flexible. However, one solution to this story could be to add an option that allows to override the main file detection regexp. Though I try to keep the number of options as low as possible, i.e. I try to keep things simple (KISS-principle).

What do you guys think? Everything is possible, the question is: What is the best/correct solution?

**Comment by Konfekt** [comment] 2015-07-08 08:09
Well... @lahwaacz : to fix the documentclass, how about a `lahwaacsz.cls` file instead of `preamble.tex` and using `\documentclass[lahwaacz]` ?

These `.cls` files are made for situations like that, where you want to force the documentclass.

**Comment by lahwaacz** [comment] 2015-07-08 08:13
Indeed, I can have `\documentclass` in a `main.tex` file followed by `\input{preamble.tex}`, thanks for the hint. Now the problem is that the "base" for `preamble.tex` is `preamble.tex`, so vimtex attempts to compile it when it is saved, which obviously fails.

**Comment by lervag** [comment] 2015-07-08 08:24
@lahwaacz I don't understand. In the following example, everything works as expected for me:
```tex
% main.tex
\documentclass{minimal}
\input{preamble.tex}
\begin{document}
\hw
\end{document}
```

```tex
% preamble.tex
\newcommand{\hw}{Hello world}
```

**Comment by lahwaacz** [comment] 2015-07-08 08:33
You are right assuming that the continuous build is active for the `main.tex` file. It would be silly to start continuous build for `preamble.tex`, but the issue also affects the single-shot build, which makes sense even for the preamble. With the previous detection based on `\begin{document}`, this worked fine assuming there was only one main file including the preamble...

**Comment by samhaney** [comment] 2015-07-08 13:35
Thanks, this seems to work now. Compiling works, although when I try to view the pdf from any file other than the main file, I get "vimtex viewer can not read PDF file!". In my .vimrc I have
let g:vimtex_view_general_viewer
    \ = '/applications/skim.app/contents/sharedsupport/displayline'
let g:vimtex_view_general_options = '@line @pdf @tex'

**Comment by lervag** [comment] 2015-07-09 17:06
That's strange. Could you please

1. Open the example where your problem occurs,
2. Start compiling the document,
3. Go to a file different from the main file,
4. Start the viewer (which according to your last post should issue the error),
5. Do `:VimtexInfo` and copy-paste the output here.

The output from `5` will provide me with a lot of useful information that might help me to understand what the problem is.

**Comment by samhaney** [comment] 2015-07-31 15:23
Sorry, I was away for a while. I'm back to the original problem, which is that compiling from any subfile tries to compile that subfile as the main file. I've switched back to LatexBox for now.

**Comment by lervag** [comment] 2015-08-01 17:19
@samhaney Well, that's strange. But with no more information it is difficult to help. Could you provide a minimal example (as explained [here](https://github.com/lervag/vimtex/issues/198#issuecomment-118999555))? If you help me to reproduce your issue, then I can find the cause of the problem and solve it.

**Comment by lervag** [comment] 2015-08-25 18:57
I'm closing this issue as unreproducible. Feel free to reopen if you can provide more information on how to reproduce.

**Closed by lervag** 2015-08-25 18:57 UTC

**Comment by lervag** [comment] 2017-11-02 19:26
Yes, as is described in the introduction of the documentation... :)
