### ISSUE TITLE
Buffer superficially raised by one line after latexmk success message

### ISSUE THREAD

**Issue by nasenatmer** [lervag/vimtex#302] opened 2015-12-16 17:51 UTC
Hey, 

since working with `vimtex` again I noticed the following issue which is somehow hard to reproduce, but reminded me a lot of the various instances when we had to introduce `:redraws` after certain `vimtex` commands in order to keep the vim buffer clean and legible.

This is the setting: I'm working in a project, have `continuous compilation running`, edit the file and save it by hitting `:w`.

From time to time then, at the moment when `vimtex` prints out the message `latexmk compile: success`, the vim buffer is raised one line up, and if I edit something in the file now it looks as if I was one line higher while I'm still in the line I was before. Only after pressing `Ctrl-L`, can I see where I'm really at.

However, I didn't find a way to reproduce this, it's not happening if I have compilation errors or at every successful compilation but randomly every 10th or so time.

If you could point me to the place where the command that prints the success message, I could try adding a `:redraw` command and find out whether that solves the problem.

Am I the only one experiencing this issue?

**Comment by lervag** [comment] 2015-12-16 22:00
I've never experienced this problem myself. As you clearly understand, it is very difficult to investigate it with no means to reproduce it.

Since it seems to occur after the callback, I would suggest you look into the function `vimtex#latexmk#callback()`. There is already a redraw there, and I think it is correct.

I'm curious, are you working inside tmux or screen? Are you in terminal Vim or gvim or MacVim?

**Comment by nasenatmer** [comment] 2015-12-17 10:26
I'm working in terminal `vim` (gvim package in Arch Linux version `7.4.944-1`) inside `tmux` (2.1).

If I can see correctly, there is one `redraw!` after `vimtex#latexmk#errors#open`, but not after `vimtex#echo#status`, so I added a `redraw!` there in line 109 of `latexmk.vim` and will work with this today to see whether the problem still occurs.

**Comment by lervag** [comment] 2015-12-17 10:28
That `redraw!` will remove the status message, i.e., you will no longer get the `latexmk compile: success|failure` message.

Can you work outside of tmux with the current version of vimtex for some time as well? I suspect this might be due to terminal issues with tmux (I've experienced similar issues, but I have never been able to pinpoint such problems before).

**Comment by nasenatmer** [comment] 2015-12-17 12:50
I'm working without `tmux` now to see whether it still happens.

**Comment by nasenatmer** [comment] 2015-12-17 17:25
Ok, it didn't happen during today's work when not using tmux, so that might actually be a clue.

But as I won't be able nor willing to do without tmux, I'll tomorrow try the `redraw!` option. As far as my short tests went today, I still saw status messages, even with `redraw!` in line 109, so I hope to find a solution there…

**Comment by lervag** [comment] 2015-12-17 21:06
I guess you mean to add a redraw before the return statement in line 108. In any case, let me know if and when you find anything.

**Comment by nasenatmer** [comment] 2015-12-28 14:07
For the time being, I added two lines before the return statement, as you said (I wasn't aware of the fact that the return would finish the the function…), which will enable me to see whether the problem persists but should solve it after a short while:

```vim
sleep 2
redraw!
```

**Comment by lervag** [comment] 2016-01-02 22:10
I'll close this for now, since there is still no way to reproduce and thus investigate this issue direcly. I'll of course follow up on the discussion if you discover something new.

Notice that the option `cmdheight` might be relevant here, although as I can't test anything myself I might be wrong.

**Closed by lervag** 2016-01-02 22:10 UTC
