### ISSUE TITLE
latexmk compile fail with xelatex

### ISSUE THREAD

**Issue by CareF** [lervag/vimtex#652] opened 2017-01-05 05:56 UTC
### Explain the issue

When I use `\ll` to start latexmk, it shows `latexmk compile: fail` with no PDF or dvi file created. 

The following command works fine in terminal:

```bash
latexmk -pdf -pdflatex="xelatex -synctex=1 %S %O" -verbose -file-line-error -interaction=nonstopmode a.tex
```
 
### Minimal working example

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

### Minimal vimrc file

```vim
set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

" Vimtex options go here 
let g:vimtex_latexmk_options='-pdf -pdflatex="xelatex -synctex=1 %S %O" -verbose -file-line-error -interaction=nonstopmode'
```

**Comment by lervag** [comment] 2017-01-05 07:15
I've edited your issue description, in particular your minimal vimrc file, since there were several duplicate lines and similar.

The problem is that you need to escape things properly. My first thought is that you must escape the `%`s, i.e., write `\%S \%O`. You can also try to escape the quotes, i.e. `-pdflatex=\"...\"`.

**Comment by CareF** [comment] 2017-01-05 07:50
@lervag  Thank you very much for your reply! 
`\%S \%O' is enough to fix.

**Comment by CareF** [comment] 2017-01-05 07:54
Thank you very much @lervag . `\%S \%O` is enough to fix it.

**Comment by lervag** [comment] 2017-01-05 07:54
Great! If this solves your problem, then we could close the issue?

tor. 5. jan. 2017 kl. 08:50 skrev L.M. (CareF) <notifications@github.com>:

**Closed** 2017-01-05 07:54 UTC
