### ISSUE TITLE
VimTex info error

### ISSUE THREAD

**Issue by rafaelferracini** [lervag/vimtex#2849] opened 2023-12-15 14:05 UTC
### Description

I've just installed VimTex in my Neovim environment (configured with Lua and Packer), and to check if the installation went well, I executed :VimtexInfo.
I believe it might be due to my computer's language settings (Portuguese-BR), but I can't change it due to Windows limitations.
 Here's the error:
 
```
Error detected while processing function vimtex#info#open[2]..vimtex#scratch#new[2]..218[32]..220[4]..206[1]..207[1]..<SNR>88_get_os_info[18]..vimtex#jobs#cached[4]..49[4]..50:
line   6:
E474: String "<c6>o do sistema operacional:             10.0.22621 N/A compila<87><c6>o 22621" contains byte that does not start any UTF-8 character
Erro detectado ao processar function vimtex#info#open[2]..vimtex#scratch#new[2]..218[32]..220[4]..206:
line    1:
E1098: String, List or Blob required
```

**Comment by lervag** [comment] 2023-12-15 22:43
> I believe it might be due to my computer's language settings (Portuguese-BR), but I can't change it due to Windows limitations.

I've tried to fix this. Can you update to the latest version and try again and let me know how it goes?

I don't expect the output to be perfect here, but I hope that it looks good enough and that there is no error.

**Comment by rafaelferracini** [comment] 2023-12-16 13:03
> > I believe it might be due to my computer's language settings (Portuguese-BR), but I can't change it due to Windows limitations.
> 
> I've tried to fix this. Can you update to the latest version and try again and let me know how it goes?
> 
> I don't expect the output to be perfect here, but I hope that it looks good enough and that there is no error.

Same error but now a different string

E474: String "<a0>rio registrado:                   (my email adress)" contains byte that does not start any UTF-8 character.

<a0>rio probably refers to "Usuário", translations for "User"

**Comment by user202729** [comment] 2023-12-16 14:31
Line 4 of `vimtex#jobs#cached` is
```
function! vimtex#jobs#cached(cmd) abort " {{{1
  " Cached version of vimtex#jobs#capture(...)
  let l:cache = vimtex#cache#open('capture')

>  return l:cache.has(a:cmd)
        \ ? l:cache.get(a:cmd)
        \ : l:cache.set(a:cmd, vimtex#jobs#capture(a:cmd))
endfunction
```

annoyingly the following functions's names are not displayed by vim, so I can't tell which function the following line 4 and line 6 is of. Neither can I tell you're using persistent or temporary cache. (persistent is the default.)

Try typing

```
:echo vimtex#cache#path("capture.json")
```
and read the content of the JSON file at the output, see what's the content.

**Comment by lervag** [comment] 2023-12-18 21:22
> annoyingly the following functions's names are not displayed by vim

I'm also annoyed by this fact, although I've become quite adapt at recognizing functions from script numbers and similar.

**Comment by lervag** [comment] 2023-12-18 21:31
> Same error but now a different string

Ok, it seems I was onto something, but I'm not quite sure. And it's hard, because I can't really reproduce this properly. Not sure how to properly catch all of this without somehow writing a full windows-1252 to utf-8 converter...

**Comment by lervag** [comment] 2023-12-18 21:31
Oh, and I would also need to properly detect the encoding. These things are hard.

**Comment by user202729** [comment] 2023-12-19 02:40
Some quick testing:
```
let a={}
function A_abc()
	echoerr 123
endfunction
let a.abc=function('A_abc')
call a.abc()
```
seems to work well enough at displaying the function name. Could anything go wrong?

**Comment by user202729** [comment] 2023-12-19 03:02
That code looks... strange (and without much rationale what's going on). Is it just that if `match(x, '[\x80-\x9F,\xE1]') > 0` then it's considered "likely" that the thing is invalid UTF8 (and thus valid Windows-1252)?

Then the next question is, why would `systeminfo` command output in Windows-1252 encoding instead of UTF-8...? Is there a way to simply make it output in UTF-8 (which would avoid the conversion)?

**Comment by lervag** [comment] 2023-12-20 21:42
> Some quick testing: …

Sorry, but I don't see quite how this is relevant. The problem here _seems_ related to the encoding of strings passed as arguments to functions. In particular, Vimscript (perhaps also valid for Lua code in neovim) relies on UTF-8 encoded strings and will raise an error if it is somehow passed a string with bytecodes that are not valid UTF-8 bytecodes.

I may have understood things wrong, though.

> That code looks... strange (and without much rationale what's going on).

I should probably write a comment here to explain!

> Is it just that if `match(x, '[\x80-\x9F,\xE1]') > 0` then it's considered "likely" that the thing is invalid UTF8 (and thus valid Windows-1252)?

Yes, exactly.

> Then the next question is, why would `systeminfo` command output in Windows-1252 encoding instead of UTF-8...? Is there a way to simply make it output in UTF-8 (which would avoid the conversion)?

Because `systeminfo` will output text encoded in whatever is specified in the system regional settings. E.g., I believe the standard encoding for Portuguese-BR is Windows 1252. @hrcHarry from #2850 reported the exact same error, so this affects multiple people.

I'm slightly inclined to just ignore it, but at the same time I feel it should be possible to find a relatively simple solution here.

> Edit: I didn't realize earlier, but neovim throws this error while trying to store such a string in JSON
> 
> https://github.com/neovim/neovim/blob/1cf51a07a6bfb827efc36911cd018da3a3cb863b/src/nvim/eval/encode.c#L633

Oh, nice! Thanks for going deeper! It seems obvious now that I should have checked the source code for this error message!

> Another thing, the code doesn't look like valid Windows-1252 either.

I agree to this. When debugging, I also found it did not seem to look right when decoded as windows-1252. So it is possible I'm wrong about the source encoding here. But I think the end result is that I need to somehow remove or convert bytes in some byterange to avoid this error.

> The word `compila<87><c6>o` probably should be `compilação`. But I can't find any encoding that makes `\x87` maps to `ç` and `\xc6` maps to `ã`.

Perhaps the problematic bytecode is a result of parsing only part of some sequence, thus that the original code has some starting part swallowed before the error appears?

**Comment by lervag** [comment] 2023-12-20 21:47
But OK, the problem is clearly related to `json_encode` used here:

https://github.com/lervag/vimtex/blob/e7ce03ea517c5b61ec9703a44019481678d60af3/autoload/vimtex/cache.vim#L218

**Comment by lervag** [comment] 2023-12-20 22:11
@rafaelferracini

> … Here's the error:
>
> ```
> E474: String "<c6>o do sistema operacional:             10.0.22621 N/A compila<87><c6>o 22621"
>
> E474: String "<a0>rio registrado:                  [my email adress here]"
> ```

Could you run `systeminfo` in your terminal (CMD or Powershell) and copy the output here? It should have strings similar to those above. Feel free to remove any sensitive or identifying info, of course!

Also; could you run `[System.Text.Encoding]::Default` in Powershell to check what it says your system encoding is (source https://superuser.com/questions/670197/finding-out-the-default-character-encoding-in-windows)?

I believe it should report CP-1252 or something like that.

----

This will be useful input to learn how to properly fix this issue. In the meantime, You can overcome the error by making a cache file with prefilled data. You can do that like this:

1. Open Vim/neovim.
2. Run `:echo vimtex#cache#path("capture.json")` - this should output something like `/home/lervag/.cache/vimtex/capture.json`, although it will look different on Windows.
3. Edit the `capture.json` file and add the following content:

    ```json
    {"systeminfo": ["Windows 11"], "__validate": "cache_v2"}
    ```

**Comment by rafaelferracini** [comment] 2023-12-20 22:48
> Could you run `systeminfo` in your terminal (CMD or Powershell) and copy the output here? It should have strings similar to those above. Feel free to remove any sensitive or identifying info, of course!
```
Nome do host:                              RAFAEL
Nome do sistema operacional:               Microsoft Windows 11 Home Single Language
Versão do sistema operacional:             10.0.22621 N/A compilação 22621
Fabricante do sistema operacional:         Microsoft Corporation
Configuração do SO:                        Estação de trabalho autônoma
Tipo de compilação do sistema operacional: Multiprocessor Free
Proprietário registrado:                   [email adress]
Organização registrada:                    N/A
Identificação do produto:                  [ID]
Data da instalação original:               09/10/2023, 20:03:16
Tempo de Inicialização do Sistema:         20/12/2023, 17:50:51
Fabricante do sistema:                     Acer
Modelo do sistema:                         Nitro AN515-57
Tipo de sistema:                           x64-based PC
Processador(es):                           1 processador(es) instalado(s).
                                           [01]: Intel64 Family 6 Model 141 Stepping 1 GenuineIntel ~2688 Mhz
Versão do BIOS:                            Insyde Corp. V1.19, 28/10/2022
Pasta do Windows:                          C:\Windows
Pasta do sistema:                          C:\Windows\system32
Inicializar dispositivo:                   \Device\HarddiskVolume1
Localidade do sistema:                     pt-br;Português (Brasil)
Localidade de entrada:                     pt-br;Português (Brasil)
Fuso horário:                              (UTC-03:00) Brasília
Memória física total:                      24.339 MB
Memória física disponível:                 17.804 MB
Memória Virtual: Tamanho Máximo:           36.627 MB
Memória Virtual: Disponível:               28.394 MB
Memória Virtual: Em Uso:                   8.233 MB
Local(is) de arquivo de paginação:         C:\pagefile.sys
Domínio:                                   WORKGROUP
Servidor de Logon:                         \\RAFAEL
Hotfix(es):                                6 hotfix(es) instalado(s).
                                           [01]: KB5032007
                                           [02]: KB5026039
                                           [03]: KB5030323
                                           [04]: KB5031274
                                           [05]: KB5033375
                                           [06]: KB5032393
Placa(s) de Rede:                          2 NIC(s) instalado(s).
                                           [01]: Killer(R) Wi-Fi 6 AX1650i 160MHz Wireless Network Adapter (201NGW)
                                                 Nome da conexão: Wi-Fi
                                                 DHCP ativado:    Sim
                                                 Servidor DHCP:   192.168.3.1
                                                 Endereço(es) IP ...
                                           [02]: Killer E2600 Gigabit Ethernet Controller
                                                 Nome da conexão: Ethernet
                                                 Status:          Mídia desconectada
Requisitos do Hyper-V:                     Hipervisor detectado. Recursos necessários para o Hyper-V não serão exibidos.
```
It's really there. E474 refers to "Versão do sistema operacional (OS version)" and E474 refers to "Proprietário registrado (registered owner)

> Also; could you run `[System.Text.Encoding]::Default` in Powershell to check what it says your system encoding is (source https://superuser.com/questions/670197/finding-out-the-default-character-encoding-in-windows)?
```
Preamble          :
BodyName          : utf-8
EncodingName      : Unicode (UTF-8)
HeaderName        : utf-8
WebName           : utf-8
WindowsCodePage   : 1200
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
IsSingleByte      : False
EncoderFallback   : System.Text.EncoderReplacementFallback
DecoderFallback   : System.Text.DecoderReplacementFallback
IsReadOnly        : True
CodePage          : 65001
```

> This will be useful input to learn how to properly fix this issue. In the meantime, You can overcome the error by making a cache file with prefilled data. You can do that like this:
> 3. Edit the `capture.json` file and add the following content:
>    ```
>    {"systeminfo": ["Windows 11"], "__validate": "cache_v2"}
>    ```

It worked with the following message:
```
System info:
  OS: Windows (['Windows 11'])
  Vim version: NVIM v0.9.4
  Has clientserver: true
  Servername: \\.\pipe\nvim.8648.0

VimTeX project: test
  base: test.tex
  root: C:\Users\rafae
  tex: C:\Users\rafae\test.tex
  main parser: fallback current file
  document class: 
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile

```

**Comment by user202729** [comment] 2023-12-21 09:27
For the first part, I mean that if the code is rewritten to avoid numbered-function, then the traceback in the log will contain the name of the function. (admittedly the code looks a little more ugly that way.)

**Comment by lervag** [comment] 2023-12-22 11:56
> For the first part, I mean that if the code is rewritten to avoid numbered-function, then the traceback in the log will contain the name of the function. (admittedly the code looks a little more ugly that way.)

Ah, ok. Yes, I agree it is annoying that the name of the function is missing in the log output. But the numbers are helpful, and the line numbers make it possible to trace things correctly.

**Comment by lervag** [comment] 2024-01-29 17:18
Ok, so, returning to this - I'm not fully sure how to continue. It is clear that we have a problem related to encoding combined with `json_encode()`, but I don't have a good way of properly making a test and fix.

**Comment by lervag** [comment] 2024-01-29 18:08
I've reverted my earlier attempt at a fix, because I can't properly ensure it is correct. However, I've added a check for the problem to avoid the initial error.

@rafaelferracini Can you help me by testing the latest version? These steps:

0. Update VimTeX to latest version.
1. Open some LaTeX file.
2. Run `:VimtexClearCache ALL`.
3. Restart Vim and VimTeX and open the LaTeX file.
4. Run `:VimtexInfo` and report the output here.
5. Please also report any errors or warnings provided (either screenshot or copy of the text).

**Comment by lervag** [comment] 2024-01-29 18:09
@hrcHarry I would be happy if you could also test similar to how I asked of Rafael above.

**Comment by hrcHarry** [comment] 2024-02-17 04:50
Hi @lervag 

The result of testing is as follows

```
VimTeX: Could not encode cache "capture"
        {'systeminfo': ['', '<a5>D<be><f7><a6>W<ba><d9>:             HW1120005', '<a7>@<b7>~<a8>t<b2>ΦW<ba><d9>:         Microsoft Windows 10 <b1>M<b7>~<aa><a9>', '<a7>@<b7>~<a8>t<b2>Ϊ<a9><a5><bb>:         10.0.19045 N/A <b2>ի<d8> 19045', '<a7>@<b7>~<a8>t<b2>λs<b3>y<b0><d3>:       Microsoft Corporation', '<a7>@<b7>~<a8>t<b2>γ]<a9>w:         <bf>W<a5>ߤu<a7>@<af><b8>', '<a7>@<b7>~<a8>t<b2>βի<d8><c3><fe><ab><ac>:     Multiprocessor Free', '<b5><f9><a5>U<aa><ba><be><b3><aa><cc>:         admin', '<b5><f9><a5>U<a4><bd><a5>q:             ', '<b2><a3><ab>~<c3>ѧO<bd>X:           00355-63057-04487-AAOEM', '<ad><ec><a9>l<a6>w<b8>ˤ<e9><b4><c1>:         2023/3/21, <a4>W<a4><c8> 11:16:38', '<a8>t<b2>ζ}<be><f7><ae>ɶ<a1>:         2024/2/16, <a4>W<a4><c8> 10:31:22', '<a8>t<b2>λs<b3>y<b0><d3>:           ASUSTeK COMPUTER INC.', '<a8>t<b2>Ϋ<ac><b8><b9>:             ASUS EXPERTBOOK B1500CEAEY_B1508CEAE_T', '<a8>t<b2><ce><c3><fe><ab><ac>:             x64-based PC', '<b3>B<b2>z<be><b9>:               <a4>w<a6>w<b8><cb> 1 <b3>B<b2>z<be><b9><a1>C', '                      [01]: Intel64 Family 6 Model 140 Stepping 1 GenuineIntel ~2803 Mhz', 'BIOS <aa><a9><a5><bb>:            ASUSTeK COMPUTER INC. B1500CEAEY.320, 2022/11/4', 'Windows <a5>ؿ<fd>:         C:\WINDOWS', '<a8>t<b2>Υؿ<fd>:
C:\WINDOWS\system32', '<b6>}<be><f7><b8>˸m:             \Device\HarddiskVolume2', '<a8>t<b2>Φa<b0>ϳ]<a9>w:         zh-tw;<a4><a4><a4><e5> (<a5>x<c6>W)', '<bf><e9><a4>J<aa>k<a6>a<b0>ϳ]<a9>w:       en-us;<ad>^<a4><e5> (<ac><fc><b0><ea>)', '<ae>ɰ<cf>:                 (UTC+08:00) <a5>x<a5>_', '<b9><ea><c5><e9><b0>O<be><d0><c5><e9><c1>`<ad>p:       16,074 MB', '<a5>i<a5>ι<ea><c5><e9><b0>O<be><d0><c5><e9>:       4,013 MB', '<b5><ea><c0>0O<be><d0><c5><e9>: <a4>j<a4>p<a4>W<ad><ad>: 22,730 MB', '<b5><ea><c0>0O<be><d0><c5><e9>: <a5>i<a5><ce>:     6,176 MB', '<b5><ea><c0>0O<be><d0><c5><e9>: <a8>ϥΤ<a4>:   16,554 MB', '<a4>-<b6><c0>ɦ<ec><b8>m:           C:\pagefile.sys', '<ba><f4><b0><ec>:                 WORKGROUP', '<b5>n<a4>J<a6><f8><aa>A<be><b9>:           \\HW1120005', 'Hotfix:               <a4>w<a6>w<b8><cb> 5 Hotfix<a1>C', '                      [01]: KB5022502', '                      [02]: KB5012170', '
               [03]: KB5015684', '                      [04]: KB5023696', '                      [05]: KB5022924', '<ba><f4><b8><f4><a5>d:               <a4>w<a6>w<b8><cb> 8 NIC<a1>C', '                      [01]: Intel(R) Ethernet Connection (13) I219-V', '                            <b3>s<bd>u<a6>W<ba><d9>:           <a4>A<a4>Ӻ<f4><b8><f4>', '
       DHCP <a4>w<b1>ҥ<ce>:          <ac>O', '                            DHCP <a6><f8><aa>A<be><b9>:        192.168.1.2', '                            IP <a6><ec><a7>}', '
                [01]: 192.168.1.62', '                            [02]: fe80::6a38:a2b7:feb3:162d', '                      [02]: Intel(R) Wi-Fi 6 AX201 160MHz', '
      <b3>s<bd>u<a6>W<ba><d9>:           Wi-Fi', '                            <aa><ac><ba>A:               <b4>C<c5><e9><a4>w<a4><a4><c2>_<b3>s<bd>u', '                      [03]: Bluetooth Device (Personal Area Network)', '                            <b3>s<bd>u<a6>W<ba><d9>:           <c2>Ť<fa><ba><f4><b8><f4><b3>s<bd>u', '                            <aa><ac><ba>A:               <b4>C<c5><e9><a4>w<a4><a4><c2>_<b3>s<bd>u', '                      [04]: Fortinet Virtual Ethernet Adapter (NDIS 6.30)', '                            <b3>s<bd>u<a6>W<ba><d9>:           <a4>A<a4>Ӻ<f4><b8><f4> 2', '                            <aa><ac><ba>A:               <b4>C<c5><e9><a4>w<a4><a4><c2>_<b3>s<bd>u', '                      [05]: Fortinet SSL VPN Virtual Ethernet Adapter', '                            <b3>s<bd>u<a6>W<ba><d9>:           <a4>A<a4>Ӻ<f4><b8><f4> 3', '                            <aa><ac><ba>A:               <b4>C<c5><e9><a4>w<a4><a4><c2>_<b3>s<bd>u', '                      [06]: VMware Virtual Ethernet Adapter for VMnet1', '                            <b3>s<bd>u<a6>W<ba><d9>:           VMware Network Adapter VMnet1', '                            DHCP <a4>w<b1>ҥ<ce>:          <a7>_', '                            IP <a6><ec><a7>}', '                            [01]: 192.168.15.1', '                            [02]: fe80::7eb3:77c:e972:a27a', '                      [07]: VMware Virtual Ethernet Adapter for VMnet8', '                            <b3>s<bd>u<a6>W<ba><d9>:           VMware Network Adapter VMnet8', '                            DHCP <a4>w<b1>ҥ<ce>:          <a7>_', '                            IP <a6><ec><a7>}', '
                  [01]: 192.168.6.1', '                            [02]: fe80::153:66b2:addc:f1b0', '                      [08]: VirtualBox Host-Only Ethernet Adapter', '
              <b3>s<bd>u<a6>W<ba><d9>:           <a4>A<a4>Ӻ<f4><b8><f4> 4', '                            DHCP <a4>w<b1>ҥ<ce>:          <a7>_', '                            IP <a6><ec><a7>}', '                            [01]: 192.168.56.1', '                            [02]: fe80::f8c1:4b59:781:b7f0', 'Hyper-V <bb>ݨD:         <b0><bb><b4><fa><a8><ec> Hypervisor<a1>C<b1>N<a4><a3><b7>|<c5><e3><a5><dc> Hyper-V <a9>һݪ<ba><a5>\<af><e0><a1>C'], '__validate': 'cache_v2'}
```

**Comment by lervag** [comment] 2024-02-18 20:26
Thanks! Does this mean that you now get this error message everytime you do `:VimtexInfo`? And how does the resulting `:VimtexInfo` output look like now?

**Comment by hrcHarry** [comment] 2024-02-19 07:41
> Hi @lervag
> 
> The result of testing is as follows
> 
> ```
> VimTeX: Could not encode cache "capture"
>         {'systeminfo': ['', '<a5>D<be><f7><a6>W<ba><d9>:             HW1120005', '<a7>@<b7>~<a8>t<b2>ΦW<ba><d9>:         Microsoft Windows 10 <b1>M<b7>~<aa><a9>', '<a7>@<b7>~<a8>t<b2>Ϊ<a9><a5><bb>:         10.0.19045 N/A <b2>ի<d8> 19045', '<a7>@<b7>~<a8>t<b2>λs<b3>y<b0><d3>:       Microsoft Corporation', '<a7>@<b7>~<a8>t<b2>γ]<a9>w:         <bf>W<a5>ߤu<a7>@<af><b8>', '<a7>@<b7>~<a8>t<b2>βի<d8><c3><fe><ab><ac>:     Multiprocessor Free', '<b5><f9><a5>U<aa><ba><be><b3><aa><cc>:         admin', '<b5><f9><a5>U<a4><bd><a5>q:             ', '<b2><a3><ab>~<c3>ѧO<bd>X:           00355-63057-04487-AAOEM', '<ad><ec><a9>l<a6>w<b8>ˤ<e9><b4><c1>:         2023/3/21, <a4>W<a4><c8> 11:16:38', '<a8>t<b2>ζ}<be><f7><ae>ɶ<a1>:         2024/2/16, <a4>W<a4><c8> 10:31:22', '<a8>t<b2>λs<b3>y<b0><d3>:           ASUSTeK COMPUTER INC.', '<a8>t<b2>Ϋ<ac><b8><b9>:             ASUS EXPERTBOOK B1500CEAEY_B1508CEAE_T', '<a8>t<b2><ce><c3><fe><ab><ac>:             x64-based PC', '<b3>B<b2>z<be><b9>:               <a4>w<a6>w<b8><cb> 1 <b3>B<b2>z<be><b9><a1>C', '                      [01]: Intel64 Family 6 Model 140 Stepping 1 GenuineIntel ~2803 Mhz', 'BIOS <aa><a9><a5><bb>:            ASUSTeK COMPUTER INC. B1500CEAEY.320, 2022/11/4', 'Windows <a5>ؿ<fd>:         C:\WINDOWS', '<a8>t<b2>Υؿ<fd>:
> C:\WINDOWS\system32', '<b6>}<be><f7><b8>˸m:             \Device\HarddiskVolume2', '<a8>t<b2>Φa<b0>ϳ]<a9>w:         zh-tw;<a4><a4><a4><e5> (<a5>x<c6>W)', '<bf><e9><a4>J<aa>k<a6>a<b0>ϳ]<a9>w:       en-us;<ad>^<a4><e5> (<ac><fc><b0><ea>)', '<ae>ɰ<cf>:                 (UTC+08:00) <a5>x<a5>_', '<b9><ea><c5><e9><b0>O<be><d0><c5><e9><c1>`<ad>p:       16,074 MB', '<a5>i<a5>ι<ea><c5><e9><b0>O<be><d0><c5><e9>:       4,013 MB', '<b5><ea><c0>0O<be><d0><c5><e9>: <a4>j<a4>p<a4>W<ad><ad>: 22,730 MB', '<b5><ea><c0>0O<be><d0><c5><e9>: <a5>i<a5><ce>:     6,176 MB', '<b5><ea><c0>0O<be><d0><c5><e9>: <a8>ϥΤ<a4>:   16,554 MB', '<a4>-<b6><c0>ɦ<ec><b8>m:           C:\pagefile.sys', '<ba><f4><b0><ec>:                 WORKGROUP', '<b5>n<a4>J<a6><f8><aa>A<be><b9>:           \\HW1120005', 'Hotfix:               <a4>w<a6>w<b8><cb> 5 Hotfix<a1>C', '                      [01]: KB5022502', '                      [02]: KB5012170', '
>                [03]: KB5015684', '                      [04]: KB5023696', '                      [05]: KB5022924', '<ba><f4><b8><f4><a5>d:               <a4>w<a6>w<b8><cb> 8 NIC<a1>C', '                      [01]: Intel(R) Ethernet Connection (13) I219-V', '                            <b3>s<bd>u<a6>W<ba><d9>:           <a4>A<a4>Ӻ<f4><b8><f4>', '
>        DHCP <a4>w<b1>ҥ<ce>:          <ac>O', '                            DHCP <a6><f8><aa>A<be><b9>:        192.168.1.2', '                            IP <a6><ec><a7>}', '
>                 [01]: 192.168.1.62', '                            [02]: fe80::6a38:a2b7:feb3:162d', '                      [02]: Intel(R) Wi-Fi 6 AX201 160MHz', '
>       <b3>s<bd>u<a6>W<ba><d9>:           Wi-Fi', '                            <aa><ac><ba>A:               <b4>C<c5><e9><a4>w<a4><a4><c2>_<b3>s<bd>u', '                      [03]: Bluetooth Device (Personal Area Network)', '                            <b3>s<bd>u<a6>W<ba><d9>:           <c2>Ť<fa><ba><f4><b8><f4><b3>s<bd>u', '                            <aa><ac><ba>A:               <b4>C<c5><e9><a4>w<a4><a4><c2>_<b3>s<bd>u', '                      [04]: Fortinet Virtual Ethernet Adapter (NDIS 6.30)', '                            <b3>s<bd>u<a6>W<ba><d9>:           <a4>A<a4>Ӻ<f4><b8><f4> 2', '                            <aa><ac><ba>A:               <b4>C<c5><e9><a4>w<a4><a4><c2>_<b3>s<bd>u', '                      [05]: Fortinet SSL VPN Virtual Ethernet Adapter', '                            <b3>s<bd>u<a6>W<ba><d9>:           <a4>A<a4>Ӻ<f4><b8><f4> 3', '                            <aa><ac><ba>A:               <b4>C<c5><e9><a4>w<a4><a4><c2>_<b3>s<bd>u', '                      [06]: VMware Virtual Ethernet Adapter for VMnet1', '                            <b3>s<bd>u<a6>W<ba><d9>:           VMware Network Adapter VMnet1', '                            DHCP <a4>w<b1>ҥ<ce>:          <a7>_', '                            IP <a6><ec><a7>}', '                            [01]: 192.168.15.1', '                            [02]: fe80::7eb3:77c:e972:a27a', '                      [07]: VMware Virtual Ethernet Adapter for VMnet8', '                            <b3>s<bd>u<a6>W<ba><d9>:           VMware Network Adapter VMnet8', '                            DHCP <a4>w<b1>ҥ<ce>:          <a7>_', '                            IP <a6><ec><a7>}', '
>                   [01]: 192.168.6.1', '                            [02]: fe80::153:66b2:addc:f1b0', '                      [08]: VirtualBox Host-Only Ethernet Adapter', '
>               <b3>s<bd>u<a6>W<ba><d9>:           <a4>A<a4>Ӻ<f4><b8><f4> 4', '                            DHCP <a4>w<b1>ҥ<ce>:          <a7>_', '                            IP <a6><ec><a7>}', '                            [01]: 192.168.56.1', '                            [02]: fe80::f8c1:4b59:781:b7f0', 'Hyper-V <bb>ݨD:         <b0><bb><b4><fa><a8><ec> Hypervisor<a1>C<b1>N<a4><a3><b7>|<c5><e3><a5><dc> Hyper-V <a9>һݪ<ba><a5>\<af><e0><a1>C'], '__validate': 'cache_v2'}
> ```

Hi @lervag 

The error message appears every time I open a new terminal executing nvim (.tex file) and doing `:VimtexInfo`. Then, it gives the normal result (`System info:` and `VimTeX project`).
One more doing `:VimtexInfo`, it only gives the normal result (`System info:` and `VimTeX project`) without the error message.

**Comment by lervag** [comment] 2024-02-21 11:38
> The error message appears every time I open a new terminal executing nvim (.tex file) and doing `:VimtexInfo`. Then, it gives the normal result (`System info:` and `VimTeX project`).

Ok, this is as expected. I believe it is an improvement from earlier, where there would still be an error, but the info window would not appear.

I'm sorry to say that I don't know how to better solve this issue. The problem has to do with your locale, which, for some reason, is not standard UTF-8. If you're able to change this in your Windows environment, then I think you won't get that error.

**Comment by lervag** [comment] 2024-02-21 11:38
I'm closing the issue as I don't know how else to proceed here.

**Closed by lervag** 2024-02-21 11:38 UTC
Labels: bug
