### ISSUE TITLE
vimtex: Compiler did not start successfully!

### ISSUE THREAD

**Issue by Sroka** [lervag/vimtex#1344] opened 2019-03-23 10:21 UTC
Hello,

I have a problem with making vimtex working on MacOS. Whenever I run `:VimtexCompile` I get `"vimtex: Compiler did not start successfully!"` message with the following compiler output:

```
*** collate_byname<char>::collate_byname failed to construct for
```

The file I run is:
```
\documentclass{minimal}
\begin{document}
Text
\end{document}
```

Output of `:VimtexInfo`:
```
System info
  OS: Mac OS X 10.14.3 (18D109)
  Vim version: NVIM v0.3.4
  Has clientserver: true
  Servername: /var/folders/bh/92j7zqp90_1bmgvpllwmd3m80000gn/T/nvimqeHjCm/0

vimtex project: Test
  base: Test.tex
  root: /Users/maciejsrokowski
  tex: /Users/maciejsrokowski/Test.tex
  out: /Users/maciejsrokowski/Test.pdf
  log: /Users/maciejsrokowski/Test.log
  aux: /Users/maciejsrokowski/Test.aux
  fls: /Users/maciejsrokowski/Test.fls
  compiler: latexmk
    backend: nvim
    output: /var/folders/bh/92j7zqp90_1bmgvpllwmd3m80000gn/T/nvimqeHjCm/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: Skim
  qf: LaTeX logfile
    config: 
      fix_paths: 1
      packages: 
        default: 1
      default: 1
  document class: minimal

```

My init.vim:
```
set clipboard+=unnamedplus

call plug#begin()
Plug 'lervag/vimtex'
Plug 'itchyny/lightline.vim'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
call plug#end()
let g:tex_flavor='latex'
let g:vimtex_view_method='skim'
let g:vimtex_quickfix_mode=0
let g:vimtex_compiler_progname='nvr'
set conceallevel=2
let g:tex_conceal='abdmg'
```

**Comment by lervag** [comment] 2019-03-23 15:05
Can you copy the output from `:VimtexCompileOutput` here as well (after you have started compilation)? I have not seen that error message before, and can only say that it is not something from vimtex directly. It might be from latexmk, but not as I know of.

**Comment by Sroka** [comment] 2019-03-23 15:49
The First snippet is the output of VimtexCompileOutput. Hmmmm, when I compile it just with latexmk I get no errors but resulting PDF doesn't seem right. I'll check it when I'm back at my computer

**Comment by Sroka** [comment] 2019-03-23 20:07
Hmmm, I just checked and when compiling from command line with "latexmk --pdf Test.tex" works fine

**Comment by lervag** [comment] 2019-03-24 21:20
Could you try with a minimal vimrc file? E.g.

```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
```

Here `~/.vim/bundle/vimtex` should of course be updated if necessary so that it points to the location of vimtex on your system. Assume the above content is in `minivimrc`, put it in the same directory as `Test.tex`, then do `vim --servername VIM -u minivimrc Test.tex`. This will open your minimal example with a minimal configuration. Check that e.g. `:VimtexInfo` still work. If it does, then test if the compilation works as expected.

**Comment by lervag** [comment] 2019-03-25 19:28
The error you mention:

```
*** collate_byname<char>::collate_byname failed to construct for
```

Is not really something I'm familiar with. When I search for it, it seems to be related to the locale. What's the output of `locale` in a terminal? Also check if the problem is resolved by adding this to your bashrc file (or whatever shell config is relevant for you):

```sh
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

**Comment by Sroka** [comment] 2019-03-26 20:22
Hey, I'm sorry for a late answer.

1)
I am using Neovim and the option --servername didn't work for me but I just deleted briefly everyting form my init.vim and left only this and plug:

```
set nocompatible
let &runtimepath  = '~/.config/nvim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.config/nvim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
```

It didn't help though :/

2)
You, sir, are a Magician! Putting this:
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
in my .bash_profile fixed everything. Thank you once again and congrats on being able to find the issue with such limited amount of data :)

**Comment by lervag** [comment] 2019-03-26 21:18
Ah, great! So it seems the problem may be due to the locale. If adding those two lines fixes things and does not have any unwanted side effects, then that is of course optimal. Note that this might override the system locale, which might e.g. mean that starting other programs from a terminal might make them start with US english language instead of the language you expect.

I am not sure where exactly the error you gave comes from. If necessary, let me know and we can try to go further. But of course, if things now just work as expected, then I'm more than happy to leave it at that! :)

**Closed by lervag** 2019-03-26 21:18 UTC
