### ISSUE TITLE
change surrounding environment in \[ and \(

### ISSUE THREAD

**Issue by nilsbecker** [lervag/vimtex#316] opened 2016-01-08 17:58 UTC
`cse` prompts for an environment when invoked inside `\[E=mc^2\]` but the replacement produces wrong output. likewise, inside `\( xyz \)`. ideally, it should be possible to also enter `$, $$, \(, \[` as the new environment. this would provide a way to promote inline equations to displayed, unnumbered and vice versa.

**Comment by lervag** [comment] 2016-01-08 22:12
The reason it does not work is that it currently only works when `\[` and `\]` are on separate lines, e.g. for

```tex
\[
  E=mc^2
\]
```

I'll leave this open, since I think this sounds like a reasonable and good feature upgrade. However, it might take some time, since I first need to make it work when everything is in one line, and I then have to add support for `$`, `$$` and `\(`.

**Comment by lervag** [comment] 2016-02-06 19:26
This should be fixed in the recent update.

**Closed by lervag** 2016-02-06 19:26 UTC
Labels: enhancement

**Comment by nilsbecker** [comment] 2016-02-07 19:26
i tried it and it works, except for a small bug (i think): when changing from `\[` to `\begin{equation*}` and then trying to invoke `cse` again, the environment is not recognized and it wants to change the whole `document` environment. this does not happen with `equation` without `*`. the enclosing environments were all on the same line

**Comment by nilsbecker** [comment] 2016-02-07 20:18
@lervag see above, i'm not sure if you get notified of comments on closed issues

**Comment by lervag** [comment] 2016-02-07 20:18
I'm actually working on this right now. I've found the problem, should be fixed soon. :)

**Comment by n0ibe** [comment] 2020-08-31 23:35
@lervag I'm not sure why this issue has been closed. In the following example,

```latex
\documentclass{article}
\begin{document}
\[
  1 + 1 = \mathrm{fish}
\]
\end{document}
```

if I place my cursor anywhere between line 3 and 5, `cse` tries to change the `document` environment and not `\[ ... \]`.

**Comment by lervag** [comment] 2020-09-01 06:24
Yes, this is as "expected" (at least as intended). `cse` works only on "regular" environments, while `cs$` works on "math" environments such as `$...$`, `$$ ... $$`, `\[ ... \]`, and so on. With `cs$` you can change to a regular environment as well.

**Comment by n0ibe** [comment] 2020-09-01 08:35
Oh, must've skipped that part of the docs. Thanks :)

**Comment by lervag** [comment] 2020-09-01 08:40
I'm not sure if that part of the docs is good enough... :p (let me know if you have suggestions for improving the docs!).
