### ISSUE TITLE
vimtex can't compile Japanese and pictures normally

### ISSUE THREAD

**Issue by michael-t94** [lervag/vimtex#991] opened 2017-11-02 23:08 UTC
I'm new here and my English is not very good so maybe I can't say my problem clearly but I'll try.

The problem is when I run \lv on a .tex file with Japanese characters, the viewer can not display Japanese. 
But when I run latexmk from my terminal(I use MacOs Sierra 10.12.6), everything went normally.
After I changed my tex file to this one and run \lv, the viewer can display Japanese normally.

```tex
\documentclass{article}
\usepackage{CJKutf8}
\begin{document}
\begin{CJK}{UTF8}{min}
日本語
\end{CJK}
\end{document}
```

so I checked the output of latexmk when I run from terminal, it's different from the one in vim when I run `:VimCompileOutput`. It seems like vimtex uses different latexmk. I don't know if this is the problem.

For example, this is my tex file:

```tex
\documentclass{article}
\begin{document}
日本語
\end{document}
```

and this my minimal .vimrc:

```vim
filetype off
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on

let g:tex_flavor = 'latex'
let g:vimtex_fold_enabled = 0
let g:vimtex_compiler_latexmk = {'callback' : 0}
let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '-r @line @pdf @tex'
```

and here is my .latexmkrc:

```perl
$latex = 'platex -synctex=1 -halt-on-error';
$pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 %S';
$latex_silent = 'platex -synctex=1 -halt-on-error -interaction=batchmode';
$bibtex = 'pbibtex';
$dvipdf = 'dvipdfmx %O -o %D %S';
$makeindex = 'mendex %O -o %D %S';
$max_repeat = 5;
$preview_continuous_mode = 1;
$pdf_mode = 3;
$pvc_view_file_via_temporary = 0;
$clean_ext = 'synctex.gz synctex.gz(busy) acn acr alg aux bbl bcf blg brf dvi fdb_latexmk glg glo gls idx ilg ind ist lof log lot lox out paux pdfsync run.xml toc';
```

I tried to figure out what went wrong by myself for hours but still got nothing so I put my quetison here. Hope somebody can help me.

**Comment by andymass** [comment] 2017-11-02 23:45
The difference is you have $latex set to platex, which works, but $pdflatex to pdflatex which doesn't work.  vimtex uses $pdflatex through the -pdf option.  You can either get rid of the '-pdf' option from vimtex,

```vim
let g:vimtex_compiler_latexmk = {
       \ 'options' : [
        \   '-verbose',
        \   '-file-line-error',
        \   '-synctex=1',
        \   '-interaction=nonstopmode',
        \ ],
        \}
```

or amend your latexmk to use platex as the $pdflatex engine (change the $pdflatex = '' string to something more appropriate)

**Comment by lervag** [comment] 2017-11-03 07:27
@michael-t94 I find your english more than adequate, don't worry! :) I took the liberty of adding some formatting to your original post, and I removed the `Vundle` part from the minimal vimrc file as that should not be relevant to this issue.

I think @andymass is right. The problem is that in the terminal, your `$pdf_mode = 3` means that `latexmk` uses `$latex -> $dvipdf`, not `$pdflatex`. I think your options are:

1. Do something like what @andymass suggests. I think perhaps it should be enough to set the option that he suggests (of course, you can keep the `callback` part if wanted).

2. You could try to use xelatex or lualatex instead of pdflatex. I don't use these myself, although I probably should. In any case, these might better handle the Japanese characters.

3. It might also be enough to load a utf package, such as `\usepackage[utf8]{inputenc}`.

**Comment by michael-t94** [comment] 2017-11-03 09:00
@andymass Thanks for your help. I took your suggestion and solved my problem. 

First I only changed $pdflatex to 'dvipdfmx' and run \lv from vim, it worked, but when I compile another japanese tex file with pictures, it display Japanese well but not the pictures. So I removed '-pdf' option from vimtex like you said, then everything worked fine, both Japanese characters and pictures. It seems like vimtex '-pdf' option overwrite the .latexmkrc file, is that right?

Anyway, thank you so much!

**Comment by michael-t94** [comment] 2017-11-03 09:09
@lervag Thank you for your reply. I took the suggestion from @andymass and solved my problem perfectly.

And when I tried to figure out my problem by myself, I did try the xelatex from my terminal, it worked fine. I was confused by the mechanism of vimtex then. Maybe I need to learn more about latex and vimtex.

**Comment by lervag** [comment] 2017-11-03 10:43
@michael-t94 Vimtex runs the `latexmk` process with the options given in `g:vimtex_compiler_latexmk.options`. The default `-pdf` tells `latexmk` to use `pdflatex` as the driver. All of these options will override the settings in your `.latexmkrc` file. Thus, if you want to make your `.latexmkrc` file specify most/all of the options, then you can remove the options from the vimtex variable. Note that a lot of the options to `latexmk` are directly passed on to the compiler, e.g. `-synctex=1` when passed to `latexmk` will be passed on to the `latex`/`platex`/`pdflatex` process.

I think at least some of these things are explained quite well in the vimtex documentation, e.g. in `:h vimtex-latexmk`.

**Comment by lervag** [comment] 2017-11-03 10:43
Btw, since it seems the issue is solved, I'll take the liberty of closing it.

**Closed by lervag** 2017-11-03 10:43 UTC

**Comment by michael-t94** [comment] 2017-11-03 11:05
@lervag Thanks, I understand now, I think I should take some time to read the documentation very carefully.

**Comment by lervag** [comment] 2017-11-03 13:17
Great! I think there should be a lot of very good information in the docs, but I also very much understand that they are very long. I don't think you need to read all of it, but you should read the introduction, as well as skim the available options and features.

In any case, feel free to open issues if you have other problems. Happy vimming! :)
