### ISSUE TITLE
inner environment text-object fails on { being the first char after \begin{}

### ISSUE THREAD

**Issue by habamax** [lervag/vimtex#2160] opened 2021-09-05 11:50 UTC
### Description

No way to visually select or delete inner environment with `vie`, `die` for the code block of the json source.

### Steps to reproduce

1. `vim -u minimal.vim minimal.tex`
2. position cursor on `"contacts"`
3. `vie`

## minimal.tex
```
\documentclass{minimal}
\begin{document}
\begin{minted}
    {
        "contacts": [
          {
            "source_id": "mandatory"
          }
        ]
    }
\end{minted}
\end{document}
```

### Expected behavior

Contents of the `minted` environment is visually selected:
![image](https://user-images.githubusercontent.com/234774/132125625-23cdcdb1-de0c-467a-b4ed-b3a379ccbf16.png)

### Actual behavior

A single char is selected at the end of the environment:
![image](https://user-images.githubusercontent.com/234774/132125662-a90d3aa0-0330-40e9-b81f-9481749d52bb.png)

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Microsoft Windows 10 Pro (10.0.19041 N/A Build 19041)
  Vim version: VIM 8.2 (1-3399)
  Has clientserver: true
  Servername: GVIM

VimTeX project: minimal
  base: minimal.tex
  root: C:\Users\maksim.kim
  tex: C:\Users\maksim.kim\minimal.tex
  main parser: current file
  document class: 
  compiler: latexmk
    engine: -lualatex
    options:
      -shell-escape
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    build_dir: minimal
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```

**Comment by habamax** [comment] 2021-09-05 11:56
It didn't work for me with crowded minted environment:
![image](https://user-images.githubusercontent.com/234774/132125807-d0370fe6-ef3e-4d42-a0d3-ca7d9493ad3e.png)

And only if I add non `{` char (not space) before `{` it starts recognizing inner environment:
![image](https://user-images.githubusercontent.com/234774/132125857-5b4170fc-b4f2-460c-a7ec-91f1137a86dd.png)

**Comment by habamax** [comment] 2021-09-05 11:59
And `vae`, `dae` works no matter what.

**Comment by lervag** [comment] 2021-09-05 12:15
`vae` and `dae` are simple. The problem here is that the initial `{` is very confusing. There is no "generic" manner to parse TeX reliably, so how do we know it is not part of the `\begin{...}[..]{..}` command?

**Comment by lervag** [comment] 2021-09-05 12:15
I think we need to make some heuristic, but I'm not sure if it is safe to do so.

**Comment by lervag** [comment] 2021-09-05 12:23
You would get the same problem with

```tex
\begin{minted}
    [
        "contacts": [
          {
            "source_id": "mandatory"
          }
        ]
    ]
\end{minted}
```

The point, as hinted, is that VimTeX parses `\begin{minted}{...}` as the beginning of the environment. The parser allows separating white space, including newlines. And this really is allowed LaTeX. Notice that the following will compile perfectly fine:

```tex
\documentclass{article}
\usepackage{minted}
\begin{document}

\begin{minted}
  [
    numbersep=5mm,
    linenos=true,
    fontsize=\footnotesize,
    breaklines
  ]
  {
    json
  }
  {
    "contacts": [
      {
        "source_id": "mandatory"
      }
    ]
  }
\end{minted}
\end{document}
```

My point is only to show that it really _is_ hard to properly parse this stuff. And I don't know if I'm able to really find a good way to make it work reliably.

**Comment by lervag** [comment] 2021-09-05 12:27
In my last example: I think we can both agree that the inner part of the environment starts at `{\n   "contacts"` (`\n` indicates newline). But the current parser is greedy and "gobbles" up the last `{ ... }` also as an argument for `\begin{minted}`, and so it puts the start of the inner area at the final `}` before `\end{minted}`.

So, at least the issue is now fully understood and explained. It remains to see if it is possible to suggest any solution. I'm afraid it is going to be hard.. :\

**Comment by lervag** [comment] 2021-09-05 12:28
Perhaps a workaround is to add an empty line first? Or a json comment?

**Comment by habamax** [comment] 2021-09-05 12:30
I can totally understand it is not a trivial thing to do, indeed.

1. Empty line doesn't make any difference
2. json comment might be a workaround but for now I just `vaekoj` :)

**Comment by habamax** [comment] 2021-09-05 12:32
I am thinking of non-greedy `{}[]{}` detection, could you point me to the place where it is defined?

**Comment by habamax** [comment] 2021-09-05 12:39
One additional thing: `cac` on `\begin` deletes all the way up to `\end` :)

**Comment by lervag** [comment] 2021-09-05 12:40
Yes; for the exact same reason.

**Comment by lervag** [comment] 2021-09-05 12:41
It is more or less impossible to write a perfect parser here, I believe. To do so, we need to know the exact signature of each command. But we don't. :\

**Comment by lervag** [comment] 2021-09-05 12:42
> I am thinking of non-greedy `{}[]{}` detection, could you point me to the place where it is defined?

In some cases, non-greedy would be perfect. In others, it would not be good and you would have to adjust.

**Comment by lervag** [comment] 2021-09-05 12:44
The text object function is here:

https://github.com/lervag/vimtex/blob/1861f3c89d9c4dc776f95639295ebdbe00c12702/autoload/vimtex/text_obj.vim#L103-L168

Here the inner object is narrowed:

https://github.com/lervag/vimtex/blob/1861f3c89d9c4dc776f95639295ebdbe00c12702/autoload/vimtex/text_obj.vim#L285-L289

The parser for environment delimiters is here:

https://github.com/lervag/vimtex/blob/1861f3c89d9c4dc776f95639295ebdbe00c12702/autoload/vimtex/delim.vim#L538-L572

**Comment by lervag** [comment] 2021-09-05 12:44
This is the outer delimiter parser, the starting point of the parser:

https://github.com/lervag/vimtex/blob/1861f3c89d9c4dc776f95639295ebdbe00c12702/autoload/vimtex/delim.vim#L426-L514

**Comment by lervag** [comment] 2021-09-05 12:49
I have to admit I'm tempted to not spend more time on this, as I can't see any clear strategy for fixing this that won't break other functionality. :\

**Comment by habamax** [comment] 2021-09-05 13:02
> I have to admit I'm tempted to not spend more time on this, as I can't see any clear strategy for fixing this that won't break other functionality. :\

You're probably right. I can only think of a newline-like `^\s*$` separator between parameters and body text.

Anyway, I can agree there is no clear solution to the problem.

**Comment by habamax** [comment] 2021-09-05 13:08
As a workaround I can use a `<C-k><space><space>` added to the beginning of the env body.

**Comment by lervag** [comment] 2021-09-05 13:14
So, just to be clear: I believe the current implementation works "as expected" most of the time, and that your specific example is simply a good example of where it does _not_ work as expected.

> I can only think of a newline-like ^\s*$ separator between parameters and body text.

I agree with that, actually, so I'll look into it.

**Comment by lervag** [comment] 2021-09-05 19:29
>  I can only think of a newline-like ^\s*$ separator between parameters and body text.

I agree; just pushed a fix for that.

> As a workaround I can use a `<C-k><space><space>` added to the beginning of the env body.

Ah, yes, that seems like an ok workarond.

For other readers: `<c-k><space><space>` in insert mode will create an unbreakable space, a different type of space. It is _not_ matched with the regex pattern `\s`, which is why it works as a workaround.

**Closed by lervag** 2021-09-05 19:29 UTC
Labels: bug

**Comment by habamax** [comment] 2021-09-06 06:43
Thx, empty line separator looks like a good solution for this.
