### ISSUE TITLE
Synctex backward search with neovim and nvr

### ISSUE THREAD

**Issue by stanislas-brossette** [lervag/vimtex#414] opened 2016-04-03 04:14 UTC
Hello,
I've been using vimtex for a while as a vim plugin.
I recently moved to neovim and everythink works like a charm just by adding the line 
`let g:vimtex_latexmk_progname = 'nvr'` to my config.
But I can't seem to figure out how to make the backward search work with qpdfview or okular
With vim I added the line 
`vim --servername LATEX --remote-silent +%2<Enter>zz %1` to the Source Editor option in qpdfview.
But with neovim and nvr, I'm not sure what to put in this option.
Any advice?

**Comment by lervag** [comment] 2016-04-03 06:56
Good question. I think `nvr` will choose the correct server if there is only a single one. Thus, if you remove the `--servername` flag and work with only one server, then it should work with `nvr`. I think.

I don't use neovim myself (I'm tempted, but I'm slightly too conservative).

I know there are others who do use it, but I think they use mupdf (which does not have backward search) or zathura (which should support it out of the box).

**Comment by stanislas-brossette** [comment] 2016-04-03 07:39
Thank you for the quick reply.
I have tried changing the Source editor option to:
"nvim --remote-silent +%2<Enter>zz %1"
But it did not allow me to do backward search from qpdfview.

I would be willing to use zathura instead of qpdfview.
At the moment my latexmkrc contains:
"
# For synctex
$pdflatex = 'pdflatex -synctex=1 %O %S';
$pdf_previewer = "start zathura --unique";
# For nomenclature
add_cus_dep("nlo", "nls", 0, "nlo2nls");
sub nlo2nls {
  system("makeindex $_[0].nlo -s nomencl.ist -o $_[0].nls -t $_[0].nlg");
}
"

And I set the vimtex options in my vimrc as:
"
" vimtex {{{
let g:vimtex_latexmk_build_dir = './build'
let g:vimtex_latexmk_progname = 'nvr'
let g:vimtex_view_general_viewer = 'zathura'
let g:vimtex_view_general_options = '--unique @pdf\#src:@tex:@line:@col'
let g:vimtex_view_general_options_latexmk = '--unique'

" Remap double click for latex
autocmd FileType tex nnoremap <silent> <2-LeftMouse> :VimtexView<CR>
" }}}
"
I assume that I'm doing something wrong because in that case the viewer does not open when invoquing it from vimtex (<Leader>+l+v)

Do you have an idea of what I should change?

**Comment by lervag** [comment] 2016-04-03 10:19
Change the vimtex settings to:

```vim
let g:vimtex_latexmk_build_dir = './build'
let g:vimtex_latexmk_progname = 'nvr'
let g:vimtex_view_method = 'zathura'
```

Please see `:h vimtex_view_method`.

By the way, and not related to anything else here, I recommend to add the option `-interaction=nonstopmode` to the pdflatex options (infront of `-synctex=1`).

**Comment by stanislas-brossette** [comment] 2016-04-03 14:03
Thanks, that setup allows to open the pdf in zathura. 
Unfortunately, the forward and inverse searches do not work out of the box.
The best I could get so far is the forward search with qpdfview. With the setup I posted earlier.
I guess it's just a matter of figuring what command to give to the source editor option in qpdfview.

**Comment by lervag** [comment] 2016-04-03 20:17
That's strange. I thought it should have worked. Does it work if you don't specify the build directory?

Does it work with Vim?

Anyways, for qpdfview: you can try to do `:echo v:servername` from within neovim, than use that explicitly in the `nvr` command in qpdfview. I don't think this is a good solution, as I think neovim do not use persistent servernames, but at least it will be a start..?

**Comment by stanislas-brossette** [comment] 2016-04-04 02:08
Specifying the build directory does not change the behavior. Still only forward search in qpdfview and nothing in zathura.
Using **vim**, the forward and backward searches work fine in qpdfview but not with zathura.
Note that I launch vimtex with the following commands:
In **vim**: `alias vimtex='vim --servername LATEX'`
In **neovim**: `alias nvimtex='NVIM_LISTEN_ADDRESS=/tmp/nvim_tex.sock nvim'`
This second one allows to always have the same servername, thus
`:echo v:servername` always give `/tmp/nvim_tex.sock`
I'm trying to find what line to give qpdfview to use that. But have not found it so far.

**Comment by lervag** [comment] 2016-04-04 16:11
How about defining a script similar to how it is explained in the [README](https://github.com/mhinz/neovim-remote) for neovim-remote? That is, in the example provided. Also, you could experiment with things like `nvr --servername /tmp/nvim_tex.sock --remote-send 'iabc<esc>'` to see if you can use the remote commands from the terminal. If this works, then it shouldn't be too difficult to extrapolate to some sensible qpdfview settings?

Regarding zathura: It should work in Vim. Do you have xdotool installed? If you get it to work in Vim, then I think it should also work with neovim.

**Comment by lervag** [comment] 2016-04-12 14:44
I'm sorry for not being able to be more helpful. Have you had any progress, though?

**Comment by stanislas-brossette** [comment] 2016-04-12 14:51
I think that the method you propose is indeed the right way to go for this. As some people report having done it in similar ways.
Unfortunately, I haven't had time to try it out more yet.

**Comment by lervag** [comment] 2016-04-12 16:25
Ok. I'll take the liberty of closing this, then. Feel free to reopen if you feel the issue is unresolved.

**Closed by lervag** 2016-04-12 16:25 UTC

**Comment by jazzpi** [comment] 2016-06-06 22:28
Since this is the first result when googling "neovim okular vimtex", I'll share my solution: I simply replaced the `vim` in the command in the helptext with `nvr`, so now the editor command in Okular is set to `nvr --remote-silent +%l "%f"`.

Does this also work with qpdfview?

**Comment by lervag** [comment] 2016-06-07 07:39
I would think so, but I have not tried it myself.

**Comment by stanislas-brossette** [comment] 2016-06-07 11:48
In my case it does not work(not with qpdfview, nor with okular). But I believe there is another problem in my config that prevents it from working. As it works perfectly with vim and I have seen it working with that method on other configs. Just haven't had time to investigate it.

**Comment by alathon** [comment] 2016-08-28 10:20
Just wanted to comment on what ended up working for me, since I found this issue via Google and it took me a few hours to debug various different problems.

In qpdfview, the command
```
nvr --remote +":%2" "%1"
```

Works for me to perform backward search. This assumes the following:

1. You have only a single NeoVim session, and so do not need to specify --servername. If you do work with multiple sessions, consider forcing the one you use to edit tex files to a specific servername, and put that in the command (e.g. start nvim as 'NVIM_LISTEN_ADDRESS=/tmp/texsocket nvim' and put --servername=/tmp/texsocket in the Source Editor command).
2. You have installed neovim-remote (allowing use of --remote things in NeoVim via an nvr command).

Curiously, I could not get the + command "%2G" to work. Nor "%2G%3|" to go to column as well. That seems more like a Neovim-Remote issue, or maybe its related to my setup - It considers that command ambiguous, but only with nvr --remote. Issuing the same exact command via nvr --remote-send works just fine.

**Comment by lervag** [comment] 2016-08-28 13:22
Thanks for writing about this here. As you say, this issue may be found on Google, and so adding text on your experience might help others.

**Comment by HarmtH** [comment] 2016-09-23 12:42
> Curiously, I could not get the + command "%2G" to work. Nor "%2G%3|" to go to column as well. That seems more like a Neovim-Remote issue, or maybe its related to my setup - It considers that command ambiguous, but only with nvr --remote. Issuing the same exact command via nvr --remote-send works just fine.

With ```--remote``` you load a file, you have to use ```-c``` to execute a command.
```-c 'drop %1 | normal! %2G%3|'``` works

**Comment by nsirolli** [comment] 2018-07-14 01:53
I'm using `nvr --remote-silent %f -c %l` as indicated in the documentation, but it is not working. Running qpdfview from the console, after trying to perform a backwards search I get the error message:

`QString::arg: 3 argument(s) missing in 'nvr --remote-silent %f -c %'`

**Comment by nsirolli** [comment] 2018-07-14 12:18
Dear Karl,

I'm sorry about this. Thinking a little more about it, I feel that it's not
a vimtex issue, and not even a neovim issue! When I run nvr --remote-silent
%f -c %l in the command line, neovim opens the file as expected. I guess
that it's qpdfview's "fault".

If you think that opening a new issue with a better description would be
helpful, I'd be glad to do so.

Best,
Nicolás.

PS: before messing up on Github again, I'd like to ask you the following.
Is there an easy way to close the errors window? I feel that some time ago
I could use <localleader>le to close/open it when it was open/closed. It
does open it, but it does not close it.

**Comment by lervag** [comment] 2018-07-16 06:03
No problem! I've not used qpdfview so much, but I think you are right that this is not vimtex's fault.

Reg. error windows, `<localleader>le` should both open and close the window. Please open a new issue for this. I'd be very happy if you can create a minimal example, cf. the issue template.

**Comment by xyegithub** [comment] 2022-03-01 01:22
> I'm using `nvr --remote-silent %f -c %l` as indicated in the documentation, but it is not working. Running qpdfview from the console, after trying to perform a backwards search I get the error message:
> 
> `QString::arg: 3 argument(s) missing in 'nvr --remote-silent %f -c %'`


I achieved the backward search by setting 'nvr --remote-silent +%2 %1'. However, qpdfview does not allow by `shift + click` or `shift + double clicks`. The backward search is triggered by 'right-mouse-click' and then chose the botton 'edit the source'. And
now, I do not know how allow backward search by 'shift + click'.

**Comment by lervag** [comment] 2022-03-01 20:31
@xyegithub This issue is almost 4 years old, also, you opened two other related issues #2339 and #2340. I will respond, I've just been too busy to respond immediately.
