### ISSUE TITLE
Error messages after quitting vim

### ISSUE THREAD

**Issue by xu-cheng** [lervag/vimtex#1104] opened 2018-04-11 14:39 UTC
## Summary 

Compiling any LaTeX file then quitting vim will show error messages:
```
Error detected while processing function <SNR>38_callback_nvim_output:
line    2:
E482: Can't open file /var/folders/sj/_8p89zdd35s1hfxlxy9f2w180000gn/T/nvimu3QuzW/1 for writing: no such file or directory
E482: Can't open file /var/folders/sj/_8p89zdd35s1hfxlxy9f2w180000gn/T/nvimu3QuzW/1 for writing: no such file or directory
```

## Environment

* OS: macOS
* Neovim 0.2.3 (HEAD f96d99a)
```
NVIM v0.2.3-dev
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180411-21059-19wrpqe/build/config -I/tmp/neovim-20180411-21059-19wrpqe/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180411-21059-19wrpqe/build/src/nvim/auto -I/tmp/neovim-20180411-21059-19wrpqe/build/include
Compiled by chengxu@Chengs-MacBook-Pro.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-f96d99a_1/share/nvim"

Run :checkhealth for more info
```

## Steps to reproduce problem

1. Minimal `vimrc` file:
```vim
let s:vimtex_path = '~/.local/share/nvim/plugged/vimtex'
set nocompatible

let &rtp = s:vimtex_path . ',' . &rtp
let &rtp .= ',' . s:vimtex_path . '/after'

let g:vimtex_compiler_method = 'latexmk'

filetype plugin indent on
syntax enable
```

2. Open any LaTeX file, compile it by `:VimtexCompile`.
3. Quit vim. 
4. You can find the above error messages.

**Comment by lervag** [comment] 2018-04-11 15:42
Interesting. What does `:chechhealth` report for Vimtex?

Note: You can remove the `g:vimtex_compiler_method` from your minimal vimrc file, as that is a default setting. Also, I don't quite see why you define the `s:vimtex_path` in the minimal vimrc file, as it only complicates things (although I agree the vimrc is still minimal in the meaningful sense).

The problem seems to be that the temporary file that neovim wants to save some output logs to (i.e. from the latexmk process started by vimtex) does not exist and can not be written to. The filename is created by `tempfile()`.

**Comment by clason** [comment] 2018-04-11 15:48
I observe the same behavior on Linux as well (with a different temp path, of course); `:checkhealth` shows all green. Note that `VimtexCompile` must still be running when quitting; if you stop before quitting, no error appears.

**Comment by xu-cheng** [comment] 2018-04-11 15:49
> What does :chechhealth report for Vimtex?

```
health#vimtex#check
========================================================================
## vimtex
  - OK: Vim version should have full support!
  - OK: Skim viewer should work!
  - OK: Compiler should work!
```

> Also, I don't quite see why you define the s:vimtex_path in the minimal vimrc file, as it only complicates things 

Because it is easy for me to locate vimtex as all I have to do is to run `vim -u /path/to/init.vim ...`.

As for the issue, the following patch will silent the messages. However, I am not sure whether it is the right fix. It seems to me that the missing temporary file is caused by a much deeper bug. 

```
diff --git a/autoload/vimtex/compiler/latexmk.vim b/autoload/vimtex/compiler/latexmk.vim
index 4e8ba83..6506e24 100644
--- a/autoload/vimtex/compiler/latexmk.vim
+++ b/autoload/vimtex/compiler/latexmk.vim
@@ -523,7 +523,7 @@ endfunction
 
 " }}}1
 function! s:callback_nvim_output(id, data, event) abort dict " {{{1
-  if !empty(a:data)
+  if !empty(a:data) && filewritable(self.output)<`2`>
     call writefile(filter(a:data, '!empty(v:val)'), self.output, 'a')
   endif
 endfunction
```

**Comment by lervag** [comment] 2018-04-11 15:50
In principle, the same stuff should happen with Vim. Is the bug present there as well?

**Comment by clason** [comment] 2018-04-11 15:52
No, it doesn't. So it's either a `neovim` or `neovim-remote` bug (or feature...)

**Comment by xu-cheng** [comment] 2018-04-11 15:54
I cannot test in the vim because:
```
vimtex: Can't use callbacks without +clientserver
        Callback option has been disabled.
```

Also, the function is called `callback_nvim_output`. So will the relevant codes be run by the vim (not neovim)?

**Comment by lervag** [comment] 2018-04-11 16:00
I've tried to reproduce on Arch Linux, see the `test/issues/1104` files. But for me, it works as expected.

However, I think it should be safe to add the `filewritable()` and so I've pushed a fix.

@clason: Can you verify that this also fixes the problem on your side?

**Closed** 2018-04-11 16:01 UTC

**Comment by lervag** [comment] 2018-04-11 16:02
@xu-cheng You are right things are handled different in Vim, and so it is not that relevant to compare.

**Comment by clason** [comment] 2018-04-11 16:06
Yes, that fixes it for me. (If it is indeed a race condition, your `minimal.tex` might be *too* minimal...)

**Comment by lervag** [comment] 2018-04-11 16:10
Yes, perhaps. But it seems fixed now, so I'm happy :)

**Comment by clason** [comment] 2018-04-11 16:13
Me, too, thanks for the quick fix! (And thanks to @xu-cheng, too -- this has been a minor but persistent niggle for me for a while ;))
