### ISSUE TITLE
vimtex#misc#wordcount into vim-airline

### ISSUE THREAD

**Issue by tunaboy** [lervag/vimtex#2228] opened 2021-10-30 17:56 UTC
This is not really an issue (with vimtex), but I just did a pull request on vim-airline so that when you are in a TeX document (and vimtex is active), it uses the `vimtex#misc#wordcount` function to report the wordcount.  It was a pretty simple fix, and it seems to work well as far as I've checked it.  I have an abstract I'm working on that I need to get under 500 words, and brevity is not my strong suit.  I can point you to my forked repository of vim-airline, so you can see it if you'd like to.  

Thanks much for this plugin.  I obviously use it a lot and love it.

Cheers 
Mike

**Comment by lervag** [comment] 2021-10-30 18:44
> This is not really an issue (with vimtex), but I just did a pull request on vim-airline

I'll take the liberty of linking it: https://github.com/vim-airline/vim-airline/pull/2454

> so that when you are in a TeX document (and vimtex is active), it uses the `vimtex#misc#wordcount` function to report the wordcount. It was a pretty simple fix, and it seems to work well as far as I've checked it.

Cool; it seems like a useful use of this feature. Be aware that it may be slow for large documents - I don't use it much, so I'm not quite sure how slow it gets (perhaps it's not a big deal).

> I have an abstract I'm working on that I need to get under 500 words, and brevity is not my strong suit.

Brevity is hard, but it is a good thing to aim for!

> Thanks much for this plugin. I obviously use it a lot and love it.

Thank you for the kind words :)

**Comment by lervag** [comment] 2021-10-30 18:45
Also, I'll take the liberty of closing this issue, as there is no actions needed on the VimTeX side.

**Closed by lervag** 2021-10-30 18:45 UTC
Labels: enhancement

**Comment by tunaboy** [comment] 2021-11-01 04:07
thanks much.  I'm trying to clean up the git repo so it's cleaner, and hopefully it will get pulled into the main version(of vim-airline).  

Mike

**Comment by lervag** [comment] 2021-11-01 08:59
No problem, glad to help :)

**Comment by OrangeRoof** [comment] 2021-11-11 21:37
hello, I'm experiencing general {insert,normal}-mode performance degradation with this enchantment and submitted an [issue](https://github.com/vim-airline/vim-airline/issues/2461) to vim-airline. I suspect if action is taken, vim-airline will just rollback the commit as it is easiest. This issue seems the best place to discuss whether vimtex can/should be enhanced instead. Please let me know if I should open a new issue!

The [airline issue](https://github.com/vim-airline/vim-airline/issues/2461) says using `vimtex#misc#wordcount` is the root cause of lagginess; looking at the profiling of `vimtex#misc#wordcount` gives:
<details>
<summary> Excerpt of profiling character deletion using `x` on 300 word lorem ipsum tex file under airline+vimtex </summary>

```
FUNCTION  vimtex#misc#wordcount()
    Defined: ~/.vim/bundle/vimtex/autoload/vimtex/misc.vim:41
Called 87 times
Total time:   5.009151
 Self time:   0.007402

count  total (s)   self (s)
   87              0.000215   let l:opts = a:0 > 0 ? a:1 : {}
                            
   87              0.000327   let l:range = get(l:opts, 'range', [1, line('$')])
   87              0.000220   if l:range == [1, line('$')]
   87              0.000115     let l:file = b:vimtex
                              else
                                let l:file = vimtex#parser#selection_to_texfile({'range': l:range})
   87              0.000033   endif
                            
   87   0.002554   0.001102   let l:cmd = 'texcount -nosub -sum ' . (get(l:opts, 'count_letters') ? '-letter ' : '') . (get(l:opts, 'detailed') ? '-inc ' : '-q -1 -merge ') . g:vimtex_texcount_custom_arg . ' ' . vimtex#util#shellescape(l:file.base)
   87   5.001788   0.001491   let l:lines = vimtex#jobs#capture(l:cmd, {'cwd': l:file.root})
                            
   87              0.000498   if l:file.base !=# b:vimtex.base
                                call delete(l:file.tex)
   87              0.000089   endif
                            
   87              0.000200   if get(l:opts, 'detailed')
                                return l:lines
   87              0.000059   else
   87              0.001728     call filter(l:lines, 'v:val !~# ''ERROR\|^\s*$''')
   87              0.000338     return join(l:lines, '')
                              endif
```
</details>

So it looks like calls to `texcount` are slowing down the editing. I have 
```
~: texcount --version
TeXcount version 3.1.1, 2018 Oct 28.
```
which seems to be included with `texlive-core 2021`. Running it directly indicates `texcount` itself is just slow:
```
$ time texcount -nosub -sum test.tex
**
Sum count: 353
**
texcount -nosub -sum test.tex  0.05s user 0.01s system 98% cpu 0.059 total
```
Assuming `vim-airline` tries to get wordcount on every keystroke or character deletion, 0.05s quickly adds up (100 keystrokes have a total 5 second delay!). From the above I would conclude that `vimtex#misc#wordcount` should not be incorporated into `vim-airline`. Please let me know if further investigation / improvement directions are possible!

**Comment by lervag** [comment] 2021-11-11 21:41
It's not really very surprising, I think. But I don't know how to improve this, because the delay is not from VimTeX, but from running the texcount utility.

I believe one possibility would be to avoid running the `vimtex#misc#wordcount` often; only run it after every `BufWrite` would probably be enough, for instance. But I don't know how to do this in vim-airline, so that will have to be a task for someone else.

I don't think this is a VimTeX issue, because VimTeX does not provide `vimtex#misc#wordcount` for the purpose of being called often as part of a statusline plugin.

**Comment by anntzer** [comment] 2021-11-29 09:55
I notice that the slowdown occurs even if texcount is not actually installed: it seems like just shelling out a subprocess and getting a "command not found" has significant overhead.
While I agree this is mostly a problem on airline's side (that can be worked around via `airline#extensions#vimtex#wordcount`), perhaps vimtex could help a bit by first caching the value of `executable('texcount')` the first time `vimtex#misc#wordcount` is called, and immediately returning an appropriate error if texcount is not installed?

**Comment by lervag** [comment] 2021-11-29 21:24
> I notice that the slowdown occurs even if texcount is not actually installed: it seems like just shelling out a subprocess and getting a "command not found" has significant overhead.

I think this overhead depends on the system, but yes, there is likely an overhead here.

> While I agree this is mostly a problem on airline's side (that can be worked around via `airline#extensions#vimtex#wordcount`),

Most definitely. The function was never created for this particular purpose.

> perhaps vimtex could help a bit by first caching the value of `executable('texcount')` the first time `vimtex#misc#wordcount` is called, and immediately returning an appropriate error if texcount is not installed?

Caching the value of `executable('texcount')` is not a good idea. Imagine we do this caching, then a user get's a warning because the utility is not available. The user installs `texcount`, but the cache means it will not be recognized by VimTeX before you clear the cache. Most users will not recognize that this is necessary.

From my point of view, the current implementation works as intended. Still, I would not mind to make updates that help speed things up, but if so, it would be very helpful with some minimal examples and benchmarks.
