### ISSUE TITLE
VimtexInfo crashes Vim with a segmentation violation if issued while command-line window is open

### ISSUE THREAD

**Issue by Aster89** [lervag/vimtex#2638] opened 2023-02-19 17:22 UTC
### Description

Calling `:VimtexInfo` when the command-line window is open causes a SegV in Vim.

### Steps to reproduce

1. Open Vim on a TeX file
2. hit <kbd>q</kbd><kbd>:</kbd>
3. execute `:VimtexInfo`

### Expected behavior

Not sure, maybe the command-line window should close without exuting anything, or it should stay open, or an error could be thrown.

### Actual behavior

Vim crashes with a segmentation violation.

This can be pretty annoying, especially for those who `:w`rite very frequently even for experimenting relying on [undotree](https://github.com/mbbill/undotree) or similar to never loose track of what they are doing. Such a bug would basically result in the entire undo tree to be thrown away and the file left in its latest saved state.

### Do you use a latexmkrc file?

Yes, but I suspect it's irrelevant, I'm not making anything.

### VimtexInfo

```yaml
That's the point.
```

**Comment by lervag** [comment] 2023-02-19 18:05
But you can do `:VimtexInfo` without the command-line window? What's the output then?

**Comment by Aster89** [comment] 2023-02-19 18:35
Yes, it simply shows
```
System info:
  OS: Arch Linux
  Vim version: VIM 9.0 (1-1302)
  Has clientserver: true
  Servername: VIM2

VimTeX project: main
  base: main.tex
  root: /home/enrico/deleteme
  tex: /home/enrico/deleteme/main.tex
  main parser: current file verified
  document class: book
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```

**Comment by lervag** [comment] 2023-02-19 22:34
Thanks. I've tried to reproduce this, but I can't. I'm on Arch Linux with the same Vim version. I used the following minimal `test.vim` (if you test, make sure to adjust the runtimepaths if necessary):

```vim
" test.vim
set nocompatible
set runtimepath^=~/.local/plugged/vimtex
set runtimepath+=~/.local/plugged/vimtex/after
filetype plugin indent on
syntax enable
```

I did this:

* `vim -u test.vim test.tex`
* `q:` to open command-line window
* `iVimtexInfo<cr>` -- info is displayed as expected

**Comment by Aster89** [comment] 2023-02-19 22:58
That's not my repro. Sorry for not being clear. What I mean is <kbd>q</kbd><kbd>:</kbd><kbd>:</kbd><kbd>V</kbd><kbd>i</kbd><kbd>m</kbd><kbd>t</kbd><kbd>e</kbd><kbd>x</kbd><kbd>I</kbd><kbd>n</kbd><kbd>f</kbd><kbd>o</kbd><kbd>CR</kbd>, that is, you open the command-line window, but then execute `VimtexInfo` from the command-line, **not the command-line window**.

**Comment by lervag** [comment] 2023-02-20 08:19
Ah, I see! I can reproduce this now with the minimal example. I'll look into it, but I am quite sure this is not a VimTeX issue.

**Comment by lervag** [comment] 2023-02-20 08:26
I'll try and make a minimal version of the `:VimtexInfo` command and see if I can reproduce this without VimTeX. Then I can open an issue on vims github page. Not sure when I get the time, but we'll keep the issue open.

**Comment by lervag** [comment] 2023-02-20 09:34
I can reproduce with this very minimal example:

```Vim
" test.vim
command! -buffer Test edit Test
```

Now `vim -u test.vim` and `q::Test<cr>` reproduces the segfault. If we remove `-buffer`, we get the relevant error message: 

```
E11: Invalid in command-line window; :q<CR> closes the window: edit Test
```

I'm closing this issue because it is not an issue with VimTeX. I'm not sure if anyone would consider this an issue at all, because this is "abusing" the command-line window. That is, why would you ever want to do this anyway? The command-line window is not something you should keep visible; you use it when you need to and close it when you are finished..?

**Closed by lervag** 2023-02-20 09:34 UTC
Labels: bug

**Comment by lervag** [comment] 2023-02-20 09:41
I've opened an issue here: https://github.com/vim/vim/issues/12029
