### ISSUE TITLE
Change the path to pdf opened by the viewer

### ISSUE THREAD

**Issue by ytterbium** [lervag/vimtex#1717] opened 2020-06-07 18:28 UTC
First, thanks for your great plugin.

I configured latexmk with a gobal latexmkrc to produce documents in a `./output` directory. It works well, and after a compilation my pdf viewer (zathura) is opened with the output pdf.  

However, when I use the command `:VimtexView`, I obtain the error `Viewer cannot read PDF file`, which is quite normal since the viewer try to open `output_file.pdf` instead of `output/output_file.pdf`. 

I would like to make the viewer open the correct file, so that I could use forward search. But I didn't find in the doc a way to indicate to the viewer where is the output pdf. I suppose that some zathura_hook could be useful, but I don't understand them. 

Is there a simple configuration to view the correct file that I missed ?

I use the following viewer config:

 ```vim
 let g:vimtex_view_method = 'zathura'
  ```

**Comment by lervag** [comment] 2020-06-07 20:06
> First, thanks for your great plugin.

Happy you like it!

> I configured latexmk with a gobal latexmkrc to produce documents in a `./output` directory. It works well, and after a compilation my pdf viewer (zathura) is opened with the output pdf.

Vimtex should pick up on this. After you open your LaTeX document, do `:VimtexInfo`. It should show some info about your project and how vimtex parses it, similar to this:

```
vimtex project: main
  base: main.tex
  ...
  source files:
    main.tex
    ...
  compiler: latexmk
    backend: nvim
    output: /tmp/nvimycpaMd/2
    configuration: 
      continuous: 1
      callback: 1
      build_dir: ./output
      ...
```

Note, the output contains more lines, but it should have a line that contains `build_dir`, which should pick up on the setting from your `.latexmkrc`.

> However, when I use the command `:VimtexView`, I obtain the error `Viewer cannot read PDF file`, which is quite normal since the viewer try to open `output_file.pdf` instead of `output/output_file.pdf`.

In fact, this should also simply work. After you i) open LaTeX file, ii) compile it (e.g. `\ll`), iii) view with e.g. `\lv`, then you can again use `:VimtexInfo` (or `\li`) to find info on the viewer, similar to:

```
  viewer: Zathura
    xwin id: 39845891
    process: 
      pid: -
      cmd: zathura -x "nvr --servername /tmp/nvimHOjhir/0 --remote-expr \"vimtex#view#reverse_goto(%{line}, '%{input}')\""  '/home/usr/path/main.pdf' >/dev/null 2>&1 &
```

It would be useful to know how this info looks.

**Comment by ytterbium** [comment] 2020-06-08 06:46
> Vimtex should pick up on this. After you open your LaTeX document, do :VimtexInfo. It should show some info about your project and how vimtex parses it, similar to this

I have no `build_dir` line in the VimtexInfo (I did not find how to copy the output, when I move in the :VimtexInfo window, I am redirected to the main window.
The problem may come from the fact I do not use a project specific `.latexmkrc`, but a global one in `~/.config/latexmk/latexmkrc`. So if vimtex try to parse the latexmkrc, it might not find the correct one. 

>In fact, this should also simply work. After you i) open LaTeX file, ii) compile it (e.g. \ll), iii) view with e.g. \lv, then you can again use :VimtexInfo (or \li) to find info on the viewer, similar to:

The only information I have about the viewer is 
```
viewer: Zathura
    xwin id: 0
```

**Comment by lervag** [comment] 2020-06-08 07:29
> I have no `build_dir` line in the VimtexInfo (I did not find how to copy the output, when I move in the :VimtexInfo window, I am redirected to the main window)

The `:VimtexInfo` window should not close just by moving. But pressing `q` would close it.

> The problem may come from the fact I do not use a project specific `.latexmkrc`, but a global one in `~/.config/latexmk/latexmkrc`. So if vimtex try to parse the latexmkrc, it might not find the correct one.

No, vimtex should read this file as well, as long as your `$XDG_CONFIG_HOME` variable is set. I'll make a minor update to use `~/.config` for `XDG_CONFIG_HOME` if it is not set. Perhaps that should fix things?

> The only information I have about the viewer is
> 
> ```
> viewer: Zathura
>     xwin id: 0
> ```

Yes, you need to do `\lv` or `:VimtexView` for the `cmd` entry to show up.

**Comment by ytterbium** [comment] 2020-06-08 08:04
> The :VimtexInfo window should not close just by moving. But pressing q would close it.

Well, it is quite strange. I can effectively move in the :VimtexInfo window with the hjkl motion key, but when I use the arrow key, this window is closed and I am back in editing mode with a A/B/C or D typed. 

> No, vimtex should read this file as well, as long as your $XDG_CONFIG_HOME variable is set. I'll make a minor update to use ~/.config for XDG_CONFIG_HOME if it is not set. Perhaps that should fix things?

Effectively my `$XDG_CONFIG_HOME` was not set. However, this fresh update doesn't seem to solve the issue. 

> Yes, you need to do \lv or :VimtexView for the cmd entry to show up.

Even after a `:VimtexView` (which does not work and raise the issue Viewer cannot read pdf file), I get the following VimtexInfo
```
  compiler: latexmk
    backend: jobs
    output: /tmp/vNcRiRr/3
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -lualatex
  viewer: Zathura
    xwin id: 0


```

**Comment by lervag** [comment] 2020-06-08 08:37
No, you misunderstand. I want you to provide _me_ the minimal configuration so that _I_ can reproduce your problem. That way I might be able to figure out what's wrong. And I want the _minimal_ configuration, because I'm _not_ interested in copying your full config. So, please provide a `minimal.vim` file, a minimal latex file, the minimal `latexmkrc` (and where you put it), and the steps required to reproduce your issue.

**Comment by ytterbium** [comment] 2020-06-08 09:11
Sorry for the misunderstanding. 

~/tmp/minimal.vim : 
```vim
  set nocompatible
  let &runtimepath  = '~/tmp/vimtex,' . &runtimepath
  let &runtimepath .= ',~/tmp/vimtex/after'
  filetype plugin indent on
  syntax enable

  let g:vimtex_view_method = 'zathura'
```

~/tmp/minimal.tex : 
```tex
  \documentclass{minimal}
  \begin{document}
  Hello world!
  \end{document}
```

.config/latexmk/latexmkrc
```
$out_dir = "./output";
$pdf_mode = 4;
```

Step to reproduce : 

1. `cd ~/tmp` ; ` vim --servername VIM -u minimal.vim minimal.tex`
2. `:VimtexCompile`
3. `:VimtexView`
Error: `vimtex: Viewer cannot read PDF file
~/tmp/minimal.pdf`

**Comment by lervag** [comment] 2020-06-08 10:18
I think it should work now, please test again.

**Closed** 2020-06-08 10:17 UTC
Labels: bug

**Comment by ytterbium** [comment] 2020-06-08 11:26
Yes ! 
All is fine now.

Thanks a lot.

**Comment by lervag** [comment] 2020-06-08 11:30
No problem, thanks for raising the issue and by that help improving vimtex!
