### ISSUE TITLE
Bad indentation in item list

### ISSUE THREAD

**Issue by arnegoeteyn** [lervag/vimtex#949] opened 2017-08-25 17:14 UTC
### Explain the issue

Whenever I am writing a list of \item it gets indented after every new \item. What I would like is
```
\begin{itemize}
    \item
        \item
            \item
\end{itemize}

```
But what I would like to achieve is 
```
\begin{itemize}
    \item
    \item
    \item
\end{itemize}
```

When I dont load the vimtex plugin I get the intended behaviour. The item gets indented at first but as soon as I press space the indentation fixes itself.

### Minimal working example

Please provide a minimal working LaTeX example, e.g.

```tex
\documentclass[12pt]{article}
\begin{document}
\maketitle

\section{Materiaal}
\label{sec:materiaal}
\begin{itemize}
	\item
		\item 
			\item
\end{itemize}



\end{document}

```

### Minimal vimrc file

```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'lervag/vimtex'
Plug 'matze/vim-tex-fold'
call plug#end()

```

**Comment by lervag** [comment] 2017-08-25 17:41
Given your example, what happens if you do `=ie` inside the `itemize` environment? Or `gg=G` from anywhere? Does it yield correct indentation?

This works well for me, also with your supplied minimal example. Could you please consider to use a more minimal vimrc file? E.g. something like this:

```vim
set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
let &rtp = '~/.vim/bundle/vim-tex-fold,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
```

Does the problem exist also if you do not load `vim-tex-fold`? (If so, _why_ do you include it in the minimal vimrc file?!)

I assume that you've understood that you must start vim like this to use the minimal vimrc file: `vim -u minivimrc minimal.tex` (or `nvim` or `gvim`, whatever is applicable).

**Comment by arnegoeteyn** [comment] 2017-08-26 09:59
`=ie `and` gg=G` yield correct indentations. I forgot to remove the` vim-tex-fold` from my minimal vimrc. But removing it doesnt yield correct indentation.

However using your minimal vimrc, I get the correct indentation. Can this be an issue with how the plugin is loaded?

**Comment by lervag** [comment] 2017-08-26 10:51
I suspect that the problem is your configuration, which is why I ask you to
create a minimal vimrc file where the problem still occurs. You should keep
the settings from your vimrc file that are relevant.

If you do not understand what I mean, let me know and I will try to explain
in more detail.

**Comment by arnegoeteyn** [comment] 2017-08-26 11:00
If I start from the minimal vimrc you have provided everything works as intended. But if I load your plugin trough `Plug 'lervag/vimtex'` the indentation gets messed up. So the vimrc that doesn't work looks like this
```vim
set nocompatible

call plug#begin('~/.local/share/nvim/plugged')
Plug 'lervag/vimtex'
call plug#end()

filetype plugin indent on
syntax enable
```

If this isn't what you're asking for then could you explain it in more detail?

**Comment by clason** [comment] 2017-08-26 16:52
As a weak data point, I seem to recall that one of the issues I reported a while back also occurred only if `vimtex` was loaded via `vim-plug` but not as in the `vimrc` template. (I was using the standard plugin directory, too; i.e., just `call plug#begin()`.)

**Comment by lervag** [comment] 2017-08-27 19:57
Strange. As you can see, I've added test files similar to what you've explained. However, everything works as expected for me both for Vim and neovim. I do `nvim -u minivimrc minimal.tex` (and `vim -u ...`), then I go to the `itemize` env and add three `\item`s. They align as expected.

**Comment by mnuke** [comment] 2017-09-24 23:36
I am also using `vim-plug` and run into the same issue with indentations in vimtex. As well, a strange issue happens when using alignment in equations that don't have a left side. Initially, after entering `&`, the equations align to the `&` in the line above, but on each indent (such as `=`), the indentation is pushed left.

In the gif below, I am just hitting `=` and the equation moves right each time
![vimtex-issue](https://user-images.githubusercontent.com/3391297/30787812-8d820ede-a15f-11e7-8d29-df35315d5cd9.gif)

**Comment by andymass** [comment] 2017-09-25 00:32
@mnuke Can you report the output of `:set shiftwidth? tabstop? softtabstop? smarttab? expandtab? preserveindent? copyindent?`   ?

I have a hunch that your specific problem is caused by vimtex not treating tabs correctly when computing positions.

**Comment by mnuke** [comment] 2017-09-25 03:24
shiftwidth=4
  tabstop=4
  softtabstop=0
nosmarttab
noexpandtab
nopreserveindent
nocopyindent

**Comment by andymass** [comment] 2017-09-25 06:01
@mnuke.  Thanks.  I think the following change would fix your particular issue:

```vim
diff --git a/indent/tex.vim b/indent/tex.vim
index 44317be..3306fda 100644
--- a/indent/tex.vim
+++ b/indent/tex.vim
@@ -45,7 +45,8 @@ function! VimtexIndent(lnum) " {{{1
   if get(g:, 'vimtex_indent_on_ampersands', 1)
         \ && l:line =~# '^\s*&'
         \ && l:prev_line =~# '\\\@<!&.*'
-    return indent(a:lnum) + match(l:prev_line, '\\\@<!&') - stridx(l:line, '&')
+    return strdisplaywidth(strpart(l:prev_line, 0,
+      \ match(l:prev_line, '\\\@<!&')))
   endif
```

I am not sure what that code was originally supposed to do.  To me, it looks like `indent()-stridx(...)` either cancel each other out, or when there are tabs computes the `&` column incorrectly.  This piece of code also doesn't "Align on ampersands" as the comment states, but only when they are the first character.

`match()`, `len()`, etc. are used throughout the indent code, so more changes are necessary, and this all should definitely be a separate issue.  Would you mind opening one so @lervag can keep track?

**Comment by lervag** [comment] 2017-09-25 06:26
Thanks, @andymass! It would be nice with a new issue, and please refer to this issue when you open a new one.

**Comment by lervag** [comment] 2017-09-25 06:28
@clason I'm closing this, as I still can't reproduce the issue. I'm sorry for the inconvenience. If you would be able to somehow refine your example or add more info that helps me reproduce, then I will be glad to try again.

**Closed by lervag** 2017-09-25 06:28 UTC

**Comment by mnuke** [comment] 2017-10-06 22:02
@andymass that did indeed fix it! thank you!

**Comment by xiamaz** [comment] 2018-06-28 16:55
I have the same issue with the wrong indent of item files. I am using neovim 0.3.0. I tested the minimal nvimrc provided.

**Comment by alexwms** [comment] 2019-06-09 21:33
@arnegoeteyn Did you ever find a fix to this? I am having the same issue.

**Comment by mnoukhov** [comment] 2019-06-10 03:26
@alexwms andymass' fix worked for me and it worked out of the box after merging. Are you using the latest version? can you give a minimal .vimrc to reproduce?

**Comment by alexwms** [comment] 2019-06-10 21:05
I am using macvim and I installed Vimtex through vim-plug (I am not sure how to check the version number).

Using this minimal .vimrc:
```
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

nnoremap q :qall!<cr>

let g:vimtex_view_automatic = 0

silent edit main.tex
```

and the command `vim --servername VIM -u .min_vimrc main.tex` (where `vim` is an alias for `mvim`), produces:
```
Hello world!
\begin{itemize}
	\item blah
		the next thing I type

\end{document}
```
I cloned vimtex from GitHub, so it is the newest code. The issue with `&` is indeed fixed.

**Comment by lervag** [comment] 2019-06-10 21:15
@alexwms @mnoukhov I'll just mention that if you find something that you think is wrong, please open a new issue and describe it there. It will make it much easier for me to work with, since this thread is so long.

**Comment by alexwms** [comment] 2019-06-10 22:01
I think I posted too early (Ignore the output that I got above, I believe I accidentally produced it with my regular .vimrc file. Sorry.). I am now having trouble running the minimal example. I have the minimal vimrc file `.min_vimrc` in my home directory (with the same contents as above). 

Running either `vim --servername VIM -u .min_vimrc main.tex` or `vim -u .min_vimrc main.tex` opens `main.tex`. When I issue the command `:VimtexCompile`, I get `E492: Not an editor command`. However, `:set runtimepath` shows that `~/.vim/bundle/vimtex` and `~/.vim/bundle/vimtex/after` are in the runtimepath. 

If you could help me to get this working I would be most grateful (I am new to vim and I'm guessing there is something simple here that I am missing).

**Comment by alexwms** [comment] 2019-06-11 16:07
Ok, for some reason when I woke up this morning everything worked just fine with my regular .vimrc file (no indent issue). I must have done something without realizing it yesterday that made everything ok. Thank you for taking the time to respond to me.

**Comment by mnoukhov** [comment] 2019-06-11 18:17
Must have been an update or something. Glad it all works!

On Tue, Jun 11, 2019 at 12:09 PM alexwms <notifications@github.com<mailto:notifications@github.com>> wrote:

Ok, for some reason when I woke up this morning everything worked just fine with my regular .vimrc file (no indent issue). I must have done something without realizing it yesterday that made everything ok. Thank you for taking the time to respond to me.

**Comment by luiggiroal** [comment] 2020-07-17 08:19
@alexwms @arnegoeteyn I fixed that issue about the '\item' label just commenting the following line(194) from the file with path `~/.config/nvim/autoload/plugged/vimtex/indent/tex.vim`:

`let l:ind += s:sw*((a:prev =~# s:envs_item)    && (a:cur  !~# s:envs_enditem))`

**Comment by lervag** [comment] 2020-07-18 07:23
> @alexwms @arnegoeteyn I fixed that issue about the '\item' label just commenting the following line(194) from the file with path `~/.config/nvim/autoload/plugged/vimtex/indent/tex.vim`:

This is not a proper fix and will break indentation in other ways. Please, if you have an issue, please open a new post with a description and a minimal example.
