### ISSUE TITLE
Some Compilation issues with ctex.

### ISSUE THREAD

**Issue by lin-behappy** [lervag/vimtex#2823] opened 2023-11-01 22:34 UTC
### Description

It is my first time use vimtex, some of the problems encountered as follows:

1.  `\ll` compile the `minimal.tex` and view in sumatraPDF.  then I add some word and save the `.tex`, sumatraPDF won't refresh the pdf, it need to close the pdf and open again to see the changes.

2. if  `minimal.tex`  use `\input{}` path has Chinese text like `\input{files/中文路径/中文文件名}`, then I have changed the `中文文件名.tex` and compile the `minimal.tex` it won't changed the pdf. I have tried compile it several times, but the pdf won't change. But if I add some word (like add blank line) in minimal.tex and compile it the changes in `中文文件名.tex` could be shown in pdf.

### Steps to reproduce

here is the minimal.tex

```tex
%! TEX TS-program = xelatex
\documentclass{ctexbook}
\begin{document}

\input{files/中文路径/中文文件名}
\end{document}
```

here is the minimal `.lua`

```lua
vim.g.vimtex_quickfix_mode=0
vim.g.vimtex_view_general_viewer = "SumatraPDF"
vim.g.vimtex_view_general_options = "-reuse-instance -forward-search @tex @line @pdf"
```

### Do you use a latexmkrc file?

no

### VimtexInfo
There is some messy code in OS: line and I can't copy it; like `<be><d2>□<b0>..`, perhaps is my Chinese name.

```yaml
System info:
 OS: DESKTOP-QO5KIHH (Microsoft Windows 10 …
 Vim version: NVIM v0.9.4
  Has clientserver: true
  Servername: \\.\pipe\nvim.5716.0

VimTeX project: minimal
  base: minimal.tex
  root: C:\tmp\minimal
  tex: C:\tmp\minimal\minimal.tex
  main parser: current file verified
  document class: ctexbook
  packages: CJK CJKpunct CJKspace CJKutf8 MULEenc ctexhook ctexpatch everysel everysel-2011-10-28 expl3 fix-cm fontenc hyperref ifpdf iftex inputenc l3keys2e xparse xparse-2020-10-01 zhnumber
  source files:
    minimal.tex
    files/中文路径/中文文件名.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 13
      output: C:\Users\JehuL\AppData\Local\Temp\nvim.0\QuStdN\0
      cmd: set max_print_line=2000 & latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -pvctimeout- -view=none -e "$compiling_cmd = ($compiling_cmd ? $compiling_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_compiling'" -e "$success_cmd = ($success_cmd ? $success_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_success'" -e "$failure_cmd = ($failure_cmd ? $failure_cmd . ' ^& ' : '') . 'echo vimtex_compiler_callback_failure'" "minimal.tex"
      pid: 11664
  viewer: General
    job: 
      pid: -
      cmd: SumatraPDF -reuse-instance -forward-search "C:\tmp\minimal\minimal.tex" 1 "C:\tmp\minimal/minimal.pdf"
  qf method: LaTeX logfile
```

**Comment by lervag** [comment] 2023-11-02 16:38
> 1. `\ll` compile the `minimal.tex` and view in sumatraPDF.  then I add some word and save the `.tex`, sumatraPDF won't refresh the pdf, it need to close the pdf and open again to see the changes.

Does this happen for _any_ minimal file, even something like this?

```tex
\documentclass{minimal}
\begin{document}
Hello World!
\end{document}
```

> 2. if `minimal.tex` use `\input{}` path has Chinese text like `\input{files/中文路径/中文文件名}`, then I have changed the `中文文件名.tex` and compile the `minimal.tex` it won't changed the pdf. I have tried compile it several times, but the pdf won't change. But if I add some word (like add blank line) in minimal.tex and compile it the changes in `中文文件名.tex` could be shown in pdf.

I don't have any idea about this, sorry. But, let us start by simplifying. That is, do you have the same problem if you _don't_ use Chinese characters? E.g., if you try this minimal project:

```tex
%%%% main.tex
%! TEX TS-program = xelatex
\documentclass{ctexbook}
\begin{document}

\input{other}
\end{document}

%%%% other.tex
Hello \LaTeX World.
```

This should be similar to the example you provided, except it does not use subdirectories and it does not use Chinese characters.

> here is the minimal `.lua`

That is not a minimal Lua script; it is only the configuration for VimTeX in Lua. Notice that the SumatraPDF configuration should not really be necessary, as it should already by defined by default on Windows.

A minimal Lua script for testing would look something like this:

```lua
vim.opt.runtimepath:prepend "~/.local/plugged/vimtex"
vim.opt.runtimepath:append "~/.local/plugged/vimtex/after"
vim.cmd[[filetype plugin indent on]]

vim.g.vimtex_quickfix_mode = 0
vim.g.vimtex_view_general_viewer = "SumatraPDF"
vim.g.vimtex_view_general_options = [[-reuse-instance -forward-search @tex @line @pdf]]
```

You would save that as `test.lua`, then start neovim from a terminal with `nvim --clean -u test.lua /path/to/file.tex`. Notice that the `runtimepath` lines should be changed to reflect the location on your system.

> ### VimtexInfo
> 
> There is some messy code in OS: line and I can't copy it; like `<be><d2>□<b0>..`, perhaps is my Chinese name.

Thats probably no problem; but I would be surprised if it was your name though.

**Comment by lin-behappy** [comment] 2023-11-02 21:23
@lervag
>  ```tex 
> \documentclass{minimal}
> \begin{document}
> Hello World!
> \end{document}
> ```

Oh, it works right, but if I change the `\documentclass{minimal}` to 
```tex 
%! TEX TS-program = xelatex
\documentclass{ctexbook}
```

it have the same problem.


> ```tex
> %%%% main.tex
> %! TEX TS-program = xelatex
> \documentclass{ctexbook}
> \begin{document}
> 
> \input{other}
> \end{document}
> 
> %%%% other.tex
> Hello \LaTeX World.
> ```

And this works right too, and change the `\input{other}` to `\input{files/中文路径/inputfile}`  it also works right. I guess it can't have Chinese characters in filename.  But as the problem mention above because the `documentclass` is
```tex 
%! TEX TS-program = xelatex
\documentclass{ctexbook}
```

It need to close the pdf and open again to show change in sumatraPDF

> ```lua
> vim.opt.runtimepath:prepend "~/.local/plugged/vimtex"
> vim.opt.runtimepath:append "~/.local/plugged/vimtex/after"
> vim.cmd[[filetype plugin indent on]]
> 
> vim.g.vimtex_quickfix_mode = 0
> vim.g.vimtex_view_general_viewer = "SumatraPDF"
> vim.g.vimtex_view_general_options = [[-reuse-instance -forward-search @tex @line @pdf]]
> ```

I was copy other blogger setting, there are lots of `.lua` files and I don't know how it work. Do I really need to change that? And I can use inverse search, does that mean `.lua` is right setting?


> > ### VimtexInfo
> > There is some messy code in OS: line and I can't copy it; like , perhaps is my Chinese name.`<be><d2>□<b0>..`
> 
> Thats probably no problem; but I would be surprised if it was your name though.

I don't know what the messy code for.

**Comment by lervag** [comment] 2023-11-04 18:01
If I understand correctly, there are two issues:

1. Any document with `ctexbook` compiled with `xelatex` for some reason does not work properly with SumatraPDF. That is, SumatraPDF does not refresh automatically and you need to close and reopen to see updates?

  Does this also happen with the following minimal document?

  ```tex
  %! TEX TS-program = xelatex
  \documentclass{ctexbook}
  \begin{document}
  Hello World.
  \end{document}
  ```

2. If you `\input{}` a file that has Chinese characters in the _filename_, then there is an issue where `latexmk` won't recompile automatically. But this issue can be fixed by avoiding Chinese characters in the filename (although Chinese characters can be used in folder names).

Can you confirm if I understand correctly?

> I was copy other blogger setting, there are lots of `.lua` files and I don't know how it work.

I know that there's a lot of stuff to learn, but I will advice that you try to avoid using configuration that you don't understand. 

> Do I really need to change that?

You need to understand what I mean when I talk about "minimal configuration/vimrc". The point is "minimal" - it is not about suggesting what your personal configuration should be, it is to present an example for reproducing issues where we remove as much as possible that is not relevant.

So, what I presented in my previous response (repeated below) was a minimal `init.lua` script for reproducing your issue. Nothing more, nothing less.

> ```lua
> vim.opt.runtimepath:prepend "~/.local/plugged/vimtex"
> vim.opt.runtimepath:append "~/.local/plugged/vimtex/after"
> vim.cmd[[filetype plugin indent on]]
> 
> vim.g.vimtex_quickfix_mode = 0
> vim.g.vimtex_view_general_viewer = "SumatraPDF"
> vim.g.vimtex_view_general_options = [[-reuse-instance -forward-search @tex
> @line @pdf]]
> ```

Of course, you don't want to use the minimal `init.lua` as your personal configuration. You want to keep most of your current neovim/Vim configuration as it is, probably. But your VimTeX specific configuration can be simplified as I mentioned. In fact, since you say you've copied things from a blog, I would suggest that you attempt to remove all VimTeX settings. I also suggest reading the VimTeX docs, or at least skim the introduction and configuration sections (`:help vimtex`).

> And I can use inverse search, does that mean `.lua` is right setting?

I don't understand what you mean with this sentence.

**Comment by lin-behappy** [comment] 2023-11-04 22:00
> If I understand correctly, there are two issues:
> 
> 1. Any document with `ctexbook` compiled with `xelatex` for some reason does not work properly with SumatraPDF. That is, SumatraPDF does not refresh automatically and you need to close and reopen to see updates?
>    Does this also happen with the following minimal document?
>    ```
>    %! TEX TS-program = xelatex
>    \documentclass{ctexbook}
>    \begin{document}
>    Hello World.
>    \end{document}
>    ```

Sorry, my English is so terrible.    I will study hard from now on.  (/▽＼)
 I have modified the `init.lua`  and `minimal.tex` as your suggestion as follow.  And yes, It also have the same problem, which need to close the pdf and reopen to see updates
> So, what I presented in my previous response (repeated below) was a minimal `init.lua` script for reproducing your issue. Nothing more, nothing less.
> 
> > ```lua
> > vim.opt.runtimepath:prepend "~/.local/plugged/vimtex"
> > vim.opt.runtimepath:append "~/.local/plugged/vimtex/after"
> > vim.cmd[[filetype plugin indent on]]
> > 
> > vim.g.vimtex_quickfix_mode = 0
> > vim.g.vimtex_view_general_viewer = "SumatraPDF"
> > vim.g.vimtex_view_general_options = [[-reuse-instance -forward-search @tex
> > @line @pdf]]
> > ```
>

**Comment by lervag** [comment] 2023-11-04 22:16
> > If I understand correctly, there are two issues:
> > 
> > 1. Any document with `ctexbook` compiled with `xelatex` for some reason does not work properly with SumatraPDF. That is, SumatraPDF does not refresh automatically and you need to close and reopen to see updates?
> >    Does this also happen with the following minimal document?
> >    ```
> >    %! TEX TS-program = xelatex
> >    \documentclass{ctexbook}
> >    \begin{document}
> >    Hello World.
> >    \end{document}
> >    ```
> 
> Sorry, my English is so terrible.

Don't worry, it seems you are doing quite fine. And you'll get better by practising!

> I have modified the `init.lua` and `minimal.tex` as your suggestion as follow. And yes, It also have the same problem, which need to close the pdf and reopen to see updates

Ok. Then I have to admit I don't have any ideas what is happening here. I tried to reproduce this on Linux with a different PDF viewer, but I don't have any problems. So, I'm not sure if I will be able to help :(

One idea though could be to try `lualatex`, e.g.

```
%! TEX TS-program = lualatex
```

Of course, this means you need to ensure you have lualatex, but since you already have xelatex I would assume you are able to do this.

**Comment by lin-behappy** [comment] 2023-11-04 23:49
> One idea though could be to try `lualatex`, e.g.
> 
> ```
> %! TEX TS-program = lualatex
> ```
> 
> Of course, this means you need to ensure you have lualatex, but since you already have xelatex I would assume you are able to do this.

Yes, it work, and also like as follow modified the `other.tex` could refresh automatically too.  
```tex
%!TEX TS-program = lualatex
\documentclass{ctexbook}
\begin{document}
Hello World.
\input{files/other}
\end{document}
```

I have tried  modified  `\input{files/other}` to `\input{files/中文路径/inputfile}` ,which has Chinese characters in, and it won't  recompile automatically. For that I will avoid using Chinese characters in filename or folder.

**Comment by lervag** [comment] 2023-11-05 09:31
Ok, it sounds like things work as expected now, then, as long as you avoid Chinese characters in your file names. I'll close the issue. 👍🏻

**Closed by lervag** 2023-11-05 09:31 UTC
Labels: bug

**Comment by lin-behappy** [comment] 2023-11-06 05:31
> Ok, it sounds like things work as expected now, then, as long as you avoid Chinese characters in your file names. I'll close the issue. 👍🏻

Ok. Thank you so much!

**Comment by lervag** [comment] 2023-11-06 20:44
Glad to help!
