### ISSUE TITLE
Forward search with zathura stills makes two windows

### ISSUE THREAD

**Issue by maksbotan** [lervag/vimtex#391] opened 2016-03-08 14:10 UTC
### Explain the issue

When vimtex compiles file with latexmk, it starts zathura with `-x` option. When latex `:VimtexView` is called, vimtex starts zathura with `--synctex-forward` and full path to pdf file. However, latexmk starts it with only basename, so zathura considers them two different documents and opens a second window.

You can see this in `ps` output (see last two lines):
```
maks      7324  7323  2 17:02 pts/0    00:00:00 perl /usr/bin/latexmk -verbose -pdf -e $pdflatex =~ s/ / -file-line-error / -pvc -e $success_cmd = "\"/home/maks/.config/nvim/neovim-remote/bin/nvr\" --servername /tmp/nvimGlqvz9/0 --remote-expr \"vimtex#latexmk#callback(1)\"" -e $failure_cmd = "\"/home/maks/.config/nvim/neovim-remote/bin/nvr\" --servername /tmp/nvimGlqvz9/0 --remote-expr \"vimtex#latexmk#callback(0)\"" -e $new_viewer_always = "0" -e $pdf_previewer = "zathura  -x \"/home/maks/.config/nvim/neovim-remote/bin/nvr --servername /tmp/nvimGlqvz9/0 --remote +%{line} %{input}\" %S" khachiyan.tex
maks      7328  7324  7 17:02 pts/0    00:00:00 zathura -x /home/maks/.config/nvim/neovim-remote/bin/nvr --servername /tmp/nvimGlqvz9/0 --remote +%{line} %{input} khachiyan.pdf
maks      7335     1  6 17:02 pts/0    00:00:00 zathura --synctex-forward 1:1:/home/maks/Projects/SPBU/Malozemov/diploma/khachiyan/khachiyan.tex /home/maks/Projects/SPBU/Malozemov/diploma/khachiyan/khachiyan.pdf
```

I was able to workaround this with a simple fix:
```diff
--- a/autoload/vimtex/view.vim
+++ b/autoload/vimtex/view.vim
@@ -363,7 +363,7 @@ function! s:zathura.forward_search(outfile) dict " {{{2
   let exe.cmd .= line('.')
   let exe.cmd .= ':' . col('.')
   let exe.cmd .= ':' . vimtex#util#shellescape(expand('%:p'))
-  let exe.cmd .= ' ' . vimtex#util#shellescape(a:outfile)
+  let exe.cmd .= ' ' . vimtex#util#shellescape(fnamemodify(a:outfile, ":t"))
   call vimtex#util#execute(exe)
   let self.cmd_forward_search = exe.cmd
 endfunction
```

Please review this change and fix appropriately.

Moreover, I propose to make zathura delay a `g:` option, as 50ms is still too short for me.

And a bit of feature request: it would be great if PDF viewer displayed current line after changes were made. I achieved this with a simple vimrc configuration:
```vim
function! VimtexHookView(status)
    if a:status != 1
        return
    endif

    execute "VimtexView"
endfunction

let g:vimtex_latexmk_callback_hook = 'VimtexHookView'
```
Is it OK to do so? Can you suggest and probably implement in master a better way?
### Minimal vimrc file

I tested with this minimal vimrc and NeoVim:
```vim
set nocompatible

let &rtp  = '~/.config/nvim/plugged/vimtex,' . &rtp
let &rtp .= ',~/.config/nvim/plugged/vimtex/after'

filetype plugin indent on
syntax enable

let g:vimtex_view_method = 'zathura'
let g:vimtex_latexmk_progname = '/home/maks/.config/nvim/neovim-remote/bin/nvr'
```

**Comment by lervag** [comment] 2016-03-08 19:32
Thanks. As far as I see, you raise three concerns:

1. Zathura opening second window on `VimtexView`.
2. The hardcoded delay is too short, shoud or could be optional.
3. You propose to add a call to `VimtexView` for the zathura callbacks, similar to what you achieve with the mentioned configuration.

I think the first two concerns are related. That is, I don't think the first concern is a real issue, instead, I think the problem is due to the delay being to short. I noticed this problem recently myself, and I think it must be something that has changed with recent versions of zathura. I first tried a delay of 10 ms, which seemed to work, but then I changed to 50 ms because 10 ms was too slow in some cases. This works well for me, but I guess it depends on your hardware and a lot of things, and so I can agree that an option could be warranted. I don't really want to add more options though; could you test whether 100 ms works for you, then I could instead increase the delay?

Regarding your feature request: I actually don't want to add this, since this is exactly why I added the callback hook. That is, you can get the desired behaviour yourself without me adding it to master.

**Comment by nasenatmer** [comment] 2016-03-23 21:49
Hm, it's exactly been 15 days since I've been using `vimtex`for writing a big LaTeX project, and back then I didn't experience the second window opening issue, but hopefully we can find a sensible delay to circumvent this.

With regards to the third question, I second lervag's point that there are often cases where you just correct sth small at a certain point in the text but don't want to necessarily jump to it in the output. Therefore, keeping this out of master and implementing it individually, where needed, seems more sensible to me.

**Comment by lervag** [comment] 2016-03-24 11:27
@nasenatmer Thanks for the input. I know there are at least a handful of users who use vimtex with zathura, and so I think this issue can't be that severe, since I think it should mean more people would react. Thus I think the issue can be closed.

@maksbotan As I still can't reproduce the issue, I'll close this now. I'll be notified on any updates, and you may feel free to reopen. If so, please respond to my earlier questions, especially regarding the delay times.

**Closed by lervag** 2016-03-24 11:27 UTC
