### ISSUE TITLE
VimtexCountWords error with Windows PowerShell

### ISSUE THREAD

**Issue by norbert-op** [lervag/vimtex#1507] opened 2019-10-03 17:32 UTC
**Issue**

I get an error message from `:VimtexCountWords` when using Windows Powershell for my command terminal. This is the first PowerShell related problem I've had with Vim. I've been using Vimtex to compile with latexmk and it interacts fine with PowerShell (though I still have issues with SumatraPDF that may be related).

This is the error message:
```
Error detected while processing function vimtex#misc#wordcount_display[1]. .vimtex#misc#wordcount:
line 17:
E484: Can't open file C:/Users/Norbert/AppData/Local/Temp/VIo7539.tmp
```
There's no sign of that temp file in the directory.

I sometimes see a message from PowerShell preceding the Vim error when using gVim, but it shows up reliably with Vim running inside Powershell. Maybe it just doesn't display properly in gVim:

```
At line:1 char:43
+ cd C:\\Users\\Norbert\\Downloads\\avb-dtrh& texcount -nosub -sum -1 -1 -merge p . . .
+                                           ~
The ampersand (&) character is  not allowed.
The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
    + CategoryInfo               : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId      : AmpersandNotAllowed
```

This is what shows up in the Vim log when I issue `:VimtexCountWords`:

```
Calling shell to execute: "cd "C:\\Users\\Norbert\\Downloads\\avb-dtrh"& texcount -nosub -sum -q -1 -merge  "paper.tex" > C:/Users/Norbert/AppData/Local/Temp/VIo7539.tmp"
```                      

**minimal.vim**
Here's a minimal Vimrc in which `:VimtexCountWords` functions:

```vim
let g:vimtex_view_general_viewer = 'SumatraPDF'
set nocompatible
filetype plugin indent on
syntax on
```

When I add these two lines I get the error message:

```vim
set shell=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
set shellcmdflag=-command
```

The error should be reproducible just by adding those two lines to a `vimrc` and issuing `:VimtexCountWords`. I disabled my other plugins for testing by removing them from `~\vimfiles\pack\*\start`, since I use the native plugin installation method.

**Possible Related Issue**

#908 is a fix from two years ago that you incorporated for Windows, including an ampersand to call `texcount`. I suspect my problem is related to the current ampersand in line 52 of `misc.vim`:

```vim
function! vimtex#misc#wordcount(...) abort " {{{1
  let l:opts = a:0 > 0 ? a:1 : {}

  let l:range = get(l:opts, 'range', [1, line('$')])
  if l:range == [1, line('$')]
    let l:file = b:vimtex
  else
    let l:file = vimtex#parser#selection_to_texfile('arg', l:range)
  endif

  let cmd  = 'cd ' . vimtex#util#shellescape(l:file.root)

" This is line 52  
  let cmd .= has('win32') ? '& ' : '; '

  let cmd .= 'texcount -nosub -sum '
  let cmd .= get(l:opts, 'count_letters') ? '-letter ' : ''
  let cmd .= get(l:opts, 'detailed') ? '-inc ' : '-q -1 -merge '
  let cmd .= g:vimtex_texcount_custom_arg . ' '
  let cmd .= vimtex#util#shellescape(l:file.base)
  let lines = split(system(cmd), '\n')

  if l:file.base !=# b:vimtex.base
    call delete(l:file.tex)
  endif

  if get(l:opts, 'detailed')
    return lines
  else
    call filter(lines, 'v:val !~# ''ERROR\|^\s*$''')
    return join(lines, '')
  endif
endfunction
```
Is this an easy fix, or do you need more information from me? I appreciate you helping us Windows users even though you're not one yourself. I use Win 8.1 with PowerShell 4 and Vim 8.1.

**Comment by leonorbert** [comment] 2019-10-03 20:17
After repeated testing with the issue cited in #1495, I found that setting PowerShell as the terminal is forward searching to break.

**minimal.vim**

This is from the help documentation.
```vim
set shell=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
set shellcmdflag=-command
source $VIMRUNTIME/vimrc_example.vim
let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options_latexmk = '-reuse-instance'
let g:vimtex_view_general_options
	\ = '-reuse-instance -forward-search @tex @line @pdf'
	\ . ' -inverse-search "gvim --servername ' . v:servername
	\ . ' --remote-send \"^<C-\^>^<C-n^>'
	\ . ':drop \%f^<CR^>:\%l^<CR^>:normal\! zzzv^<CR^>'
	\ . ':execute ''drop '' . fnameescape(''\%f'')^<CR^>'
	\ . ':\%l^<CR^>:normal\! zzzv^<CR^>'
	\ . ':call remote_foreground('''.v:servername.''')^<CR^>^<CR^>\""'
```

**minimal.tex**
```tex
\documentclass{article}

\begin{document}
	This is my minimal .tex example.
\newpage
    Here's a second page of text.
\end{document}
```
**Steps to reproduce**

1. Run PowerShell and change directory to the location of minimal.vim and minimal.txt.
2. Run `vim --servername vim -u minimal.vim minimal.tex
3. Type "\ll" to compile.
4. Alt-tab back to Vim, move down to second line, and type "\lv" for forward search. Nothing happens.
5. Scroll back to first page in SumatraPDF and double-click for inverse search. Error message about GVIM server.

2b. Run `vim --servername gvim -u minimal.vim minimal.tex`. This gets inverse search working.

2c. Run `gvim -u minimal.vim minimal.tex`. Inverse search works, forward search still does nothing.

I'm hopeful that you can find a way to support Powershell without breaking forward search for Command Prompt use. Automatic detection would of course be better than setting an option. Thanks for looking into it, and let me know if you need any further testing.

**Comment by lervag** [comment] 2019-10-04 22:05
I'll look into this later, but could you please raise the second comment as a new issue and delete it from here? The root cause might be related, but it would help for me to work on a single thing at a time (as I already commented elsewhere).

Also, your minimal vimrc file is not clear, because you are sourcing a file that is not immediately available on my system. Could you please update it (both here and in the new issue)? In particular, your current example makes it impossible for me to know how you actually load vimtex, because it is not explicitly stated.

**Comment by lervag** [comment] 2019-10-04 22:06
(By the way, I'm happy to try and help, and I appreciate your effort in both detailing the issue and looking into possible causes/solutions.)

**Comment by leonorbert** [comment] 2019-10-05 08:08
Thanks for looking at this. I took the essential line from that default vimrc and made the minimal.vim truly minimal. That default file came with my installation, I hadn't even opened it before. Vimtex is loaded automatically from the `~\vimfiles\*\start` directory, I just need to have ft detection on.

I made the second comment a separate issue and also updated the minimal.vim there.

As a temporary solution, can you suggest a way to switch the shell back to command prompt whenever .tex files are loaded? I'm not sure if this can be done mid session, and whether the shell setting is for a single buffer or global.

**Comment by Konfekt** [comment] 2019-10-10 10:05
Support for `powershell` as `&shell` is incomplete. You could try adapting `&shellcmdflag` as suggested at https://stackoverflow.com/a/27499996 and https://github.com/tpope/vim-fugitive/issues/435#event-2699501243 .

For a complete correct setup, perhaps the settings at https://github.com/janlazo/dotvim8/blob/064808d46ddfbd4904c54fec47bcef5ee15ecc4a/shared.vim#L203 could be of help.

**Comment by lervag** [comment] 2019-10-10 19:40
I'm considering two possible actions here:

1. Specify in the docs that vimtex only works on Windows with default shell settings. One could ensure such defaults for only `.tex` files with autocommands or a custom `ftplugin`, except that the options are global. So it would not be perfect.

2. I could try to wrap every system call so that the shell options are intermediately set to their defaults on Windows. This should solve your issues, but it does feel hacky.

I'm curious, how would you feel if I chose the "easy way out" and updated the docs? What part of your Vim workflow breaks if you don't use Powershell as the main shell (or if you set it to defaults for LaTeX files)?

**Comment by lervag** [comment] 2019-10-10 19:44
And by the way: Could you (@norbert-op) confirm that Vimtex works as expected for you as long as you don't change the `&shell` options?

**Comment by norbert-op** [comment] 2019-10-21 00:58
Thank you, @Konfekt, for the suggestions. I tried them out, and in various combinations, but can't get the word count function or forward search working.  A couple suggestions did get me past the temp file error, but there are other unspecified errors for VimtexCountWords and the forward search doesn't work at all.

@lervag, I would be fine with you taking the easy way out. Vimtex does work fine with default shell settings on Windows. It wouldn't interfere with my current workflow to use Command Prompt for my shell from Vim. If you wrote something to ensure that default when `.tex` are loaded, that would prevent problems for new users. If PowerShell is important to someone's workflow, he would at least know from the Vimtex Doc about the problem. I saw that some people have resorted to creating a command to toggle the Vim shell back and forth, so I could always do that if necessary.

That said, it would be great if the compatibility issue were solved, but it seems like a complex problem.

**Comment by Konfekt** [comment] 2019-10-21 07:01
Dear @norbert-op , I vaguely recall that https://stackoverflow.com/a/27499996 also got me past the temp file error, but in the end `&shell = powershell`  had to be abandoned due to other incompatibilities. This setup is just not yet common enough to be supported, even though powershell now runs on Linux and MacOS, too.

For inspiration on how to handle this, vim-fugitive now runs under powershell as discussed at the mentioned thread https://github.com/tpope/vim-fugitive/issues/435 

Threse https://github.com/tpope/vim-fugitive/commit/ea818f1fabce967bc754dfbeb7782d6322064538 and https://github.com/tpope/vim-fugitive/commit/51cdb1b190f14d6f2509ffbba363402a951b8312 are the two commits that mention powershell support.

**Comment by lervag** [comment] 2019-10-21 13:25
> That said, it would be great if the compatibility issue were solved, but it seems like a complex problem.

I agree it would be nice, but at the same time it does not seem like a crucial problem. I'll rather spend my time working on other issues. Of course, I'll be glad to consider pull requests or suggestions for handling this, but since I don't use windows for testing it becomes difficult. I'll therefore close the issue for now with a minor update to the docs.

**Closed by lervag** 2019-10-21 13:25 UTC
Labels: bug

**Comment by Konfekt** [comment] 2019-10-24 09:29
There is already
```vim
if has('win32')
  function! s:process._prepare() abort dict " {{{1
    if &shell !~? 'cmd'
      let self.win32_restore_shell = 1
      let self.win32_saved_shell = [
            \ &shell,
            \ &shellcmdflag,
            \ &shellxquote,
            \ &shellxescape,
            \ &shellquote,
            \ &shellpipe,
            \ &shellredir,
            \ &shellslash
            \]
      set shell& shellcmdflag& shellxquote& shellxescape&
      set shellquote& shellpipe& shellredir& shellslash&
    else
      let self.win32_restore_shell = 0
    endif

  ...

  endfunction
```
However, there are still eleven direct calls to `system()`, for example at
```vim
autoload/vimtex/misc.vim|58| let lines = split(system(cmd), '\n')
```
If these could be run by
```vim
" autoload/vimtex/process.vim (line 13)
function! vimtex#process#run(cmd, ...) abort " {{{1
```
instead, maybe vimtex would be independent of the shell on windows by always intermediary switching to `cmd`.

**Comment by lervag** [comment] 2019-10-24 19:21
Yes, you're right. I'll look into it.

**Comment by lervag** [comment] 2019-10-24 20:09
Ok, I've updated. I think things should work quite well now.

**Comment by norbert-op** [comment] 2019-10-24 20:49
Thanks for the further work, I can confirm the VimtexCountWords goes through now when my `&shell` is `pwsh`. Did you intend it just for this function? Forward search is still not working.

**Comment by lervag** [comment] 2019-10-24 20:53
Ok. The problem with forward search is more complicated, it seems: it already uses the process wrapper. I don't know why it doesn't work, sorry.
